### ISSUE TITLE
[Bug] Lack of feedback when loading a map from a cloud provider

### ISSUE THREAD

**Issue by neokore** [keplergl/kepler.gl#1002]
**Describe the bug**
When a user loads a map from a URL from a cloud provider, there is no loading animation or error messages when something goes wrong.

**To Reproduce**
1. Navigate to a shared map URL from a cloud provider
2. While it is loading, it just shows the "Load Data" modal.
3. In case of error, it just remains on the "Load Data" modal without feedback

**Expected behavior**
While loading, it should show the loading animation used when you load a map using the modal. In case of error, it should show an error notification.

**Comment by macrigiuseppe** [comment]
fixed
