### ISSUE TITLE
Please help: White screen after uploading a CSV or JSON on kepler.gl

### ISSUE THREAD

**Issue by bartkloostra** [keplergl/kepler.gl#1012]
**Describe the bug**
White screen after uploading a comma delimited CSV in Kepler

**To Reproduce**
1. Go to 'kepler.gl'
2. Click on 'Get started'
2. Click on 'browse your files'
4. Click on my CSV
5. See white screen

**Expected behavior**
I expected to upload my CSV

**Screenshots**
![image](https://user-images.githubusercontent.com/33312781/76869556-cdfcb680-6868-11ea-8248-9e4f475227d3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macrigiuseppe** [comment]
@bartkloostra can you please provide a sample of your data?

**Comment by heshan0131** [comment]
@bartkloostra your dataset is not using mercator projection coordinates. The coordinates should be in latitude and longitude. You can take a look at our demo maps
Here is an example
https://github.com/uber-web/kepler.gl-data/blob/master/earthquakes/data.csv

**Comment by ashydv09** [comment]
Screen white out when selecting trip while plotting a linestring geojson, however it is getting plotted when selected polygon
Sample csv data
id,geojson
one,"{""features"": [{""geometry"": {""coordinates"": [[77.590508, 12.932197], [77.590591, 12.932181], [77.590508, 12.93222], [77.590508, 12.932197], [77.59051, 12.932197], [77.590508, 12.932197], [77.588867, 12.928998], [77.60179, 12.866754], [77.590508, 12.932197], [77.590591, 12.932181]], ""type"": ""LineString""}, ""properties"": {""bike_id"": ""xxxx"", ""user_id"": ""xxxx""}, ""type"": ""Feature""}], ""type"": ""FeatureCollection""}"
