### ISSUE TITLE
[Bug] Kepler stops recognition of geo type column

### ISSUE THREAD

**Issue by b2kdaman** [keplergl/kepler.gl#1015]
**Describe the bug**
When we pass over 5mb data to Kepler with GeoJSON formatted polygon data it stops recognizing it in the UI as _geo_ but does as _string_. Default layer is not created and user have to manually create layer.
When data size is smaller it works fine.

**To Reproduce**
1. Add parsed json data with size over 2MB(?TBD) using addDataToMap method

**Expected behavior**
Default polygon layer should be created.

**Comment by heshan0131** [comment]
@b2kdaman it currently works for our testing file, so this might be a special case. Would you mind share a snippet of your GeoJSON?

**Comment by macrigiuseppe** [comment]
closing because inactive
