### ISSUE TITLE
[Question] Icon in json

### ISSUE THREAD

**Issue by Skyloq** [keplergl/kepler.gl#1020]
[data.txt](https://github.com/keplergl/kepler.gl/files/4369414/data.txt)

Could you give me an example of an icon in json?

I have no problem making them appear with the .csv format but it is more complicated with the json. And no matter how much I look, I can't find an example online.

I would like to insert them in the same way as for my LineString

`{\"type\":\"Icon\",\"Latitude\":-0.370844,\"Longitude\":49.175196,\"icone\":\"android\"}}"`

I try this too :

`"{\"type\":\"Icon\",\"coordinates\":[-0.370844,49.175196],\"icone\":\"android\"}}"`

Can you tell what is wrong please ?

**Comment by heshan0131** [comment]
This json should work
```js
[
  {
    "icon": "apple",
    "latitude": 29.9927699,
    "longitude": 31.2461142
  },
  {
    "icon": "android",
    "latitude": 29.9870074,
    "longitude": 31.2175827

  },
  {
    "latitude": 30.0116207,
    "longitude": 31.2179346,
    "icon": "bold"
  },
  {
    "latitude": 30.0218999,
    "longitude": 31.2178842,
    "icon": "cloud"
  }
]
```

**Comment by Skyloq** [comment]
Thanks !
