### ISSUE TITLE
[Bug] centerMap feature filters out 2% of data, causing an incorrect viewport

### ISSUE THREAD

**Issue by jonsadka** [keplergl/kepler.gl#1025]
**Describe the bug**
When loading a dataset into Kepler and setting `centerMap: true`, the computation to compute the latitude / longitude bounds assumes that 2% of the data are outliers and [filters them out](https://github.com/keplergl/kepler.gl/blob/master/src/utils/data-utils.js#L94), causing incorrect bound calculations for datasets. 

**Expected behavior**
Three possible approaches here:
- Do not filter the data when computing the bounds [Preferred]
- Calculate outliers with a more mathematical approach before filtering them out
- Allow the user to specify if outliers should be filtered or not (should default to false)

I prefer the first option, but could see a use case for combining options 2 and 3 (i.e. a user can decide if they want to filter outliers before computing the bounds and, if so, the outlier logic is made more robust)

**Screenshots**

Before
<img width="1435" alt="Screen Shot 2020-03-23 at 6 14 29 PM" src="https://user-images.githubusercontent.com/6504944/77378065-3698d700-6d32-11ea-9b7c-a0844bd39171.png">

After (Removing the 99 percentile filter)
<img width="1435" alt="Screen Shot 2020-03-23 at 6 11 45 PM" src="https://user-images.githubusercontent.com/6504944/77378073-3993c780-6d32-11ea-8549-47e5d85eaae9.png">

**Comment by jonsadka** [comment]
If we decide option #1 is the correct approach, I went ahead and issued a PR for the fix #1026

**Comment by heshan0131** [comment]
the problem is not the outliner being filtered out. It is because we are only taking a sample of the rows to calculate bounds: 

https://github.com/keplergl/kepler.gl/blob/master/src/layers/base-layer.js#L716-L718

this is for performance concern,  you can try increasing the max sample size to be 50000, which should probably still be okay. but keep in mind, kepler will try calculate bounds for ALL auto detected the layers, so this process will be repeated for  all new layers.

**Comment by jonsadka** [comment]
I think taking a random subset of `sampleData` above a threshold makes total sense, but I still dont quite follow how this outlier logic is useful.

Let's say in the in the example above, the dataset being loaded is a size of ~2,000. We then arbitrarily chop off the first 1% of values and last 1% of values, meaning we are removing ~40 data points without properly calculating if they are actually outliers or not. 

If we do truly believe that computing outliers is valuable, which I dont think should be the default case, we should properly compute them with a quantile calculation like below. Happy to make these changes if you prefer
```
import {ascending, quantileSorted} from 'd3-array';

export function getLatLngBounds(points, idx, limit) {
  const lats = points
    .map(d => Array.isArray(d) && d[idx])
    .filter(Number.isFinite)
    .sort(ascending);

  if (!lats.length) {
    return null;
  }

  const lowerBound = quantileSorted(lats, 0.01);
  const upperBound = quantileSorted(lats, 0.99);
  return [Math.max(lowerBound, limit[0]), Math.min(upperBound, limit[1])];
}
```
