### ISSUE TITLE
CSV loading, but not displaying

### ISSUE THREAD

**Issue by rsimon** [keplergl/kepler.gl#103]
Sorry for not having a more descriptive title, or a more specific description of the problem. I'll try to describe what I'm seeing as detailed as possible; and I'm attaching the test data below.

I have a CSV that is just not displaying on the map. It's a three-column file (title, WKT geometry, an "ItemType" string field). Some observations: 

- Upload seems to go fine. Colum types are properly recognized (string, geo, string), and everything looks ok in the grid view
- After loading, the map stays empty
- If I add a filter to show just rows of ItemType __PLACE__, the map renders as it should
- If I add a filter to show just rows of ItemType __OBJECT__, the map goes back to blank
- If I clip the CSV to just the first 500 rows (all of which are OBJECTs), and upload to a fresh map, everything works as it should. 

Since the clipped dataset works, I'm guessing there might be _something_ in the data that kepler.gl doesn't like. But I can't figure out what it is. Below, I'm attaching:

- The full dataset [all.csv.zip](https://github.com/uber/kepler.gl/files/2075195/all.csv.zip) (that's causing the issues)
- Only the first 500 rows [partial_500.csv.zip](https://github.com/uber/kepler.gl/files/2075197/partial_500.csv.zip) (which look ok on the map)

**Comment by huaruiwu** [comment]
You have some `GEOMETRYCOLLECTION`s in your data that I think might be causing the problem

**Comment by rsimon** [comment]
Thanks! Yes, I can confirm that removing all `GEOMETRYCOLLECTIONS` does the trick. Is there any chance to get `GEOMETRYCOLLECTIONS` supported though? (Or is this just a problem that affects WKT-encoded geometries?)

**Comment by yiyaya66** [comment]
@rsimon `GEOMETRYCOLLECTIONS` is not supported in Deck.gl. What is your use case with`GEOMETRYCOLLECTIONS`? If you'd like this feature, feel free to open an feature ticket with more details.

**Comment by rsimon** [comment]
It’s really just my source data. But I guess I’ll be able to work around with Multipoint and Multipolygon. Or are there restrictions on those types, too?

**Comment by macrigiuseppe** [comment]
mentioned in #498
