### ISSUE TITLE
[QUESTION] Kepler.gl and Carto Open source

### ISSUE THREAD

**Issue by nicoali** [keplergl/kepler.gl#1030]
If i want to connect kepler.gl with my own Carto instance is it possible and which files i have to edit?

The connection is available only from v 2.0.1 of kepler? with 2.0 i can see the logo of carto but the link doesn't work for me!

Thanks

**Comment by neokore** [comment]
Hi @nicoali! What kind of CARTO instance do you have installed? The way to connect depends on how each CARTO service is accessed, but in general you just need to edit the `domain` constant in `carto-provider.js` (https://github.com/keplergl/kepler.gl/blob/master/examples/demo-app/src/cloud-providers/carto/carto-provider.js#L30).

**Comment by nicoali** [comment]
I have installed from their repository a week ago! so i think it's one of the latest release.
I'will try to edit the  domain constant and use an api key from my carto instance!

**Comment by macrigiuseppe** [comment]
gonna close this because inactive
