### ISSUE TITLE
[Bug]Export Map HTML with satellite basemap Results in a Blank Page

### ISSUE THREAD

**Issue by jessicagiles** [keplergl/kepler.gl#1031]
When exporting map to HTML, the file opens as a blank page with the kepler.gl logo on the top left. This issue persists with different map box tokens, without using a map box token, and readable vs. editable maps. 

To reproduce: 
1. Go to 'Export Map'
2. Select 'HTML' as map format
3. Export
4. Open output file in web browser

Expected behavior: 
The map exports as an HTML file that can be viewed in a web browser.

Desktop: 
 - OS: iOS Version 10.15.2
 - Browser: Chrome, Safari

**Comment by heshan0131** [comment]
@jessicagiles can you try load this map: https://kepler.gl/demo/movement_pittsburgh and export to html? if it works, then there might be something wrong with the data you loaded to kepler.

Can you open your js console (cmd + shift + I) in chrome, and screen capture any red error message in there?

**Comment by jessicagiles** [comment]
@heshan0131 I was able to load the movement_pittsburgh map and export to HTML. When inspecting in Chrome there are no error messages. I will keep troubleshooting with my data, thank you!

**Comment by jessicagiles** [comment]
@heshan0131 The export to HTML is working when I used the 'Muted Night' or 'Dark' basemap. Exporting to HTML is not working when using the satellite basemap. If I pull your map in and export as satellite basemap I am getting the same issue.

**Comment by heshan0131** [comment]
Got it, I will look into it

**Comment by macrigiuseppe** [comment]
@jessicagiles I tested the satellite export map and it works. Please see below

![export-satellite-map](https://user-images.githubusercontent.com/2554552/78527922-ffdfa980-7792-11ea-90e3-bc4552171718.gif)

Are you using a particular dataset or something you can share to help reproduce the issue?

**Comment by jessicagiles** [comment]
@macrigiuseppe @heshan0131 I have just tested with https://kepler.gl/demo/movement_pittsburgh and it appears to be working properly now. Thanks!

**Comment by AlexTelloG** [comment]
This seems to be an issue on my side still. I tested with my own exports and with  https://kepler.gl/demo/movement_pittsburgh and neither works, only white screen.
