### ISSUE TITLE
Smoothing filter when using the date only serie

### ISSUE THREAD

**Issue by vishalmhjn** [keplergl/kepler.gl#1032]
How can I make a smooth filter when using the date only series. In the picture, you can see that the y-axis values drop after every date value because data is not available for the hourly intervals.

<img width="1035" alt="Screen Shot 2020-03-26 at 09 23 54" src="https://user-images.githubusercontent.com/42190624/77625261-8d292f80-6f43-11ea-93fc-94ee88947bfe.png">

**Comment by rbhatia46** [comment]
How can we use the date-only series for playback, can you please tell me the approach for this?

**Comment by heshan0131** [comment]
Hi @rbhatia46 you can edit your date from `01/29/2020` to `01/29/2020 00:00`

**Comment by rbhatia46** [comment]
@heshan0131  Thanks for the reply, can you please tell the minimum Kepler version this would work with?

**Comment by macrigiuseppe** [comment]
gonna close this because inactive
