### ISSUE TITLE
Kepler.gl without mapbox API token

### ISSUE THREAD

**Issue by francescocretti** [keplergl/kepler.gl#1033]
Hey everybody. I'm using KeplerGL in conjunction with a custom tile server (with [TileServerGL](http://tileserver.org/)) serving OpenStreetMaps tiles and is working well.
However I can't find a way to stop Kepler asking for the Mapbox API token.

Is there a way to use KeplerGL without providing the `mapboxApiAccessToken` property, when  using a custom tile server?

I'm currently passing an empty string but is not a clean solution.

Thanks a lot,
Francesco

**Comment by francescocretti** [comment]
I put a basic (free) Mapbox token in Kepler and I havo no more warnings.
Using my custom TileServer I don't request tiles from Mapbox (looking at the network activities)  so that can be a solution!

**Comment by heshan0131** [comment]
@francescocretti are you using kepler.gl as a library? how are you passing the custom tile server map tiles to kepler? Is it via custom map styles?

**Comment by francescocretti** [comment]
Hi @heshan0131 ! Thank you for answering
Yes I'm using Kepler as a library in a project section.
Yes I'm passing the tiles via custom map styles like this:

```javascript
    this.props.dispatch(inputMapStyle({
      id: "customStyle",
      label: "Custom style",
      url: "/tilemap/server/url",
      style: styleConfig
    }));
```

**Comment by heshan0131** [comment]
Got it. I think the warning comes from kepler's default mapStyles (dark, light, muted...). They are still mapbox styles that requires a mapbox token to load. And kepler will try to load them when initialized. If you don't need any of the default mapstyles. you could use (`keplerGlReducer.initialState`)[https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/custom-initial-state.md] method and overide the default mapStyles like this:

```js
const myKeplerReducer = = keplerGlReducer
  .initialState({
    mapStyles:  {} // make this an empty object
    styleType: 'customStyle  // make this your custom style id
   });
```

let me know if this works

**Comment by francescocretti** [comment]
Thanks @heshan0131  works like a charm! :)

**Comment by ibgreen** [comment]
My bad didn't mean to close it by accident

**Comment by DrissiReda** [comment]
@francescocretti in what file did you add the custom style? I'm trying to use kepler in superset from a custom tileserver.

**Comment by francescocretti** [comment]
@DrissiReda what do you mean exactly?

I put the config json in a dedicated folder, then from the main `App` component (`app.js`) I called 

```javascript

import MAP_STYLE_CONFIG from './map_style';
// other imports...

class App extends Component {
  constructor() {
    // stuff...
  }

  conmponentDidMount() {
    // ...

    this.props.dispatch(inputMapStyle({
      id: "OpenStreetMap",
      label: "OpenStreetMap",
      url: "/custom/tileserver/url",
      style: MAP_STYLE_CONFIG
    }));
  }

  render() {
    // render function
  }
}
```

Hope it helps...
