### ISSUE TITLE
Restrict side panel functionalities

### ISSUE THREAD

**Issue by francescocretti** [keplergl/kepler.gl#1045]
**Is your feature request related to a problem?**
I would like to let my users play with some pre-configured filters in the side panel, without having the option to add a new filter, to export the map or to switch to _Layers_, _Interactions_ or _Base map_-. 
Currently I can only hide or show the whole side panel or select the initial state with the **activeSidePanel** property in my custom Kepler reducer.

**Describe the solution you'd like**
Would be really useful a parameter where to specify the functionalities I want to be enabled in the side panel.

**Describe alternatives you've considered**
As a workaround i thought to disable or hide panel icons that i don't need with hardcoded JS/CSS.

**Comment by heshan0131** [comment]
@francescocretti All of those can be achieved using dependency injection

1. Create your own CustomSidePanel and returns kepler's [SidePanel](https://github.com/keplergl/kepler.gl/blob/master/src/components/side-panel.js#L112
),  Replace SidePanel.defaultProps to pass in less panels

```js
import {SidePanelFactory} from 'kepler.gl/components';
import {SIDEBAR_PANELS} from 'kepler.gl/constants';

function CustomSidePanelFactory(...args) {
  const CustomSidePanel = SidePanelFactory(...args);

  CustomSidePanel.defaultProps = {
    ...CustomSidePanel.defaultProps,
    panels: SIDEBAR_PANELS.filter(({id}) => id === 'filter')
  };

  return CustomSidePanel;
}

CustomSidePanelFactory.deps = SidePanelFactory.deps;
```

2. Use css selector to hide buttons
```
.add-filter-button {
  display: none
}
```

3. set `uiState` initial `activeSidePanel` to be `filter`
```js
const customizedKeplerGlReducer = keplerGlReducer
  .initialState({
    uiState: {
      activeSidePanel: 'filter'
    }
  })
```

**Comment by francescocretti** [comment]
Ehy @heshan0131 thank you for your answer!
The method you suggested works perfectly, thanks a lot.
I have two further questions:

1. Can I use the same method of dependency injection to *add* custom buttons on the side panel (for example to change the base map style)? 
2. The *NEW FILTER* button does not have an `add-filter-button` class, but it has auto-generated classes like `ifZwlr`. Is it safe to target the button using this class code (sound like a dumb question, but not knowing how the class name is generated I don't know if can change)

**Comment by macrigiuseppe** [comment]
@francescocretti 
1. In order to override the collapse button you can override its factory: https://github.com/keplergl/kepler.gl/blob/master/src/components/side-panel/side-bar.js#L76
2. It is not safe to target that class, you can target __add-filter-button__ class

For the bug, please create a new issue. I am gonna close this one

**Comment by francescocretti** [comment]
Ehy @macrigiuseppe .
Thanks for your reply.

Unfortunately there's no `add-filter-button` class in the Add Nre Filter element.

```html
<div width="105px" class="sc-kAzzGY ifZwlr button">
   <svg viewBox="0 0 64 64" width="12px" height="12px" class="data-ex-icons-add " style="fill: 
   currentcolor;">
      <path d="M35.93,28.57V9.89a1,1,0,0,0-1-1h-5.9a1,1,0,0,0-1,1V28.57H9.39a1,1,0,0,0- 
     1,1v5.9a1,1,0,0,0,1,1H28.07V55.11a1,1,0,0,0,1,1h5.9a1,1,0,0,0,1-1V36.43H54.61a1,1,0,0,0,1- 
     1v-5.9a1,1,0,0,0-1-1Z"></path>
   </svg>
   Add Filter
</div>
```

I'm using Kepler v2.0.1.

Thanks in any case for your help

**Comment by macrigiuseppe** [comment]
@francescocretti please upgrade to the latest version. A new class has been added: https://github.com/keplergl/kepler.gl/blob/master/src/components/side-panel/filter-manager.js#L93
