### ISSUE TITLE
[Bug] Module not found: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by leodavinci1** [keplergl/kepler.gl#1050]
**Describe the bug**
I have installed the kepler.gl package and first thing when I run npm start I get this error:

> ./node_modules/kepler.gl/dist/components/kepler-gl.js
Module not found: Can't resolve 'styled-components' in 'C:\Users\leo_c\leo-gis-web\node_modules\kepler.gl\dist\components'

I have already tried deleting node_modules and installing again

**To Reproduce**
1. npm install kepler.gl
2. npm start

**Screenshots**
![sdd](https://user-images.githubusercontent.com/22947676/78307013-3a3f1180-751b-11ea-9ac8-20acbf9a1a3a.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by leodavinci1** [comment]
deleted package-lock.json and node_modules, after that running "npm install" fixed this issue

**Comment by cjrobbertse** [comment]
still getting this problem.

**Comment by CamiloMontoyaAdc** [comment]
you can try doing: "npm i styled-components", this fixed it for me.

**Comment by NizanHulq** [comment]
> you can try doing: "npm i styled-components", this fixed it for me.

thankyuu this work for mee
