### ISSUE TITLE
[Bug] Can't resolve styled-components

### ISSUE THREAD

**Issue by GarrettJMU** [keplergl/kepler.gl#1051]
**Describe the bug**
Won't generate development JavaScript bundle:
```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'styled-components' in '/etc/etc/node_modules/kepler.gl/dist/styles'
```

**To Reproduce**
1. run yarn develop, doesn't compile

**Expected behavior**
It should combile

**Desktop (please complete the following information):**
node version: 11.10.1
react version: tried 16.3, 16.6, 16.13 (all no luck)
redux: 4.0.5
kepler.gl: 1.1.13 and 2 (with no luck)

**Comment by leodavinci1** [comment]
Try deleting your **package-lock.json** file and your **node_modules** folder. After that run 
`yarn install`

**Comment by macrigiuseppe** [comment]
@GarrettJMU if you are trying to use Kepler.gl as dependency you are required to add styled-components as one of your project dependencies. In fact, styled-components is one of kepler.gl peer dependencies

**Comment by DanRYoung** [comment]
@macrigiuseppe Should we update the readme to include that information? The `Install Kepler.gl` section doesn't mention this crucial dependency anywhere, so I ran into the same issue as @GarrettJMU.

(Your suggested fix worked perfectly, by the way! `yarn add styled-components` did the trick.)
