### ISSUE TITLE
How to append the data into the single HTML file? 

### ISSUE THREAD

**Issue by gohkokhan** [keplergl/kepler.gl#1060]
I was using https://kepler.gl/demo to generate a single HTML file, I embed it into my Wordpress. I have a cron job that is running every 20 minutes to get the latest data. I notice in the HTML file there is hardcoded the data 
`(function customize(keplerGl, store) {
            const datasets = [{"version":"v1","data":{"id":"2fz8qegsp","label":"filename.csv","color":[143,47,191],"allData":[[**allthedatahere**`

I have very little knowledge in HTML, what is the best way that I can set the variable _datasets_ to my new JSON? I'll make sure the JSON has the same schema.

**Comment by macrigiuseppe** [comment]
@gohkokhan if you want to dynamically interact with the map, you need to perform the following steps:
- Parse your data: https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/processors/processors.md
- Add your data to the map: https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/actions/actions.md#adddatatomap
