### ISSUE TITLE
[Enhancement] Add Portuguese translations

### ISSUE THREAD

**Issue by leodavinci1** [keplergl/kepler.gl#1062]
Hello guys, I'm adding the translations to Portuguese following the instructions in the overview file from localizations.

[Pull Request](https://github.com/keplergl/kepler.gl/pull/1063)

**Comment by leodavinci1** [comment]
Added **locales.js** file so less configuration is needed to install a new translation:

[d1b6695](https://github.com/keplergl/kepler.gl/pull/1063/commits/d1b6695b2fdc3a967329eef78adf88650cc1d095)

**Comment by macrigiuseppe** [comment]
this is implemented
