### ISSUE TITLE
[Bug] Not able to save or export map (Windows/MSEdge)

### ISSUE THREAD

**Issue by Vself** [keplergl/kepler.gl#1069]
**Describe the bug**
I cannot save or export the map created in Kepler.

**To Reproduce**
1. Go to a created map in Kepler.gl
2. Click on 'Save', click 'login' under Dropbox
3. See error. A new blank project window popup.
or
1. Click 'Share', then click any of the four options.
2. Select the selections provided.
3. Click 'Download' or 'Export'.
4. See error. No response.

**Expected behavior**
Successfully save or export the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/63382175/78851236-a27e7d80-7a5c-11ea-99cd-f12f4261b83c.png)
![image](https://user-images.githubusercontent.com/63382175/78851315-d5c10c80-7a5c-11ea-93bd-0047b0b9eeb9.png)
![image](https://user-images.githubusercontent.com/63382175/78851340-e5d8ec00-7a5c-11ea-90f8-1ea954abfd38.png)

![image](https://user-images.githubusercontent.com/63382175/78851366-f4270800-7a5c-11ea-80bd-fac2ce966477.png)
![image](https://user-images.githubusercontent.com/63382175/78851410-128d0380-7a5d-11ea-998c-70f32bfc91ba.png)
![image](https://user-images.githubusercontent.com/63382175/78851445-289ac400-7a5d-11ea-95f8-ce6d87c0b32c.png)
![image](https://user-images.githubusercontent.com/63382175/78851494-3f411b00-7a5d-11ea-8695-77839fd88af4.png)
![image](https://user-images.githubusercontent.com/63382175/78851524-4ec06400-7a5d-11ea-9206-da0a8022ad2f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  (not OS) Windows 10
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22] 44.18362.449.0

**Smartphone (please complete the following information):**

**Additional context**
I'm wondering if the tool is specifically designed for OS system? I cannot use this online tool in Windows, can I?

**Comment by macrigiuseppe** [comment]
@Vself can you please describe the bug?

**Comment by Vself** [comment]
@macrigiuseppe 
I can't save or export the maps created in Kepler.gl
click 'Save' or 'Export' will either open a new project or no response.

**Comment by macrigiuseppe** [comment]
@Vself just tested both save and export and they are working fine. 

Can you please describe the steps (including screenshots)? It's important to know the steps you are performing to better troubleshoot your issue.
If you are using a custom dataset, would you share a sample?

**Comment by Vself** [comment]
@macrigiuseppe 
The screenshots and detailed steps are listed above.
(Go to a created map in Kepler.gl
Click on 'Save', click 'login' under Dropbox
See error. A new blank project window popup.
or
Click 'Share', then click any of the four options.
Select the selections provided.
Click 'Download' or 'Export'.
See error. No response.)
I suspect that if this tool is particularly developed for OS system? because I'm using Windows...

**Comment by macrigiuseppe** [comment]
@Vself can you please share your OS System and Browser?

**Comment by Vself** [comment]
@macrigiuseppe 
Sorry but as I said I'm using Windows 10 and Microsoft Edge.
Is this the reason why it doesn't work for me?

**Comment by macrigiuseppe** [comment]
> @macrigiuseppe
> Sorry but as I said I'm using Windows 10 and Microsoft Edge.
> Is this the reason why it doesn't work for me?

I was able to reproduce it using windows and ms edge. I will look into this issue.

In the meanwhile, you can use chrome on windows.

**Comment by Vself** [comment]
@macrigiuseppe 
Thank you very much for the suggestion.
I will try if it works in Chrome. (hopefully)

**Comment by macrigiuseppe** [comment]
@Vself i created a patch, can you try this: https://deploy-preview-1074--keplergl.netlify.com/
and let me know if it works?

**Comment by Vself** [comment]
@macrigiuseppe 
I just tried to save and export my map.
This time 'Share' works, now I can export the maps or the data.
However, 'Save' is still malfunctional... Dropbox shows Error 400, and Cartio pops a new project window like before after I logging in my account.

Thank you very much for your help, at least now I can somehow store the results after all.

**Comment by macrigiuseppe** [comment]
@Vself That's good to hear. I will deploy to prod and you can retest it. Dropbox should work once deployed into prod.
