### ISSUE TITLE
[Bug] Carto data not correctly displayed

### ISSUE THREAD

**Issue by BioBricoleur** [keplergl/kepler.gl#1075]
**Describe the bug**
After saving and publishing to carto, data laer was renamed (not a problem) but alos scrambled rather than being geolocated to the lat lon, points were in regimented but random grid

**To Reproduce**
1. Go to share map
2. Save to carto
3. copy and open shared link
4. See scrambled data, cant get back to original

**Expected behavior**
Be able to see the data layers I loaded in the right place.

**Screenshots**

**Desktop (please complete the following information):**
 - OSX, chrome 80.sumpin

**Comment by macrigiuseppe** [comment]
hey @VictorVelarde, can you look into this and check whether it's a CARTO issue?

thank you

**Comment by VictorVelarde** [comment]
Hi @BioBricoleur

I'm sorry to hear you had problems with the provider. 

I have tested it right now with my account and both public and private maps seemed to work. So I suspect the problem might be related to something in the dataset itself.

It would be very useful to have a copy of the original dataset (.csv) or at least a sample of it. And if it is a public map, would you mind sharing here the link?

**Comment by macrigiuseppe** [comment]
closing this one because inactive
