### ISSUE TITLE
white screen when selecting trip visualisation

### ISSUE THREAD

**Issue by ashydv09** [keplergl/kepler.gl#1076]
**Describe the bug**
The browser goes 

**To Reproduce**
1. Go to 'kepler.gl'
2. Add data
2. Click on 'select Trip visualisation'

**Expected behavior**
Trip map

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [e.g. chrome]

**Additional context**
Polygon is built with same

**Comment by ashydv09** [comment]
Data


id,geojson
onw,"{""features"": [{""geometry"": {""coordinates"": [[77.590508, 12.932197], [77.590591, 12.932181], [77.590508, 12.93222], [77.590508, 12.932197], [77.59051, 12.932197], [77.590508, 12.932197], [77.588867, 12.928998], [77.60179, 12.866754], [77.590508, 12.932197], [77.590591, 12.932181]], ""type"": ""LineString""}, ""properties"": {""bike_id"": ""43633"", ""user_id"": ""4387310""}, ""type"": ""Feature""}], ""type"": ""FeatureCollection""}"

**Comment by heshan0131** [comment]
Hi @ashydv09 looks like your geometry doesn't contain ts, please take a look at the how to link on select trip layer regarding data format

**Comment by macrigiuseppe** [comment]
@ashydv09 you can take a look at the doc: https://docs.kepler.gl/docs/user-guides/c-types-of-layers/k-trip

**Comment by johnathanchen** [comment]
Hi, I keep getting the same problem too, and I spent the last 5 hours trying to figure out why it's crashing. Here's an example snippet:

```
{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'geometry': {'coordinates': [[-75.19078859999998,
      39.9527732,
      0,
      1449704491271],
     [-75.190796, 39.95274, 0, 1449704521285.0],
     [-75.190796, 39.95274, 0, 1449704491271.0],
     [-75.19078859999998, 39.9527732, 0, 1449704521285.0]],
    'type': 'LineString'},
   'properties': {'distance': 1, 'duration': 0}}]}
```

Is there anything wrong with the format structure above? This is driving me crazy, and I read the docs multiple times. Love Kepler though; appreciate all the work you've put into it.

**Comment by heshan0131** [comment]
@johnathanchen the data format looks right. Can you open your chrome js console (cmd+shift+I) and take a screenshot of the red error message after the crash?

**Comment by johnathanchen** [comment]
@heshan0131 I figured it out a few hours after I posted. For some reason, Kepler doens't play well with floating point values when dealing in ms units. Forcing them into integers seemed to do the trick. I'll keep you posted if I discover anything else! Thanks for building this.

**Comment by sergiocaccamo** [comment]
Rounding to integer might make your trajectory look jumpy in time.
I noticed that it behaves properly when you round your timestamps to 3 fp digits.

Basically wrap your timestamps with `round(timestamp.timestamp(), 3)`,  assuming `timestamp` is something like `pandas.Timestamp.now()` .

Examples:
```
vehicle_positions_ts_round = []
vehicle_positions_ts_int = []
vehicle_positions_ts_float = []
latitudes = numpy.linspace(18,18.01,20)
longitudes = numpy.linspace(59,59.01,20)
timestamp = pandas.Timestamp.now()

for lat,long in zip(latitudes, longitudes):
    timestamp = timestamp + pandas.Timedelta(100, unit="ms")
    print('Current ts: ', timestamp.timestamp())
    vehicle_positions_ts_round.append([lat, long, 0, round(timestamp.timestamp(), 3)]) # GOOD and SMOOTH
    vehicle_positions_ts_int.append([lat, long, 0, int(timestamp.timestamp())]) # Works but jumpy trajectory
    vehicle_positions_ts_float.append([lat, long, 0, timestamp.timestamp()]) # TRIP DOES NOT WORK,polygon does
```
