### ISSUE TITLE
[QUESTION] It is possible set the strokeColor scale manually?

### ISSUE THREAD

**Issue by miketsui3a** [keplergl/kepler.gl#1080]
let say I have a data represent traffic condition of a road.
I have a congestion index ranges from 0 to 9.
I want 0-2 showing color green,  3-7 showing color yellow and 8-9 showing red.
Is it possible?

**Comment by heshan0131** [comment]
@miketsui3a what's the format of your data? in geojson layer you can define strokeColor a s property for the feature, which makes apply arbitrary color possible.

https://docs.kepler.gl/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map#2-auto-styling
