### ISSUE TITLE
Map addition.

### ISSUE THREAD

**Issue by YinZhaoJie** [keplergl/kepler.gl#1096]
# Is this tool : "https://www.mapbox.cn/labs/mbxdataexplorer/"  developed by your team or company?

## Is there any possible that you  make the tool's map embed into kepler.gl?  As you know,in China,we need map with a map-review-number (in Chinese: 审图号) 。

![map_review_number](https://user-images.githubusercontent.com/46802408/80444722-fa662100-8944-11ea-9196-e030392fb8f4.png)

**Comment by macrigiuseppe** [comment]
@YinZhaoJie we didn't build the above tool and as far as Uber and Mapbox, we have a running collaboration but we are not "family" as you mentioned.

Incorporating this tool is not part of Kepler.gl roadmap
