### ISSUE TITLE
How to build demo-app as static?

### ISSUE THREAD

**Issue by eugenest** [keplergl/kepler.gl#1097]
hi and thank you for kepler)

my issue is like this https://github.com/keplergl/kepler.gl/issues/354

are there options to run kepler-gl demo-app without node at all (for example, if node isn't available on production server)? i want just to have production webpack build and upload index.html and bundle.js on server with configured nginx

i've tried, but with no success — after webpack -p and deploying files i see blank page

in devtools i see empty <div></div> in document.body with no content
console has no errors also

both index.html and bundle.js are available by http (checked it on devtools)

PS: eventually i've found umd-client example, which fits to my requirements, but anyway, what am i missing on build-demo-app-as-static approach?

thanks in advance

**Comment by macrigiuseppe** [comment]
@eugenest in order to compile the demo app into a single file, you need to create a build step in package.json.
You can look at the website folder to find out the build step you require, here: https://github.com/keplergl/kepler.gl/blob/master/website/package.json#L19

**Comment by eugenest** [comment]
cannot check it right now, but looks like what i need

thank you!
