### ISSUE TITLE
Binning for Hexbin changes when using timeline playback while moving the map around.

### ISSUE THREAD

**Issue by jvanlier** [keplergl/kepler.gl#1103]
**Describe the bug**
When using the Hexbin, and the timeline playback feature, the bins shift around when the map is moved. They do not shift around when moving the map while on pause. This makes it quite awkward to investigate and compare locations while the timeline is progressing.

See attached video (in the attached zip).

**To Reproduce**
I attached a couple of files in the .zip:
- CSV with simulated data
- Corresponding Kepler.gl config
- Jupyter Notebook to create the map.
- HTML file with the map created (through Jupyter)

Easiest way to reproduce is to simply open the HTML file, press the Play button and move the map around.

**Expected behavior**
I would expect consistent binning across time when moving the map around.

**Screenshots**
Please see the attached video - it shows the issue better than screenshots could.

**Desktop (please complete the following information):**
- OS: MacOS 10.15.4
- Browser: Chrome  81.0.4044.129
- Python package `keplergl==0.1.2`

**Additional context**
n/a

[hexbin-shift-issue.zip](https://github.com/keplergl/kepler.gl/files/4573965/hexbin-shift-issue.zip)

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/issues/1104

**Comment by heshan0131** [comment]
#1110 

Please upgrade to keplergl==0.2.0, it should fix this

**Comment by jvanlier** [comment]
Confirmed! Works now, thanks!
