### ISSUE TITLE
[Bug][Jupyter widget] Can not save map to html

### ISSUE THREAD

**Issue by NhuNguyenThao** [keplergl/kepler.gl#1106]
**Describe the bug**
I cannot save my map to html (nearly 200MB). The error is showed in the screenshot below.

**Environment (please complete the following information):**
 - Python version: Python 3.8.1
 - keplergl Widget version [e.g. 0.1.0]

![Screen Shot 2020-05-07 at 9 53 27 AM](https://user-images.githubusercontent.com/41143727/81249520-063e9b00-9049-11ea-8a34-e4d981c99126.png)
![Screen Shot 2020-05-07 at 9 53 32 AM](https://user-images.githubusercontent.com/41143727/81249523-08085e80-9049-11ea-9008-e5d8e982a41c.png)

**Comment by heshan0131** [comment]
Please convert the Timestamp in your DataFrame to a unix time string and try again
