### ISSUE TITLE
Question about Y axis in timeline bar

### ISSUE THREAD

**Issue by elaineleeworld** [keplergl/kepler.gl#1107]
I successfully created a Kepler.gl map to use for my data.  Just a question as to what data the default Y axis is displaying?  When I choose filters for the timeline bar, it correctly displays corresponding data, ie Latitude etc.  The default Y axis, however, appears to display spikes in data I am not sure why.   I have attached a screenshot of a spike example.  There is no default pop up when I hover over the highlighted bar to see what data it is, like when I hover on the filtered data.  Is the default Y axis an aggregate of all the data that is being used?  @heshan0131 wondering if you may know or can explain what the default Y axis data is displaying?  Thank you in advance.  Elaine
![Screen Shot 2020-05-07 at 4 27 19 PM](https://user-images.githubusercontent.com/8484891/81354163-c050f980-907f-11ea-9134-73d2c73db994.png)

**Comment by heshan0131** [comment]
it's a time histogram, with a fix number of bins set to 100

**Comment by elaineleeworld** [comment]
ah I see.  thanks, @heshan0131 for your quick response. can you direct me to where in the Kepler codebase is doing this aggregation of bins to 100?

**Comment by rdhara** [comment]
@elaineleeworld Here you go: https://github.com/keplergl/kepler.gl/blob/ee9e460f6aacd06ef976968f04b79f0b3479bc96/src/utils/filter-utils.js#L774

**Comment by elaineleeworld** [comment]
thank you!  @rdhara
