### ISSUE TITLE
'Units' text field for column data values

### ISSUE THREAD

**Issue by jcfbeardsley** [keplergl/kepler.gl#1122]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for Kepler to inform the user of the units of the variable they are exploring. Although this is not required for Kepler to function, it would be really useful if these could be defined and displayed when the user is viewing tooltips, labels, legends etc. 

**Describe the solution you'd like**
Once a dataset is loaded, it would be great to have the option to define the units for each column in the dataset as a text field value (e.g $/£, °C/°F, km/miles/meters etc.), which would then be appended to the data value (or prepended in the case of a currency symbol) when viewing legends, tooltips and labels. Where no unit is specified, Kepler would continue to render variables in its current fashion.

**Describe alternatives you've considered**
Units are currently being incorporated into the column name (e.g. 'temp_deg_c') as a workaround, which is okay but not as 'tidy' as it could be.

**Additional context**
Nil.

**Comment by heshan0131** [comment]
There is been worked on, @b2kdaman is working on the tooltip formatting functionality

**Comment by b2kdaman** [comment]
Check this feature request https://github.com/keplergl/kepler.gl/issues/1081

**Comment by jcfbeardsley** [comment]
Fantastic, thanks very much.
