### ISSUE TITLE
[Bug] Exported HTML file does not save custom tooltips

### ISSUE THREAD

**Issue by BashirAli** [keplergl/kepler.gl#1160]
**Describe the bug**
When modifying tooltips then exporting map to HTML, tooltips do not stay modified, rather they reset to default.
**To Reproduce**
1. Modify tooltips under Interactions
2. Click on 'Export to HTML'
3. Open saved HTML file
4. Hover over plotted data and see tooltips are not customised.

**Expected behavior**

**Desktop (please complete the following information):**
 - Windows 10 64 bit
 - Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by will-locsci** [comment]
Same as #1144

**Comment by heshan0131** [comment]
fixes posted to #1162
