### ISSUE TITLE
[Bug] Customiaztion of tooltip fileds doesn't stored in exported map

### ISSUE THREAD

**Issue by tbicr** [keplergl/kepler.gl#1162]
**Describe the bug**
Customiaztion of tooltip fileds doesn't stored in exported map.

**To Reproduce**
1. Add new geojson dataset with 6+ properties
2. Select polygons visualization and select integer filed for visualization
3. Go to tooltip configuration and select 6+ features.
4. Export map
5. Open exported map
6. See that tooltip on exported map not configured

**Expected behavior**
Changes on tooltip configuation nice to store within export map.

**Screenshots**
![image](https://user-images.githubusercontent.com/416731/85277568-48525d80-b48c-11ea-8b99-3b8f28936af2.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser: firefox
 - Version 77.0.1

**Smartphone (please complete the following information):**
No

**Additional context**
No

**Comment by heshan0131** [comment]
@tbicr how are you exporting the map? downloaded a json or html?

**Comment by tbicr** [comment]
@heshan0131 , html in `Allow users to read the map` mode

**Comment by will-locsci** [comment]
Please also see #1144 & #1160

**Comment by heshan0131** [comment]
this should be fixed now. for your exported html to load, open it in a text editor and change the kepler.gl version in this line to `2.3.0`

```
   <!-- Load Kepler.gl -->
        <script src="https://unpkg.com/kepler.gl@2.3.0/umd/keplergl.min.js" crossorigin></script>

```

**Comment by tbicr** [comment]
Thanks!
