### ISSUE TITLE
The division on colour map based on values is not linear- can it be made custom?

### ISSUE THREAD

**Issue by JB-data** [keplergl/kepler.gl#1164]
I am impressed with kepler gl-very handy to get some nice results quick, but still had a question.
I created a h3 map with 10 colours based on values that range from 0-100k.
I notice that the division is not linear: it is not like this that for  every 5k increase in value, a new colour is assigned. As a result all values from >3k to 100k are assigned the same colour, which result in a big part of my map having the same colour.
Is there a method to change this and decide yourself what slices of the dataset will receive the same colour? I would prefer to have many more colour distinctions for the higher values. Or a linear relation between colour/value.
Thanks for the good work!

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/issues/399

Please follow the above issue

**Comment by heshan0131** [comment]
The default color scale is quantile, you can change it to quantize, which is linear scale
