### ISSUE TITLE
[Bug] GeoJSON with GeometryCollection causes crash

### ISSUE THREAD

**Issue by dudv** [keplergl/kepler.gl#1167]
**Describe the bug**
Providing GeoJSON containing GeometryCollection as data causes crash

**To Reproduce**
1. Go to https://kepler.gl/demo
2. Upload the JSON file below
4. Screen turns blank, in the console I see the following:
```
bundle.js:113 Error: Pixel project matrix not invertible
    at t.e (bundle.js:78)
    at new t (bundle.js:12)
    at bundle.js:19
    at gu (bundle.js:113)
    at ls (bundle.js:113)
    at us (bundle.js:113)
    at $u (bundle.js:113)
    at bundle.js:113
    at t.unstable_runWithPriority (bundle.js:121)
    at Yi (bundle.js:113)
```

**Expected behavior**
No crash happens, a single point is rendered

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 83

**JSON to test**
```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "GeometryCollection",
                "geometries": [
                    {
                        "type": "Point",
                        "coordinates": [
                            37.427849229309786,
                            -122.14948116363452
                        ]
                    }
                ]
            }
        }
    ]
}
```

**Comment by heshan0131** [comment]
`GeometryCollection` is not supported in kepler, break them into individual features inside `FeatureCollection`

**Comment by dudv** [comment]
Well, crashing still does not seem like a great way to handle it. Also, it's not documented anywhere.

**Comment by heshan0131** [comment]
it is documented under [supported GeoJSON format](https://docs.kepler.gl/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map#1-feature-types)

But you are right, it shouldn't crash the app
