### ISSUE TITLE
[Bug] Map config can not be set dynamically on addDataToMap for geojson layer

### ISSUE THREAD

**Issue by saricicekibrahim** [keplergl/kepler.gl#1175]
**Describe the bug**

May be there is another way to set config but seems bug for me.
I'm using json for points and geojson for non point objects.
This is the code
```

  if (_result) {
    let datasets = _result;
    //check geometryType_
    if (mapDataParams.geometryType !== GEOMETRY_TYPES.POINT) {
      datasets = {
        //process data if result is geoJson
        data: processGeojson(_result)
      }
    }
    this.props.dispatch(
      wrapTo("keplerMap", addDataToMap(
        {
          datasets: datasets,
           // set config if exists. problem on geojson !!
          config: this.state.mapConfig ? this.state.mapConfig : config
        })
      )
    );
  }
```

**Resets config on mapLoad for geoJson! But works for json layer.**

**Expected behavior**
config should be set dynamically also for geojson datasets

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser [chrome]
 - Version [83.0.4103.116]

**Additional context**
Kepler version 1.1.8

**Comment by heshan0131** [comment]
it's hard to know what went wrong with the full context. looks like you are not given you geojson dataset an `id` that matches the `layer.config.dataId` of your layer. your dataset should be 
`{data: processGeojson(_result), info: {id: 'my_data'))` for kepler to matches this data to your layer s in the config

**Comment by saricicekibrahim** [comment]
thank you that works
