### ISSUE TITLE
ability to add imagery tilelayers that aren't Mapbox

### ISSUE THREAD

**Issue by magamonsta** [keplergl/kepler.gl#118]
mapbox is great but it would be hugely beneficial if users had the option to load in WMS/WMTS imagery tilelayers as basemaps that are hosted/sold by other companies

or if you can't allow entire tilelayers to be added, consider adding single raster images, especially when users want to use kepler in disconnected environments where they woudn't have access to mapbox baselayers they could load a single raster image that is stored locally instead and still get the same effect

**Comment by yiyaya66** [comment]
@magamonsta can you share an example using WMS/WMTS  and also any documentation regarding this if applicable?

**Comment by magamonsta** [comment]
yeah! not sure if you're familiar with [leaflet](https://leafletjs.com/), it allows you to build customized maps and load in various basemaps and tilelayers, here is a link to their documentation for adding in a [tilelayer](https://leafletjs.com/reference-1.3.0.html#tilelayer) and adding in a [wms](https://leafletjs.com/reference-1.3.0.html#tilelayer-wms). in past projects i've been required to use certain base maps, similar to some of these that [ESRI](https://services.arcgisonline.com/arcgis/rest/services) has.

**Comment by wmhafiz** [comment]
any luck on having custom wms/wmts support so far? our company maintain our own basemap service and thats the only issue preventing us from using this amazing library

**Comment by ibgreen** [comment]
@wmhafiz It does not look too hard to add support for this, and I agree that this would be a valuable addition to kepler.gl / deck.gl / loaders.gl. If someone contributed a solid implementation, it would almost certainly be accepted! 

At the same time, keep in mind that the kepler.gl open source team is essentially working for free, and it may be hard for them to justify adding support for a backend system they are not using themselves.

However, if this is really critical to your use case, feel free to contact me directly to discuss options (e.g. on the kepler.gl slack channel or via my github profile).

**Comment by wmhafiz** [comment]
Thats great! I would be interested to have a go at it, if u can help point me in the right direction. I will try to find some time to read through the source code first though.

What's your username on slack? i just joined the slack channel and hope to talk to you soon!

**Comment by ibgreen** [comment]
@wmhafiz  I found you on kepler.gl slack and messaged you - I will summarize in repo later if we make progress.

**Comment by dguceleste** [comment]
Hi guys. Any news about this?

**Comment by ibgreen** [comment]
Unfortunately we failed to connect, so no progress was made.

**Comment by kylebarron** [comment]
This issue's title could be improved, because here the question is specifically about loading tiles _in a non-XYZ_ tile index. You can already load non-Mapbox imagery tile layers by referencing them in a `style.json` file, see https://github.com/keplergl/kepler.gl/issues/406#issuecomment-644946912. 

This issue is more geared towards supporting the WMS/WMTS indexing/tile request systems. I don't know enough about them to comment.

**Comment by julienr** [comment]
I managed to load a WMS as a custom basemap map style with a json file looking like this (this needs to be accessible through a URL which you then use as the "map style URL" in kepler).
```
{
  "version": 8,
  "name": "My raster",
  "sources": {
    "raster-source-1": {
      "type": "raster",
      "tiles": [
        "https://wms.zh.ch/OrthoZHWMS?Request=GetMap&layers=ortho_18&bbox={bbox-epsg-3857}&crs=EPSG:3857&format=image/png&width=256&height=256&version=1.3.0"
      ],
      "scheme": "tms"
    }
  },
  "layers": [
    {
      "id": "raster-layer-1",
      "type": "raster",
      "source": "raster-source-1"
    }
  ],
  "id": "my-raster"
}
```

This particular WMS only contains data over zurich switzerland. You can load the following GeoJSON in kepler (a square over Zurich) to test it:
```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[8.496551513671873,47.34696504890934],[8.573455810546875,47.34696504890934],[8.573455810546875,47.38858773975688],[8.496551513671873,47.38858773975688],[8.496551513671873,47.34696504890934]]]}}]}
```

**Comment by macrigiuseppe** [comment]
please have a look at this one: https://github.com/keplergl/kepler.gl/pull/1440

**Comment by runsalot87** [comment]
> I managed to load a WMS as a custom basemap map style with a json file looking like this (this needs to be accessible through a URL which you then use as the "map style URL" in kepler).
> 
> ```
> {
>   "version": 8,
>   "name": "My raster",
>   "sources": {
>     "raster-source-1": {
>       "type": "raster",
>       "tiles": [
>         "https://wms.zh.ch/OrthoZHWMS?Request=GetMap&layers=ortho_18&bbox={bbox-epsg-3857}&crs=EPSG:3857&format=image/png&width=256&height=256&version=1.3.0"
>       ],
>       "scheme": "tms"
>     }
>   },
>   "layers": [
>     {
>       "id": "raster-layer-1",
>       "type": "raster",
>       "source": "raster-source-1"
>     }
>   ],
>   "id": "my-raster"
> }
> ```
> 
> This particular WMS only contains data over zurich switzerland. You can load the following GeoJSON in kepler (a square over Zurich) to test it:
> 
> ```
> {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[8.496551513671873,47.34696504890934],[8.573455810546875,47.34696504890934],[8.573455810546875,47.38858773975688],[8.496551513671873,47.38858773975688],[8.496551513671873,47.34696504890934]]]}}]}
> ```

@julienr - does this method still work? I cannot seem to get this to work (probably user error on my part).  Could you perhaps share with me how you did this? Also, have you had any luck with with a XYZ tiler server? Thanks in advance!

**Comment by julienr** [comment]
@runsalot87 I haven't used kepler recently, so I'm not sure if this is still working. Never tried it on XYZ server.

**Comment by osterm38** [comment]
@runsalot87 : With slight modification, @julienr 's style works (python 3.9.10, jupyterlab 3.3.4, keplergl 0.3.2).  I got the [following style.json](https://raw.githubusercontent.com/osterm38/mapbox-styles/main/basic_zh.json) working, though this (and a few adjacent in my repo) mostly serves as an example for when I find a better WMS (non-xyz) basemap to load into kepler: 
```
{
    "version": 8,
    "id": "my-raster",
    "name": "My raster",
    "zoom": 1,
    "pitch": 0,
    "bearing": 0,
    "center": [
      0,
      0
    ],
    "layers": [
        {
          "id": "raster-layer-1",
          "type": "raster",
          "source": "raster-source-1",
          "paint": {}
        }
      ],
      "sources": {
      "raster-source-1": {
        "type": "raster",
        "tiles": [
          "https://wms.zh.ch/OrthoZHWMS?Request=GetMap&layers=ortho_s_18&bbox={bbox-epsg-3857}&crs=EPSG:3857&format=image/png&width=256&height=256&version=1.3.0"
        ],
        "tileSize": 256
      }
    }
  }
```
