### ISSUE TITLE
Kepler.gl not mapping co-ordinates properly

### ISSUE THREAD

**Issue by simeon9696** [keplergl/kepler.gl#1183]
I'm using the data from the repository _[COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University.](https://github.com/CSSEGISandData/COVID-19)_ Usually the data points get mapped correctly but recently they haven't. They seem to be offset and end up improperly placed on the map (but just with respect to location, see image) 

- Clone the repository 
- Load the file `time_series_covid19_confirmed_global.csv` into [https://kepler.gl/demo](https://kepler.gl/demo)
- Use the following settings to get a Hexabin layer

Settings: 
1. After import, select Add Layer
2. Layer type : Hexbin 
    Lat: Lat
    Lon: Long
    Radius: 35km
    Height: Elevation Scale 100
    Height: Height based on 7/9/2020

**Expected behavior**
The co-ordinates in the file get mapped to the proper cities etc on the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/31748055/87182876-ffcfd800-c2b2-11ea-905c-0ce3c647cec1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by heshan0131** [comment]
hi please send a snippet of the data when you create a bug. Likely the coordinate is not in mercator lat lng format

**Comment by simeon9696** [comment]
> hi please send a snippet of the data when you create a bug. Likely the coordinate is not in mercator lat lng format
 Apologies, please see the attached image. Is there a difference betweeen mercator lat long and just lat lng?  


![image](https://user-images.githubusercontent.com/31748055/87212864-daf95600-c2ee-11ea-8845-5a29e5588253.png)

**Comment by heshan0131** [comment]
The lat lng value looks correct. Can you confirm the wrong project only happens in hexbin layer, not point layer?

Could you send a link to the dataset you are using?

**Comment by simeon9696** [comment]
@heshan0131  Can confirm it occurs with the point layer as well. Here's the link to the dataset [https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)

![image](https://user-images.githubusercontent.com/31748055/87442297-1c755400-c5c2-11ea-94cd-8904d0af67f8.png)

**Comment by simeon9696** [comment]
> @heshan0131 Can confirm it occurs with the point layer as well. Here's the link to the dataset https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
> 
> ![image](https://user-images.githubusercontent.com/31748055/87442297-1c755400-c5c2-11ea-94cd-8904d0af67f8.png)

Hi @heshan0131 any update?

**Comment by heshan0131** [comment]
@simeon9696 
I wasn't able to reproduce this error. Are you using http://kepler.gl/demo ?
Here is what I did
1. Go to https://kepler.gl/demo
2. Select 'Load Map using URL'
<img width="959" alt="Screen Shot 2020-07-30 at 2 24 41 PM" src="https://user-images.githubusercontent.com/3605556/88976149-69b71e00-d270-11ea-8297-d29332beb709.png">
3. Enter

`https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv`

4. Create a point Layer:
<img width="1488" alt="Screen Shot 2020-07-30 at 2 25 48 PM" src="https://user-images.githubusercontent.com/3605556/88976238-93704500-d270-11ea-9bb0-366fdfaa3194.png">

I put up an my map here, let me know if you are seeing the same thing
https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/mz50g5dc5c7gpow/keplergl_jiqdmlq.json

**Comment by simeon9696** [comment]
@heshan0131 not entirely sure why it didn't work in the first place but it's back to normal. Even the hexbin layer. Thanks for looking into it and getting back to me!

**Comment by rkoten** [comment]
To anyone who runs into this and finds this thread: your coordinates are probably flipped and you're using lats as lons and vice versa.
