### ISSUE TITLE
[Bug] Unable to apply "Map Layers" settings on custom map styles

### ISSUE THREAD

**Issue by thucnc** [keplergl/kepler.gl#1198]
In kepler.gl's `Base map` panel, there is a control called `map layers` to hide/show some data on current map style. This feature works with default map styles such as `Dark/Light`, but when I added some new styles such as `Blue Print` (in screenshot), I can't apply the change on my map with `Map Layers` control. 

<img width="1075" alt="Screen Shot 2020-07-18 at 1 45 45 PM" src="https://user-images.githubusercontent.com/2088055/87846882-9a589880-c8fd-11ea-98aa-ecbe4563cbbf.png">

**Comment by heshan0131** [comment]
@thucnc the map layer detection rely fulling on layer.id in your style
Here are the matcing rules...
```
export const DEFAULT_LAYER_GROUPS = [
  {
    slug: 'label',
    filter: ({id}) => id.match(/(?=(label|place-|poi-))/),
    defaultVisibility: true
  },
  {
    slug: 'road',
    filter: ({id}) => id.match(/(?=(road|railway|tunnel|street|bridge))(?!.*label)/),
    defaultVisibility: true
  },
  {
    slug: 'border',
    filter: ({id}) => id.match(/border|boundaries/),
    defaultVisibility: false
  },
  {
    slug: 'building',
    filter: ({id}) => id.match(/building/),
    defaultVisibility: true
  },
  {
    slug: 'water',
    filter: ({id}) => id.match(/(?=(water|stream|ferry))/),
    defaultVisibility: true
  },
  {
    slug: 'land',
    filter: ({id}) => id.match(/(?=(parks|landcover|industrial|sand|hillshade))/),
    defaultVisibility: true
  },
  {
    slug: '3d building',
    filter: () => false,
    defaultVisibility: false
  }
];
```

**Comment by thucnc** [comment]
@heshan0131 My **"blueprint"** style came from this repository https://github.com/jingsam/mapbox-gl-styles/blob/master/Blueprint.json and it doesn't work with "Map Layers" control.
May you take a look.

Thanks

**Comment by thucnc** [comment]
Hi, 
Please ignore my previous comment. It's our bug when adding map styles in code. The map layers work fine when I use "Add Map Style" button in the tool.

Thanks,
