### ISSUE TITLE
add a method to return html as string without writing to disk.

### ISSUE THREAD

**Issue by francois-baptiste** [keplergl/kepler.gl#1205]
Add a method to return html as string without writing to disk.

This can be useful to serve kepler gl with a python web server as flask as it is possible to do with folium

For instance https://python-visualization.github.io/folium/flask.html

**Comment by francois-baptiste** [comment]
#1202

**Comment by francois-baptiste** [comment]
#1202

**Comment by waterchinap** [comment]
Hi, I tried the _repr_html_() as show in the documentaion.
and find out it is not work.
It seems the funciton has not online?

**Comment by francois-baptiste** [comment]
@waterchinap version 2.1 does not include this change and then have not yet been posted on pypi.org.
Since then you can pip install from git master branch or copy paste  [keplergl.py  master branch file](https://github.com/keplergl/kepler.gl/blob/master/bindings/kepler.gl-jupyter/keplergl/keplergl.py) into your `site-package/keplergl`.

**Comment by johnwmillr** [comment]
Hi @francois-baptiste or @heshan0131, do you know when this version of `keplergl` with the `_repr_html_` method might be uploaded to PyPI?

**Comment by heshan0131** [comment]
0.3.0 should have it
