### ISSUE TITLE
[Bug] Export Image not working

### ISSUE THREAD

**Issue by ford-scoop** [keplergl/kepler.gl#1222]
**Describe the bug**
Kepler hangs when loading the image export screen and fails to complete the export.

**To Reproduce**
1. Go to 'kepler.gl/demo'
2. Load data - I tried with several of my own datasets as well as with the Uber Pittsburgh movement sample data, so it seems to be independent of the data
3. Click on `Share`
4. Click on `Export Image`
5. Error occurs

**Expected behavior**
Ability to export/download an image of the map.

**Screenshots**
Export image window:
![image](https://user-images.githubusercontent.com/47126227/89465797-8eefd480-d727-11ea-81ec-2e61ed389b07.png)
Javascript console: 
![image](https://user-images.githubusercontent.com/47126227/89465859-aa5adf80-d727-11ea-9a0e-4a17a9592f1f.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Chrome
 - Version: 84.0.4147.105 

Also tried on Safari v 13.1 with same OS

**Additional context**
First noticed yesterday, 8/4/20, and was also seen on coworker's laptop (similar specs to this desktop info).

**Comment by heshan0131** [comment]
This should be resolved now

**Comment by venumallireddy** [comment]
![image](https://user-images.githubusercontent.com/68327501/91692413-fc581f00-eb86-11ea-8d64-b88795e2c9e1.png)

Hi,
Even i'm gerring the same , In my localhost "Export Image" is not working with my react app, Even I'm not getting errors in the console

**Comment by heshan0131** [comment]
The css issue should not cause export image to fail, is it catched, there is some other issue there. We just rewrote the export image logic, update kepler.gl and give it a try?
