### ISSUE TITLE
[Bug] Error 404 when exporting map image

### ISSUE THREAD

**Issue by mjvar** [keplergl/kepler.gl#1224]
**Describe the bug**
The website refuses to export any map images. This feature was working for me just a few days ago, but now no matter which browser I try or what data I use, I am unable to export a map image. It even occurs when there is no data uploaded.

**To Reproduce**
1. Open kepler.gl
2. Click "Share", then "Export Image"

**Expected behavior**
To export an image of the map.

**Screenshots**
<img width="552" alt="Screen Shot 2020-08-07 at 7 48 23 PM" src="https://user-images.githubusercontent.com/54776369/89642764-01f37980-d8e7-11ea-8a00-df4cdc1a9dc2.png">
<img width="1440" alt="Screen Shot 2020-08-07 at 7 46 33 PM" src="https://user-images.githubusercontent.com/54776369/89642623-b5a83980-d8e6-11ea-85d7-0ec0fe29f830.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Tested on Safari, Chrome, and Brave. 

**Additional context**
The error appears to have nothing to do with the user end, because it persists regardless of whether or not data was uploaded or which browser I am using.

**Comment by heshan0131** [comment]
fixed
