### ISSUE TITLE
[Bug] Cannot display geojson from URL in React Kepler.gl, works in demo

### ISSUE THREAD

**Issue by glher** [keplergl/kepler.gl#1231]
**Describe the bug**
A geojson from a API URL is not loading in my local React app. However, the same URL does load without issue in the demo.

**More information**

https://stackoverflow.com/questions/63379668/cannot-display-geojson-from-url-in-react-kepler-gl

I cannot get the Kepler.gl React code to display my geojson from a localhost API URL. When I use the Kepler.gl/demo website, I can "Load Data From URL" and input my same localhost URL and it works.

I'm following this tutorial : https://youtu.be/BEZjt08Myxs with this source code https://github.com/leighhalliday/keplergl-demo

My API returns a geojson:

    http://localhost:8000/api/mytest/distance.geojson

The geojson looks like:

    {"type":"FeatureCollection","features":[{"id":183124,"type":"Feature","geometry":{"type":"Point","coordinates":[-7.6192,33.59279999999999]},"properties":{"event_date":"1999-12-24","event_time":"1999-12-24T00:00:00Z","event_type":"Test","sub_event_type":"Test","notes":"This is a test of the application, hopefully this displays"}}]}

The App.js looks like:

    import React from "react";
    import keplerGlReducer from "kepler.gl/reducers";
    import { createStore, combineReducers, applyMiddleware } from "redux";
    import { taskMiddleware } from "react-palm/tasks";
    import { Provider, useDispatch } from "react-redux";
    import KeplerGl from "kepler.gl";
    import { addDataToMap } from "kepler.gl/actions";
    import useSwr from "swr";

    const reducers = combineReducers({
      keplerGl: keplerGlReducer
    });

    const store = createStore(reducers, {}, applyMiddleware(taskMiddleware));

    export default function App() {
      return (
        <Provider store={store}>
          <Map />
        </Provider>
      );
    }

    function Map() {
      const dispatch = useDispatch();
      const { data } = useSwr("conflict", async () => {
        const response = await fetch(
          "http://localhost:8000/api/test/distance.geojson"
        );
        const data = await response.json();
        console.log(data);
        return data;
      });

      React.useEffect(() => {
        if (data) {
          dispatch(
            addDataToMap({
              datasets: {
                info: {
                  label: "TESTS",
                  id: "test20"
                },
                 data
              },
               option: {
                centerMap: true,
                readOnly: false
              },
              config: {}
            })
          );
        }
       }, [dispatch, data]);

      return (
        <KeplerGl
          id="test"
          mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_API}
          width={window.innerWidth}
          height={window.innerHeight}
        />
      );
    }

Note that when I use the data from the tutorial in the code in the Map() function, that is:

https://gist.githubusercontent.com/leighhalliday/a994915d8050e90d413515e97babd3b3/raw/a3eaaadcc784168e3845a98931780bd60afb362f/covid19.json

Then it works great. Maybe I need to add a reference to a geojson somewhere, though I thought that was the point of forcing the geojson extension in the URL.

When I go to the kepler.gl demo, I can use the Load Map From URL function to correctly display my localhost URL. I can also download the geojson to my desktop and use the Load Files, which also works great.

I'm kind of at a loss here.

Here is my package.json (identical as the one from the tutorial):

    {
      "name": "kepler-demo",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@testing-library/jest-dom": "^4.2.4",
        "@testing-library/react": "^9.3.2",
        "@testing-library/user-event": "^7.1.2",
        "kepler.gl": "^2.3.1",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "react-palm": "^3.1.2",
        "react-redux": "^7.2.0",
        "react-scripts": "3.4.1",
        "redux": "^4.0.5",
        "styled-components": "^5.0.1",
        "swr": "^0.1.18"
       },
       "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": "react-app"
      },
       "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
         "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      }
    }

Here is the result from the console.log(data) in the Map() function, showing me that something is seen (the correct result, which looks like a geojson to me)

[![See screenshot][1]][1]

[![See screenshot][2]][2]

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Version 2.3.1

  [1]: https://i.stack.imgur.com/RdZau.png
  [2]: https://i.stack.imgur.com/UEVao.jpg

**Comment by majkprpik** [comment]
Hi, 

in documentation there is a part about data field:

data.datasets.data Object *required The data object, in a tabular format with 2 properties fields and rows
data.datasets.data.fields Array<Object> *required Array of fields,
data.datasets.data.fields.name string *required Name of the field,
data.datasets.data.rows Array<Array> *required Array of rows, in a tabular format with fields and rows

https://docs.kepler.gl/docs/api-reference/actions/actions#adddatatomap

your data need to be in format:

{
 fields: []
 rows: []
}


How I managed to do this:

1. Upload your data with UI
2. Export your data:  Share button => Export Map => JSON (Map format)
 - make object from that data
  let newData =  {
      fields: [
        ...data.datasets[0].data.fields
      ],
      rows: [
        ...data.datasets[0].data.allData
      ]
    }
3. Copy Map config for addDataToMap 

Hope this helps.

**Comment by glher** [comment]
Ah that makes perfect sense, I got stuck on "my geojson is valid, what's going on" and didn't see that part in the documentation!

Thank you for your time, have a great day!

**Comment by rabira-hierpa** [comment]
Had the similar issue with `geojson` files but used `processGeojson` of the `Process` property which comes in handy to handle data conversion between `csv,geojson and json` and `kepler.gl` format.

Example 

```javascript
  import { processGeojson } from "kepler.gl/processors";
  const buildingData = useSWR("buildings", async () => {
    const response = await fetch(
      "https://raw.githubusercontent.com/rabira-hierpa/react-3d-maps/main/data/Building_noZ.geojson"
    );
    const buildingData = await response.json();
    return processGeojson(buildingData);
  });
```

`processGeojson` file will automatically convert the data to the `fields` and `rows` data format required by kepler the same goes if you have `csv` files you just have to use `processCSV` files
