### ISSUE TITLE
Add a way to export geometry of polygon filter

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#1241]
After drawing a polygon. make it possible to copy the geometry of the polygon

**Comment by fb39ca4** [comment]
Looking for exactly this! I want to be able to draw polygons in a map and give the coordinates to the rest of my application.

**Comment by Natday** [comment]
Also super interested in this feature!

**Comment by ntl67** [comment]
This would be amazing! Would also be great to be able to upload polygons in kml format - would be a huge help for mapping.

**Comment by gustavoproprio** [comment]
Hey I'm really looking forward to this one! Let me follow this thread. I want to keep updated on this topic too

**Comment by gustavoproprio** [comment]
Thank you for the thread link @heshan0131 ! Looking forward to the acceptance of your pull request!

**Comment by heshan0131** [comment]
Merged, kepler.gl/demo should be updated
will be included in kepler.gl@2.4.1

**Comment by rocket-yg** [comment]
Hey I am able to copy the polygon geometry.

Can someone guide how to then recreate it back using the content for eg, the given one..


`{"type":"Polygon","coordinates":[[[77.17102690725116,28.66363254152939],[77.18592165403177,28.69951849844307],[77.23216206194594,28.706148252958577],[77.278624779515,28.670849726995332],[77.27306703818036,28.634758830428233],[77.21059802556225,28.623441289467213],[77.17102690725116,28.66363254152939]]]}`
