### ISSUE TITLE
[Bug]  Kepler Demo React Intl Error -  Missing message: "modal.loadData.remote" for locale: "en"

### ISSUE THREAD

**Issue by LeonanCarvalho** [keplergl/kepler.gl#1247]
**Describe the bug**
For some reason, the application is not parsing the message keys at Load Remote Modal.

**To Reproduce**
1. Download latest source code
2. Install and Run example ["Demo APP"](https://github.com/keplergl/kepler.gl/tree/master/examples/demo-app)
3. Open "Add-data" modal

**Expected behavior**

**Screenshots**
![screen-capture (5)](https://user-images.githubusercontent.com/3593706/91090833-14cab580-e62c-11ea-8e93-6573b58d5543.gif)
![image](https://user-images.githubusercontent.com/3593706/91091013-58252400-e62c-11ea-89ed-13261ad5c77b.png)

**Desktop (please complete the following information):**
 - OS: Win: 10
 - Browser Chrome
 - Version 84.0.4147.135  64 bits

**Additional context**
It looks okay at https://kepler.gl/demo, I have React Developer Tool installed.

**Comment by LeonanCarvalho** [comment]
This issue appears to be related to #1265 
The code from the demo example seans to be outdated

**Comment by ilhamakbar12** [comment]
> This issue appears to be related to #1265
> The code from the demo example seans to be outdated

i've try it, you should try run demo from kepler.gl dir, not from kepler.gl/example/demo-app/ dir, use 'npm start'. because there is some update at localization code.
