### ISSUE TITLE
[Bug] Unable to switch data sources

### ISSUE THREAD

**Issue by jayaramkasi** [keplergl/kepler.gl#1249]
**Describe the bug**
Data sources switching is disabled. Not able to enable it. 

**To Reproduce**
1. Add a data source
2. Add a layer (any layer).
3. Add another data source
4. Add another layer (any layer).

It is selecting data source 1 by default. 

**Expected behavior**
User should have the flexibility to choose which data source they want for each layer.

**Screenshots**
![Screenshot 2020-08-28 at 10 31 32 AM](https://user-images.githubusercontent.com/13430452/91523178-acc0eb80-e919-11ea-9b31-668ad3636f7f.png)

**Desktop (please complete the following information):**
MacOSX 10.15
Firefox v78

**Comment by heshan0131** [comment]
this is fixed
