### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lixc1216** [keplergl/kepler.gl#1259]
当添加一个2.5m的城市管线数据后，开普勒会直接白屏崩溃

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ibgreen** [comment]
> 当添加一个2.5m的城市管线数据后，开普勒会直接白屏崩溃

@lixc1216 Your data is probably not in mercator coordinates. It is most likely related to [this react-map-gl issue](https://github.com/visgl/react-map-gl/issues/1163), and could be fixed either there or in kepler.

**Comment by ibgreen** [comment]
To be more specific, the fix I have in mind will prevent kepler from crashing and make it possible to show an error message. 

However, Kepler only supports mercator coordinates, so ultimately you'll still need to find a way to reproject your data before opening it in kepler.
