### ISSUE TITLE
TimeSlider precision

### ISSUE THREAD

**Issue by k0pernicus** [keplergl/kepler.gl#126]
I would like to thanks the team first for this awesome projet :)

I have one week of data to display, and the frequency of data is per second.
I wanted to implement a TimeSlider widget to reduce the number of my data on screen, but it seems I can't reduce the slider's interval less than 24h...

Is there any hack to reduce the quantity of time in the time slider please (console hack, something like that...)?

Thanks!

**Comment by yiyaya66** [comment]
@k0pernicus would you mind including the dataset if possible?

**Comment by k0pernicus** [comment]
Hello @yiyaya66 - sorry but I can't, the data are classified by the company.
My dataset is just a huge dataset of ms/s records, for 30 days.

**Comment by heshan0131** [comment]
@k0pernicus how's your date format? Just send me a couple lines of the date would be enough. Also a screenshot of just the time playback widget so I can see the inferred the time range by kepler.gl

**Comment by heshan0131** [comment]
should be fixed now the after #500
