### ISSUE TITLE
Usage of the default background maps in kepler.gl

### ISSUE THREAD

**Issue by bergkvist** [keplergl/kepler.gl#1264]
I really can't express with words how much I love the default (dark) background map in kepler.gl.

Is there a way I could use this map together with `pydeck` or `deck.gl` or other map libraries?

**Comment by bergkvist** [comment]
Found it in the code base: https://github.com/keplergl/kepler.gl/blob/b6fd39166be2a43526ac63c9ad880d72f2ec797b/src/constants/default-settings.js#L228-L263

**Comment by luelhagos** [comment]
Is the 'Muted Light' map style used in Kepler.gl available on Mapbox for direct use or customization?
