### ISSUE TITLE
The 'Save Map' modal 'save' button is always disabled

### ISSUE THREAD

**Issue by Guilherme-mm** [keplergl/kepler.gl#1265]
**Description**
Using the demo_app example project I could not enable the save button of the save map modal. During my tests, I created a custom cloud provider and was authenticated on it. Whenever I try to save the current map, the thumbnail is not generated, and filling the map name does not enable the save button. Even without the custom cloud-provider, the behavior seems to persist.

**To Reproduce**
1. Clone the demo_app example directory
2. Run the installation steps and start the project with npm start
3. Click on the 'Cloud Storage' button and then on 'Save'
4. Fill the 'name' input
5. See that both the thumbnail wasn't generated and the save button is still disabled

**Expected behavior**
After filling the form and being authenticated in a cloud provider, the save button should be enabled for clicking. Also, it was expected for the thumbnail to be generated.  

**Screenshots**
![image](https://user-images.githubusercontent.com/17601576/92277413-4ca5e880-eec9-11ea-9f1d-958e151c7e8a.png)

**Desktop:**
 - OS: Windows 10 - 1909
 - Browser: Tested on both: Chromium Edge and Chrome
 - Version: Chrome:  85.0.4183.83 / Edge: 84.0.522.63

**Comment by LeonanCarvalho** [comment]
Is this code is the same as https://kepler.gl/demo?
Because it works on the Kepler Demo page

https://kepler.gl/demo

Maybe the code is not fully synced

**Comment by LeonanCarvalho** [comment]
I got the same issue with the Overwrite  modal, 
The "Yes" button does not become available, maybe something is missing on the cloud provider? 

![image](https://user-images.githubusercontent.com/3593706/93610570-9ac7eb00-f9a3-11ea-8fb1-281e2e2f42f3.png)

**Comment by heshan0131** [comment]
the button is disabled if 
```js
         uiState.exportImage.processing ||
         !isValidMapInfo(visState.mapInfo) ||
         !providerState.currentProvider,
```
you can debug your code to see if any of those is truth?

https://github.com/keplergl/kepler.gl/blob/master/src/components/modal-container.js#L471-L474

**Comment by lalzart** [comment]
I was having the same problem. The issue was info was being overwritten when using addDataToMap.
