### ISSUE TITLE
Point layer is not mapped properly on mobile displays

### ISSUE THREAD

**Issue by simeon9696** [keplergl/kepler.gl#1275]
**Describe the bug**
Point layer is not overlayed properly on mobile displays

**To Reproduce**
1. Go to https://maps.coronavirustt.info/ on a mobile device and desktop

**Expected behavior**
The point is mapped to the co-ordinates provided as they are on a desktop view. Even if the browser is resized on desktop, the points are mapped correctly. 

**Screenshots**
This is the desktop 
![image](https://user-images.githubusercontent.com/31748055/93255583-1fc6c080-f768-11ea-9ebc-5c93e2785d63.png)

And this is mobile:
![Screenshot_20200915-143918 (1)](https://user-images.githubusercontent.com/31748055/93255620-29e8bf00-f768-11ea-9d60-563dc5728cc4.jpg)

This is Responsive View on Desktop 
![image](https://user-images.githubusercontent.com/31748055/93256021-b6937d00-f768-11ea-9b7b-ec789ce1cc34.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 85

**Smartphone:**
 - Device: OnePlus 8
 - OS: Android 
 - Browser: Chrome
 - Version 84

**Comment by heshan0131** [comment]
this should be fixed, please reopen if the error pesist
