### ISSUE TITLE
Demo App "Cannot read property 'filters' of undefined"

### ISSUE THREAD

**Issue by RaymondDashWu** [keplergl/kepler.gl#1277]
I'm making some modifications to the Demo app and consistently get the following 2 issues:

![image](https://user-images.githubusercontent.com/33266041/93422956-bdee7f80-f869-11ea-8ef9-693c6921704e.png)

It's possibly a lifecycle issue as I'm rendering my additional component with the following so that both the deck.gl layers in my example load before the component does:
`{this.props.mapData && this.props.mapData.visState.layers.length == 2 && <RenderSettingsModal />}
`

There was also an error about mounting reducers. However, I believe the demo app takes care of that in its store.js
![image](https://user-images.githubusercontent.com/33266041/93423018-d9598a80-f869-11ea-8334-bb24be52c128.png)

**Comment by chrisgervang** [comment]
For some more context, we're trying to build a react component outside of kepler that uses kepler's store data.

One thing we could use help with understanding here is what conditions trigger the "state does not exist" error? 
We've done some of the basic debugging steps together, like ensuring "filters" is actually defined in according to our console logs.

**Comment by RaymondDashWu** [comment]
Solved https://github.com/CodeLabs-Hubble-gl/hubble.gl/issues/12#issuecomment-695159319

**Comment by RaymondDashWu** [comment]
Solved https://github.com/CodeLabs-Hubble-gl/hubble.gl/issues/12#issuecomment-695159319
