### ISSUE TITLE
how to upload custom map in kepler.gl? 

### ISSUE THREAD

**Issue by gowridev** [keplergl/kepler.gl#128]
I would like to upload map(for example: Delhi,Redfort place) in kelper.gl and perform analytics. Which maps formats are supported in this application. Could you please guide me regarding this?

**Comment by heshan0131** [comment]
@gowridev you can take a look at this guide
https://github.com/uber/kepler.gl/blob/get-started/docs/j-get-started.md#1-add-data-to-your-map

**Comment by macrigiuseppe** [comment]
Closing
