### ISSUE TITLE
General question about how to add custom components into Kepler.gl

### ISSUE THREAD

**Issue by LuTang-Terrence** [keplergl/kepler.gl#1293]
Hi guys, I'm trying to add a few analysis tools as new components into Kepler.gl. I'm new to React and feeling there's generally two ways:

1. Embed Kepler.gl as a child component in my React app, and create the analysis component as other child components. The question is: how do I get the state from Kepler.gl component? For example, if in Kepler user filtered a half of the data off, is there a way in my root app knowing the filtered state for the data?

2. Directly add custom components into Kepler.gl source code. Not sure how hard this would be. 

Thanks for any suggestions!

**Comment by akre54** [comment]
Hi @LuTang-Terrence you might be looking for https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/replace-ui-component.md and https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/reducer-plugin.md

See if that helps

**Comment by LuTang-Terrence** [comment]
> Hi @LuTang-Terrence you might be looking for https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/replace-ui-component.md and https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/reducer-plugin.md
> 
> See if that helps

@akre54  Thanks a lot! The examples are very helpful!
