### ISSUE TITLE
[Bug] Chrome browser freezes when loading demo datasets

### ISSUE THREAD

**Issue by tourist-C** [keplergl/kepler.gl#1299]
Hi, just read about kepler.gl on some blog and decided to check it out. Unfortunately, I was unable to use the demo.

**Describe the bug**
Chrome browser freezes when loading demo datasets.
https://kepler.gl/demo/earthquakes
https://kepler.gl/demo/world_flights

**To Reproduce**
1. Go to 'https://kepler.gl/demo/earthquakes'
2. Chrome freezes. High CPU load observed in Task Manager

**Expected behavior**
Able to load, pan and highlight data points.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by heshan0131** [comment]
This is likely due to your laptop configuration and the size of your memory? We don't see this happen anywhere else.
