### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by corsomartin91** [keplergl/kepler.gl#1304]
**Describe the bug**
Hey there, 

When editing a custom palette of colors for a set if points, the 1st color box, when trying to edit the color or move around the pointer on the color board, the board will disappear. It will work for the other boxes in the custom palette. 

**To Reproduce**
Go to Layers > "Points" > Fill Color > Click on Palette > Toggle Custom Palette "On" > Select the 1st box in the descending order and try to manipulate the choice (this is what is broken)

**Expected behavior**
Expected to be able to choose a color or slide the bar to the color choice. 

**Screenshots**
Attached
![kepler bug](https://user-images.githubusercontent.com/38925091/96911654-1f100100-146f-11eb-8541-c7f77d9ed5e3.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome
 -Version 86.0.4240.80 (Official Build) (x86_64)

**Comment by heshan0131** [comment]
fixed 🎉
