### ISSUE TITLE
Allow add marker icon via geojson point feature.

### ISSUE THREAD

**Issue by agradipyahoo** [keplergl/kepler.gl#1321]
**Is your feature request related to a problem? Please describe.**
I want to add a marker icon programmatically to the map via geojson
**Describe the solution you'd like**
I want processGeoJson to take a feature as point like  below
```
{
      "type": "Feature",
      "properties": {
        "marker-color": "#7e7e7e",
        "marker-size": "medium",
        "marker-symbol": "town"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -92.5048828125,
          44.10336537791152
        ]
      }
    }
```

**Describe alternatives you've considered**

**Additional context**

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/issues/1429

Duplicated issue, please follow #1429
