### ISSUE TITLE
[Bug] Cannot use with NPM 7

### ISSUE THREAD

**Issue by dvkndn** [keplergl/kepler.gl#1324]
**Describe the bug** Cannot install kepler.gl with NPM 7 because NPM 7 require peer dependencies to be installed, and react-tooltip (the version kepler.gl@2.3.2 uses) specifies invalid syntax for React (`>=^16.0.0`)

**To Reproduce**
1. Create new folder
2. npm init
3. npm install kepler.gl (npm 7)

![Screenshot from 2020-11-19 16-59-36](https://user-images.githubusercontent.com/5953369/99651027-b07f8c80-2a88-11eb-8ea2-50ac15ac1eec.png)

**Additional context**

- A work-around is to use "--legacy-peer-deps" option in NPM so that the peer dependencies are not installed
- This also means the issue does not happen for NPM 6 (no forced install, just a warning)
- Also it seems the issue is fixed upstream and the new version of react-tooltip is already added in the master branch
---> So I think a release cut should fix this issue

**Comment by heshan0131** [comment]
`2.4.0` is published, should fixes your issue?

**Comment by dvkndn** [comment]
It fixes most, but one dependency called "react-sortable" still has incorrect peer-dependencies.

That being said, I think this is not important at all since the "legacy-deps" mode would help so I'm gonna close this issue :D
