### ISSUE TITLE
adddata  to  map  using  ArrowLoader

### ISSUE THREAD

**Issue by vikashsingh009** [keplergl/kepler.gl#1332]
**Describe the bug**
processRowObject  Processor not  binding  on  map 

**To Reproduce**
1. install  arrow  loader using  npm
2. import Arrow Loader
here  is  the  code 

```
async _loadArrowData() {
     var url= 'https://gist.githubusercontent.com/TheNeuralBit/64d8cc13050c9b5743281dcf66059de5/raw/c146baf28a8e78cfe982c6ab5015207c4cbd84e3/scrabble.arrow'

    const data =  await parse(fetchFile(url), ArrowLoader, {worker: false});
    console.log("data",data)
    console.log("dataType",data.type)
    // load arrow
    this.props.dispatch(
      addDataToMap({
        datasets: [
          {
            info: {label: 'Pipeline Arrow', id: 'pipe2071'},
            data: processRowObject(data)
          },
          //  {
          //    info: {label: 'SF Zip Geo', id: 'sf-zip-geo'},
          //    data: processGeojson(sampleGeojson)
          //  }
        ],
        options: {
          keepExistingConfig: true
        },
        //config: sampleGeojsonConfig
      })
    );
  }
```

i  can't  see  any  Error  but also  cannot  able  to see  map 

![image](https://user-images.githubusercontent.com/7962189/100582604-82633d80-330f-11eb-8a13-57ae5b5ef8b5.png)

**Comment by ibgreen** [comment]
As you can see in your table, the `ArrowLoader` returns a columnar table, but kepler uses row-based tables. 

You could transform the table yourself with a small code snippet.

Also, it would not be unreasonable for the `ArrowLoader` to do the conversion. To get help with this, please open a linked issue on loaders.gl.

**Comment by vikashsingh009** [comment]
@ibgreen thanks  for  you  reply, any  help  on  providing transformation  from  Columnar  to  row .i  cant  see  any  api  provided  by  arrow js  on  this

**Comment by ibgreen** [comment]
- arrow-js does support this through the Row class if you work with raw arrow tables. 
- loaders.gl already offers this for streaming loads, but not for atomic loads.
- if you open an issue in loaders.gl, we'll fix it for atomic loads as well.

**Comment by ibgreen** [comment]
loaders.gl v2.3.7 now supports `options.arrow.rowFormat='object'`;
