### ISSUE TITLE
Can't load from Storage

### ISSUE THREAD

**Issue by patdevinwilson** [keplergl/kepler.gl#1333]
**Describe the bug**

> bundle.js:514 TypeError: Cannot read property 'getManagementUrl' of undefined
>     at a.value (bundle.js:48)
>     at Na (bundle.js:514)
>     at Fa (bundle.js:514)
>     at yu (bundle.js:514)
>     at sl (bundle.js:514)
>     at ul (bundle.js:514)
>     at $u (bundle.js:514)
>     at bundle.js:514
>     at t.unstable_runWithPriority (bundle.js:522)
>     at Yi (bundle.js:514)

**To Reproduce**
1. Go to Add Data
2. Click Load from Storage

**Expected behavior**
Ability to click from Carto prompt or Dropbox

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 86.0.4240.198 (Official Build) (x86_64)

**Additional context**

**Comment by heshan0131** [comment]
this should be fixed
