### ISSUE TITLE
Drawing small objects with cm accurancy

### ISSUE THREAD

**Issue by sstiene** [keplergl/kepler.gl#135]
Hello,
I want to use kepler.gl to draw small objects with high precision. An example application would be drawing  RTK-GPS datasets of agriculture machines where I have cm accurancy.

If I use "Layer type points" with radius 50cm or less, some of the points dissapear or look like ellipses (even with high precission drawing turned on).

Is there any way to draw details with cm accurancy?

I have seen this post on deck.gl https://eng.uber.com/atg-dataviz/ and I hope that I can draw vehicle positions with a similar accurancy in kepler.gl as it is based on deck.gl

Regards
Stefan

**Comment by chrisirhc** [comment]
@ibgreen does deck.gl's 64-bit support have cm accuracy?

**Comment by ibgreen** [comment]
Absolutely, `fp64` mode will work for centimeter scale and beyond. 

Some additional info:

* Another approach (for data that only covers a small area) sets is to use `COORDINATE_SYSTEM.METER_OFFSETS or `COORDINATE_SYSTEM.LNGLAT_DELTA` layers, but that requires more work with preparing the right coordinates.

* For deck.gl 6.1 we are investigating adding a default LNGLAT mode that handles centimeter precision without the performance impact of `fp64`. For more details see the [RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.1/improved-lnglat-projection-rfc.md), there is also an open PR.

**Comment by ibgreen** [comment]
@sstiene Have you tried the "High Precision" checkbox at the bottom of the layer controls?

**Comment by sstiene** [comment]
yes, with this option the circles look like circles but it seams that kepler does some kind of rounding on the longitute value. I want to draw the following test structure:

-0.000002254844,4.511265074290
-0.000002254844,4.511291951281
0.000002254844,4.511291951281
0.000002254844,4.511265074290
0.000009019376,4.511258355042
0.000036077503,4.511258355041
0.000036077503,4.511253875543
0.000009019376,4.511253875544
0.000002254844,4.511247156296
0.000002254844,4.511220279307
-0.000002254844,4.511220279307
-0.000002254844,4.511247156296
-0.000009019376,4.511253875544
-0.000036077503,4.511253875543
-0.000036077503,4.511258355041
-0.000009019376,4.511258355042

the google image  (google_test.png) shows how it should look like.
Adding the same coordinates to kepler (original and shifted a little bit and with different radius 1.5m to 5cm) and high precision turned on results in the other picture (kepler.png).
 
So the problem seams not to be, that the structure is not drawn, but that the lon values are not exact. So that the circles are drawn on the same position.

Or the problem sits in front of the laptop ;-). 

Regards

Stefan

PS.: with high performance turned on scroling a little bit took 4-5 seconds and I have only ~100 points in the scene...

![google_test](https://user-images.githubusercontent.com/24275399/41875381-08138cfc-78cb-11e8-8128-76564b236915.png)
![kepler](https://user-images.githubusercontent.com/24275399/41875382-0843f7de-78cb-11e8-87ee-bddf117529b9.png)

**Comment by macrigiuseppe** [comment]
fp64 is currently supported out of the box in kepler.gl, does your issue still exist?
