### ISSUE TITLE
[Feature] Layer duplication

### ISSUE THREAD

**Issue by b2kdaman** [keplergl/kepler.gl#1354]
**Is your feature request related to a problem? Please describe.**
As a user I want to duplicate layers.

**Describe the solution you'd like**
This can be implemented with additional button in layer header panel.

**Describe alternatives you've considered**
Copy pasting layer meta data in raw config

**Additional context**
Here's the screenshot of our implementation:
![image](https://user-images.githubusercontent.com/7579297/101212852-1459a600-3682-11eb-8855-5176a651193b.png)

Icon is TBD

**Comment by b2kdaman** [comment]
@thunter009

**Comment by b2kdaman** [comment]
Created PR: https://github.com/keplergl/kepler.gl/pull/1370

**Comment by heshan0131** [comment]
#1370
