### ISSUE TITLE
[Bug] ARC / LINE "Select a Type" Layer

### ISSUE THREAD

**Issue by CarlottaO** [keplergl/kepler.gl#1364]
**Describe the bug**
White screen, no loading data when clicking on arc or line type of layer.

**To Reproduce**
1. Go to 'Add layer'
2. Click on 'Basic'
3. Scroll down to 'Arc' or 'Line'

**Expected behavior**
Opening of Arc or Line option for the current layer.

**Screenshots**

[
![error](https://user-images.githubusercontent.com/75619243/101351155-6f60e800-3890-11eb-8f49-4e9544f90f5b.PNG)
](url)

**Desktop (please complete the following information):**
 - OS: [Microsoft]
 - Browser [chrome]
 - Version [87.0.4280.88]

**Additional context**
In the past this error did not occured.

**Comment by hvester** [comment]
I encountered the same bug. Here is the error from the browser console:
```
bundle.js:514 TypeError: Cannot read property 'channelScaleType' of undefined
    at bundle.js:14
    at Xo (bundle.js:514)
    at yu (bundle.js:514)
    at sl (bundle.js:514)
    at ul (bundle.js:514)
    at $u (bundle.js:514)
    at bundle.js:514
    at t.unstable_runWithPriority (bundle.js:522)
    at Yi (bundle.js:514)
    at Wi (bundle.js:514)
```
