### ISSUE TITLE
Cannot add layer

### ISSUE THREAD

**Issue by yagiltzur** [keplergl/kepler.gl#1368]
**Describe the bug**
After importing a CSV, when adding a new layer and selecting a type, for example Arc, Kepler crashes

**To Reproduce**
1. Load Kepler
2. Open "Add Data To Map"
3. Drag the attached excel saved to CSV
2. Click on "Add Layer"
3. Click on "Select A Type"
4. Click on "Arc"
5. Kepler crashes

**Expected behavior**
A map should be displayed based on the CSV

**Screenshots**
![Screenshot 2020-12-08 140852](https://user-images.githubusercontent.com/27949416/101482147-ef558380-395e-11eb-8d75-9bde51b504f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser1 Chrome 87.0.4280.88 (Official Build) (64-bit),
 - Browser2 Edge version 87.0.664.57 (Official build) (64-bit)

[data-1607258876785.xlsx](https://github.com/keplergl/kepler.gl/files/5659198/data-1607258876785.xlsx)

**Additional context**

**Comment by Kevin-Bi** [comment]
I experience the same issue with running Kepler on MacOS. I was able to add arc layer for the same dataset few days ago.

**Comment by tatomorten** [comment]
I experience the same issue on Windows 10 Pro, arc and line doesnt work, but others do

**Comment by tatomorten** [comment]
Just found out, if you upload the your data set and then export the map as editable an use that html, it will work.

**Comment by jhnfere** [comment]
Same problem here. Is this only on the hosted demo version? or acts the same on any server applications?
