### ISSUE TITLE
Upgrade Deck.gl to v6.0.0

### ISSUE THREAD

**Issue by javidhsueh** [keplergl/kepler.gl#137]
We should upgrade Deck.gl/Luma.gl to the latest version to get more performance gains.

**Comment by ChunhongZhao** [comment]
When does this enhancement finish?

**Comment by hobochild** [comment]
@ChunhongZhao There is a PR open https://github.com/uber/kepler.gl/pull/153 looks like it's nearly there.

**Comment by ChunhongZhao** [comment]
@hobochild thanks for your information
