### ISSUE TITLE
[Bug] - Kepler crashes after adding Arc or Line layer

### ISSUE THREAD

**Issue by Umademyday** [keplergl/kepler.gl#1372]
**Describe the bug**
Screen drops when trying to add arc or line layer

**To Reproduce**
1. On any data just try to add arc or line layer

**Expected behavior**
Used to work before

**Screenshots**
![image](https://user-images.githubusercontent.com/44100662/101694892-d646f280-3a84-11eb-8eae-6b0ecba69023.png)

**Desktop (please complete the following information):**
 - OS: MacOs BigSur 11.0.1
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Comment by Umademyday** [comment]
Just the same as
https://github.com/keplergl/kepler.gl/issues/1368

**Comment by heshan0131** [comment]
This is fixed now
