### ISSUE TITLE
[Bug] Clicking on Share Map URL crashes app

### ISSUE THREAD

**Issue by davidywang** [keplergl/kepler.gl#1374]
**Describe the bug**
Clicking on Share Map URL on any valid map (including sample maps) crashes the app.

**To Reproduce**
1. Upload any valid map (including the sample maps).
2. Click on Share icon on the top right of the side bar.
3. Click on Share Map URL.
4. App crashes. See error in Screenshots:

**Expected behavior**
It should go to the original Share Map URL pop up with the Dropbox and Cartio options.

**Screenshots**
<img width="1268" alt="Screen Shot 2020-12-09 at 9 24 01 PM" src="https://user-images.githubusercontent.com/31499820/101734764-de8f3580-3a64-11eb-8d08-6f020f4506d0.png">

**Desktop:**
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
I've also tried this on a Windows 10 laptop using Chrome Version 87 and it has the same error.

**Comment by Ignatych** [comment]
I checked it in different browsers on my Mac and take same problem

**Comment by toasfand** [comment]
Do we have any resolution for this issue?

**Comment by davidywang** [comment]
Just checked it today and it's still not working.

**Comment by toasfand** [comment]
And do we have any idea who will be looking after these issues?

**Comment by tt87** [comment]
Still not working. Same exceptions.

![image](https://user-images.githubusercontent.com/9537310/106125495-4ca2cf80-616d-11eb-984c-bc7c2759529b.png)

**Comment by heshan0131** [comment]
this is fixed now
