### ISSUE TITLE
[Bug] with sharing map url in Kepler

### ISSUE THREAD

**Issue by juusokaijomaa** [keplergl/kepler.gl#1378]
**Describe the bug**
When I press "share map url", I get a blank screen and lose my data. I tried with Chrome and Safari, with data uploaded and without any data and asked my colleague to try also. The result was the same for him also.

**To Reproduce**
1. Go to Kepler
2. Click on share map url

**Expected behavior**
You'll get a blank screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser: chrome 87.0.4280.88 and safari 14.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by erlenbusch** [comment]
Confirming same issue, even on the most basic map without any data loaded... clicking on "Share URL" leads to blank screen.

**Comment by Sharvil97** [comment]
Same issue. Tried different browsers still unable to use any of the share options.

**Comment by cverluise** [comment]
Same for me. Mac OS Catalina, tried with Chrome, Safari and Mozilla. All share options failed.

**Comment by ThomasEFliit** [comment]
same for me. Also saving to dropbox has the same effect

**Comment by shakasom** [comment]
I have the same issue.

**Comment by kenjiasada** [comment]
Me too. Hope someone solve this problem...

**Comment by ColinLaurence** [comment]
This same issue also occurs when trying to "Export Image".

**Comment by cpatz** [comment]
same for me!

**Comment by BenUsername** [comment]
same problem! please advise!

**Comment by DamiMartinez** [comment]
Same here! Thank you.

**Comment by heshan0131** [comment]
This should be fixed. Please confirm

**Comment by juusokaijomaa** [comment]
Seems like its working again yes

**Comment by AnezkaZezulova** [comment]
Hi, I have the same problem as is written here - when I click on share map, I can't upload it anywhere. When it connects to my dropbox and then click on Upload, I get a blank screen. I tried different ways, diffrent browsers, Save intead of Share etc. but it does not work, I can't get URL. Please, could You fix it or help me, how to solve it? Thank You!
