### ISSUE TITLE
Kepler.gl time filter

### ISSUE THREAD

**Issue by atiqa16** [keplergl/kepler.gl#1379]
I'm using .py file to generate kepler.gl html file. 
It is showing the energy consumed by the buildings for all the dates  entered in the file. If the user wants to see the current date and time data they have to do it manually. Is there any way to do it by default that on page load it shows the data according to the current date and time
![image](https://user-images.githubusercontent.com/72857189/101977924-04a00b80-3c06-11eb-8003-12e9942516a1.png)
![image](https://user-images.githubusercontent.com/72857189/101977946-28635180-3c06-11eb-807f-61e6882664d6.png)

**Comment by b2kdaman** [comment]
This case is very uncommon because vast majority of the users work with datasets that were collected in the past. I hardly doubt that this feature will made it to prod.

**Comment by heshan0131** [comment]
you can add a filter.value to your config?  This will load the filter and filter the data based on value. But as for filter it based on `current` datetime e.g. `new Date(now)` it is not realistic...
