### ISSUE TITLE
Need Kepler Integration with Vue

### ISSUE THREAD

**Issue by sanmoh-hombal** [keplergl/kepler.gl#1380]
**Is your feature request related to a problem? Please describe.**
We're trying to integrate Kepler into our UI which is written in Vue / Typescript. Nuxt to be more precise and there's according to the documentation and JS examples you guys only support Redux as of now. I need help with integration with Vue / Typescript.

**Describe the solution you'd like**
Essentially a Vue Component and Support with Vuex Store.

**Describe alternatives you've considered**
Having react run inside Vue can be achieved but that'd cause too much unwanted code in our repository.

**Comment by macrigiuseppe** [comment]
Integration with Vue is not part of our roadmap but happy if you want to collaborate with us and create one

**Comment by hhaensel** [comment]
I've started writing my own implementation for the GenieFramework,
It's not built with vite but currently just a manual Vue component, but it could serve as starting point for someone with better skills in Vue than me, to build a vite project.
Moreover, we are still lacking resizing and replotting. Help is welcome.
https://github.com/GenieFramework/StippleKeplerGL.jl/blob/main/assets/js/KeplerGL.js

**Comment by hhaensel** [comment]
Update: I meanwhile realized resizing and replotting of new data. Replotting after window changes is not yet implemented.
Have a look at [StippleKeplerGL.jl](https://github.com/GenieFramework/StippleKeplerGL.jl), particularly [KeplerGL.js](https://github.com/GenieFramework/StippleKeplerGL.jl/blob/main/assets/js/KeplerGL.js)
