### ISSUE TITLE
[Feature] Tracking functionality is needed

### ISSUE THREAD

**Issue by nikolaytoplev** [keplergl/kepler.gl#1381]
When I am working on realtime tracking with this kepler.gl library, I used to face a big problem with low speed.
I think there should be tracking functionality in this wonderful kepler.gl, so this tracking will help many developers including me.
This kind of work can be found on the following site.
https://kepler-drive.herokuapp.com
The minion table is updating in real-time and there location should be tracked on the map.
But there is no proper way to do this effectively because deck.gl base library has not this functionality.
Thank you for your attention.
Best wishes.

**Comment by heshan0131** [comment]
This will need us to allow data streaming into dataset, and partially update the map. it is a big architecture change, we currently don't have plan to work on it. If more requests like this come up in the future, we will move it to the front of the queue. Please stay tuned

**Comment by nikolaytoplev** [comment]
> This will need us to allow data streaming into dataset, and partially update the map. it is a big architecture change, we currently don't have plan to work on it. If more requests like this come up in the future, we will move it to the front of the queue. Please stay tuned

Thanks for your concern.
Hope you are doing well.
