### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by korayyoung** [keplergl/kepler.gl#1382]
**Describe the bug**
A clear and concise description of what the bug is when uploading a new CSV document, the background of the map disappeared.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macrigiuseppe** [comment]
@korayyoung please create an issue with info and steps to reproduce it
