### ISSUE TITLE
Go to side panel. Click on radius range-slider. kepler.gl crashes stating the error "g is null". It also happens while zoom in and zoom out                           

### ISSUE THREAD

**Issue by atiqa16** [keplergl/kepler.gl#1386]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macrigiuseppe** [comment]
please re-open or create the issue with all necessary info and steps to reproduce it
