### ISSUE TITLE
[Bug][Jupyter Widget] Jupyterlab 3 not supported

### ISSUE THREAD

**Issue by jperkins12** [keplergl/kepler.gl#1390]
**Describe the bug**
The keplergl-jupyter extension fails to install in JupyterLab (3.0.3)

**To Reproduce**
1. Load JupyterLab
2. Go to extensions tab. Click "Enable".
3. Install keplergl-jupyter.
4. The following error occurs (see screenshot):
 
>Extension Installation Error
>An error occurred installing \<code\>keplergl-jupyter\</code\>.
>Error message:
>The extension "keplergl-jupyter" does not yet support the current version of JupyterLab.

>Conflicting Dependencies:
>JupyterLabExtension        Package
>\>=17.0.1 <18.0.0>=16.8.4 <17.0.0 react
>\>=17.0.1 <18.0.0>=16.8.4 <17.0.0 react-dom

**Expected behavior**
keplergl-jupyter extension installs without error.

**Screenshots**
![extension_install_error](https://user-images.githubusercontent.com/17438718/104360052-536ee880-54c5-11eb-9284-951873a21531.png)

**Environment:**
 - python3
 - JupyterLab 3.0.3

**Comment by Zeromika** [comment]
I am facing exact same issue as well just wanted to give a heads up.

**Comment by tomsant** [comment]
I am also experiencing this issue.

**Comment by jamesmyatt** [comment]
The extension will need to be updated to Jupyterlab 3. In the meantime, I suggest that you stick to Jupyterlab 2.

**Comment by darribas** [comment]
Just to add I can confirm this behaviour. I'm starting to prep a new release of the [`gds_env`](https://darribas.org/gds_env/), which will be on JL 3.0 and would _love_ love to keep Kepler on the list of installed packages. Any idea on whether this will be updated and if so when?

**Comment by mblackpp** [comment]
Same here, would love to this added for JL 3

**Comment by senkuluca** [comment]
Just ran into this issue. Would be really useful if it could be ported to the latest JupyterLab.

**Comment by kyri-petrou** [comment]
Any updates on this? We migrated to JL3 and would really love to have Kepler available

**Comment by bergkvist** [comment]
Upgrading react to version 17.0.2 seems to remove the React version conflict:
```diff
diff --git a/bindings/kepler.gl-jupyter/js/package.json b/bindings/kepler.gl-jupyter/js/package.json
index a0f7e535..4282ce10 100644
--- a/bindings/kepler.gl-jupyter/js/package.json
+++ b/bindings/kepler.gl-jupyter/js/package.json
@@ -64,9 +64,9 @@
     "@jupyter-widgets/base": "^1.1.10 || ^2.0.0 || ^3.0.0",
     "global": "^4.3.0",
     "kepler.gl": "^2.4.0",
-    "react": "^16.8.4",
+    "react": "^17.0.2",
     "react-copy-to-clipboard": "^5.0.2",
-    "react-dom": "^16.8.4",
+    "react-dom": "^17.0.2",
     "react-helmet": "^5.2.0",
     "react-intl": "^3.12.0",
     "react-redux": "^7.1.3",
```

And now we get a new error message:
```
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'assert' in '/home/tobias/.local/share/jupyter/lab/staging/node_modules/kepler.gl/dist/processors'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

Seems like jupyterlab might be using webpack v5, which no longer ships nodejs polyfills. To mitigate this, we could install [node-polyfill-webpack-plugin](https://www.npmjs.com/package/node-polyfill-webpack-plugin):

```diff
diff --git a/bindings/kepler.gl-jupyter/js/package.json b/bindings/kepler.gl-jupyter/js/package.json
index a0f7e535..f09c0990 100644
--- a/bindings/kepler.gl-jupyter/js/package.json
+++ b/bindings/kepler.gl-jupyter/js/package.json
@@ -64,9 +64,10 @@
     "@jupyter-widgets/base": "^1.1.10 || ^2.0.0 || ^3.0.0",
     "global": "^4.3.0",
     "kepler.gl": "^2.4.0",
-    "react": "^16.8.4",
+    "node-polyfill-webpack-plugin": "^1.1.2",
+    "react": "^17.0.2",
     "react-copy-to-clipboard": "^5.0.2",
-    "react-dom": "^16.8.4",
+    "react-dom": "^17.0.2",
     "react-helmet": "^5.2.0",
     "react-intl": "^3.12.0",
     "react-redux": "^7.1.3",
```
And magically, it "just works" (after I remembered to set `process.env.MapboxAccessTokenJupyter`):

![image](https://user-images.githubusercontent.com/410028/121072621-bdb85a80-c7d1-11eb-8a3f-65a7ce965616.png)
