### ISSUE TITLE
Save to Cloud Storage does not work

### ISSUE THREAD

**Issue by christianadelsberger** [keplergl/kepler.gl#1391]
Save to cloud storage ends up with empty page

1. Go to icon "Cloud Storage"
2. Click on icon
3. Click on "Save"
4. An empty page appears

**Expected behavior**
Save to cloud storage should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/77387011/104439942-086ed700-5592-11eb-8313-7a29c4a7f670.png)

Browser: Google Chrome is up to date
Version 87.0.4280.141 (Official Build) (x86_64)

**Comment by hjoner** [comment]
I'm stuck on this too.

**Comment by munizlimap15** [comment]
Yeah, same here! Also missing this functionality!

**Comment by oini** [comment]
Same here. I also get the same issue when trying to share the map URL.

![image](https://user-images.githubusercontent.com/1933377/105535368-a99d1200-5ca3-11eb-883a-94eaf4d638a8.png).
_Browser error_
