### ISSUE TITLE
Safari & Chrome | This webpage as reloaded because it was using significant memory

### ISSUE THREAD

**Issue by wasauce** [keplergl/kepler.gl#140]
Hi!

I am consistently getting the following error "This webpage as reloaded because it was using significant memory" in Safari or Chrome.

A screenshot:

![screen shot 2018-06-22 at 8 36 40 pm](https://user-images.githubusercontent.com/41729/41816970-97cb41f0-779a-11e8-821d-6a4153f36121.png)

When this happens the entire site is reloaded and whatever work I was doing is lost.

I am running kepler on;
MacBook Pro (Retina, 15-inch, Mid 2015) 
Running 10.13.4 (17E202)
2.2 GHz Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris Pro 1536 MB

I make sure to quit all apps and only have kepler open in a single window - 1 tab only.

I can shortly upload the file I have been using -- but it is ~30 MB - far below the limit. On the order of 100K-175K rows in my CSV. The format is the same as the Uber NYC taxi trips -- actually I just got the issue to reproduce using the Uber NYC Taxi Trips data.

Should this be expected on a ... not so new machine? I would have thought my laptop would still be powerful enough.

When does it happen:
1. When I load the data and display it as a heatmap (this only happens occasionally)
2. It especially when showing a timelapse (i.e. filter by time) and showing an Arc from start to end location.

**Comment by wasauce** [comment]
Safari Version 11.1 (13605.1.33.1.4)

**Comment by heshan0131** [comment]
A 15 in macbook pro should be enough to render the 100k - 175k rows. @1chandu have we observed deck.gl glitches with this specific version of mac?
