### ISSUE TITLE
[BUG] Sidepanel re-opens on Layer menu, annoying when customizing menu

### ISSUE THREAD

**Issue by ethubert** [keplergl/kepler.gl#1406]
**Describe the bug**
When implementing a custom panel and hiding the default ones ( layer, filter etc ), when you toggle off/on the sidepanel it sets the layer panel as active. 

**To Reproduce**
Implement custom panel and hide default panels buttons in the panel header using css

**Expected behavior**
Toggling back the sidepanel shouldn't change the active panel

**Screenshots**
![image](https://user-images.githubusercontent.com/26383429/107044975-4a6fef00-67c5-11eb-8dff-7e5c1d263cde.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Additional context**
Custom React App

**Comment by macrigiuseppe** [comment]
hello @ethubert, we are currently working on easy way to customize the side panel components. You will be able to specify in code (array) which ones to visualize.

In the meanwhile i noticed you are using CSS rules to hide those elements

**Comment by ethubert** [comment]
@macrigiuseppe Indeed, I am using CSS to hide the boutons that allow to switch panels. The problem is hiding the panels themselves doesn't help as they will be automatically set as active by the toggle show/hide button.
Can't do more without modifying the library.

**Comment by KrishnaVishwakarma1595** [comment]
hello @ethubert, I'm also trying to customize the side panels and trying to add more tabs along with its default tabs (layers, filter, etc.). But, my custom panel is not rendering beside the default tabs. Can you help me with that. How did you show your custom panels there? I'm injecting the components like this 

`const KeplerGl = injectComponents([
    [SidebarFactory, CustomSidebarFactory],
    [PanelHeaderFactory, CustomPanelHeaderFactory],
    [PanelToggleFactory, CustomPanelToggleFactory],    
    [CustomPanelsFactory, CustomSidePanelsFactory], // there is I've defined my custom panels
]);`

I'm following this [https://github.com/keplergl/kepler.gl/blob/master/examples/replace-component/src/components/custom-panel.js](url) for custom panels

But it is now rendering on the side bar. Your suggestion will be very helpful.

**Comment by heshan0131** [comment]
> @macrigiuseppe Indeed, I am using CSS to hide the boutons that allow to switch panels. The problem is hiding the panels themselves doesn't help as they will be automatically set as active by the toggle show/hide button.
> Can't do more without modifying the library.

Indeed, this is very unfortunate, one thing you can do is to  overide the `toggleSidePanel`  handler using reducer plugins
```js
import {ActionTypes} from 'kepler.gl/actions';

const customizedKeplerGlReducer = keplerGlReducer
  // handle additional actions
  .plugin({
   [ActionTypes.TOGGLE_SIDE_PANEL]: (state, {payload: id}) => {
     // This funciton get called AFTER the default TOGGLE_SIDE_PANEL in kepler.gl reducer is applied
      console.log(id);
      if (id === 'layer') {
        return {
          ...state,
          uiState: {
            ...state.uiState,
            // set panel to anything you want here
            activeSidePanel: 'filter'
          }
        };
      }
      // do nothing for other panel changes
      return state;
    }
  });

const reducers = combineReducers({
  keplerGl: customizedKeplerGlReducer,
  app: appReducer
});

```

**Comment by ethubert** [comment]
> > @macrigiuseppe Indeed, I am using CSS to hide the boutons that allow to switch panels. The problem is hiding the panels themselves doesn't help as they will be automatically set as active by the toggle show/hide button.
> > Can't do more without modifying the library.
> 
> Indeed, this is very unfortunate, one thing you can do is to overide the `toggleSidePanel` handler using reducer plugins
> 
> ```js
> import {ActionTypes} from 'kepler.gl/actions';
> 
> const customizedKeplerGlReducer = keplerGlReducer
>   // handle additional actions
>   .plugin({
>    [ActionTypes.TOGGLE_SIDE_PANEL]: (state, {payload: id}) => {
>      // This funciton get called AFTER the default TOGGLE_SIDE_PANEL in kepler.gl reducer is applied
>       console.log(id);
>       if (id === 'layer') {
>         return {
>           ...state,
>           uiState: {
>             ...state.uiState,
>             // set panel to anything you want here
>             activeSidePanel: 'filter'
>           }
>         };
>       }
>       // do nothing for other panel changes
>       return state;
>     }
>   });
> 
> const reducers = combineReducers({
>   keplerGl: customizedKeplerGlReducer,
>   app: appReducer
> });
> ```

Thanks for the reply but I already figure I can modify kepler's state directly and made my own actions using that plugin. Great job on the library, thank you for the massive work you did!
