### ISSUE TITLE
Customizable attribution

### ISSUE THREAD

**Issue by hbruch** [keplergl/kepler.gl#1407]
The data I'm visualizing is BY-licensed, so I'd like to add an attribution. Currently, I can't find an easy (configurable) way to add an attribution.

**Describe the solution you'd like**
I'd like to be able to specify an attribution text (ideally containing a link), which is displayed besides the kepler, osm and mapbox attributions in the lower right corner.

**Describe alternatives you've considered**
Another option might be to display an attribution in a project description box as is displayed for the kepler.gl samples. I neither found documentation describing how I could supply such information.

**Comment by heshan0131** [comment]
You can replace default map-container, hide the `.attrition-link` with css, and render your own attrition on top of it

```js
import styled from 'styled-components';
import {MapContainerFactory, injectComponents} from 'kepler.gl/components';

const StyledCustomMapContainer = styled.div`
  .mapbox-attribution-container {
    display: none;
  }
`;

export const Attribution = () => <div>My own attrition</div>;
const CustomMapContainerFactory = (...deps) => {
  const MapContainer = MapContainerFactory(...deps);

  const CustomMapContainer = props => {
    return (
      <StyledCustomMapContainer>
        <MapContainer {...props} />
        <Attrition style={{position: 'absolute', bottom: 0; right: 0}} />
      </StyledCustomMapContainer>
    );
  };

  return CustomMapContainer;
};

CustomMapContainerFactory.deps = MapContainerFactory.deps;

export function replaceMapContainer() {
  return [MapContainerFactory, CustomMapContainerFactory];
}

};

CustomMapContainerFactory.deps = MapContainerFactory.deps;

const KeplerGl = injectComponents(
  [
     [MapContainerFactory, CustomMapContainerFactory]
  ]
);
```

**Comment by lokkelvin2** [comment]
In the above code, I believe there is a typo and it should be 
```javascript
<Attribution style={{position: 'absolute', bottom: 0, right: 0}} /> 
````
However, using this custom container factory, I can hide the default attribution but my custom attribution defined in `Attribution` does not show up.
