### ISSUE TITLE
Background missing in Looker

### ISSUE THREAD

**Issue by gilsonjrpicpay** [keplergl/kepler.gl#1415]
**Describe the bug**
I have been using kepler map with looker and a few days ago we can't see the map in backgroup of the data ploted on the object. Can anyone help me about that ?
I saw an error to install mapbox-gl.css, but i need some help to do it.

**Screenshot**
<img width="1158" alt="Captura de Tela 2021-02-11 às 10 09 22" src="https://user-images.githubusercontent.com/72142036/107641035-dcf31100-6c51-11eb-84d8-4854b9d026a8.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version : 1.1.13

**Comment by hbruch** [comment]
Does it work in other browsers? You could enable the developer tools in your (desktop) browser, switch to the network tab and see if there and why the retrieval of background tiles files. My guess is, that you quota for the (mapbox?) tile service is exceeded...

**Comment by gilsonjrpicpay** [comment]
> Does it work in other browsers? You could enable the developer tools in your (desktop) browser, switch to the network tab and see if there and why the retrieval of background tiles files. My guess is, that you quota for the (mapbox?) tile service is exceeded...

Inspect by developer google tool, i saw these errors messages....
<img width="783" alt="Captura de Tela 2021-02-11 às 10 24 20" src="https://user-images.githubusercontent.com/72142036/107644755-9b189980-6c56-11eb-9607-58df41f98812.png">

**Comment by hbruch** [comment]
403 Forbidden indeed indicates that the mapbox token you are using is exceeded. This is no Kepler.gl bug so I suggest you close this issue.

Be sure you are using a proper mapbox token and not did not exceed your licensed quotas. If unsure, consult your mapbox support.

**Comment by gilsonjrpicpay** [comment]
> 403 Forbidden indeed indicates that the mapbox token you are using is exceeded. This is no Kepler.gl bug so I suggest you close this issue.
> 
> Be sure you are using a proper mapbox token and not did not exceed your licensed quotas. If unsure, consult your mapbox support.

Thank you very much for your help.....Regards....

**Comment by daaain** [comment]
If anyone else is running into this issue, the solution is to explicitly set your Mapbox style URL and token as it seems the default Uber one doesn't work any more.

With the Looker custom visualization specifically, you can either set these as a per Look setting in the visualization settings or as a global default, see:
https://github.com/team-blaze/custom_visualizations_v2/tree/master/src/examples/kepler#custom-style

**Comment by gauhar-tier** [comment]
@gilsonjrpicpay Is that correct that we can add the Kepler dashboard into the Looker? If that's correct, could you, please, point to any documentation that could help us integrate Kepler into our Looker. I really appreciate it.
Thank you!
