### ISSUE TITLE
[Bug] Dependency colorbrewer version should be 1.4.0

### ISSUE THREAD

**Issue by DanielM235** [keplergl/kepler.gl#1416]
**Describe the bug**
When colorbrewer dependency is resolved to v1.0.0 as allowed in current package.json, attribute `colorbrewer.schemeGroups` is not defined, leading to an error.

**Comment by rk-yen** [comment]
`"colorbrewer": "^1.0.0",` ... this does allow `1.4.0` to be picked up.

I did see this issue ... but it ended up being because of [cartocolor](https://github.com/CartoDB/CartoColor/blob/master/package.json#L24-L26)

**Comment by DanielM235** [comment]
> `"colorbrewer": "^1.0.0",` ... this does allow `1.4.0` to be picked up.
> 
> I did see this issue ... but it ended up being because of [cartocolor](https://github.com/CartoDB/CartoColor/blob/master/package.json#L24-L26)

true, "as allowed" is a more accurate description than "as defined", i'll update my first comment

**Comment by heshan0131** [comment]
Can you opn a PR to upgrade kepler to `colorbrewer@1.4.0`?

**Comment by DanielM235** [comment]
@heshan0131 [done](https://github.com/keplergl/kepler.gl/pull/1428)!
