### ISSUE TITLE
Fill Color : setting color based on programmatically 

### ISSUE THREAD

**Issue by GodSaveTheDucks** [keplergl/kepler.gl#1417]
I'm trying to find the documentation for this but I'm not able to figure out how to set "Color Based on" programmatically. Can someone please help me with this?

<img width="298" alt="Screenshot 2021-02-15 at 1 01 16 AM" src="https://user-images.githubusercontent.com/34424158/107887029-5d9f5f00-6f29-11eb-95e1-94710a085a60.png">

**Comment by heshan0131** [comment]
The action you can call to update color Field is [`layerVisualChannelChange`](https://docs.kepler.gl/docs/api-reference/actions/actions#layervisualchannelconfigchange). by passing the layer object, a new config object, and a channel name.

You can use redux dev tools to look at the action dispatched by kepler when selecting a field.

**Comment by heshan0131** [comment]
Close this for now, if more question, please reopen
