### ISSUE TITLE
[Bug] "width is required for transition" error when using geocoder with exported Kepler config in React

### ISSUE THREAD

**Issue by codrin-lanterne** [keplergl/kepler.gl#1418]
**Describe the bug**
`Uncaught Error: width is required for transition` is raised when using geocoder on a visualisation which uses a Kepler config exported from the Kepler demo website. I created a repository which should help with better understanding and recreating the problem, you can find the link in the **To Reproduce** section.

This happens when using 9e5bfdca2951d21be21d180ee162646caac86d50 (the latest master commit at the time of writing this issue) specified as a dependency in `package.json`. The reason for using this version of Kepler and not the released one is because it includes 32d801826641924f9ea56fab6b174c2713c96dc1 which solves an issue me and my team encountered when creating a prototype for our application.

**To Reproduce**
The repository which can help with better understanding and reproducing this problem can be found at https://github.com/Lanterne-Tech/kepler_width_is_required_for_transition_error.

One thing you should know about the above repository is that it uses `"kepler.gl": "github:Lanterne-Tech/kepler.gl"` when declaring the Kepler dependency instead of `"kepler.gl": "^2.4.0"`. `github:Lanterne-Tech/kepler.gl` is a fork of 9e5bfdca2951d21be21d180ee162646caac86d50 with a slight modification to `package.json` which adds a `prepare` script (you can see the changes made after forking at ca708a3e32191f28c61c806813f797ca5d7f41a7). If declaring the dependency as `"kepler.gl": "github:keplergl/kepler.gl"` a compliation error would occur because `"Module not found: Can't resolve './dist/actions' in '.../node_modules/kepler.gl'".` (https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts)

The repository uses as the Kepler config the JSON copied from the Kepler demo website when exporting a map:
![image](https://user-images.githubusercontent.com/75673730/108240886-f285a080-7153-11eb-8a7a-da09536a37bc.png)

There's also a fix to the problem described in the repository's README (how to change the config exported from Kepler to make this bug go away).

**Expected behavior**
Exporting a config from the Kepler demo website should work as long as `dataId` is set properly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.150 (Official Build) (64-bit)
 
**Additional context**
I thought this might have been an error caused by the fact that the version of Kepler deployed on the demo website doesn't export configs compatible with the latest Kepler version that we are using (9e5bfdca2951d21be21d180ee162646caac86d50) but exporting the config using the latest version leads to the same problem.

**Comment by macrigiuseppe** [comment]
@codrin-lanterne would you be able to provide your configuration and a small sample of your dataset?

we can test this one in our official repo and let you know whether it works.

**Comment by codrin-lanterne** [comment]
I uploaded the dataset and Kepler config used at https://github.com/Lanterne-Tech/kepler_width_is_required_for_transition_error/tree/master/data.

**Comment by macrigiuseppe** [comment]
@codrin-lanterne we have cloned your repo and indeed we saw the `../dist/actions` error. We have upgrade to use kepler.gl 2.5.0 and the `dist/actions` errrors disappears and we are able to use the geocoder.

see below

<img width="1792" alt="Screen Shot 2021-03-19 at 4 54 11 PM" src="https://user-images.githubusercontent.com/2554552/111841085-c769aa80-88d3-11eb-8eb4-f6f3a534a6f7.png">
