### ISSUE TITLE
[Bug]Tooltip disappears when you click on a layer

### ISSUE THREAD

**Issue by shotaa0109** [keplergl/kepler.gl#1419]
**Describe the bug**
When hovering over a layer, there is no problem at all, but once you click on the layer, the Tooltip disappears.

https://github.com/keplergl/kepler.gl/blob/9e5bfdca2951d21be21d180ee162646caac86d50/src/components/map-container.js#L320-L331

The reason is that `clicked` doesn't have `lngLat`, so the value of `pinnedPosition` passed to `MapPopover` is empty.

The root cause seems to be caused by a modification to https://github.com/visgl/deck.gl/pull/5208 that removes the `lngLat`.

Also, the dependency of `deck.gl` on `kepler.gl` is as follows

```
    "@deck.gl/aggregation-layers": "^8.2.0",
    "@deck.gl/core": "^8.2.0",
    "@deck.gl/extensions": "^8.2.0",
    "@deck.gl/geo-layers": "^8.2.0",
    "@deck.gl/layers": "^8.2.0",
    "@deck.gl/mesh-layers": "^8.2.0",
    "@deck.gl/react": "^8.2.0",
```

`npm install kepler.gl` actually installs `8.4.5` for `deck.gl`. The `8.4.5` has a merge of the fix from the earlier pull request, which is probably causing this problem.

I think the deck.gl in kepler.gl/demo is 8.2.0. So the series of problems are not reproduced in the demo environment.

you can fix this issue by the code below on https://github.com/keplergl/kepler.gl/blob/master/src/components/map-container.js#L323
```diff
- const lngLat = clicked ? clicked.lngLat : pinned.coordinate;
+ const lngLat = clicked ? clicked.coordinate : pinned.coordinate;

```
**To Reproduce**
1. download the latest kepler.gl
2. run `examples/demo-app`(https://github.com/keplergl/kepler.gl/tree/master/examples/demo-app)
3. add data
4. click on data layer

**Expected behavior**
Keep Tooltip visible after layer clicks

**Screenshots**

#### hover
![スクリーンショット 2021-02-18 19 26 52](https://user-images.githubusercontent.com/9813222/108343481-59bc5700-721f-11eb-9e4e-1066651e0fd2.png)

#### after clicks
![スクリーンショット 2021-02-18 19 26 58](https://user-images.githubusercontent.com/9813222/108343497-5de87480-721f-11eb-8bae-663fe25082c6.png)

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Browser: Chrome
- Version: 88.0.4324.150（Official Build） （x86_64）

**Comment by heshan0131** [comment]
`deck.gl` version should be locked to `8.2.0` when using with kepler.gl.
 `deck.gl@8.4.5` introduced some more issues, not only the tooltip bug. We are actively working on upgrading to `deck.gl@8.4.5` that will include the fixes for this issue
