### ISSUE TITLE
doing election map with kepler.gl

### ISSUE THREAD

**Issue by pinardag** [keplergl/kepler.gl#143]
hi, 

ı try to use  kepler.gl for the  election however it does not work.

can you help pls. the data is here:
https://gist.github.com/oztalha/0bdaa68e53466f64055ad276f11e868e

thank you

**Comment by heshan0131** [comment]
@pinardag 
You will need to add latitude and longitude of each city as columnes

**Comment by pinardag** [comment]
ok, thank you. It means a lot of work :)
