### ISSUE TITLE
examples/demo-app Netlify deploy

### ISSUE THREAD

**Issue by kunalbotla** [keplergl/kepler.gl#1430]
I'm trying to deploy the examples/demo-app build to Netlify using the CLI and GitHub repo. It works when it's built locally but not when deployed to Netlify. I can't seem to find an issue on Netlify so it seems to be on the kepler.gl side.

**Comment by hbruch** [comment]
By „not working“ you mean what exactly? Any error messages in the browser console/networking tab of the dev tools?

no background map? Did you enter a proper mapbox token as required?

**Comment by kunalbotla** [comment]
I mean that it just shows a blank white page. I've entered all the tokens as needed and there are no errors in the local environment. You can see what the result is on https://maps.kunalbotla.com.

**Comment by hbruch** [comment]
Looks like the bundle.js is not deployed(?)
<img width="692" alt="image" src="https://user-images.githubusercontent.com/2187389/109606221-a0b32200-7b26-11eb-8afa-29d23e1344b8.png">

To analyze errors in the browser, open the browser's developer tools and watch out for any error messages in the console or network tab.

**Comment by kunalbotla** [comment]
Yeah, where is the `bundle.js`. They aren't there in the root directory or `examples/demo-app`

**Comment by kunalbotla** [comment]
I think this might be related to #354 and #1097 but I can't seem to use the solution they have.

**Comment by macrigiuseppe** [comment]
@kunalbotla and @hbruch kepler.com is currenlty deployed on netlify. In order to set up your netlify build correctly, use the following settings:

<img width="869" alt="Screen Shot 2021-03-05 at 4 20 44 PM" src="https://user-images.githubusercontent.com/2554552/110174852-c7938180-7dce-11eb-8393-16c2ab265e3a.png">
