### ISSUE TITLE
[Bug] Adding hexbin height mutes/darkens colors

### ISSUE THREAD

**Issue by davidcalhoun** [keplergl/kepler.gl#1433]
**Describe the bug**
When using a 2d hexbin, the color palette displays normally.  However, when adding a height and triggering 3d mode, the colors become darkened and muted somewhat (with normal layer blending).

**To Reproduce**
1. Add a dataset with lat/lon and magnitudes (e.g. earthquakes)
2. Display as a hexbin
3. Toggle on the Height control.

**Expected behavior**
Expected the colors palette to remain fairly consistent across 2d and 3d contexts.

**Screenshots**

https://user-images.githubusercontent.com/120596/109830340-66bc4b80-7c0c-11eb-9ee2-776be9891d54.mp4

**Desktop (please complete the following information):**
 - OS: macOS 11.2.1
 - Browser: Firefox 86, Chrome 88
 - kepler.gl Version: 2.4.0

**Additional context**
Changing blending mode to additive partially restores some bright colors, but with an unwanted blending effect.

**Comment by heshan0131** [comment]
When height is enabled, the map is suppose to be viewed in 3d mode using the cube button on the top right. The difference in color changed is an effect of enabling lighting / shadow to render 3d object. 

<img width="822" alt="Screen Shot 2021-03-03 at 9 32 41 PM" src="https://user-images.githubusercontent.com/3605556/109916175-ff33e980-7c67-11eb-9ffe-81d0e6a89d35.png">

**Comment by davidcalhoun** [comment]
Thanks for the quick reply and clarification!  Is there any way to adjust lighting - is it recommended to do it [through Mapbox](https://docs.mapbox.com/mapbox-gl-js/style-spec/light/)?

Thank you in advance!

**Comment by heshan0131** [comment]
Lighting is enabled through [Deck.gl lighting](https://deck.gl/docs/developer-guide/using-lighting)

**Comment by davidcalhoun** [comment]
Awesome, thank you!  I must not have been looking in the right part of the docs.  This is awesome!  I'll close this out.
