### ISSUE TITLE
Can't remove the dataset using removeDataset action or removeDatasetUpdater

### ISSUE THREAD

**Issue by KrishnaVishwakarma1595** [keplergl/kepler.gl#1444]
Hello, I need help to remove the dataset programmatically from the Kepler map. According to the documentation, I'm using the removeDateset action to remove the dataset passing the dataset id but it doesn't work and don't remove any layer or filter from the map. Here is my code below :

`const hasDataSet = () => {
        let storeState = store.getState();
        let dataSet = storeState.keplerGl.foo.visState.datasets;
        console.log(dataSet);
        if(Object.keys(dataSet).length > 0){                        
            let city = localStorage.getItem('city');
            console.log(city);            
            store.dispatch(removeDataset({key: 'ny_exp'}));    
            // props.dispatch(removeDataset({key: 'ny_exp'}));                                               
        }   
 }`

Please help me with that.

**Comment by macrigiuseppe** [comment]
Hello @KrishnaVishwakarma1595, you code has an issue invoking the `removeDataset` action, you need to do the following:
```
const hasDataSet = () => { let storeState = store.getState(); let dataSet = storeState.keplerGl.foo.visState.datasets; console.log(dataSet); if(Object.keys(dataSet).length > 0){ let city = localStorage.getItem('city'); console.log(city); store.dispatch(removeDataset('ny_exp')); // props.dispatch(removeDataset('ny_exp'); } }
```

it's `removeDataset('ny_exp')`

**Comment by KrishnaVishwakarma1595** [comment]
> Hello @KrishnaVishwakarma1595, you code has an issue invoking the `removeDataset` action, you need to do the following:
> 
> ```
> const hasDataSet = () => { let storeState = store.getState(); let dataSet = storeState.keplerGl.foo.visState.datasets; console.log(dataSet); if(Object.keys(dataSet).length > 0){ let city = localStorage.getItem('city'); console.log(city); store.dispatch(removeDataset('ny_exp')); // props.dispatch(removeDataset('ny_exp'); } }
> ```
> 
> it's `removeDataset('ny_exp')`

Thanks, @macrigiuseppe for the help. It is working.
