### ISSUE TITLE
Is it possible to automatically start a Time Playback graph in a config setting?

### ISSUE THREAD

**Issue by sfuller79** [keplergl/kepler.gl#1448]
Hi, 
Apologies if this is answered somewhere. I've found solutions for html exports but not for jupyter embedded plots.
I have a function for generating animated histograms.
I would like to be able to set these to play automatically, but I can't seem to find the option in the config.
I'm able to the playback option to "moving" in advance, and even set the playback to "enlarged=true" so all I need to do is press play.
But ideally I would like to be able to set it to autoplay and have "enlarged=false".
Have I missed a config option here or is this not currently available?
Thank you, and thank you for the wonderful software.

**Comment by macrigiuseppe** [comment]
Hey @sfuller79, try to modify the filter json configuration by changing it to this:
```
 {
          dataId: 'test_trip_data',
          name: 'tpep_pickup_datetime',
          enlarged: true,
          isAnimating: true,  // this
          value: [] // this
},
```
I highlighted the main properties you need add to your filter configuration in order to kick off the animation.

**Comment by sfuller79** [comment]
@macrigiuseppe Ah just what I was looking for - thanks!
