### ISSUE TITLE
The npm install process get   stuck at react-drop-file 

### ISSUE THREAD

**Issue by GeoIntelSolution** [keplergl/kepler.gl#145]
followinng the instruction,I find the example  get stuck when it install kepler.gl ;
It show a decrapted messages:
![default](https://user-images.githubusercontent.com/8498063/42018927-2be22dce-7ae6-11e8-9bd9-b22b7797c95c.PNG)
and the install process seems to wait in a loop

**Comment by macrigiuseppe** [comment]
closing
