### ISSUE TITLE
Appending new map styles to existing ones 

### ISSUE THREAD

**Issue by oguzcanbudumlu** [keplergl/kepler.gl#1454]
I want to add `voyager` and `terrain` map styles (in `custom-map-style` example) to default layer types (dark, light and so on). I tried to access via keplerGlReducer to default layer types but I could not succeed. When I define  `voyager`  and `terrain` in initial state, it merges to default state and default state disappears as we expect. Is there anyone who can help?

**Comment by heshan0131** [comment]
default them in `initialState` and merge with `DEFAULT_MAP_STYLES` from `kepler.gl/constants`

```js
const customizedKeplerGlReducer = keplerGlReducer.initialState({
  mapStyle: {
    mapStyles: {
        ...DEFAULT_MAP_STYLES,
        ...customMapStyles
    },
    styleType: 'voyager'
  }
});
```
