### ISSUE TITLE
Link time filters

### ISSUE THREAD

**Issue by yvanrichard** [keplergl/kepler.gl#146]
As far as I can tell, it doesn't seem possible to link several time filters. One can only filter one layer at a time. But it would make sense to link the filters so that one could see how several layers change together with time. It would be especially useful with the dual panel view and the time animation.

**Comment by heshan0131** [comment]
@yvanrichard The time filter should filter all data from the same dataset, hence affecting all layers of that dataset. Unless you have layers under multiple datasets, in which case, the filter won't apply to all.

This is a big change for us, at the moment the workaround is to merge those 2 sets into 1.

**Comment by macrigiuseppe** [comment]
this feature is going to be available in [studio.unfolded.ai](https://studio.unfolded.ai) in the next few months
