### ISSUE TITLE
Click event - onLayerClick

### ISSUE THREAD

**Issue by openlayers-droid** [keplergl/kepler.gl#1464]
Thank you for the great tool!

an example on how to fire click events using onLayerClick is very much needed. i tried to hook up with MapBoxGL click event but it is not working - only zoomend/zoonstart events are firing.

many thanks

**Comment by openlayers-droid** [comment]
i found that some people were looking for this, after some research i came up with the following:
app-reducer.js
`const appReducer = handleActions(
  {
    [INIT]: (state, action) => ({
      ...state,
      loaded: true
    }),
    [ActionTypes.LAYER_CLICK]: (state,info) => {
      console.log("info",info)
      return {...state}
    },
  },`

it is working for me, but i am not too sure of this is the right way.

**Comment by openlayers-droid** [comment]
app-reduce.js

`const appReducer = handleActions(
  {
    [INIT]: (state, action) => ({
      ...state,
      loaded: true
    }),
    [ActionTypes.LAYER_CLICK]: (state,info) => {
      console.log("info",info)
      return {...state}
    },
  },`

**Comment by SincerelyUnique** [comment]
> app-reduce.js
> 
> `const appReducer = handleActions( { [INIT]: (state, action) => ({ ...state, loaded: true }), [ActionTypes.LAYER_CLICK]: (state,info) => { console.log("info",info) return {...state} }, },`

Hi, openlayers-droid, thanks for your help so much,  and could you share the detail usage here? :)

**Comment by SincerelyUnique** [comment]
Cool, thank you so so so much~ now I can get the click info, let me check the data 
![image](https://github.com/keplergl/kepler.gl/assets/16249717/8460a76f-ae05-4f83-8ea2-dd658b985ead)

![image](https://github.com/keplergl/kepler.gl/assets/16249717/9d82e06d-c978-4c3e-9e56-11e3d6c3c4e5)

**Comment by SincerelyUnique** [comment]
![image](https://github.com/keplergl/kepler.gl/assets/16249717/6a6fc16d-d69c-4a56-95f3-f3e16b2d98f3)

![image](https://github.com/keplergl/kepler.gl/assets/16249717/774a17e0-9f2e-45f9-88a8-68168f6930f8)


it seems these properties can not be get from the LAYER_CLICK action, do you know which action support to get these infomation? I want to get the modal information when I click the point in the map.

**Comment by SincerelyUnique** [comment]
for my question, I find a solution, we can see the index:100 from my F12 dev console, it is the data index which I set from addDataToMap action, by the way , I send the geoJsonDataArray, so here 100 is my data array index, I can use the index to find the actual data (eg: geojson properties)
