### ISSUE TITLE
Kepler tooltip by default shows 5 fields. How can that be changed to include more fields in the tooltip.

### ISSUE THREAD

**Issue by shreyario** [keplergl/kepler.gl#1477]
![2D8AD8B3-DB8A-4BCA-9177-30D07A671717_4_5005_c](https://user-images.githubusercontent.com/60377769/117927477-d6e1fe80-b32c-11eb-9142-d3d616bdf970.jpeg)

Here it is set as 5, If I am following https://github.com/keplergl/kepler.gl/blob/14c35fc048a745faab0c6770cab7a4625ccedda3/src/templates/export-map-html.js to insert my data into Kepler, how can I change this default number of fields in the tooltip?
https://github.com/keplergl/kepler.gl/blob/14c35fc048a745faab0c6770cab7a4625ccedda3/src/constants/default-settings.js#L649

**Comment by heshan0131** [comment]
there is not an easy way to overide this at the moment
you can always pass in your defined tooltip in the config to skip the auto creation

```js
export const sampleTripDataConfig = {
  version: 'v1',
  config: {
    visState: {
       interactionConfig: {
          tooltip: {
            fieldsToShow: {
               <dataId>: ['field_1',  'field_2',  'field_3']
            }
          }
       }
    }
  }
};
```

Another way is to add `MAX_DEFAULT_TOOLTIPS` to `visState`, that would require small changes in the kepler.gl code. if you would like to create a PR, I can point you to the code

**Comment by Rikuoja** [comment]
I would be interested in working on this feature, if you can give me some pointers to the code?

**Comment by heshan0131** [comment]
1. add `maxDefaultTooltip = MAX_DEFAULT_TOOLTIPS` to `vis-state-updaters` `INITIAL_VIS_STATE`, `MAX_DEFAULT_TOOLTIPS` can be imported from `constants/default-settings`
2. edit `addDefaultTooltips` function in`vis-state-updaters` to pass `state.maxDefaultTooltip` to `defaultTooltipFields` function,, replacing the current use of constants
https://github.com/keplergl/kepler.gl/blob/master/src/reducers/vis-state-updaters.js#L1717-L1725 

Thanks it!
