### ISSUE TITLE
Hexbin visualisation producing deck.gl error on demo-app

### ISSUE THREAD

**Issue by nickbroom98** [keplergl/kepler.gl#1479]
**Describe the bug**

Hexbin visualisation failing on demo application. I have been able to visualise the following dataset on kepler.gl ([(uk traffic data](https://www.kaggle.com/daveianhickey/2000-16-traffic-flow-england-scotland-wales?select=accidents_2005_to_2007.csv)) using a hexbin layer to aggregate readings. However, when I installed the [demo-app](https://github.com/keplergl/kepler.gl/tree/master/examples/demo-app) and tried to create the same visualisation I received two errors from deck.gl:

An error in deck.gl: Cannot read property '1' of undefined in 38imks
An error in deck.gl: Cannot read property 'sortedBins' of undefined in 38imks-hexagon-cell

I'm getting similar errors when I follow the [Get Started Instructions](https://docs.kepler.gl/docs/api-reference/get-started) and integrate Kepler into my existing web application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the demo-app from the [Github repo](https://github.com/keplergl/kepler.gl/tree/master/examples/demo-app)
2. Follow the installation instructions in the README.md
3. Launch the demo application
4. Download [this dataset](https://www.kaggle.com/daveianhickey/2000-16-traffic-flow-england-scotland-wales?select=accidents_2005_to_2007.csv) and upload it to the demo application
5. Create a hexbin visualisation layer and set the color based on attribute.

**Expected behavior**
Hexbin visualisation produced and color updates when the color based on attribute changes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71817910/118105376-3810dd00-b3d4-11eb-9518-8508df304971.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Browser Chrome
 - Version  90.0.4430.212

**Comment by BremzeLV** [comment]
Try this: https://github.com/keplergl/kepler.gl/issues/1470

Use yarn and lock Keplers dependecy on deck.gl based on whats needed in kepler.gl package.json, atleast for me for Grid it helped and errors were quite similar.

**Comment by nickbroom98** [comment]
Thank you!

Switched my package manager from npm to yarn and added the resolutions in and it has fixed the problem.
