### ISSUE TITLE
Info-box like in the demos

### ISSUE THREAD

**Issue by AndreasAtakan** [keplergl/kepler.gl#1484]
Hi everyone!

I am wondering if it is possible to add an info-box to my own map like in the demos. See pic.
![image](https://user-images.githubusercontent.com/45392631/118841588-bd125f80-b8c8-11eb-8a14-055c4badcf11.jpeg)

It seems to be related to a "detail", "dataUrl" and "configUrl" config, but I have no idea where I would put this.
Any hints @heshan0131 or anyone?

**Comment by pdh21** [comment]
HI @AndreasAtakan did you work out how to add the info-box?

**Comment by AndreasAtakan** [comment]
> HI @AndreasAtakan did you work out how to add the info-box? 

Yes, I found an example where I could add an info-box.
Thanks!
