### ISSUE TITLE
[Bug] Arc layer is causing the application to crash

### ISSUE THREAD

**Issue by SarahLagpacan** [keplergl/kepler.gl#1485]
**Describe the bug**
Creating an "Arc" layer causes the page to crash, and creating a "Line" layer does not visualize anything.

**To Reproduce**
Steps to reproduce the Arc behavior:
1. Go to 'Add Layer'
2. Click on 'Select A Type'
3. Click on 'Arc'

Steps to reproduce the Line behavior:
1. Go to 'Add Layer'
2. Click on 'Select A Type'
3. Click on 'Line'

**Expected behavior**
When drawing an "Arc" layer, entire page turns white and unable to click on anything until page is refreshed. When drawing a "Line" layer, map remains the same, even after inputting data.

**Screenshots**
![Arc layer](https://user-images.githubusercontent.com/84520690/119003570-d44e5d00-b95b-11eb-811e-3b7ad4608b9d.PNG)
![Line layer](https://user-images.githubusercontent.com/84520690/119003573-d44e5d00-b95b-11eb-9dac-43f2b6d08bb4.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Dell laptop
 - OS: Windows 10 Enterprise 
 - Browser Google Chrome
 - Version 1809

**Additional context**

**Comment by macrigiuseppe** [comment]
Hello @SarahLagpacan, would you be able to share your dataset or a sample of it that causes the crashes?

**Comment by heshan0131** [comment]
Fix should be deployed
