### ISSUE TITLE
[Question] Is it possible to assign point color by field value?

### ISSUE THREAD

**Issue by leodavinci1** [keplergl/kepler.gl#1486]
Is there a way of changing the color of points based on a field value? Right now I understand that there's a way of sending an array of colors, but there's no way to assign color by values
![image](https://user-images.githubusercontent.com/22947676/119012330-52b2fb00-b96c-11eb-89c4-1f2adae1a33a.png)

**Comment by macrigiuseppe** [comment]
HI @leodavinci1, you can set point color based on any field bu using:
- the UI
<img width="1792" alt="Screen Shot 2021-05-21 at 5 22 37 PM" src="https://user-images.githubusercontent.com/2554552/119161431-9b94ad80-ba59-11eb-9c81-2e016909766a.png">

- Or customize the map config
![Screen Shot 2021-05-21 at 5 24 23 PM](https://user-images.githubusercontent.com/2554552/119161405-96376300-ba59-11eb-854d-1a6aedf02bbb.png)

**Comment by macrigiuseppe** [comment]
You will also be able to achieve this when we land https://github.com/keplergl/kepler.gl/issues/399

**Comment by cristianUrbina** [comment]
Is this still possible. Where should I put that map config object?

**Comment by SebastianoX** [comment]
There are cases when I know what colour each item should have in the map before passing the dataframe/geojson item to kepler.

Is it possible to assign the colour programmatically, e.g. passing it as value to a column of the inputed DataFrame?

Thank you!

**Comment by Farhan082** [comment]
{
          "id": "5vcu0dv",
          "type": "point",
          "config": {
            "dataId": "monitors",
            "label": "Monitors",
            "color": [110, 48, 182],
            "columns": {
              "lat": "latitude",
              "lng": "longitude"
            },
            "isVisible": false,
            "visConfig": {
              "radius": 20,
              "filled": true,
              "fixedRadius": false,
              "opacity": 0.8,
              "strokeColor": [110, 48, 182],
              "outline": false,
              "thickness": 1,
              "colorRange": {
                "name": "Custom Colors",
                "type": "diverging",
                "category": "custom",
                "colors": ["#FF0000", "#00FF00"],
                "domain" : ["online", "offline"]
              },
              "radiusRange": [0, 50],
              "hi-precision": false
            }
          },
          "visualChannels": {
            "colorField": {
              "name": "status",
              "type": "string"
            },
            "colorScale": "quantize",
            "sizeField": null,
            "sizeScale": "linear"
          }
        }
        
        I want to change my map point color green when status become online and ren when status is offline
