### ISSUE TITLE
[Bug] Layer legend considers a numerical column as string

### ISSUE THREAD

**Issue by bkowshik** [keplergl/kepler.gl#1493]
**Describe the bug**
The layer legend considers a numerical column as a string column.

**To Reproduce**

Upload the csv below on Kepler.gl

```
hex_id, value
88619aa6edfffff, 0
88619aa683fffff, 11.17
88619aa687fffff, 6.87
88619aa68bfffff, 10.87
88619aa681fffff, 10.37
88619aa6b9fffff, 11.12
88619aa695fffff, 12.88
88619aa69dfffff, 14.92
```

Then, color the hex IDs based on the `value` column.

**Expected behavior**
The `Color based on` feature does not understand a numerical column, but instead takes it as a String column. Instead, it should consider the column as a numerical column, sort and then create a colour band appropriately.

**Screenshots**
<img width="1147" alt="Screenshot 2021-05-24 at 3 54 56 PM" src="https://user-images.githubusercontent.com/2899501/119334874-3a631900-bca9-11eb-90c2-76c8bc964366.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave
 - Version: Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (x86_64)

**Comment by heshan0131** [comment]
There is empty space character in yoru `value column`

After deleting them it works
<img width="292" alt="Screen Shot 2021-06-07 at 4 47 14 PM" src="https://user-images.githubusercontent.com/3605556/121101135-18d95580-c7b0-11eb-9cd1-97817a1a0fa1.png">

You can test it with 
```
hex_id,value
88619aa6edfffff,0
88619aa683fffff,11.17
88619aa687fffff,6.87
88619aa68bfffff,10.87
88619aa681fffff,10.37
88619aa6b9fffff,11.12
88619aa695fffff,12.88
88619aa69dfffff,14.92
```

**Comment by heshan0131** [comment]
Should be fiexed now

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1503
