### ISSUE TITLE
[Bug] centerMap causing an incorrect viewport

### ISSUE THREAD

**Issue by GuyShaanan** [keplergl/kepler.gl#1499]
**Describe the bug**
Using the following csv as example:
```csv
lon,lat
30,30
40,40
```
results in the points not being shown after csv is loaded, unless you zoom out a bit.
Something is not working correctly with the fit to bounds.
(Might be related to #1025 (although the issue there is already fixed))
(Edit: might not be kepler bug, but this? https://github.com/mapbox/geo-viewport/issues/30)

**To Reproduce**
1. Go to kepler.gl (Issue can be easily reproduced there, but also when using keper.gl 2.5.1 in React app)
2. Add the above CSV to map (when using kepler.gl code, use `centerMap: true`)

**Current behavior**
The 2 points are not shown in viewport. You have to zoom out a bit to see them.
![image](https://user-images.githubusercontent.com/7248108/120229152-3610a000-c255-11eb-94e0-3a06f6ac703d.png)

**Expected behavior**
The 2 points should be shown in viewport.
![image](https://user-images.githubusercontent.com/7248108/120229211-4d4f8d80-c255-11eb-8fe2-e006a3b69d51.png)

**Desktop (please complete the following information):**
 - OS: *
 - Browser: Chrome
 - Version 91

**Comment by heshan0131** [comment]
Unfortunately this is a standard behavior of `[@mapbox/geo-viewport](https://www.npmjs.com/package/@mapbox/geo-viewport)`

**Comment by heshan0131** [comment]
This should be fixed
