### ISSUE TITLE
[Bug] App crashes on using redux dev tools

### ISSUE THREAD

**Issue by pervezalam-83** [keplergl/kepler.gl#1519]
**App crashes when I use redux dev tools**
I have been playing with the application and wanted to see the redux state in redux dev tool so I have added redux-devtools-extension in my application when I have enabled it app keep on crashing when within 2 mins of using it.

**Comment by heshan0131** [comment]
You should ignore `@@kepler.gl/UPDATE_MAP`, @@kepler.gl/LAYER_HOVER` and `@@kepler.gl/MOUSE_MOVE` actions
