### ISSUE TITLE
[Website] Fix GeoDataViewer VSCode Extension Github link

### ISSUE THREAD

**Issue by RandomFractals** [keplergl/kepler.gl#1524]
to point to the GeoDataViewer extension github repo: https://github.com/RandomFractals/geo-data-viewer

similar to Jupyter and Tablleau plugins github repo links in the Ecosystem section on your website home page.

Currently, that button link points directly to VS Marketplace for extension installation, which might not be the desired extension store for some devs using vscode with Open VSIX registry in some restricted environments.

Also, I would prefer that extension was called out by name. Otherwise, it just looks like it's part of the kepler.gl platform tools, and it's not. It's just one of the tools built with keplergl and has some extras in it.

Thanks!

**Comment by heshan0131** [comment]
Can you create a PR? I will merge it

**Comment by RandomFractals** [comment]
I can. I am just note sure about the last part in that request and how that would fit with your current Ecosystem section UI design. 

Will send a PR for just link change tomorrow. Thanks!

**Comment by heshan0131** [comment]
Both are fine with me. Update the link to your github, change the name to ### **VS Code Geo Data Viewer**
