### ISSUE TITLE
H3 integration

### ISSUE THREAD

**Issue by unverciftci** [keplergl/kepler.gl#154]
Do you plan to integrate H3 indexing to Kepler.gl?

**Comment by heshan0131** [comment]
Yes, we are going to add an h3 layer to kepler.gl

**Comment by stefan--** [comment]
@heshan0131 
With h3 layer added, will the hexagon radius selection become more granular (from km to m)?

**Comment by heshan0131** [comment]
Currently, out h3 layer only supports drawing hexagons based on `h3_id`. You can create a h3 layer by specify a column containing hexagon ids. 

But I think what you want is to add an option to the hexbin layer to support bin by h3 indexing? We can do that too, but can you explain the exact use cases of this?

**Comment by heshan0131** [comment]
#394
