### ISSUE TITLE
Control default side panel state for Jupyter version

### ISSUE THREAD

**Issue by johnnybarrels** [keplergl/kepler.gl#1556]
I have an application that builds Kepler.gl maps in Python, saves them to HTML and loads them in an `<iframe>`. I would like to be able to make the side panel enabled (visible) by default in the saved maps.

I found this in https://github.com/keplergl/kepler.gl/issues/945#issuecomment-598851684 :

```js
const customizedKeplerGlReducer = keplerGlReducer.initialState({
  uiState: {
    // hide side panel when mounted
    activeSidePanel: null,
    // hide all modals when mounted
    currentModal: null
  }
});
```
but I am wondering how to do the same in the Jupyter version. Going through HTML of a saved Kepler map I find this:

```js
var c = o.keplerGlReducer.initialState({ uiState: { currentModal: null, activeSidePanel: null } })
```
but changing the value of `activeSidePanel` to `true` breaks the map entirely. More specifically: nothing is displayed in the browser and the console lists the error: `react-dom.production.min.js:117 Error: [React Intl] An id must be provided to format a message.`

Is there any way to control the default behavior of the side panel from Kepler Jupyter?

**Comment by heshan0131** [comment]
you should  provide the actual panel id of the default side panel. e.g. `activeSidePanel: 'layer'`

**Comment by johnnybarrels** [comment]
Perfect, works a treat. Thanks heaps!

**Comment by SuperThinking** [comment]
@heshan0131 While trying to extend the side panels by adding a new custom panel, I get the same error. Is there any way to add more custom side panels?
