### ISSUE TITLE
How to apply kepler.gl to other types of maps?

### ISSUE THREAD

**Issue by RobinLiew** [keplergl/kepler.gl#156]
This is an impressive work!
I'm working on a large map data processing work and I want to apply kepler.gl to my html page. First,I use Apache Zeppelin spark interpreter to acquire map data.then I bind these data to my map page as shown.
[click this image](https://raw.githubusercontent.com/RobinLiew/RobinLiew.github.io/master/Issue/wkt.png)
The HTML page display as follows
[click this image](https://raw.githubusercontent.com/RobinLiew/RobinLiew.github.io/master/Issue/wkt2.png)
Now,I want to apply kepler.gl to my html map(not mapbox, maybe google map,sogou map,etc ).So,what should I do?  Could you give me some advice or solutions? Thank you very much.

**Comment by BlankRain** [comment]
看见sogoumap 我就知道这是个中国人~

**Comment by BlankRain** [comment]
@hienchu   https://github.com/uber/deck.gl/tree/master/modules/mapbox
maybe you can hack it.

**Comment by BlankRain** [comment]
@RobinLiew  @hienchu  国内的地图是要转投影及坐标的,而且基本都要申请ac.
 无缝兼容免token的可以用openstreet的地图, 
我自己魔改了一下源码,可以不用access token,加载openstreet的地图. 太费劲. 
国内mapbox访问慢,建议搭建个代理服务器转发, 这样是最轻松的.

**Comment by RobinLiew** [comment]
@BlankRain @hienchu Thank you very much for your comments.  I'll try and see if I can solve it.

**Comment by hienchu** [comment]
@macrigiuseppe any luck on this? I am trying to make it working with 高德地图

**Comment by macrigiuseppe** [comment]
@hienchu Kepler.gl supports only mapbox for now. We currently have no plan for extend Kepler to other map frameworks

**Comment by chriswu42** [comment]
Mapbox.cn offers licensed China map styles, reach out to me if you're having issues integrating.

**Comment by PancakeCard** [comment]
@BlankRain  我想把底图换高德的瓦片，这个可以加瓦片地图吗？你说的魔改，是js版本的么，python的有没有可能，谢谢！

**Comment by YinZhaoJie** [comment]
> @hienchu Kepler.gl supports only mapbox for now. We currently have no plan for extend Kepler to other map frameworks

Hi  macrigiuseppe ,  is this tool : "https://www.mapbox.cn/labs/mbxdataexplorer/" from your team or company (Uber and mapbox are the family now, isn't?) ?   
Is there any possible that make the tool's map embed into kepler.gl?  As you know,in china,we need map with a map-review-number (审图号) 。

**Comment by andrzejmiazek** [comment]
Hi, Any advise how easy way used json kepler.gl output in Google earth *with all coordinates, ranges, colors already there)? Any usable online converter that can help here (using Windows)
