### ISSUE TITLE
Unable to get this working on glitch.com due to bundle size

### ISSUE THREAD

**Issue by chrisirhc** [keplergl/kepler.gl#157]
**Describe the bug**
Huge number of dependencies might make this package difficult to add on public code playgrounds.

**To Reproduce**
1. Go to 'glitch.com'
2. Attempt to install package
3. (Takes very long to install)
4. Change code to add vis-tutorial code
5. (Never succeeds in webpack build)

**Expected behavior**
* Packages installs quickly
* webpack build succeeds within 20 seconds

**Comment by heshan0131** [comment]
closing this for now, let me know if you can make it work on glitch.com
