### ISSUE TITLE
[Bug] addDataToMap config does not seem to update

### ISSUE THREAD

**Issue by stoneman1** [keplergl/kepler.gl#1571]
**Describe the bug**
When I use dispatch(addDataToMap({datasets: dataset, config: testConfig})) for example the layers are not being added to layers array, but they go in to layersToBeMerged array instead. Not sure if it is intended, but at least the documentation has no information on that matter.

**Expected behavior**
I should have the correct config with correct layers instead of having the new layers config in layersToBeMerged.

**Comment by hkorhola** [comment]
any comments on this @heshan0131 ?

**Comment by heshan0131** [comment]
Make sure the layer.config.dataId matches the dataset.info.id you are adding
