### ISSUE TITLE
How to display heatmap in kepler.gl using react js

### ISSUE THREAD

**Issue by Sakthi3016** [keplergl/kepler.gl#1606]
this is my code
import React from "react";
import keplerGlReducer from "kepler.gl/reducers";
import { createStore, combineReducers, applyMiddleware } from "redux";
import { taskMiddleware } from "react-palm/tasks";
import { Provider, useDispatch } from "react-redux";
import KeplerGl from "kepler.gl";
import { addDataToMap } from "kepler.gl/actions";
import useSwr from "swr";
import { ThemeProvider } from "styled-components";

const reducers = combineReducers({
  keplerGl: keplerGlReducer
});

const store = createStore(reducers, {}, applyMiddleware(taskMiddleware));

const white = '#ffffff';
const customTheme = {
  sidePanelBg: white,
  titleTextColor: '#000000',
  sidePanelHeaderBg: '#f7f7F7',
  subtextColorActive: '#2473bd'
};

export default function AreaGl() {
  return (
    
  
    <Provider store={store}>
      
      <Map />
    </Provider>
  );
}

function Map() {
  const dispatch = useDispatch();
  //to load data we use useswr
  //we need to give key for useswr and say whether sync or async
  //fetch is used to fetch the response
  
  const { data } = useSwr("conflict", async () => {
    const response = await fetch(
      "https://gist.githubusercontent.com/leighhalliday/a994915d8050e90d413515e97babd3b3/raw/a3eaaadcc784168e3845a98931780bd60afb362f/covid19.json"
    );
    const data = await response.json();
    console.log(data);
    return data;
  });

  //to get data we use redux dispatch hook is used
  React.useEffect(() => {
    if (data) {
      dispatch(
        addDataToMap({
          datasets: {
            info: {
              label: "area-busyness",
              id: "area-busyness"
            },
            data
          },
          option: {
            centerMap: true,
            readOnly: false
            
          },
          config: {}
        })
      );
    }
  }, [dispatch, data]);
  const token="pk.eyJ1Ijoic2FrdGhpaWlpaWlpIiwiYSI6ImNrdDV1cTIxcjBjY2wyb2xhaHNqNTlwZXoifQ.v6irGWrvuHnFIf-_EwMMQg"
  return (
    
  <ThemeProvider theme={customTheme}>
  
    <KeplerGl
      id="area-busyness"
      mapboxApiAccessToken={token}
      width={1300}
      height={700}
      
    />
    </ThemeProvider>
            
  );
}

**Comment by heshan0131** [comment]
Pass in config should contain a heatmap in layers
an example of it here
https://github.com/keplergl/kepler.gl/blob/master/examples/demo-app/src/data/sample-trip-data.js#L3983-L3994
