### ISSUE TITLE
"If you are running in a headless environment, please do not use the open flag"

### ISSUE THREAD

**Issue by kirkjaa** [keplergl/kepler.gl#161]
Hello,
I had no issue running this from my local environment, however as I tried to install this on DO Server:
I'm trying to have this run on a server and  yes it gave me this error where I can't access the application on port 8080. Where to omit the open flag ?

**Comment by kirkjaa** [comment]
Hello,
I'm still eagerly await on some form or fashion of contructive support from your opensource team. Basically people need to be able to install this into a headless environment on a server. And if you can run this on a laptop it's pretty hard to share this your geo data set with a team. So yes document on installation on a server would be good.  Thanks for reading and it would be great to reply. @heshan0131

**Comment by heshan0131** [comment]
@kirkjaa I haven't tried running it on a server, following [webpack-dev-server source code](https://app.codacy.com/app/webpack/webpack-dev-server/pullRequest?prid=666034) Can you try delete `--open` in [examples/demo-app/packge.json](https://github.com/uber/kepler.gl/blob/master/examples/demo-app/package.json#L4) and see if that fixes it?

**Comment by kirkjaa** [comment]
@heshan0131 I deleted --open in both examples/demo-app/packge.json and website it runs now without the headless message but still can't access from the server. So I have to figure it our from  webpack-dev-server source code ? I supposed to get it working on server URL or IP address. Thanks anyway for the suggestion.

**Comment by nkochanek** [comment]
@kirkjaa  

This should be your fix.

```
"start": "webpack-dev-server --progress --hot --port 8009 --host 0.0.0.0"
```

Basically you need to set the ```--host ``` flag to be 0.0.0.0 (ie. not localhost). This is working fine for me on AWS w/ Ubuntu 16.04. Just make sure that you're also allowing inbound requests to your server as well.

**Comment by kirkjaa** [comment]
@nkochanek Sorry for a reply since other project preoccupied my time for the past couple of days. I can vouched 100% your tip rocks ! I got it working now on DO Ubuntu 16.04 node 9. Thank you and your tip was probably the most helpful I got from this repo LOL

**Comment by doc-DJJ** [comment]
> @ heshan0131我删除了 - 在示例/ demo-app / packge.json和网站中打开它现在运行时没有无头消息，但仍然无法从服务器访问。所以我必须从webpack-dev-server源代码中找到它们？我应该让它在服务器URL或IP地址上工作。无论如何，谢谢你的建议。

I have taken your approach, but it still doesn't work.
