### ISSUE TITLE
How to load files without messing with processors and without using drag and drop?

### ISSUE THREAD

**Issue by hxnt** [keplergl/kepler.gl#162]
Kepler has the ability to drop in csv, json, and geojson files, where the file processing and converting into a kepler.gl structure {fields, rows} is handled in the background, and does not require re-bundling and re-loading the application. How do I load in data files like the drag and drop system does, but by specifying the filepath in the code? I have worked through the [Vis Acedemy tutorial](http://vis.academy/#/kepler.gl/) but I still cannot find a solution.

**Comment by heshan0131** [comment]
@austinwade if your data files are  in `csv` or `geojson` format, you will need to use processors. The Vis Academy tutorial should show you how to do that.

Are you asking how to directly load files with `{fields, rows}`? 

If you share a code snippet, it would be easier to under stand the request

**Comment by austinwade** [comment]
Hi @heshan0131, thanks so much for the reply.

When you press `Add Data` on the left sidebar and drag files in, everything including processing and converting the files to `{fields, rows}` is handled. Using the `Add Data` button, you can load arbitrary `csv` and `geojson` files, where Kepler determines the file type, which processor to use, and loads the data seamlessly without the user having to do anything.

I am trying to load data files (`csv`, `geojson`) in this way, but without the user having to go through the literal motion of dragging and dropping a file. Is there a way to instead of dragging and dropping a file, specify a file path that Kepler will load data from on startup, and load the file the same way the `Add Data` button does so that I don't have to explicitly specify processors?

**Comment by heshan0131** [comment]
[The load data section](http://vis.academy/#/kepler.gl/2-load-data) in vis.academy does exactly that.

**Comment by austinwade** [comment]
[The load data section](http://vis.academy/#/kepler.gl/2-load-data) walks through importing a raw data file and then manually choosing which processor to use, either `processCsvData()` or `processGeojson()`. When using the `Add Data` button, `processors/file-handler.js` appears to be being used to, without users explicitly specifying in `src/app.js`, choose which processor to use and loads the data.

I'd ideally like to load data from a file without dragging and dropping or choosing the file from my drive via pop up window, and without knowing ahead of time what the right Kepler processor to use is, thus using `processors/file-handler.js` or something the same way the `Add Data` button loads data. I've searched and tried to implement this myself but I simply couldn't get it to work. I'm new to React so maybe it's just my lack of understanding. Thanks for helping @heshan0131.

**Comment by rozajay** [comment]
Any updates on this? Currently trying to upload 2 default csv files on start of web app but struggling to navigate around the files in order to achieve this.

**Comment by rozajay** [comment]
Hey @austinwade not sure if this is what you are after but I was able to load multiple datasets without drag and drop on start with this code:

```javascript  componentDidMount() {
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data_ta = Processors.processCsvData(nycTrips);
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data_m = Processors.processCsvData(dataset01);
    var data = data_ta;
    // Create dataset structure
    const dataset_t = {
      data,
      info: {
        // `info` property are optional, adding an `id` associate with this dataset makes it easier
        // to replace it later
        id: "my_data"
      }
    };
    data = data_m;
    // Create dataset structure
    const dataset_s = {
      data,
      info: {
        // `info` property are optional, adding an `id` associate with this dataset makes it easier
        // to replace it later
        id: "my_data_s"
      }
    };
    // addDataToMap action to inject dataset into kepler.gl instance
    // I'm parsing them in as an array
    this.props.dispatch(addDataToMap({ datasets: [dataset_s,dataset_t] }));

  }`

**Comment by heshan0131** [comment]
You can dispatch the [`loadFiles`](https://github.com/uber/kepler.gl/blob/master/src/actions/vis-state-actions.js#L224-L229) action, exported by kepler.gl. This action takes an array of `fileBlobs`, it will determine which processor to use based on filename `.csv` or `.json`, process the file then call `updateVisData`; See the source code of `loadFilesUpdater` - reducer handler of the `loadFiles` action [here](https://github.com/uber/kepler.gl/blob/master/src/reducers/vis-state-updaters.js#L927-L966)
  
```
import {loadFiles} from `kepler.gl/actions`;
...
componentDidMount() {
    // create blob from string
    const myblob = new Blob([JSON.stringify(sampleGeojson)]);
    // create file from blob, adding file name
    const files = new File([myblob], 'zip.json');
    this.props.dispatch(loadFiles(
      [files]
    ))
}
```

Note that, you won't be able to pass in any config using `loadFiles` action
