### ISSUE TITLE
To-Triage: Add custom base map tiles

### ISSUE THREAD

**Issue by ziyili66** [keplergl/kepler.gl#164]

**Comment by mogita** [comment]
Do we have any updates on this?
We plan to use our self-hosted map tile server in Kepler.gl too.

**Comment by macrigiuseppe** [comment]
please have a look at the documentation for custom map styles, here: https://github.com/keplergl/kepler.gl/blob/master/README.md#mapstyles-array-optional

In the URL part you can point to https://[WHERE YOUR STYLE JSON IS HOSTED]
