### ISSUE TITLE
Custom Reducer Example - Mapbox not loading (v0.0.25)

### ISSUE THREAD

**Issue by izuro** [keplergl/kepler.gl#165]
Mapbox isn't loading for me on kepler.gl (v0.0.25) I have tried the **Demo App** example which loads fine, however the Custom Reducer example gives me a blank map.

- It appears the mapbox tile requests are being denied for the [Custom Reducer Example (v0.0.25)](https://github.com/uber/kepler.gl/tree/master/examples/custom-reducer) `{"message":"Forbidden"}`
- I've made sure my MapboxAccessToken is valid, tested and working on the [visacademy examples](http://vis.academy/#/kepler.gl/setup) (kepler.gl v0.0.19)
- When using v0.0.25 on visacademy examples the map doesnt load, without any errors in console.
- Deployed on localhost

![s1](https://user-images.githubusercontent.com/1096891/42670879-46ec81fa-8612-11e8-8db7-9731aae008dd.JPG)
![s2](https://user-images.githubusercontent.com/1096891/42670982-b5a14842-8612-11e8-97bd-7117954069c1.JPG)

**Comment by rochapablo** [comment]
Any news about this?

**Comment by heshan0131** [comment]
should be fixed, closing for now
