### ISSUE TITLE
[Bug] Custom side panels no longer working in `replace-component` example

### ISSUE THREAD

**Issue by fnoble** [keplergl/kepler.gl#1650]
**Describe the bug**
`replace-component` example no longer shows the Rocket and Chart custom side panels in v2.5.0

**To Reproduce**
Run the `replace-component` example from kepler.gl v2.5.0

**Expected behavior**
The custom side panels are displayed.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Browser: Brave (Chromium derivative)
 - Version: 1.29.79

**Additional context**
I believe this is due to the changes introduced in #1339. I've tried to make a version that follows how `side-panel-test.js` now injects a custom `SidePanelFactory`, however I haven't been able to get it working yet as it seems like `injectComponents()` isn't correctly picking up the custom `SidePanelFactory`.

**Comment by fnoble** [comment]
Ok I got my own code working, I just needed to ensure `CustomSidePanelFactory` was injected first otherwise it overrides the injection of `CustomPanelsFactory` as per the warning message.

**Comment by fnoble** [comment]
Why was this closed? Although I got my own code working, the example code in the repo is still broken..

**Comment by heshan0131** [comment]
There was a PR fixing it, but I will take a look at the examples again

**Comment by pdashk** [comment]
any update on this? or @fnoble able to share a minimal working example? many thanks

**Comment by nuKs** [comment]
I wonder if this also broke the jupyterlab copy button (I am new to kepler, found it in code but not in the widget / html)

**Comment by Rahul-0108** [comment]
This issue is there in v2.5.5 , Can anyyone give solution how to make this work ??

**Comment by lalzart** [comment]
@Rahul-0108  @fnoble 

Were you able to render a custom side panel? I'm really struggling with this one.
