### ISSUE TITLE
How to add a Custom svg icon as a pointer and how to rotate that pointer using angle?

### ISSUE THREAD

**Issue by mrgopal15** [keplergl/kepler.gl#1654]
First Thanks for the awesome Map component.

I want to add a custom svg icon as a pointer Icon and I want to rotate the pointer using angle. in React Leaflet have that option.

Is that any similar option available at Kepler gl?

If anyone have idea, please share with me

Thanks

**Comment by sinannoureddine** [comment]
Were you able to solve this? I can't figure  out how to change the icon yet
