### ISSUE TITLE
Organize layers by dataset

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#1658]
### Problem
Currently the only way to associate a layer with a dataset is by matching the colors of dataset square with the color border of a layer panel.  It would be nice to have a option in the layer panel to organize layers by dataset, display layers as childrens of the dataset it is based on. 

### Solution
1. Add a `PanelViewListToggle` component on top of the layer manager
2. Add `layerPanelListView` to `uiState` reducer. `uiState.layerPanelListView = 'list' | 'sortByDataset'`
3. Add `toggleLayerPanelListView` to `uiStateActions` 
4. `PanelViewListToggle` component should render 2 view options `list` `sortByDataset`
5. `PanelViewListToggle` should call `toggleLayerPanelListView` to update `uiState.layerPanelListView`
6. Default `uiStat.layerPanelListView` value should be `'list'`
7. Render layer panels group by dataset if `layerPanelListView === 'sortByDataset'`

### UI Design

**PanelViewListToggle Component**

<img width="357" alt="Screen Shot 2021-11-30 at 10 14 53 AM" src="https://user-images.githubusercontent.com/3605556/144074107-c20ccba5-33e2-40cc-8086-2503640f6134.png">

**Organize layers by dataset**

<img width="353" alt="Screen Shot 2021-11-30 at 10 15 01 AM" src="https://user-images.githubusercontent.com/3605556/144074164-4fe5ad67-53d8-4820-b315-e1ad1f942145.png">

**Comment by ibgreen** [comment]
Love this! 

FWIW, I would personally prefer if the datasets list at the top disappeared in the hierarchical view (and the dataset cards were moved into the tree, replacing the dataset headers). 

That dataset list is a bit of a "design crutch" IMHO, it kind of bothers me that the first thing I see in the "layers" tab is a list of "datasets" (although I do understand why it is done this way and I agree that it has some value in the "flat" view).
