### ISSUE TITLE
Extend SidePanel native tabs components

### ISSUE THREAD

**Issue by kutuev** [keplergl/kepler.gl#167]
Hello,

I need to add a custom tab on SidePanel. So yes, it's possible to override SidePanel since it extended as a factory:
```
// factories
export {default as SidePanelFactory} from './side-panel';
```

But other tabs (LayerManager, FilterManager etc) are not extended, so if I will create a custom SidePanel I'd like to have a native SidePanel tabs + my custom tab.

But locally I extended common/index.js file and added:

```
export {default as Sidebar} from './side-panel/side-bar';
export {default as LayerManager} from './side-panel/layer-manager';
export {default as FilterManager} from './side-panel/filter-manager';
export {default as InteractionManager} from './side-panel/interaction-manager';
export {default as MapManager} from './side-panel/map-manager';
export {default as PanelToggle} from './side-panel/panel-toggle';
```

After I'm able to use native tabs in my custom SidePanel

My question is: Can you extend this code or probably I can create a pull request so you can consider and merge it later?

**Comment by heshan0131** [comment]
close as this is merged with #282 into `^0.2.0`
