### ISSUE TITLE
[Bug][Jupyter Widget] Widget does not render on Databricks Notebooks

### ISSUE THREAD

**Issue by Inrixia** [keplergl/kepler.gl#1680]
**Describe the bug**
Widget does not appear to work on Azure Databricks Notebooks. Is there something I am missing or is kepler.gl not usable here?

**To Reproduce**
1. Install & load kepler
2. Try to display a map

**Expected behavior**
The map displays

**Screenshots**
![image](https://user-images.githubusercontent.com/6373693/150464008-608ed67f-7614-48ba-abf0-00c72ca2db26.png)

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/6373693/150464026-6f46a13d-908c-456e-938c-ecd406952e5e.png)
![image](https://user-images.githubusercontent.com/6373693/150464038-498f215c-fc46-4a36-860a-359cee9d0f66.png)
![image](https://user-images.githubusercontent.com/6373693/150464054-73822b6f-2b21-49a1-8d07-d3e07e5d3fd4.png)

**Comment by lixun910** [comment]
Is there any related error message in the browser console?

**Comment by Inrixia** [comment]
Not from what I can tell. I'm trying out running some commands on the cluster to install node and a few other libraries to see if I can hack it into working, but I feel like it shouldn't be required.

**Comment by Inrixia** [comment]
Yep no errors in console

**Comment by Inrixia** [comment]
I attempted manually installing node and the labextension incase it could make any difference but it does not.
![image](https://user-images.githubusercontent.com/6373693/150465415-520801cd-a3ca-4a18-8e0c-24c2cffd8929.png)

**Comment by lixun910** [comment]
Em, does `map_1.show()` work?

**Comment by Inrixia** [comment]
I did try it earlier, just gives nothing 
![image](https://user-images.githubusercontent.com/6373693/150465942-ed3673b8-ae66-420e-aed7-8b987701403c.png)

**Comment by Inrixia** [comment]
Looks like this might be a databricks issue as trying another interactive notebook library `ipyleaflet` also does not work...
![image](https://user-images.githubusercontent.com/6373693/150466720-e37aa74d-fb45-4f2f-809b-bcb750da087c.png)

Weirdly calling `display()` does though... Let me know if you have any ideas on why this might be, Ill open a support ticket with Azure

**Comment by lixun910** [comment]
I was able to try it in databricks and got the same issue. Will take a look at it.

**Comment by Inrixia** [comment]
Supposedly databricks does not use Jupiter notebooks under the hood and this is why its not working.
Generating the map and then saving it gets around this issue easily. You can also use the `displayHTML()` function but this is limited to 10MB files.

```python
from keplergl import KeplerGl

data = mapDF.toPandas()

map_1 = KeplerGl()
map_1.add_data(data=data, name='My map data')

map_1.save_to_html(file_name="/dbfs/FileStore/" + FILENAME)
displayHTML("""<a href="https://REDACTED.azuredatabricks.net/files/""" + FILENAME + """" download>Download BL Map</a>""")
```
