### ISSUE TITLE
Node.js backend server for interaction with map

### ISSUE THREAD

**Issue by chintanp** [keplergl/kepler.gl#171]
**Is your feature request related to a problem? Please describe.**
I have been through the tutorials on [vis-academy](vis.academy/) to begin work on kepler.gl  and while the tutorials are incredibly helpful, the rather technically advanced nature of the tech stack (React + MapBox.gl +... etc.) makes it hard to make enhancements, especially something as fundamental as hooking up a Node.js server to interact with the frontend. So, for example, I would like to load a map, and then update it based on user-click  -- which gets sent to the backend and is acted upon -- and the response triggers a redraw of the map. 

**Describe the solution you'd like**
The [FAQ](https://github.com/uber/kepler.gl/blob/master/docs/i-FAQ.md#how-can-i-get-data-from-my-back-end-service-into-keplergl) does talk in brief about the idea, a slightly detailed algorithm, or a brief example demonstrating interactions with the server would be really helpful.

**Comment by rochapablo** [comment]
Any update about this?

**Comment by mikefab** [comment]
github.com/unicef/magicbox-kepler-demo

**Comment by heshan0131** [comment]
Closing it for now, please reopen if there is any further development

**Comment by cjrobbertse** [comment]
> Hi @chintanp,
> thank you for using Kepler.gl.
> If you look at the latest vis.academy example (http://vis.academy/#/kepler.gl/3-load-config). You will notice the last step of the tutorial shows how to replace your current dataset.
> 
> I think you can take a look at the example and in your case, you have to handle user interaction (click) and trigger a call to your backend server.
> 
> Flow:
> 
>     * User clicks
> 
>     * Trigger an async call to your server
> 
> 
> Once you have your data back from the server you can use something similar to this:
> 
> ```
> // Created to show how to replace dataset with new data and keeping the same configuration
>   updateData = () => {
>     // Retrieve the new data from the server
>    const {data} = this.props; // a simple way
> 
>     // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
>     const data = Processors.processCsvData(newData);
>     // Create dataset structure
>     const dataset = {
>       data,
>       info: {
>         id: 'my_data'
>         // It is paramount that this id mathces your configuration otherwise the configuration file will be ignored.
>       }
>     };
> 
>     // This is extremely importatnt
>    // read the current configuration
>     const config = this.getMapConfig();
> 
>     // addDataToMap action to inject dataset into kepler.gl instance
>     this.props.dispatch(addDataToMap({datasets: dataset, config}));
>   };
> ```
> 
> Let me know if this helps.

I have not been able to use any async function within this context. The browser goes white.

**Comment by chintanp** [comment]
@cjrobbertse It would help to look at a code sample of how you are doing it on the client and server.

**Comment by cjrobbertse** [comment]
After using the web developer console, I found the logs which made debugging a lot easier. But I tried to perform a basic async function and it did not work. This was before I checked the logs, and the display remained white. 

```js
// Created to show how to replace dataset with new data and keeping the same configuration
updateData = () => {
  async function test () {
    const newData = `TMSI,Latitude,Longitude,Confidence
      null,50.54072,-1.24957,20`
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data = Processors.processCsvData(newData)
    // Create dataset structure
    const dataset = {
      data,
      info: {
        id: 'my_data'
        // It is paramount that this id mathces your configuration otherwise the configuration file will be ignored.
      }
    }

    // This is extremely importatnt
    // read the current configuration
    const config = this.getMapConfig()

    // addDataToMap action to inject dataset into kepler.gl instance
    this.props.dispatch(addDataToMap({ datasets: dataset, config }))
  }

  test()
}
```
