### ISSUE TITLE
Allow wrapping on meridian line or changing its location

### ISSUE THREAD

**Issue by Inrixia** [keplergl/kepler.gl#1716]
**Is your feature request related to a problem? Please describe.**
As can be seen in this image:
![image](https://user-images.githubusercontent.com/6373693/154380566-6c8059c8-8863-421f-ab71-55df8d8f6fa0.png)
When data lies across the meridian line it gets cutoff.

**Describe the solution you'd like**
The ability to either move this boundary so that all data can be displayed together, or the ability to wrap visualizations so there is no cutoff and everything just repeats on the x axis.

**Describe alternatives you've considered**
This isnt an alternative fix to this.

**Comment by heshan0131** [comment]
Thank you for reporting this, can you share a sample of your data for us to test with?
