### ISSUE TITLE
Loading multiple datasets on start up

### ISSUE THREAD

**Issue by rozajay** [keplergl/kepler.gl#172]
Hi there :)

Currently following through the tutorial on vis academy. http://vis.academy/#/kepler.gl/2-load-data
The tutorial is super clear and easy to follow through.
However, I'm having trouble loading two sets of data in componentDidMount.
This is what I have tried so far:

```javascript
  componentDidMount() {
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data = Processors.processCsvData(nycTrips);
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data_ta = Processors.processCsvData(dummydata01);
    // Create dataset structure
    const dataset = {
      data,
      info: {
        // `info` property are optional, adding an `id` associate with this dataset makes it easier
        // to replace it later
        id: "my_data"
      }
    };
    // Creaing a second dataset
    const dataset_ta = {
      data_ta,
      info: {
        // `info` property are optional, adding an `id` associate with this dataset makes it easier
        // to replace it later
        id: "data_ta"
      }
    };
    // addDataToMap action to inject dataset into kepler.gl instance
    // I'm parsing them in as an array
    this.props.dispatch(addDataToMap({ datasets: [dataset,data_ta] }));
  }```

Is this the right approach or am I totally on the wrong path?

Thanks in advance for your help. 

@heshan0131

**Comment by rozajay** [comment]
I think I have managed to achieve this through change componentDidMount() function here.
```javascript  
componentDidMount() {
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data_ta = Processors.processCsvData(nycTrips);
    // Use processCsvData helper to convert csv file into kepler.gl structure {fields, rows}
    const data_m = Processors.processCsvData(dataset01);
    var data = data_ta;
    // Create dataset structure
    const dataset_t = {
      data,
      info: {
        // `info` property are optional, adding an `id` associate with this dataset makes it easier
        // to replace it later
        id: "my_data"
      }
    };
    data = data_m;
    // Create dataset structure
    const dataset_s = {
      data,
      info: {
        // `info` property are optional, adding an `id` associate with this dataset makes it easier
        // to replace it later
        id: "my_data_s"
      }
    };
    // addDataToMap action to inject dataset into kepler.gl instance
    // I'm parsing them in as an array
    this.props.dispatch(addDataToMap({ datasets: [dataset_s,dataset_t] }));

  }`

**Comment by heshan0131** [comment]
You can dispatch the [`loadFiles`](https://github.com/uber/kepler.gl/blob/master/src/actions/vis-state-actions.js#L224-L229) action, exported by kepler.gl. This action takes an array of `fileBlobs`, it will determine which processor to use based on filename `.csv` or `.json`, process the file then call `updateVisData`; See the source code of `loadFilesUpdater` - reducer handler of the `loadFiles` action [here](https://github.com/uber/kepler.gl/blob/master/src/reducers/vis-state-updaters.js#L927-L966)
  
```
import {loadFiles} from `kepler.gl/actions`;
...
componentDidMount() {
    // create blob from string
    const myblob = new Blob([JSON.stringify(sampleGeojson)]);
    // create file from blob, adding file name
    const files = new File([myblob], 'zip.json');
    this.props.dispatch(loadFiles(
      [files]
    ))
}
```

Note that, you won't be able to pass in any config using `loadFiles` action

**Comment by Laneville** [comment]
@rozajay was this solved? did you manage to achieve loading two datasets?

**Comment by rozajay** [comment]
Hey yeah this was solved. Had to change the config file and the code to be loading new data.

**Comment by Laneville** [comment]
@rozajay do you mind sharing a snippet of your code? I've tried the same approach you mentioned above but it doesn't seem to be taking both datasets.

**Comment by tanveer21** [comment]
> @rozajay do you mind sharing a snippet of your code? I've tried the same approach you mentioned above but it doesn't seem to be taking both datasets.

Is there any update on this?

**Comment by brianshano** [comment]
I'm importing 2 datasets in a functional component, just dropping the code exampe if it helps. 


```
import dataset_a from "data.json"
import dataset_b from "datab.json"

......
const dispatch = useDispatch();

  useEffect(() => {
    if (dataset_a) {
      dispatch(
        addDataToMap({
          datasets: [
            {
              info: {
                label: "dataset a",
                id: "data_a",
              },
              data: dataset_a,
            },
            {
              info: {
                label: "dataset b",
                id: "data_b",
              },
              data: dataset_b,
            },
          ],
          option: {
            centerMap: true,
            readOnly: false,
          },
        })
      );
    }
  }, [dispatch, dataset_a]);
```

**Comment by heshan0131** [comment]
> I'm importing 2 datasets in a functional component, just dropping the code exampe if it helps.
> 
> ```
> import dataset_a from "data.json"
> import dataset_b from "datab.json"
> 
> ......
> const dispatch = useDispatch();
> 
>   useEffect(() => {
>     if (dataset_a) {
>       dispatch(
>         addDataToMap({
>           datasets: [
>             {
>               info: {
>                 label: "dataset a",
>                 id: "data_a",
>               },
>               data: dataset_a,
>             },
>             {
>               info: {
>                 label: "dataset b",
>                 id: "data_b",
>               },
>               data: dataset_b,
>             },
>           ],
>           option: {
>             centerMap: true,
>             readOnly: false,
>           },
>         })
>       );
>     }
>   }, [dispatch, dataset_a]);
> ```

the way you pass in datasets to addDataToMap is correct, looking at the above code, you should add `dataset_a` to your useEffect dependencies and check `if (dataset_a, dataset_b)`

**Comment by raghavrawat98** [comment]
Hello. I want to fetch multiple geojson() data and then load on my map. Can you please help? I'm stuck.
Here is my code snippet. I then need to add layer to this data.
` const { dataset_a } = useSwr("dataset_a", async () => {
    const response = await fetch(
      "url1"
      );
      const dataset_a = response.json();
    return dataset_a;
  });

  const { dataset_b } = useSwr("dataset_b", async () => {
    const response1 = await fetch(
      "url2"
    );
     const dataset_b = response1.json();
    return dataset_b;
  });

  const { dataset_c } = useSwr("dataset_c", async () => {
    const response2 = await fetch(
      "url3"
    );
    const dataset_c = await response2.json();
    return dataset_c;
  });

  React.useEffect(() => {
    if ([dataset_a,dataset_b,dataset_c].includes(undefined)==false) {
      dispatch(
        addDataToMap({
          datasets: [
            {
              info: {
                label: "dataset a",
                id: "data_a"
              },
              data: dataset_a,
            },
            {
              info: {
                label: "dataset b",
                id: "data_b"
              },
              data: dataset_b,
            },
            {
              info: {
                label: "dataset c",
                id: "data_c"
              },
              data: dataset_c,
            }
          ],
          option: {
            centerMap: true,
            readOnly: false
          },
          config: {}
        })
      );
    }
  }, [dispatch, data]);`
