### ISSUE TITLE
Add feature to open map-popover programmatically

### ISSUE THREAD

**Issue by kutuev** [keplergl/kepler.gl#173]
Hello,

Looks like it's impossible to open map-popover programmatically.
I used onLayerHover action, but have coordinates of the point (lngLat) and data.
In that case viewport is null but function _renderObjectLayerPopover  requires it.

So, can we add a possibility to open map-popover programmatically?

Thanks,
Alexander

**Comment by macrigiuseppe** [comment]
hello @kutuev, can you share more details?
Do you simply want to open the tooltip or sho any react component?

Thank you

**Comment by rochapablo** [comment]
I have a question that could be related...

Is it possible add actions inside the tooltip or even load external react component as mentioned?

Like, the user use the right click and delete or add some information about an specific row.

**Comment by macrigiuseppe** [comment]
Hi @rochapablo, you are talking about Annotations. That's a different feature!!

**Comment by macrigiuseppe** [comment]
this will be part of https://github.com/keplergl/kepler.gl/issues/398

**Comment by mkopani** [comment]
I'd like to open this up again. Is there a way to programmatically show and pin a map-popover using coordinates (a single lat-long pair) in 2024? I have already implemented the search util that finds the polygon feature containing the coordinates but I have been unable to trigger `LAYER_HOVER` or `LAYER_CLICK` using the feature.

@akutuev did you ever end up figuring it out?

Thank you
