### ISSUE TITLE
[Bug] White Window when try to Add an HexBin Layer

### ISSUE THREAD

**Issue by GuMesZe** [keplergl/kepler.gl#1766]
**Describe the bug**
When Add a DataBase, and try to add an HexBin Layer, the window turn into white window.

**To Reproduce**
1. Go to '(https://kepler.gl/demo)'
2. Click on 'Add Data.'
3. Add a .CSV data
4. Change the Layer from Point to HexBin
5. See the error.

**Expected behavior**
Change to HexBin Layer

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 99.0.4844.84

**Comment by heshan0131** [comment]
#1795

**Comment by heshan0131** [comment]
Fix is merged, close for now
