### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Frenzyt01** [keplergl/kepler.gl#1770]
**Describe the bug**
The programme crashes everytime I try to select the Grid or Hexbin types,
Do not know why, was working some days ago...

**Expected behavior**
Not crashing 

**Screenshots**
the page just became white suddenly 

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [e.g. chrome, and edge ]

**Additional context**
Any help would be highly appreciated.
Thanks

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1795

**Comment by heshan0131** [comment]
Fix is merged, close for now
