### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lukasfriberger** [keplergl/kepler.gl#1785]
**Kepler Crashing**
When selecting grid or hexabin in a dataset, the Kepler application crashes every time. 

**To Reproduce**
1. Go to 'the main page'
2. Click on 'upload data'
3. Upload a dataset with geodata  
4. Try to change the data from 'point count' to hexabin
5. See error

**Expected behavior**
The scree goes white and you have to reload kepler

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [e.g. chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cathulhu** [comment]
Also got the exact same bug on PC

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1795
