### ISSUE TITLE
How to Add Custom Side panel and button for that in PanelToggle

### ISSUE THREAD

**Issue by Rahul-0108** [keplergl/kepler.gl#1800]
I followed the replace component example in kepler gl . I cannot see the custom side panel there . can you help to create a custom side panel along with the toggle button

and also how to remove layer toggle button 

![image](https://user-images.githubusercontent.com/53996840/164702446-c6554a56-c3e7-4f91-aac2-64d716704773.png)

**Comment by Rahul-0108** [comment]
Its Solved

**Comment by gonzalezge** [comment]
How did you solved it?
