### ISSUE TITLE
Kepler.GL integration in Next JS app

### ISSUE THREAD

**Issue by SusantaKumar27** [keplergl/kepler.gl#1802]
I am integrating Kepler.GL in my Next JS app, but while rendering the <KeplerGL /> component, I am getting the following error.

`Error: Could not find "store" in the context of "Connect(Container)". Either wrap the root component in a <Provider> or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Container) in connect options.`

I have tried different versions of the packages, as well as in different Next JS apps. Also, I have wrapped my root component in a <Provider /> tag and passed the store correctly (as suggested in the error), but still getting the same error every time.

 - store.js
```import thunk from 'redux-thunk';
import { composeWithDevTools } from 'redux-devtools-extension';
import { createStore, combineReducers, applyMiddleware } from 'redux';
import keplerGlReducer from 'kepler.gl/reducers';
import { appReducer } from '../reducers/appReducer';

const initialState = {};

const reducers = combineReducers({
    app: appReducer,
    keplerGl: keplerGlReducer,
});
const middleware = [thunk];

export const store = createStore(
    reducers,
    initialState,
    composeWithDevTools(applyMiddleware(...middleware))
);
```

 - app.js
```import '../styles/globals.css';
import { Provider } from 'react-redux';
import { store } from '../store';

function MyApp({ Component, pageProps }) {
    return (
        <Provider store={store}>
            <Component {...pageProps} />
        </Provider>
    );
}

export default MyApp;
```

 - KeplerMap.js
```import React from 'react';
import KeplerGl from 'kepler.gl';

function KeplerMap(props) {
    return (
        <div>
            <KeplerGl
                id="example"
                mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
                width={400}
                height={400}
            />
        </div>
    );
}

export default KeplerMap;
```

I am not sure that Kepler.GL is compatible with Next JS or not, but I want to know why this error is showing and how to resolve it

**Comment by benliq** [comment]
Hello @SusantaKumar27 , did you finally managed to implement keplerGL in NextJS?
I try since few days, but can't get a working solution. Thanks a lot. Ben

**Comment by SusantaKumar27** [comment]
> Hello @SusantaKumar27 , did you finally managed to implement keplerGL in NextJS? I try since few days, but can't get a working solution. Thanks a lot. Ben

Hi @benliq , yes I was able to implement it. 
There are some version compatibility issues. Kepler.GL is not compatible with react 18, So I had to downgrade my React version and as the latest version of Next.JS requires React 18, so I had to downgrade the Next.JS version as well.

The versions of the packages used in my `package.json` are:
`{
  "name": "project-name",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/mapbox-gl": "^2.7.6",
    "kepler.gl": "^2.5.5",
    "mapbox-gl": "^2.10.0",
    "next": "11.1.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-palm": "^3.3.8",
    "react-redux": "^7.2.8",
    "redux": "^4.2.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.4.2",
    "swr": "^1.3.0"
  },
  "resolutions": {
    "@types/react": "~17.0.21"
  },
  "devDependencies": {
    "@types/node": "^16.7.10",
    "@types/react": "17.0.15",
    "@types/react-dom": "18.0.6",
    "eslint": "7.31.0",
    "eslint-config-next": "11.0.1",
    "typescript": "4.8.4"
  }
}`

**Comment by benliq** [comment]
Thanks a lot @SusantaKumar27 for your help. It's working now!

**Comment by tazo90** [comment]
@benliq, @SusantaKumar27 
I was able to successfully run kelper on nextjs 13.
Kepler should work only as a client-side component, we have to disable SSR on it.

The following code works for me:

```
import dynamic from "next/dynamic";
const KeplerGL = dynamic(() => import("@packages/kepler"), { ssr: false });

export default function App() {
  return <KeplerGL />;
}
```
