### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read properties of null (reading 'setProps') at Deck.setProps

### ISSUE THREAD

**Issue by kp1129** [keplergl/kepler.gl#1842]
**Describe the bug**
  
I am integrating kepler.gl into my CRA app. When I start the app, the left sidebar controls and the 'Add Data to Map' modal appear on the screen for a moment, then the app breaks with the following errors in the browser console:
  
<img width="700" alt="Screen Shot 2022-06-14 at 12 41 19 PM" src="https://user-images.githubusercontent.com/41562973/173631021-c09314d6-a93c-46f1-8c87-50862300d6bf.png">

I haven't touched the Deck component at all, and I haven't seen anything in the docs about manually setting props on the Deck component as part of installation and setup 🤔  Please help me understand what I'm doing wrong.
    
My code:
```
import keplerGlReducer from 'kepler.gl/reducers';
import { createStore, combineReducers, applyMiddleware } from 'redux';
import { taskMiddleware } from 'react-palm/tasks';
import { Provider } from 'react-redux';
import { KeplerGl } from 'kepler.gl/dist/components';


const reducers =  combineReducers({
  keplerGl: keplerGlReducer
});

const store = createStore(reducers, {}, applyMiddleware(taskMiddleware));

function App() {
  return (
    <Provider store={store}>
      <Map />
    </Provider>
  )
}

export default App;

function Map() {
  return (
    <KeplerGl 
      id="covid" 
      mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_API} 
      width={window.innerWidth}
      height={window.innerHeight}
      store={store}
    />
  )
}
```
Dependencies:
```
"dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "kepler.gl": "^2.5.5",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-palm": "^3.3.8",
    "react-redux": "^8.0.2",
    "react-scripts": "5.0.1",
    "redux": "^4.2.0",
    "styled-components": "^5.3.5",
    "swr": "^1.3.0",
    "web-vitals": "^2.1.4"
  }
```

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.0.1
 - Browser: Chrome 100.0.4896.88

**Comment by kp1129** [comment]
I ended up reverting to an earlier version of React + using yarn instead of npm and it finally worked.

**Comment by RahulGupta-8319** [comment]
can you tell which version you use
