### ISSUE TITLE
react Kepler Gl map crashes when importing CSV file (Class constructor Geometry cannot be invoked without 'new')

### ISSUE THREAD

**Issue by sinannoureddine** [keplergl/kepler.gl#1873]
Hello, i'm running Kepler GL and the map works fine but crashes when i import a CSV file.

The console is returning "Class constructor Geometry cannot be invoked without 'new'" when i import the CSV file. However same CSV file works well when i import it on the Kepler Demo map (https://kepler.gl/demo)
My node version on my pc is : 16.16.0
Here is my package.json file in React. 

{
  "scripts": {
    "start": "node server.js",
    "start-local": "WEBPACK_ENV=es6 node server.js"
  },
  "dependencies": {
    "express": "^4.17.1",
    "global": "^4.3.0",
    "kepler.gl": "^2.5.5",
    "react": "^17.0.2",
    "react-dom": "^16.8.4",
    "react-palm": "^3.3.6",
    "react-redux": "^7.1.3",
    "react-virtualized": "^9.21.0",
    "redux-actions": "^2.2.1",
    "styled-components": "^4.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.1",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "@babel/preset-typescript": "^7.16.7",
    "babel-loader": "^8.0.0",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1",
    "webpack-dev-middleware": "^3.7.0",
    "webpack-dev-server": "^3.1.14",
    "webpack-hot-middleware": "^2.25.0"
  }
}

Any idea why that might be happening? Thank you!

**Comment by rayavarapusrikanth** [comment]
can someone please let me know the solution for this issue please? I'm also facing the same issue.
