### ISSUE TITLE
How can I link custom button in toggle Panel and the content ? 

### ISSUE THREAD

**Issue by RedRosh** [keplergl/kepler.gl#1884]
I am trying to add one custom button in the side-panel ( Toggle Panel ). I was able to add the button  using factory logic :
```
      export const CustomPanelToggleFactory = (...deps: any[]) => {
        const PanelToggle = PanelToggleFactory(...deps);
        return (props: any) => {
        
          return (
            <>
              <PanelToggle
                {...props}
                panels={[
                  ...props.panels,
                  {
                    id: "city",
                    label: "City",
                    iconComponent: CityIcon,
                    components: (props: any) => {
                      console.log(props);
                      return <div>City</div>;
                    },
                    // onClick: () => {
                    //   console.log(props);
                    // },
                  },
                ]}
              />
            </>
          );
        };
      };
```
![Screenshot 2022-07-27 222740](https://user-images.githubusercontent.com/61188411/181376967-0fcbba16-5158-4d07-80bb-f6ec8e45ae74.png)

the problem that am facing now is when I click on the new button an getting an error . so I am wondering   how can I link between the toggle and the content ?,  I tried to set the component prop but it did not work.
![Screenshot 2022-07-27 223053](https://user-images.githubusercontent.com/61188411/181377211-4ad63c44-1668-483d-b604-1979871cd3ba.png)

Thanks

**Comment by RedRosh** [comment]
I solved the issue. instead of using toggle factory, I needed to use the side panel factory.

**Comment by alharthyTH** [comment]
@RedRosh Could you please share your example?
