### ISSUE TITLE
Filters reset range as setting same value

### ISSUE THREAD

**Issue by yeshuanova** [keplergl/kepler.gl#190]
**Describe the bug**

In [Kepler.gl Demo](http://kepler.gl/#/demo), I update my dataset and add a filter for integer data type. I set integer as same range, for example [155, 155], and click other functions (ex "Layers"). When I click "Filters" function again, this integer filter will reset as [min, max] range.

**To Reproduce**
1. Read dataset with integer data type
2. Click **Filters** function and add new one for integer data.
3. Click **Layers** and back to "Filters" again.
4. Filter range reset to [min, max]

**Expected behavior**

Keep the value range, not reset range.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: 68.0.3440.84

**Additional context**
This problem also happens as float data type.

**Comment by macrigiuseppe** [comment]
@yeshuanova thank you for reporting this. I was able to reproduce the issue and I will put it in my bucket list.

**Comment by heshan0131** [comment]
This should be fixed
