### ISSUE TITLE
Parse Integer data type to boolean  

### ISSUE THREAD

**Issue by yeshuanova** [keplergl/kepler.gl#191]
**Describe the bug**

I have a dataset that content two column **c1** and **c2**.  c2 column is integer value but exist many value **1** in previous rows. For example 

| c1 | c2 |
| ---|---| 
| 1 | 1 |
| 2 | 1 |
| 3| 1 |
|...| ...|
| 199| 1|
|200| 200 | 

In [Kepler.gl Demo](http://kepler.gl/#/demo), I load a CSV dataset. Column **c1** is parsed to  **int** but **c2** parse to **bool**

**To Reproduce**

1. Generate test dataset and save to disk.
2. Load dataset to [kepler.gl](http://kepler.gl/#/demo)
2. See the data column and **c2** is parsed to **bool**

**Expected behavior**

Column **c2** also infer to integer

**Screenshots**

![kepler-error](https://user-images.githubusercontent.com/4150014/43817214-de36d53a-9b0a-11e8-8d29-9489345f54ba.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: 68.0.3440.84

**Comment by macrigiuseppe** [comment]
@schnerd would you be able to share a sample of the dataset? in order to debug the issue?

Thank you!

**Comment by yeshuanova** [comment]
@macrigiuseppe [kepler_error.csv.zip](https://github.com/uber/kepler.gl/files/2304890/kepler_error.csv.zip) is a simple dataset that will cause this situation.

**Comment by andreyz** [comment]
Any update on the issue or a known workaround? Hitting the same bug.

**Comment by heshan0131** [comment]
Flixed. After upgradeing [type-analyzer](https://github.com/uber-web/type-analyzer/commit/a182a501703c03b1ad7b995b280b43abeeebabc7) 
Closing this
