### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sobustakahashi** [keplergl/kepler.gl#1946]
**Describe the bug**

**To Reproduce**
1. Go to 'https://kepler.gl/demo'
2. Click on 'browse your files'
3. chose my file and uploaded
4. the progress was 100% but could not use.
5. I have been wating from about 30min but the situation is same.

**Expected behavior**

**Screenshots**
<img width="939" alt="the bug screenshot from sobus" src="https://user-images.githubusercontent.com/111815274/186036397-15faa81e-f6bf-450c-8e66-165ecf9d7e66.png">

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome 
 - Version 104.0.5112.101]

thank you.
Please check and fix it.

**Additional context**
<img width="939" alt="the bug screenshot from sobus" src="https://user-images.githubusercontent.com/111815274/186036329-8921b1de-98d6-46ef-8754-5b9b0f8ba5c3.png">

**Comment by runsalot87** [comment]
@heshan0131 Can you please assist? Same issue I am having with #1945

**Comment by ChenPan0506** [comment]
The size of the data set must be less than 5000 or this problem will occur. Is this because of the limit size of the demo project??

**Comment by heshan0131** [comment]
This should be fixed now

**Comment by Sobustakahashi** [comment]
thank you all.

**Comment by apoorvm91** [comment]
I am seeing this issue again.

**Comment by heshan0131** [comment]
Doesn't happen when I tested it. can you open your jacascript console and show me any error you see?

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1964

**Comment by Niko-La** [comment]
> Doesn't happen when I tested it. can you open your jacascript console and show me any error you see?

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/14004559/187279781-cb55d47b-1b96-4d79-bb7a-1d1eb8a82d25.png">

**Comment by apoorvm91** [comment]
> Doesn't happen when I tested it. can you open your jacascript console and show me any error you see?

![image](https://user-images.githubusercontent.com/9020327/187280931-83cc8dcb-9d20-4bc7-948c-68ec695bd176.png)
 
![image](https://user-images.githubusercontent.com/9020327/187281008-432d5abd-89ec-4574-b462-8e52b23e1672.png)
