### ISSUE TITLE
Allow CSV import with other delimiters (tab, semicolon).

### ISSUE THREAD

**Issue by BorisVSchmid** [keplergl/kepler.gl#196]
**Is your feature request related to a problem? Please describe.**
Sometimes it is convenient to have an alternative delimiter in a CSV file than commas (for example when you have a lot of commas in your text fields. Also, if I want to make a CSV that also opens nicely in Excel, using a semicolon works better than using commas. 

**Describe the solution you'd like**
Correct import of CSV data that use other delimiters than commas

**Describe alternatives you've considered**
Changing the delimiter with replace all in the csv file prior to import of course works as well.

**Comment by heshan0131** [comment]
Duplicated task
Follow #202
