### ISSUE TITLE
Stagnant response after dataset load

### ISSUE THREAD

**Issue by apoorvm91** [keplergl/kepler.gl#1963]
After loading the dataset, the loading status bar states "100%" but the image does not render. Same issue that was closed last week #1945 and #1946.

**Comment by apoorvm91** [comment]
@heshan0131 Would appreciate your help on this as you closed similar bug last week.

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/1964

**Comment by apoorvm91** [comment]
Still receiving the same issue: https://github.com/keplergl/kepler.gl/issues/1946#issuecomment-1230747578
I have the error screenshot added to provide more information.

**Comment by Niko-La** [comment]
> Still receiving the same issue: [#1946 (comment)](https://github.com/keplergl/kepler.gl/issues/1946#issuecomment-1230747578) I have the error screenshot added to provide more information.

Looks like it is fixed now.

**Comment by apoorvm91** [comment]
Can confirm that the issue is fixed. Thanks @heshan0131 .
