### ISSUE TITLE
[Bug] Error caused by dispatching layerVisualChannelConfigChange action

### ISSUE THREAD

**Issue by DenisovKirill** [keplergl/kepler.gl#2000]
I am using Kepler.gl in my react application. All is amazing but recently I faced the following problem.

When I try to update visual channels by dispatching layerVisualChannelConfigChange action I have the following error in my app:
"An error in deck.gl: field.valueAccessor is not a function in y7ghveg"

In the same time "Color Based On" field on the side pannel shows  visual channels changed "traffic".

You can see it on the screenshot below.

![layerVisualChannelConfigChange_error](https://user-images.githubusercontent.com/22613538/194079691-2553fcc0-da0d-479a-878b-53a2b2b5c9cb.png)

**Here is my function that cases this error:**

const changeVisualChannel = () => {
  dispatch(
    layerVisualChannelConfigChange(
      keplerGlState.map.visState.layers[0],
      { colorField: { name: "traffic", type: "real" } },
      "color"
    )
  );
};

**Here is visualChannels field in my config:**

    visualChannels: {
      colorField: { name: "subscribers", type: "real" },
      colorScale: "quantile",
      sizeField: { name: "traffic", type: "real" },
      sizeScale: "linear",
    },

**Comment by SelbyLinux** [comment]
> I am using Kepler.gl in my react application. All is amazing but recently I faced the following problem.
> 
> When I try to update visual channels by dispatching layerVisualChannelConfigChange action I have the following error in my app: "An error in deck.gl: field.valueAccessor is not a function in y7ghveg"
> 
> In the same time "Color Based On" field on the side pannel shows visual channels changed "traffic".
> 
> You can see it on the screenshot below.
> 
> ![layerVisualChannelConfigChange_error](https://user-images.githubusercontent.com/22613538/194079691-2553fcc0-da0d-479a-878b-53a2b2b5c9cb.png)
> 
> **Here is my function that cases this error:**
> 
> const changeVisualChannel = () => { dispatch( layerVisualChannelConfigChange( keplerGlState.map.visState.layers[0], { colorField: { name: "traffic", type: "real" } }, "color" ) ); };
> 
> **Here is visualChannels field in my config:**
> 
> ```
> visualChannels: {
>   colorField: { name: "subscribers", type: "real" },
>   colorScale: "quantile",
>   sizeField: { name: "traffic", type: "real" },
>   sizeScale: "linear",
> },
> ```

hi, @DenisovKirill , did you change the "Color Based On" field successfully? If you did, could you share an example code, how to realize, thanks a lot. I am confused with that for a long time.

**Comment by SuperThinking** [comment]
@DenisovKirill @SelbyLinux could you please share the solution?

**Comment by SuperThinking** [comment]
This was painful, but I solved this by basically extracting the exact field from kepler's state (inside dataset). Sharing what I did below:

```ts
const loadVisualChannels = async (layerIds: string[]) => {
    const channels = [
      "color",
      "strokeColor",
      "size",
      "coverage",
      "height",
      "radius",
    ];
    const getKeyChannel = (key) =>
      channels.find((channel) => key.startsWith(channel));

    for (const layerId of layerIds) {
      const dataset = props.keplerDatasets[layerDataMap[layerId]]; // props.keplerDatasets are your kepler datasets in state.kepler.keplerGl.map.visState.datasets
      const oldLayer = props.keplerLayers.filter((l) => l.id === layerId)[0]; // props.keplerLayers are your kepler layers in state.kepler.keplerGl.map.visState.layers

      const visualChannels = layerMap[layerId].visualChannels; // I have a layerMap that stores the visualChannels object against the layerId
      for (const cfgKey of Object.keys(visualChannels)) {
        const channel = getKeyChannel(cfgKey);
        if (!channel) {
          console.log(
            "[Urgent!] No channel found for this config key, kindly add the config to the channels list above",
            cfgKey,
          );
          continue;
        }
        if (!visualChannels[cfgKey]) continue;

        const newConfig = {
          [cfgKey]: visualChannels[cfgKey],
        };

        if (cfgKey.endsWith("Field")) // If the key is of type config, extract the field from dataset by filtering on name
          newConfig[cfgKey] = {
            ...newConfig[cfgKey],
            ...dataset.fields.filter(
              (f) => f.name == visualChannels[cfgKey].name,
            )[0],
          };

        await props.dispatch(
          layerVisualChannelConfigChange(oldLayer, newConfig, channel),
        );
      }
    }
};
```

**Comment by SuperThinking** [comment]
@heshan0131 do we have any better way to do this? I'm on kepler 2.5.5
