### ISSUE TITLE
[Bug] Load Map using URL "Incorrect UrL"

### ISSUE THREAD

**Issue by JanKleine** [keplergl/kepler.gl#2048]
**Describe the bug**
I don't seem to be able to load data from a URL. It only ever displays "Incorrect URL". To make sure it's not CORS or something similar I followed the [example in the docs](https://docs.kepler.gl/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map#load-map-using-url) exactly and used a raw github link. Quering the URL with curl confirms that CORS is enabled.

**To Reproduce**
1. Go to kepler.gl
2. Select "Load Map using URL"
3. Insert https://raw.githubusercontent.com/JanKleine/dummy/main/export.csv
4. Klick "Fetch"

**Expected behavior**
It should load the sample CSV.

**Desktop:**
 - OS: MacOS 13.0.1
 - Browser: Firefox
 - Version: 107.0.1

**Comment by jleedev** [comment]
Caused by https://github.com/keplergl/kepler.gl/pull/1837
