### ISSUE TITLE
Exported HTML map loads unavailable kepler.gl package

### ISSUE THREAD

**Issue by mlhollestelle** [keplergl/kepler.gl#2060]
**Describe the bug**
Map does not render when opening any HTML map from the kepler.gl web app in browser.

**To Reproduce**
1. Load for example example data Travel Times From Uber Movement
2. Export to HTML (view-only) with own mapbox token
3. Open downloaded HTML in browser

**Expected behavior**
One would expect the map to render, but instead it returns a blank page.

Console output:
```
keplergl.min.js:1          Failed to load resource: the server responded with a status of 404 ()
kepler.gl%20(1).html:1 Refused to execute script from 'https://unpkg.com/kepler.gl@3.0.0-alpha.0/umd/keplergl.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
kepler.gl (1).html:99 Uncaught ReferenceError: KeplerGl is not defined
    at file:///C:/Users/mhollestelle/Downloads/kepler.gl%20(1).html:99:20
kepler.gl (1).html:225 Uncaught ReferenceError: KeplerGl is not defined
    at file:///C:/Users/mhollestelle/Downloads/kepler.gl%20(1).html:225:13
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I suspect the cause is that loaded kepler.gl version is not available: https://unpkg.com/kepler.gl@3.0.0-alpha.0/umd/keplergl.min.js
Fix that did it for me was to modify the html to load https://unpkg.com/kepler.gl/umd/keplergl.min.js instead.

**Comment by gohsu** [comment]
Facing same issue, thanks for suggesting the html fix.

**Comment by mlhollestelle** [comment]
Duplicate of #2028. So I will close this one.
