### ISSUE TITLE
Add support for on-premise maps - Mapbox Atlas Server

### ISSUE THREAD

**Issue by ryanbaumann** [keplergl/kepler.gl#207]
**Is your feature request related to a problem? Please describe.**

Kepler.gl deployments on Enterprise networks in certain industries like Gov, Finance, and Healthcare have requirements to run in a controlled environment or VPC.  

**Describe the solution you'd like**

Use Kepler.gl visualizations with map styles and data hosted on my Enterprise network at a URL I specify with Mapbox Atlas Server.

**Additional context**

The reference implementation for supporting Atlas server:  https://www.mapbox.com/atlas-server/overview/products/#use-mapbox-gl-js-with-atlas

Add a `mapboxgl.config.API_URL = '<your-atlas-url>';` option in the Kepler.gl UI.  The default mapboxgl.config.API_URL value points to `https://api.mapbox.com`.  This should remain the default in Kepler.gl.

cc/ @heshan0131

**Comment by heshan0131** [comment]
closing it after mergin #554
