### ISSUE TITLE
rendering issue with map config files having zoom levels of 1-2

### ISSUE THREAD

**Issue by guidorice** [keplergl/kepler.gl#214]
**Describe the bug**

This is a reproducible rendering issue, but takes a few steps to set it up.  This can be reproduced with various datasets, but I created a saved config to make it easier to repro with a few points.

**To Reproduce**

The gist at https://gist.github.com/guidorice/1ddbe42ff352126a5c2f4b632c263f7b
has some point data which I created with geojson.io, where I  dropped pins on some European countries (all points are on land masses).

I then loaded it into kepler.gl and zoomed the map out to near 1.0, and exported the config into the gist.

1. Go to http://kepler.gl/#/demo
2. Drop the keplergl.json file from my gist into the Add Data to Map dialog
3. The following render problem occurs. The vector data is skewed and not aligned with the base map.
4. _Note this issue only occurs when browser size is large._ If you have a small display, then you can emulate a larger browser window by doing:

Chrome Devtools | Toogle device toolbar | edit | create new device with 1920 x 1080 and then set the scaled to 50% or whatever so you can see the whole window.

5. After the points are loaded, then if you can interact with the map by zoom or pan, and the points snap into the expected place.

**Expected behavior**

Vector data should be drawn correctly over basemap.

**Screenshots**

Wrong:
![screen shot 2018-08-23 at 2 29 06 pm](https://user-images.githubusercontent.com/766758/44550526-cb17ff00-a6e1-11e8-900d-942f7590b0cf.png)

Right:
![screen shot 2018-08-23 at 2 29 13 pm](https://user-images.githubusercontent.com/766758/44550621-04e90580-a6e2-11e8-9981-3eb1286cffe6.png)

**Desktop (please complete the following information):**

 - OS: OS X
 - Browser: chrome
 - Version: 68

**Additional context**

Sorry, I do not know how to fix the rendering problem, or even what the root cause is, however, a workaround I came up with is to clamp the map zoom to a minimum of 2.0 in the function `loadRemoteMap()`. Let me know if want me to submit a PR for this. (fixing root cause would be better though).

**Comment by heshan0131** [comment]
@Pessimistress could this be a reac-map-gl issue? The projection is off at a low zoom level=1

**Comment by heshan0131** [comment]
Should be fixed now
