### ISSUE TITLE
Embedded HTML file unresponsive

### ISSUE THREAD

**Issue by shashankpalur** [keplergl/kepler.gl#2146]
**Describe the bug**
The html file that is created after exporting map throws up a blank page

**To Reproduce**
1. Go to 'Share'
2. Click on 'Export Map'
3. Scroll down to 'Click on HTML'

**Expected behavior**
Should show the map with its element on a website

**Screenshots**
![image](https://user-images.githubusercontent.com/106950529/222637157-811cc4be-bf52-454a-9883-4ba981a16eb5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [All Browsers]
 -

**Comment by tedder** [comment]
I was going to report this, the shared HTML tries to load the keplergl script from here: https://unpkg.com/kepler.gl@3.0.0-alpha.0/umd/keplergl.min.js

That's a 404. I can replace it with the previous version and it works: https://unpkg.com/kepler.gl@2.5.5/umd/keplergl.min.js

**Comment by tedder** [comment]
same issue #2143 #2141 #2125 #2074 #2028 #2033

**Comment by shashankpalur** [comment]
Thanks, This fixed the issue.
