### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ThatScorpio** [keplergl/kepler.gl#2158]
After creating two split maps, I can only turn off layers on the right side map. I can't choose which layers to visualize on the right side, I can't turn off any of the layers.

**Desktop (please complete the following information):**
 - Windows 11
 - Microsoft Edge

![Ekrano kopija 2023-03-11 142036](https://user-images.githubusercontent.com/124143401/224484484-2eec67c5-c764-48e3-9b85-572db2b715ea.png)

I tried to open my project on Opera browser and I still can't turn off the right side map's layers.

**Comment by heshan0131** [comment]
@igorDykhta Can you investigate this?
