### ISSUE TITLE
Add custom onClick on my Points

### ISSUE THREAD

**Issue by AntoshJkeee** [keplergl/kepler.gl#2165]
Hi!,

Many thanks in advance to all.

I overwrote the `MapPopoverFactory` to my custom component and styled it, everything works fine

But the props I get (such as `layerHoverProp`, `frozen`, `zoom` and so on) are not enough to solve my problem.

When you hover the mouse over a pin, everything works correctly and my custom popover appears, but can I somehow overwrite exactly the `onClick` on this pin? I need to click on the pin not to measure the popover, but to expand it with more detailed information.

Can someone help me?)

**Comment by AntoshJkeee** [comment]
figured out

**Comment by lalzart** [comment]
@AntoshJkeee how did you manage to achieve this?
