### ISSUE TITLE
Custom Mapbox API token input

### ISSUE THREAD

**Issue by chrisirhc** [keplergl/kepler.gl#22]

**Comment by davidfaynzilberg** [comment]
MapboxAccessToken=MapboxAPIKey npm start is not working
I am trying to install it on Windows 10

Any help would be greatly appreciated

**Comment by chrisirhc** [comment]
@davidfaynzilberg please don't use this as a avenue for getting support.

When using Windows, you can set environmental variables using `SET`.
Try `SET MapboxAccessToken=MapboxAPIKey && npm start`.

**Comment by argenisleon** [comment]
I had several problems running kepler on windows 10. I just make it work using cywin and cloning the repo(not using npm install --save kepler.gl) . With cywing you just need to follow the instructions as in a linux console.

**Comment by macrigiuseppe** [comment]
Closing
