### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dbnezami** [keplergl/kepler.gl#2204]
**Describe the bug**
Image download button does nothing

**To Reproduce**
Create a custom map with a custom dataset, attempt to download image of map

**Expected behavior**
A downloadable image of the map

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RaineEkman** [comment]
Duplicate of https://github.com/keplergl/kepler.gl/issues/1960?

**Comment by chrisgervang** [comment]
I believe this is fixed now with #2368. Try `3.0.0-alpha.1`
