### ISSUE TITLE
[bug] Unable to load map styles - uberdata/sprites not found

### ISSUE THREAD

**Issue by devcer** [keplergl/kepler.gl#222]
**Describe the bug**
Unable to run kepler.gl samples from the past 5 days

**To Reproduce**
1. Follow the steps listed in kepler.gl
2. Do npm start
3. See the 404 not found error in console

**Expected behavior**
The kepler.gl demo app should run without any errors

**Screenshots**
![keplergl-error](https://user-images.githubusercontent.com/3799600/45016977-f08efc00-b043-11e8-8689-309f5c940813.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 68

**Comment by matheusmonte** [comment]
@heshan0131 Can I help?
