### ISSUE TITLE
White map

### ISSUE THREAD

**Issue by davidheads** [keplergl/kepler.gl#2223]
**Describe the bug**
White map using React

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1440" alt="React_Kepler" src="https://github.com/keplergl/kepler.gl/assets/58658053/c1b68d50-e872-48a3-87ea-03706930a048">

**Desktop (please complete the following information):**
 - Browser chrome
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "assert": "^2.0.0",
    "kepler.gl": "^2.5.5",
    "querystring-es3": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "redux": "^4.2.1",
    "redux-saga": "^1.2.3",
    "url": "^0.11.0",
    "web-vitals": "^2.1.4"
<img width="1014" alt="console_error" src="https://github.com/keplergl/kepler.gl/assets/58658053/93fd9496-8880-4249-8c9b-ad46fa0d7d28">

**Additional context**
I have made sure that I am using a valid Mapbox token.

**Comment by oltipreka** [comment]
I am facing the same issue!

**Comment by dangelsaurus** [comment]
dumb question maybe... but what is the issue?
