### ISSUE TITLE
layers on static html (export map as static html)

### ISSUE THREAD

**Issue by rohithreddy13** [keplergl/kepler.gl#223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rohithreddy13** [comment]
i wanted to use kepler to create a static html page with layers already added so that they can be directly shown on opening without any uploading or adding layers . plese let me know if there is any way to do this

**Comment by rohithreddy13** [comment]
i was able to create a html with map but we have to load layers mannually

**Comment by heshan0131** [comment]
@rohithreddy13 depends on how you created html with map, you should be able to use js to load both data and config to kepler.gl with the `addDataToMap` action. 
YOu can take a look at the (vis.academy tutorial)[http://vis.academy/#/kepler.gl/3-load-config]
