### ISSUE TITLE
Integer fields are identified as timestamp

### ISSUE THREAD

**Issue by palamago** [keplergl/kepler.gl#226]
**Describe the bug**
I have four `integer` columns in my dataset. One of them is interpreted as `timestamp` and I can't use it as `colorField` properly.
I tried to force it before `addDataToMap` dispatch with no luck.
```
let data = Processors.processCsvData(response.responseText);
    data.fields = data.fields.map(f => {
      f.type = f.type == "timestamp" ? "integer" : f.type;
      f.format = "";
      return f;
    });
```

**To Reproduce**
1. Download [this csv](https://pastebin.com/kgt1QMcZ)
2. Add it on kepler
3. You will see that the column `qty2` is rendered as `timestamp` instead of `integer`
![captura de pantalla 2018-09-05 a la s 15 12 03](https://user-images.githubusercontent.com/1203432/45112478-18eb2900-b11e-11e8-9831-46eb3f199b6b.png)

**Expected behavior**
The numbers are integers.
A way to force the types programmatically, maybe?

**Screenshots**
Fields
<img width="268" alt="captura de pantalla 2018-09-05 a la s 14 54 34" src="https://user-images.githubusercontent.com/1203432/45111610-c3ae1800-b11b-11e8-8295-94e6abb697a5.png">

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser: Chrome
 - Version 68

**Additional context**
Working on a React + Kepler 0.1.2 custom app.
Kepler.gl is a beautiful piece of code. Thanks!

**Comment by heshan0131** [comment]
Force editing the field type after `processCsvData` should work after this PR is merged
#240

**Comment by jakubmlacki** [comment]
This is an old topic but I have a similar question. My ID colum sometimes contains strings and not integer. The column is detected as String. Then `processCsvData` puts NaN into the resulting object. Is there a way to force the type before calling `processCsvData`?

**Comment by palamago** [comment]
@jakubmlacki you should do a transformation in the dataset before call processCsvData or edit the object -field type- after processCsvData. Try it and let me know.
