### ISSUE TITLE
403 Forbidden for Base Map

### ISSUE THREAD

**Issue by magamonsta** [keplergl/kepler.gl#229]
**Describe the bug**
Toggling Map Styles throws 403 Forbidden Error for Map Styles Light & Muted Light when Map Layers Label is selected 

**To Reproduce**
1. Go to http://kepler.gl/#/demo
2. Click on Base Map
3. Select Add Map Style
4. Add Mapbox Style using the on screen instructions
5. Once the new Style is uploaded, change the Map Style to be Light or Muted Light
6. See that Base Map doesn't properly load
7. See 403 Forbidden errors in console output.
8. Unselect 'Label' Map Layers and the Base Map will then load

**Expected behavior**
The Base Map should load without errors

**Screenshots**
<img width="1275" alt="screen shot 2018-09-07 at 1 47 35 pm" src="https://user-images.githubusercontent.com/38330505/45234805-d0aa4300-b2a4-11e8-9fe8-af41f901e504.png">

**Desktop (please complete the following information):**
 - OS: iOS & Windows
 - Browser chrome

**Additional context**
seems to be similar to my previous issue #121 which was 403 Forbidden errors for Light and Muted Light when running a local deployment of Kepler

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/292/files

**Comment by alexlevy0** [comment]
I have the same problem :/
