### ISSUE TITLE
[Bug] Content Security Policy blocks unpkg and thus arrow-worker.js loading data

### ISSUE THREAD

**Issue by exrhizo** [keplergl/kepler.gl#2290]
Deck.gl uses webworker loaded from unpkg, this means kepler.gl can't be run with the level of security we need.

**To Reproduce**
I basically forked this [codesandbox](https://codesandbox.io/s/create-react-app-typescript-keplergl-bv0vb)

A create-react-app using `import KeplerGl from "kepler.gl";`

with `kepler.gl@2.5.5`

I do something like this, which works when I disable CSP.
```ts
message.payload.datasets.data = processRowObject(
  message.payload.datasets.data
);
dispatch(addDataToMap(message.payload));
```

I can give more context if that is helpful, but as far as I can tell this is deck.gl behavior.

```
Refused to load the script 'https://unpkg.com/@loaders.gl/arrow@3.4.4/dist/arrow-worker.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Expected behavior**
The library to not require running scripts from 3rd party urls.

**Additional context**

I thought to try this, but it didn't work for me
 `https://unpkg.com/@loaders.gl/arrow@3.4.4/dist/arrow-worker.js` still showed up the network tab when I was testing locally.

```ts
const store = configureStore({
  reducer: {
    keplerGl: keplerGlReducer.initialState({
      visState: {
        // loaders: [],
        loadOptions: {
          arrow: {
            workerUrl: `${process.env.PUBLIC_URL}/arrow.worker.js}`
          }
        }
      }
    }),
  },
  middleware: [taskMiddleware],
});
```

**Comment by ibgreen** [comment]
The `workerUrl` option should work the way you wrote it. 

Some random guesses, the visState `loadOptions` might not be passed through to the loaders.gl load calls? or the version of loaders.gl in kepler.gl is old?

@igorDykhta You are working more actively in the code base, any thoughts?

**Comment by lmeyerov** [comment]
@ibgreen @igorDykhta Any ideas? This breaks most F500 & gov scenarios that we see

**Comment by lmeyerov** [comment]
loaders.gl/core is `"3.0.9^"`, which in theory should allow the current `"3.4.x"` , but the `yarn.lock` looks like `3.0.9` instead of more recent: https://github.com/keplergl/kepler.gl/blob/5bae745b6a2fe60a9aba96f2539c979626cc80c5/yarn.lock#L1565 Not sure if a rebuild or some other dependency forcing that?

**Comment by lmeyerov** [comment]
We were able to update just the `loader.gl/*` dependencies and that was enough for `{arrow: {CDA: null}}` to do the trick

It still seems like, by default, an unusual thing to have to do
