### ISSUE TITLE
Cannot find package kepler.gl@3.0.0-alpha.0

### ISSUE THREAD

**Issue by graeme44** [keplergl/kepler.gl#2296]
**Describe the bug**
After loading an html map which has been exported using the demo page (running 3.0.0-alpha), the map fails to load due to https://unpkg.com/kepler.gl@3.0.0-alpha.0/umd/keplergl.min.js not found.

**To Reproduce**
1. Go to 'https://unpkg.com/kepler.gl@3.0.0-alpha.0/umd/keplergl.min.js'
2. See error: not found

or

1. Download and open example: [examples/umd-client/index.html](https://github.com/keplergl/kepler.gl/blob/5bae745b6a2fe60a9aba96f2539c979626cc80c5/examples/umd-client/index.html)

**Expected behavior**
Example should run.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by ibgreen** [comment]
@igorDykhta I believe that in 3.0 we no longer publish the kepler.gl module, instead we publish scoped modules like `@kepler.gl/actions` etc. Perhaps the export functionality hasn't been updated?

**Comment by graeme44** [comment]
Closing, I see active PR to resolve: https://github.com/keplergl/kepler.gl/pull/2292
