### ISSUE TITLE
Add Square root scale

### ISSUE THREAD

**Issue by holstius** [keplergl/kepler.gl#230]
Currently, cell heights can be made proportional to *n* (the cell count). This is great!

On the other hand, **the square root of *n* makes for a better approximation of something like "confidence"**. (For the finicky, *n* + 1.)

Could the square root of *n* be an alternative metric to swap in for height, opacity, etc.?

**Comment by heshan0131** [comment]
merge issue into
https://github.com/keplergl/kepler.gl/issues/652
