### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by oliveirafatima** [keplergl/kepler.gl#2309]
Unable to subscribe to Kepler.gl mailing list to submit this question...

Is there an option to license Kepler?

**Comment by ibgreen** [comment]
What do you want to achieve? 
- Use it to build your own products? It is open source, assuming MIT license works for you, just go ahead.
- License the kepler.gl name? That is not an option, it is owned by OpenJS Foundation/Linux Foundation, you just give credit.
- Do you want commercial support for extending kepler? There are companies like Action Engine that are long-time experts and provide very cost effective development services.
- Do you want to license a hosted version of kepler.gl? Foursquare Studio is very comprehensive and has a free tier you can try out, there is CARTO Builder, and probably many other products that leverage kepler in some way.
