### ISSUE TITLE
[BUG] Using onPrem Map Styles does not use the API key

### ISSUE THREAD

**Issue by prune998** [keplergl/kepler.gl#243]
**Describe the bug**
When using the `Custom Mapbox Style` with an OnPrem style, using OnPrem generated tiles, the API key is not added to the URL, leading to a `invalid token` error.

**To Reproduce**
1. Go to `Base Map` menu
2. Click on `Add Map Style`
3. Provide the URL of your style and the Token key
![image](https://user-images.githubusercontent.com/1110398/46415811-14516a80-c6f4-11e8-9db0-f00e72f5cbc7.png)
5. error from the Inspector : 
![image](https://user-images.githubusercontent.com/1110398/46415983-83c75a00-c6f4-11e8-84e6-1d4893b10db5.png)

**Expected behavior**
The requested URL should include the token like : 
```
https://tiles.xxx.ca/tiles/6/32/21.pbf?access_token=pk.xxx
```

**Desktop (please complete the following information):**
 - OS: view on OsX Sierra 
 - Browser: chrome, safari, firefox
 - Version: Kepler 1.0

**Comment by macrigiuseppe** [comment]
this should be fixed. Please try it out and let us know
