### ISSUE TITLE
Update Copyright and License References as per OpenJS Foundation Guidance

### ISSUE THREAD

**Issue by chrisgervang** [keplergl/kepler.gl#2467]
### Description

As per the recent guidance from the OpenJS Foundation's legal council regarding the Kepler.gl project, which has been a Linux Foundation for a number of years and is now governed within the OpenJS Foundation, there are a few updates required in our project's copyright and license documentation.

### Proposed Changes

1. **Update Copyright Notice:**
   - **Current:** The project files currently carry the Uber copyright notice.
   - **Proposed Change:** Replace with "Copyright contributors to the kepler.gl project". This change is suggested as the project is now under the Linux Foundation, and continuing with the Uber copyright is no longer necessary.

2. **Simplify License References in Headers:**
   - **Current:** Complete MIT license copy is included in our file headers.
   - **Proposed Change:** Replace with a shorthand reference to the MIT license, in line with the guidance provided by the OpenJS Foundation. The reference format is detailed here: [ASWF License Specification](https://tac.aswf.io/process/contributing#license-specification).

### Impact

These changes will bring our project documentation in line with the legal requirements and recommendations provided by the OpenJS Foundation. It will also simplify our file headers while maintaining proper licensing.

### Request

I request the maintainers and contributors to review these proposed changes and provide their feedback. If there are no objections, we can proceed to implement these changes in our project files.

---

### Next Steps

- [x] Discussion and feedback from the community
- [x] Finalize the changes
- [x] Update the project files accordingly

**Comment by ibgreen** [comment]
As we are part of OpenJS and Linux foundation, we should just go ahead and conform to their best practices. Part of the value of being part of these foundations is that they have legal experts who have spent a lot of time thinking about this and getting it right.

We can leave this open for a few days to ensure the community had a changes , however I think in practical terms

- there is a license script that automatically slaps licenses on new files, so we want to open a PR that either disables that or updates to add the new license. 
- We want a second PR that updates all existing licenses.

**Comment by chrisgervang** [comment]
Running `yarn`, `yarn bootstrap`, etc.. will now add the correct license header to new files with `.js`, `.ts`, `.tsx`, `.mjs`, and `.py` extensions. As before, it won't remove incorrect file headers, so contributors should be mindful to not re-introduce an Uber header.

To make a bulk change in the future someone can run `yarn run babel-node ./scripts/license-header/bin --license ./NEW-HEADER --legacy ./OLD-HEADER`
