### ISSUE TITLE
[Bug]Default Basemap Not Displaying

### ISSUE THREAD

**Issue by andrew20012656** [keplergl/kepler.gl#2484]
After clone the repo and install it locally, I managed to upload some custom datasets and correctly display the layers. However, now I'm having trouble displaying the default basemaps (E.g. Dark, Light, etc.). Can anyone please suggest where I should look into/ where might be causing the problem? Thanks.

**Expected behavior**
Displaying the basemap as background to the layers.

**Screenshots**
<img width="1050" alt="Screenshot 2023-12-19 at 2 59 22 AM" src="https://github.com/keplergl/kepler.gl/assets/81542178/9df1156e-756d-4c7d-82c8-02f0eda6833d">

**Comment by andrew20012656** [comment]
Wrong Tag. Reposted an issue

**Comment by ibgreen** [comment]
If you are building kepler.gl on your own, you likely need to create and supply your own mapbox token, or use non-mapbox basemaps such as the CARTO basemaps. As it is external to the project, you'll need to search for info on how to do that, but there is some info in the deck.gl docs and also in the react-map-gl docs that might get you started.

**Comment by andrew20012656** [comment]
> If you are building kepler.gl on your own, you likely need to create and supply your own mapbox token, or use non-mapbox basemaps such as the CARTO basemaps. As it is external to the project, you'll need to search for info on how to do that, but there is some info in the deck.gl docs and also in the react-map-gl docs that might get you started.

When you say "supply your own mapbox token", do you mean just the token is needed? I'm wondering if the default basemaps are included in the repository. Thanks!
