### ISSUE TITLE
Why is the mapbox missing after the 3.0.0 update?

### ISSUE THREAD

**Issue by luka077a** [keplergl/kepler.gl#2498]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ibgreen** [comment]
It is unclear what problem you are trying to report, but kepler.gl 3.0 has switched basemap to maplibre and no longer uses mapbox. Some additional information can be found in the [kepler.gl 3.0 release blogpost](https://openjsf.org/blog/whats-new-in-the-keplergl-30-application)
