### ISSUE TITLE
Uploading a Empty JSON File Shows Loading Forever

### ISSUE THREAD

**Issue by starry97** [keplergl/kepler.gl#253]
Loading an empty JSON file or any other files that are not in the expected format displays an uploading spinning icon forever.

**To Reproduce**
1. Go to 'Get Started' > 'Load your Data' tab
2. Upload an empty JSON file

**Expected behavior**
It should show an error message. 

**Desktop**
 - OS: High Sierra
 - Browser: chrome
 - Version: 69.0.3497.81

**Comment by chrisdiana** [comment]
@starry97 this seems to be related to another underlying issue with displaying error feedback when processing. I created another issue here #294 that encompasses this issue and #281 too.

**Comment by macrigiuseppe** [comment]
#681
