### ISSUE TITLE
[Bug] SSL Cert Expired?

### ISSUE THREAD

**Issue by aporter-de** [keplergl/kepler.gl#2551]
**Describe the bug**
My browser things Kepler.gl is trying to steal my info:

_Your connection is not private
Attackers might be trying to steal your information from kepler.gl (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID_

**To Reproduce**
1. Go to https://kepler.gl

**Expected behavior**
The page loads

**Screenshots**

**Desktop (please complete the following information):**
All computers

**Additional context**
from https://www.digicert.com/
The Certificate is not issued by DigiCert, GeoTrust, Thawte, or RapidSSL
Make sure the website you want to check is secured by a certificate from one of our product lines.

Common Name = *.myservices.hosting
Subject Alternative Names = *.myservices.hosting, myservices.hosting
Issuer = Sectigo RSA Domain Validation Secure Server CA
Serial Number = C5C5E83F16185CA758B56F695183274C
SHA1 Thumbprint = 90EE61C2D5E712F0BB043168E414E58B992964CA
Key Length = 4096
Signature algorithm = SHA256-RSA
Secure Renegotiation:

**TLS Certificate status cannot be validated**
OCSP Staple: | Not Enabled
-- | --
OCSP Origin: |  
CRL Status: | Not Enabled

<br class="Apple-interchange-newline">

Certificate does not match name kepler.gl

**TLS Certificate is not trusted**
The certificate is not signed by a trusted authority (checking against Mozilla's root store). If you bought the certificate from a trusted authority, you probably just need to install one or more Intermediate certificates. Contact your certificate provider for assistance doing this for your server platform.

**Comment by ibgreen** [comment]
Apologies, this is related to ongoing work of transferring DNS to the Linux Foundation, hopefully the downtime should not be too long.

**Comment by ibgreen** [comment]
Site is working again. Reverted for now, until we have a new approach.
