### ISSUE TITLE
Support for other Geocoders

### ISSUE THREAD

**Issue by jamesdbaker** [keplergl/kepler.gl#2578]
Is it possible - either at present, or as a future feature - to switch out the MapBox Geocoder for other services (e.g. a locally hosted [Nominatim](https://nominatim.org/) instance)?

The documentation here seems to suggest that it's been considered, but the documentation isn't complete so I can't tell if it's implemented yet or not: https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/custom-map-styles.md

**Comment by ibgreen** [comment]
@jamesdbaker Thanks for your interest.

First, this repo already has over 500 open issues, so please move further comments to GitHub discussions for anything that is not a clear bug.

As for your question, there is no pluggable system unfortunately, you would need to modify https://github.com/keplergl/kepler.gl/blob/89180277d7b45b6056f573afe59252ffcfbf818e/src/components/src/geocoder/geocoder.tsx#L7
