### ISSUE TITLE
Prevent loading layers automatically when using addDataToMap

### ISSUE THREAD

**Issue by SuperThinking** [keplergl/kepler.gl#2595]
Issue: I want to load layers manually using `addLayer` and I'm using `addDataToMap` to load data with preset dataId (which I use inside the layer config when doing addLayer). Issue is when doing addDataToMap it automatically adds layers from the given data. How to prevent this?

**Comment by agussudiana** [comment]
Hi @SuperThinking , please try this
`addDataToMap({datasets,options:{autoCreateLayers:false}})`
