### ISSUE TITLE
update data

### ISSUE THREAD

**Issue by Damirinho9** [keplergl/kepler.gl#2619]
Hello. I need a function to automatically update data from a csv that is in google drive. The csv itself is automatically updated from google sheets. Or tell me how to open a csv file from a link from google drive.

**Comment by ibgreen** [comment]
The issues section is for bugs. For repo hygiene reasons, questions should go in discussions. 

In the mean time, a first hint is: can you generate a publicly available URL from your google drive? Then you should be looking for a way to import data from a URL.
