### ISSUE TITLE
Extended S2 functions

### ISSUE THREAD

**Issue by missinglink** [keplergl/kepler.gl#2621]
Hi all,

I'm pleased to announce a new pure JS port of the s2 spherical geometry library for {browser, node}

The library includes many features not available in the current dependency, most notably `RegionCoverer` which might be a nice addition to Kepler.

https://github.com/missinglink/s2js

**Comment by ibgreen** [comment]
@missinglink Thanks for reaching out. This does indeed look promising.

In fact we have a bit of a mess on our hands, we use different S2 implementations in kepler.gl, deck.gl, math.gl and loaders.gl. I have been wanting to standardize. This could be a solution. Will give it more thought and let you know if there is anything we need.

Some developer guide material would be nice, right now I could only find autogenerated reference docs which presume a fair bit of knowledge about S2 etc.

**Comment by ibgreen** [comment]
Since this is not an actual issue, I will close this, let's move further conversation to the discussions tab.
