### ISSUE TITLE
[Bug] Can't find the 3d map button

### ISSUE THREAD

**Issue by Glo9062** [keplergl/kepler.gl#2682]
**Describe the bug**
Can't find the '3d map' and 'Legend' button on the top right corner.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/0c9589ce-88d0-4cc9-8fee-b68b1a099909)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by VincentAntoine** [comment]
Same here. This is new from today, it was working yesterday. And it's not just the 3D button, all map controls are missing. Especially the legend !

![image](https://github.com/user-attachments/assets/4d2f0ffb-d75f-4623-a64a-bc64c58faff7)

**Comment by jspalink** [comment]
I'm observing the same problems here

**Comment by RickyLxzz** [comment]
The same issue

**Comment by b6100111524** [comment]
I'm observing the same problems here.

**Comment by VincentAntoine** [comment]
The last change on map-control.tsx was on October 10th, which corresponds to the start of this bug:

https://github.com/keplergl/kepler.gl/pull/2679/files#diff-d8ba840abff3b8ca8c325756492e40c00ebedd31b8bd1cdbf818a523cb7b2c7f

@heshan0131 would you be able to check if this is the cause of the issue ?

**Comment by mikep007** [comment]
@heshan0131 any luck?  My clients blowing my phones up.

**Comment by xfeng33smart** [comment]
+1
