### ISSUE TITLE
[Bug] No basemap when map is opened with a link

### ISSUE THREAD

**Issue by tekelala** [keplergl/kepler.gl#2698]
**Describe the bug**

**To Reproduce**
1. Go to 'https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/scl/fi/2dayi8260kmii1m8ikq92/keplergl_f55dlzp.json?rlkey=84wgu66jovguialdjn9s0mdtn&dl=0'
2. See the map without a basemap

**Expected behavior**
I expected to see a basemap

**Screenshots**
<img width="1489" alt="Screenshot 2024-10-15 at 10 42 44 AM" src="https://github.com/user-attachments/assets/ef0a0842-db63-4443-b588-c6637beb4e84">

**Desktop (please complete the following information):**
 - OS: MacOS 15.0.1 (24A348)
 - Browser Arc
 - Version 1.63.1

**Additional context**

**Comment by indranildeveloper** [comment]
[Question]: Is this map is a Mapbox map or Maplibre map?
