### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by thanthamky** [keplergl/kepler.gl#2701]
**Describe the bug**
In Kepler's demo, the 3D icon on Right panel disappears. Please fix the button back

**To Reproduce**
1. Normal behavior
2. On Right panel icons
3. No 3D view icon to press

**Expected behavior**
There should be a 3D View Icon on the right panel of he map

**Screenshots**

![Screenshot 2567-10-16 at 10 49 22](https://github.com/user-attachments/assets/6c58330e-cad1-459f-a4c4-4481eefa2990)

**Comment by skylee03** [comment]
Duplicated with the following issue:
- #2682

**Comment by heshan0131** [comment]
Duplicate issue, fix has been deployed
