### ISSUE TITLE
Loading json file created using AirNow api won't work and kepler keeps spinning

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#281]
**Describe the bug**
When i try to upload a json file created using AirNow api, kepler keeps on spinning without any feedback.

File
[air.json.zip](https://github.com/uber/kepler.gl/files/2587470/air.json.zip)

**Comment by chrisdiana** [comment]
@macrigiuseppe this seems to be related to another underlying issue with displaying error feedback when processing. I created another issue here #294 that encompasses this issue and #253 too.

**Comment by macrigiuseppe** [comment]
Please follow development here: https://github.com/uber/kepler.gl/issues/307
