### ISSUE TITLE
Documentation on how to embed a map into HTML?

### ISSUE THREAD

**Issue by Monsignor** [keplergl/kepler.gl#301]
I have a very basic request here. For someone who has successfully setup the local demo and imported a JSON into it, the next step is to make this map available on a webpage.

So I configured it, exported the entire map data, and now I have this geoJSON and I want to use it to load a map on my website.

Looking at your docs, it seems like there is no clear process for how to do this and/or that it requires being proficient in React/Redux, which I am not.

Compare this with Google Maps instructions for the same thing, where you literally just add an iframe with the relevant configuration options, and you're done. Since Kepler is all on the client, I don't see why we wouldn't have an embed option that works simply by including a script and using a path to our JSON/CSV data file as a parameter.

Any suggestions welcome, maybe I am missing something (I hope I am). Either way, more to-the-point documentation on this matter would be useful I think.

**Comment by gcoimbra** [comment]
@Monsignor I see anyone responded to this request. Have you been able to figure out a way to do it?

**Comment by heshan0131** [comment]
we are working on exporting map into a single index.html

**Comment by gcoimbra** [comment]
> we are working on exporting map into a single index.html

That's really cool @heshan0131. May I ask if you plan is also to provide this in your demo?  Or this will be just locally?

**Comment by xr0master** [comment]
Why you can't just put it in iframe? It works pretty well for me

**Comment by gcoimbra** [comment]
Haven't tried it yet. I'm going to give it a go...

Em December 24, 2018 9:40:17 AM UTC, xr0master <notifications@github.com> escreveu:
>Why you can't just put it in iframe? It works pretty well for me
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/uber/kepler.gl/issues/301#issuecomment-449710128

Abraço, 
Gabriel Coimbra.
Aluno na UFV

-- 
Favor manter em privado.

**Comment by gcoimbra** [comment]
Do you mind to show how you have done? I must say that this is my first time for web development ;)

Em December 24, 2018 9:40:17 AM UTC, xr0master <notifications@github.com> escreveu:
>Why you can't just put it in iframe? It works pretty well for me
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/uber/kepler.gl/issues/301#issuecomment-449710128

Abraço, 
Gabriel Coimbra.
Aluno na UFV

-- 
Favor manter em privado.

**Comment by bumbeishvili** [comment]
I put it inside an iframe - steps are listed here 

https://beta.observablehq.com/@bumbeishvili/kepler-gl-iframe
