### ISSUE TITLE
Notification UI/UX

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#307]
**Is your feature request related to a problem? Please describe.**
The current state of Kepler doesn't provide a standard way of displaying errors and it's difficult for users to understand when something is not working the way it should be and for developers to extend UI in a cohesive and consistent way as part of the workflow.

**Describe the solution you'd like**
If we consider Kepler.gl workflow we have the main steps:
- Pick source and load data.
- Create your visualization.
- Since Kepler.gl can also be consumed as library, the notification feature should be flexible enough to accommodate extensions/plugins.

Given the above use cases, Kepler.gl should provide flexible enough set of APIs to support multiple areas/topics out of the box, e.g. file/url/sharing and in more details
-- Ability to register new topics (maybe this is not needed, we can automatically detect the topic field from the notification entry)
-- Ability to register new notifications
-- Ability to remove notifications

**Implementation**
This section will describe the implementation of the solution in details and will cover new APIs and their functionalities.

We can start form the the storage of the notifications
The new feature should provide the ability to:
- Register notifications through API by calling a method, e.g. __registerNotification__, and providing the notification type, e.g. error, and which topic of the app the message is targeting hence we need to develop a little bit more on the second parameter and understand how this will be used to address the UI/UX. The register notification api will return the id of the newly generated entry
- Remove notifications: the user can call at any time the removeNotification and pass the notification id to remove the notification from the screen.

***Storing solution***
We are going to take advantage of the uiState reducer and create a property object called __notifications__. Within the new notifications property we are going create an entry for each part of the application we want to target, e.g. file. The final result should look something like the following snippet:

```javascript
const reducer = {
      uiState: {
        notifications: {
          file: [
            {
              uuid: 123456,
              type: 'warning',
              message: 'Your file contains invalid rows',
              topic: 'file'
            }
          ],
          url: [
            {
              uuid: 678901,
              type: 'success',
              message: 'Your url is has been loaded correctly',
              topic: 'url'
            }
          ],
          // this is generated by a consumer app
          sharing: [
            {
              uuid: 567890,
              type: 'error',
              message: 'The application is not able to upload the current map onto your dropbox account'
              topic: 'sharing'
            }
          ]
        }
      }
    };
```
***Register a new notification***
Kepler.gl will provide a new API (action/helper) to register a new notification, the input of the new API will be an object representing the notification.  In order to make the creation of new notifications we are going to provide helper methods
The signature of said methods are the followings:

```javascript
export type MessageType = 'info' | 'error' | 'warning' | 'success';
export type Notification = {
  uuiid: string,
  message: number,
  type: MessageType,
  topic: string
};
function createNotification({
      message: string,
      type: string,
      topic: string
    }): Notification {
      return {
        uuid: 'runtime generate and time uuid',
        message: 'whatever',
        type: 'warning',
        topic: 'file'
      };
    }
```
**Describe alternatives you've considered**

**Additional context**

**Comment by benshope** [comment]
I've found it beneficial to keep error state close to the part of the state tree that the error pertains to:
```
{
  files: {
    loaded: [...],
    errors: [
      {
          uuid: 123456,
          type: 'warning',
          message: 'One of your files contains invalid rows',
          topic: 'file'
       }
  ],
  alerts: [{uuid: 12345, type: 'error', message: 'Your files just loaded'}]
}
```
By keeping error-state close to success-state you make it easier to pass the errors into components and you leave room for extremely specific types of file-loading errors like a 'fileBadDrag' or `fileExtensionIncorrect` without needing add a random `fileErrorType` or `tags` property onto the `notification`.

I believe this is flexible enough to meet the stated requirements since, as you mention above, users can `register new notifications` and `remove notifications` by altering Kepler's state in the Redux store - which they already have access to.

Not sure if I understand the `register new topics` requirement but if more flexibility is needed in terms of displaying notifications within Kepler, a portals-based solution might be worth considering - but that likely is not necessary in the initial implementation.

**Comment by btford** [comment]
whynotboth.jpg

I generally agree with Ben for the cases we're considering. But I think we should defer the decision of where this state concretely gets set to the consumer as long as it doesn't introduce too much more boilerplate.

It's a little easier to filter than aggregate. I'd rather have a flat array of errors/alerts and then filter them for my app than have to traverse `uiState.notifications`.

Other considerations:

- I'd rather use something deterministic for ids. Generating a UUID using a random number makes it much harder to write tests. Monotonically incrementing integers for ids are just as effective without introducing non-determinism.
- If you're going to allow users to edit Kepler's state, it should ideally only be done through exported helper methods. Directly changing Kepler's exported state makes it hard to enforce invariants, and generally makes the API surface much bigger.

**Comment by heshan0131** [comment]
Agree with @macrigiuseppe and @btford on storing the errors/notifications in a central place: `ui-state-reducer` rather than spread them out to all places of the state.

Agree with @btford to use a flat array of notification instead of a map. each notification should have the same shape. then we can filter them based on `type` or `uuid`

`type Notification` should also be more flexible to allow user pass in additional payload if they need to. One of the common entry of error notification is the `new Error` object, which usually includes a handy stack trace.

**Comment by macrigiuseppe** [comment]
This is blocking https://github.com/uber/kepler.gl/issues/263

**Comment by macrigiuseppe** [comment]
> Agree with @macrigiuseppe and @btford on storing the errors/notifications in a central place: `ui-state-reducer` rather than spread them out to all places of the state.
> 
> Agree with @btford to use a flat array of notification instead of a map. each notification should have the same shape. then we can filter them based on `type` or `uuid`
> 
> `type Notification` should also be more flexible to allow user pass in additional payload if they need to. One of the common entry of error notification is the `new Error` object, which usually includes a handy stack trace.

Based on the conversation we are moving forward with the following requirements:
- Each error will have a __type__ and __uuid__ properties
- The array holding errors will flat
- __createNotification__ will allow users to pass extra optional properties
