### ISSUE TITLE
CityGML and optionally IndoorGML standard support

### ISSUE THREAD

**Issue by archenroot** [keplergl/kepler.gl#318]
**Describe the solution you'd like**
Do you plan to support CityGML and IndoorGML standards?

**Comment by heshan0131** [comment]
We don't have plans to support CityGML yet. To my understanding, it is a format used mainly for 3D spatial models. kepler.gl doesn't have true 3D support, it renders 2.5D.

However, we would like to understand how this might help your use cases.

Is there any converter library / app that can convert CityGML to Geojson?
