### ISSUE TITLE
GPU data filtering integration

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#328]
**Problem**
Data filtering is currently executed on the CPU in javascript. The logic generates a new array every time it runs, causing deck.gl to invalidate all buffers and recreate them. CPU filtering causes lagging on large datasets, especially during time playback.

**Solution**
We will move dynamic data filtering logic into the GPU side, using customized shader modules by deck.gl (rfc)[https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/data-filter-rfc.md. This will not apply to all filters, only the filters that require constant updates: time filter and range slider. 

**Limitation**
1. Only one filter can be GPU accelerated, we need to add logic to determine which filter to be handled by the GPU during runtime. 
    - [Solution] Add GPU filter priority for each filter type. 0: time filter, 1: range filter, 3: multi selection & boolean.
    - [Alternative] Allow multiple filters to be added to GPU filter shader module. 

2. Aggregation layer might not be filtered in GPU. 

### Implementation Steps
1. Add `.gpu` property to filter. Implement logic to manage which filter is gpu enabled
https://github.com/uber/kepler.gl/pull/451 #464 
2. Implement data filtering logic and format layer data logic  #469 
3. Add gpu filter logic to deck.gl layer and shader with [Deck.gl layer extension](https://github.com/uber/deck.gl/pull/2684) #604 #858 
4. Add gpu filter logic to aggregation layers.#858 
5. Generalize base-layer class to incoporate gpu filtering methods 
6. Cover edge cases, address layers can only be cpu filtered (heatmap) #858 
7. Adding layer tests #618 
8. Implement CPU filtering to support export filtered data to csv #890 
9. Upgrade deck.gl to 7.3 Use deck.gl brushing module #901 
7. Benchmarking

#### Testcase 1
<img width="1025" alt="Screen Shot 2019-04-05 at 12 41 44 PM" src="https://user-images.githubusercontent.com/3605556/55652381-3362af00-57a0-11e9-9c3e-5b39e5fb3f48.png">

* Data Size: 680k rows, 
* Number of Layers: 1
* Filter: range filter

**Before**
<img width="633" alt="Screen Shot 2019-04-05 at 12 40 26 PM" src="https://user-images.githubusercontent.com/3605556/55652425-4b3a3300-57a0-11e9-87ad-5aff6b0968a0.png">

**After**
<img width="625" alt="Screen Shot 2019-04-05 at 12 35 06 PM" src="https://user-images.githubusercontent.com/3605556/55652111-75d7bc00-579f-11e9-9215-29b7114d09b7.png">

#### Testcase 2
<img width="1031" alt="Screen Shot 2019-04-05 at 12 48 12 PM" src="https://user-images.githubusercontent.com/3605556/55652750-50e44880-57a1-11e9-884b-d39d27935393.png">

* Data Size: 680k rows, 
* Number of Layers: 3
* Filter: range filter

 **Before**
<img width="601" alt="Screen Shot 2019-04-05 at 12 48 50 PM" src="https://user-images.githubusercontent.com/3605556/55652766-5b9edd80-57a1-11e9-95ec-ab1a4fce968b.png">

**After**
<img width="603" alt="Screen Shot 2019-04-05 at 12 49 33 PM" src="https://user-images.githubusercontent.com/3605556/55652805-75402500-57a1-11e9-8cc2-27526e50c0b9.png">

**Comment by briantcl** [comment]
Spring Mar 22, 2019: pending discussion with the deck.gl in GPU data aggregation

**Comment by briantcl** [comment]
update June 14, 2019 : done with GPU data filter steps: 1, 2, 3, 4, 5

**Comment by heshan0131** [comment]
landed in master
