### ISSUE TITLE
Sidebar and panels collapsible/expandable options on default in config 

### ISSUE THREAD

**Issue by Brioan** [keplergl/kepler.gl#335]
**Issue:**
When loading a .json with config, the current default behaviors are that the left side bar is expanded and the legend is collapsed.

**Solution:**
An option in config that allows user to choose whether the sidebar/ any panels are shown on page load.

**Comment by heshan0131** [comment]
Are you running kepler.gl in your own app? If so, you can pass in `options: {readOnly: true}` when calling `addDataToMap`. 

If you are using the demo app we hosted. currently, we don't have options in the config to allow setting up the side panel state.

**Comment by rdhara** [comment]
Note that you can dispatch the actions directly to close these modals (see https://github.com/keplergl/kepler.gl/issues/945#issuecomment-592880099)
