### ISSUE TITLE
Unable to filter map on boolean variables.

### ISSUE THREAD

**Issue by luke2141** [keplergl/kepler.gl#344]
**Describe the bug**
Unable to filter off a boolean variable.  When setting a boolean variable, all rows are excluded.

**To Reproduce**
1. Add data to a map which includes boolean column.  Sample data provided - 
[georgia_ozone_tracts_trunc.geojson.zip](https://github.com/uber/kepler.gl/files/2792189/georgia_ozone_tracts_trunc.geojson.zip)

2. Click 'Filters'
3. Click '+ Add Filter'
4. Select 'ozone_tract'
5. Try to filter boundaries on either True or False

**Expected behavior**
Should be able to choose a subset of the boundaries on the map.

**Screenshots**
Pre-filter image:
![screen shot 2019-01-24 at 9 23 50 am](https://user-images.githubusercontent.com/45365059/51685511-7512f480-1fbc-11e9-9ff4-23ff80901850.png)

Empty map regardless if True or False are selected:
![screen shot 2019-01-24 at 9 24 14 am](https://user-images.githubusercontent.com/45365059/51685687-d8048b80-1fbc-11e9-9772-93608b638731.png)
![screen shot 2019-01-24 at 9 24 31 am](https://user-images.githubusercontent.com/45365059/51685691-d9ce4f00-1fbc-11e9-93f7-f90e72c6d0ad.png)

**Desktop (please complete the following information):**
 - OS: macos mojave v 10.14.2
 - Browser: chrome
 - Version: 71.0.3578.98

**Comment by heshan0131** [comment]
@luke2141, `ozone_tract` contains `No` `Yes`, and was detected as Boolean. However, it was not correctly parsed. Can you replace `No` with `False` and `Yes` with `True` in your data and try again?

**Comment by luke2141** [comment]
Changing `Yes` to `True` and `No` to `False` did not solve the issue.  My work-around has been to set the column to values that will not be interpreted as a boolean.

**Dataset with 'ozone_tract' = boolean [True, False]:**
[georgia_ozone_tracts_trunc2.geojson.zip](https://github.com/uber/kepler.gl/files/2796506/georgia_ozone_tracts_trunc2.geojson.zip)

**Dataset with 'ozone_tract' = string ["Yes-Ozone", "Not-Ozone"]:**
[georgia_ozone_tracts_trunc3.geojson.zip](https://github.com/uber/kepler.gl/files/2796564/georgia_ozone_tracts_trunc3.geojson.zip)

**Comment by macrigiuseppe** [comment]
this should be fixed
