### ISSUE TITLE
Allow replacing default components with dependencies

### ISSUE THREAD

**Issue by khwj** [keplergl/kepler.gl#356]
**Is your feature request related to a problem? Please describe.**
Kepler.gl currently provides a really nice dependency injection, simple default components can be replaced with no issues (e.g. `PanelHeaderFactory` component like in the example).
However, when I tried to replace a more complex default component, e.g. `SidePanel`, which has dependencies, things get for complicated.
If I also specified the dependencies in the new component as well (e.g. through `PanelHeaderFactory.deps = [...]`) , I'll get the following error:
```
<Some dependency> is required as a dependency of <Some parent component>, 
but is not provided to injectComponents. It will not be rendered
```
And sure enough, I tried to add `<Some dependency>` to `injectComponents` method as well and got the same error.
It's not quite clear to me how to replace those components properly, I ended up reconstructed all the dependencies and embedded them in the new component so it requires no dependency but it's quit hacky.
Often times, developers might want to replace only the parent component and specify the same dependencies (or less) as the default component.

**Describe the solution you'd like**
* If a dependency is a default component, it should be automatically discovered and injected.
* If a dependency is not a default component, there should be a way to inject the new factory that required.

**Describe alternatives you've considered**
Maybe there is a better way to do this which is not documented. If so, please treat this a documentation request.

**Comment by heshan0131** [comment]
@khwj which version of kepler are you on? component injector should automatically looke for `factory.deps` and add them to `injectComponents`

**Comment by khwj** [comment]
Thanks @heshan0131 . I upgrade from v0.2.1-beta-1 to v0.2.1.

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/430
This should address the issue
