### ISSUE TITLE
Is it possible to add a custom layer without much change in the whole app?

### ISSUE THREAD

**Issue by gcoimbra** [keplergl/kepler.gl#358]
Hello.

I'm looking foward to develop a spark-powered backend for greater data analysis that will work together with the awesome kepler.gl visualization facilities. 

Since a documentation that fullfil this kind of question could be huge, I'm opening this issue (sorry if isn't the right place) to ask if it's possible to make a custom layer that will fetch the data from the backend without much impact in the rest of the app...

Thanks

**Comment by gcoimbra** [comment]
Maybe if you have interest in cooperation, I think a powerful backend is a nice improvement on kepler.gl...

**Comment by heshan0131** [comment]
The layer is intended to be independent, each of them is a subclass of the base-layer class. It should n't be that hard to add a custom layer. We will create an example. But creating a custom layer requires basic understanding of how layer cycle works, at the time, we don't have the band-width to document it.

May  I ask what type of custom layer do you want to create. Also why it has anything to do with a spark-powered backend?

**Comment by gcoimbra** [comment]
Thanks for the answer. Is these layer cycle related to the deck.gl API? 

Sure you may. The layer will probably be simple, it will just need to gather the data from backend instead. One of the first will probably get the kmeans data and plot the clusters/dots to the map. Just a test.

Further, we will add more resource intensive algorithms. Spark will probably be neede when aiming for big datasets. We choose Kepler because it does a good job when visualizing the data, it's fast and beautiful.

**Comment by simonprovost** [comment]
@gcoimbra what did you manage to do? Any luck? Trying to create a custom layer type too!
