### ISSUE TITLE
processRowObject runs typeAnalyzer on all data not a sample

### ISSUE THREAD

**Issue by CharlieMartell** [keplergl/kepler.gl#39]
https://github.com/uber/kepler.gl/blob/master/src/processors/data-processor.js#L271

This function should probably call `getSampleForTypeAnalyze` before passing to `getFieldsFromData`

**Comment by macrigiuseppe** [comment]
The new line is this: https://github.com/keplergl/kepler.gl/blob/master/src/processors/data-processor.js#L368
