### ISSUE TITLE
Example modal dialog is bigger than the actual window height

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#425]
**Describe the bug**
The modal component is longer the actual height of the window. The component should adapt to the height of the window and be internally scrollable

<img width="1391" alt="screenshot 2019-03-03 22 47 12" src="https://user-images.githubusercontent.com/2554552/53715384-7e3a8100-3e06-11e9-9f58-2f7417e4d8d9.png">

This is really useful for tableau integration given the small size of the frame

**Comment by macrigiuseppe** [comment]
Since we are going to use react 16 we can also take advantage of react portals: https://reactjs.org/docs/portals.html

**Comment by chrisirhc** [comment]
Done via #501
