### ISSUE TITLE
Enable filter to be cumulative for a point in time (e.g., starting time of data)

### ISSUE THREAD

**Issue by demartsc** [keplergl/kepler.gl#435]
**Is your feature request related to a problem? Please describe.**
I would like to show overall growth and global footprint of my data as an animation, but since I cannot freeze the starting point of the filter this does not work when clicking the play button. 

**Describe the solution you'd like**
You should be able to "freeze" or "lock" the starting point of the filter animation and the filter brush should grow from that point till then end and then loop from that point again next time through. 

**Describe alternatives you've considered**
You could try things like filtering data before hand or manually moving the slider while taking a video but neither would really work. 

**Additional context**
See attached gif as an example of the experience I am trying to describe, this was done manually by moving the filter with my mouse and taking a screen capture. 
![Kepler Cumulative Filter Example](https://user-images.githubusercontent.com/22157638/54174882-ea8c3480-4445-11e9-80df-fe38bf47eea8.gif)

**Comment by kunalganglani** [comment]
+1, yes even I would like to have this feature for our product. Please let me know if this is in plan?

**Comment by djouallah** [comment]
+1, yes please, I am doing it manually and it will be really cool to have it automatically

**Comment by digvijaypatil17** [comment]
Even i need to know how to make cumulative time series...

**Comment by DrSosh** [comment]
This would be very useful. Manipulating data to be able to "simulate" it explodes the size of the data file very quickly and is not practical. Any hint on when this can be expected?

**Comment by 4returns** [comment]
Oh man, this would would be super useful! Having this option would make me use Kepler way more than i do now
