### ISSUE TITLE
Google Chrome processGeojson func latency when input includes text fields

### ISSUE THREAD

**Issue by fpapadopou** [keplergl/kepler.gl#438]
**Describe the bug**
Geojson input including text fields makes the `processGeojson` function struggle in Google Chrome. Any input with a text field longer than 200 characters slows down the processor function and anything above 250 characters makes the whole tab unresponsive.
**The same input gets processed in an instant in Safari.**

**To Reproduce**
1. Go to `http://kepler.gl/demo` using **Google Chrome**
2. Click on `Load Data`
3. Upload the files provided in [samples.zip](https://github.com/uber/kepler.gl/files/2956323/samples.zip)
4. The `sample-slow.geojson` file should take _some seconds_ to load
5. The `sample-very-slow.geojson` file should take _several minutes_ to load, during which the tab might become unresponsive
6. Repeat the process using **Safari** browser in order to verify that the files get uploaded instantly there.

**Expected behavior**
The file is expected to load instantly and render the provided Mulitpolygons in kepler.

**Screenshots**
Not applicable.

**Desktop:**
 - OS: Mac OS Mojave 10.14.2
 - Browser: Google Chrome
 - Version: 72.0.3626.121 (Official Build) (64-bit)

**Smartphone:**
Not applicable.

**Additional context**
None.

**Comment by heshan0131** [comment]
Fixed by https://github.com/keplergl/kepler.gl/pull/781
