### ISSUE TITLE
kepler.gl doesn't show actual version number

### ISSUE THREAD

**Issue by chrisirhc** [keplergl/kepler.gl#458]
**Describe the bug**
As seen in the screenshots in #457, we're not displaying the actual version number and instead we display "1.0" :
> Local:
> ![image](https://user-images.githubusercontent.com/49069202/55237971-a9f92d00-5233-11e9-848e-c0af745d935e.png)
> 
> Kepler.gl:
> ![image](https://user-images.githubusercontent.com/49069202/55238005-bda49380-5233-11e9-974a-4584151fc7b8.png)

This can be confusing to users who were expecting certain features that weren't yet released in the build they're using.

**Comment by macrigiuseppe** [comment]
Closing this since it was merged into master
