### ISSUE TITLE
Investigate integration with netlify/githup repo

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#460]
**Is your feature request related to a problem? Please describe.**
We currently perform manual operations to deploy and publish new versions of kepler.gl

We should investigate where we can leverage netlify to improve our process through the usage of probots or github apps

**Comment by macrigiuseppe** [comment]
travis-ci could be an alternative option

**Comment by macrigiuseppe** [comment]
Implement netlify integration

**Comment by chrisirhc** [comment]
Done via #516 and #525
