### ISSUE TITLE
Support Typescript?

### ISSUE THREAD

**Issue by dash-alex** [keplergl/kepler.gl#473]
I want to integrate it into a React App which is written by typescript.

**Describe the solution you'd like**
Myabe write a .d.ts file?

**Comment by macrigiuseppe** [comment]
@dash-alex would you wanna to work on this feature and collaborate with us?

**Comment by macrigiuseppe** [comment]
I am gonna close this one since we didn't receive any feedback

**Comment by 1995parham** [comment]
@macrigiuseppe I have time to write a .d.ts file for Kepler if you want to support typescripts.

**Comment by mayteio** [comment]
hey @macrigiuseppe I'd also be happy to collaborate with you on writing types for Kepler.gl.

**Comment by epan** [comment]
For others interested in the topic, some type definition support was added here https://github.com/keplergl/kepler.gl/pull/1116
