### ISSUE TITLE
Can't export to image

### ISSUE THREAD

**Issue by darkat** [keplergl/kepler.gl#478]
**Is your feature request related to a problem? Please describe.**
Can't export to image in local. I get error when i push export imagen button

**Screenshot**
![Captura2](https://user-images.githubusercontent.com/8228219/56280047-b0c7e100-6109-11e9-88d8-8bbb750860f9.PNG)

![Captura](https://user-images.githubusercontent.com/8228219/56279948-71999000-6109-11e9-8cee-4c89a2406677.PNG)

**Additional context**
React 16.6.3
Redux 4.0.1
react-redux 6.0.0

**Comment by heshan0131** [comment]
What os and browser environment are you running this in?

**Comment by macrigiuseppe** [comment]
Closed since no feedback was provided in more than two weeks
