### ISSUE TITLE
slowing down time animation

### ISSUE THREAD

**Issue by grobins** [keplergl/kepler.gl#481]
I'm trying to animate points on a map, but the slowest speed is still too fast.  Is there any way to choose a slower increment for the animation, or a way to scrub the slider below the time animation.  Current scrubbing only works if there is a large gap between the start and end of the window, which means the window is too high.

To give an idea, I want to show activity of vehicles over a day, second by second, so need 86400 increments to replay over 5minutes or so.

**Comment by heshan0131** [comment]
Seems like we need to optimize the speed logic based on the relative time span of the entire dataset

**Comment by grobins** [comment]
Or give a variable in terms of frames per second?
QGIS Time manager allows for frame display time, fps, and a window in which to include points.

**Comment by abhayap** [comment]
+1

**Comment by briantcl** [comment]
closing this as this is being completed.
