### ISSUE TITLE
Enhancement in Kepler HTML Download

### ISSUE THREAD

**Issue by briantcl** [keplergl/kepler.gl#483]
having a 'studio mode' vs 'view mode' where view mode there will have no option for the side panel but only have the time play back if possible. for 'studio mode', it will have every components listed

**Comment by omegadeep10** [comment]
I believe this already exists in Kepler, it's just referenced as readOnly in the docs. You would have to pass `readOnly: true`   in the initial UI state when you init the Kepler GL reducer. Please see here for more info: https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/reducers/ui-state.md#initial_ui_state

I think "Studio Mode" is the default Kepler.GL state, and the "readOnly" version would be the same as your "View Mode" (and yes, the time playback still works in "readOnly" mode). 

I just answered another issue with an example file where I was able to toggle readOnly with a URL param by adding some code. This issue may be of interest to you: https://github.com/keplergl/kepler.gl/issues/658

**Comment by macrigiuseppe** [comment]
this has been implemented and deployed
