### ISSUE TITLE
View state transitions

### ISSUE THREAD

**Issue by mayteio** [keplergl/kepler.gl#492]
**Is your feature request related to a problem? Please describe.**
Kepler's data-management is extremely optimised and far better than anything we can roll ourselves. We'd love to use Kepler's data and layer management to handle several datasets we load into a story map, however, the story requires view state transitions as described in [deck.gl's](https://github.com/uber/deck.gl/blob/master/docs/api-reference/view-state-transitions.md) documentation.

**Describe the solution you'd like**
Support DeckGL viewState transitions in kepler.gl. Additional dispatch method flyTo() that accepts `{latitude, longitude, pitch, bearing, zoom, interpolator = "FlyToInterpolator", duration: 3000}` and smoothly transitions the mapState.

**Describe alternatives you've considered**
Don't use kepler.gl. Try to do the data management on my own.

**Comment by heshan0131** [comment]
@chrisgervang is working on a view transition UI that can be imported  by kepler.gl~

**Comment by heshan0131** [comment]
That said, if you are using kepler.gl in your own app, you can still dispatch `updateMap` action to kepler.gl reducer add the `FlyToInterpolator` to payload

I create a `view-transition` example to demo it. You can find it here. Pretty easy to do
https://github.com/uber/kepler.gl/blob/view-transition-example/examples/view-transition/src/app.js

![view-transition](https://user-images.githubusercontent.com/3605556/57036619-b04f4000-6c09-11e9-8a83-4195a1959cec.gif)

**Comment by chrisgervang** [comment]
I’m currently trying to learn more about how people would like to use the editor, and have a couple questions.

Would you like to be able to playback a couple view state transitions, as if it were like a short video? 

Or maybe, would you like to manually trigger transitions as part of a love presentation?

If you are hoping to use it in another way, I’d like to know too. Thanks!

**Comment by mayteio** [comment]
@heshan0131 that's exactly what I was after, thanks.

@chrisgervang probably both? I imagine the latter would allow the former.
