### ISSUE TITLE
Add bookmark feature

### ISSUE THREAD

**Issue by itamar-otonomo** [keplergl/kepler.gl#496]
When I want to impress my friends and foes (co-workers) with some brilliant geospatial data representation, It is really difficult for me to orchestrate the fast movement between pre-set locations.

I am ashamed to admit that the best method I found is to save multiple files, each with the same data and config, but in a different zoom and starting position. Whenever I want to jump to a different example, I double click on the relevant file (I know it's sad, please help).

Would be great to have a bookmarks panel where I would be able to store locations and zoom level and switch between them.

**Comment by heshan0131** [comment]
I think you are asking for this:
https://github.com/uber/kepler.gl/issues/492
