### ISSUE TITLE
Reduce Bundle Size (v1.0.0-2)

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#499]
**Is your feature request related to a problem? Please describe.**
Based on the current size evaluation: 
- https://bundlephobia.com/result?p=kepler.gl@1.0.0-2

Kepler.gl is using some heavy libraries that we should evaluate to replace/remove to reduce the package size.

Libraries to evaluate:

| Library |  %  | (KB) | Alternatives | Reduce of | Issue |
|--------|----|------|-------------|-----------|-------|
| react-data-grid | 5.9 | 167.9 | [react-window](https://github.com/bvaughn/react-window) | | #553  |
| moment| 7.7 | 231.7 |   [date-fns](https://github.com/oysterprotocol/webnode/pull/116)  | |
| react-vis | 7.6 | 307.6 |  ad hoc | |
| rect-tooltip | 1 | 28 | [react-microtip](https://github.com/davidtran/react-microtip) | |
| react-modal | 0.5 | 20.1 | ad hoc | |

We should an evaluate a reasonable lighter alternative for each and every one of the above libraries. The evaluation should include:
- Feature overlapping
- Required amount of work to replace each library

**Comment by macrigiuseppe** [comment]
V1.1.0
- https://bundlephobia.com/result?p=kepler.gl@1.1.0

Libraries to evaluate:

| Library |  %  | Alternatives | Reduce of | Issue |
|--------|----|-------------|-----------|-------|
| react-data-grid | 6.1 | [react-window](https://github.com/bvaughn/react-window) | | #553  |
| moment| 7.9 |   [date-fns](https://github.com/oysterprotocol/webnode/pull/116)  | |
| react-vis | 7.6 |  ad hoc | |
| rect-tooltip | 1 | [react-microtip](https://github.com/davidtran/react-microtip) | |
| react-modal | 0.5 | ad hoc | |

**Comment by matheusmonte** [comment]
Hi @macrigiuseppe 

Can I help with this?

**Comment by macrigiuseppe** [comment]
> Hi @macrigiuseppe
> 
> Can I help with this?

Of course, which task would you like to take on?

thank you,
Giuseppe

**Comment by matheusmonte** [comment]
@macrigiuseppe 


What do you think is priority ?   

If all have the same priority, Can I work in remove moment.js and substitute by date-fns?

**Comment by macrigiuseppe** [comment]
> @macrigiuseppe
> 
> What do you think is priority ?
> 
> If all have the same priority, Can I work in remove moment.js and substitute by date-fns?

Please go ahead with moment and data-fns task.

Thank you

**Comment by matheusmonte** [comment]
hi @macrigiuseppe sorry for delay, I have crazy days on work.

I'm back working on this, but I get some problem using date-fns, on docs, they say that UTC submodule is on development, but on Kepler, we use a lot of moment.utc(val) method. 

Will we go on this?

**Comment by macrigiuseppe** [comment]
> hi @macrigiuseppe sorry for delay, I have crazy days on work.
> 
> I'm back working on this, but I get some problem using date-fns, on docs, they say that UTC submodule is on development, but on Kepler, we use a lot of moment.utc(val) method.
> 
> Will we go on this?

@matheusmonte 
If i recall correctly moment.utc() can be simply replaced by [Date.UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC) since they will both return a new Date object with utc offset.

**Comment by matheusmonte** [comment]
I get, Thanks, I will use this
