### ISSUE TITLE
Layer movement by dragging doesn't give expected layer positioning

### ISSUE THREAD

**Issue by sidPhoenix17** [keplergl/kepler.gl#503]
**Describe the bug**
The layers of points/polygons do not move as expected on dragging. If I want to move the issue at top to another position, dragging it to the relevant position makes some other layers move but that layer still remains at the top, making the order more unorganized.

**To Reproduce**
1. Have atleast 4-5 layers added into the map from multiple files
2. Try moving around the layers and re-positioning them.
(say original position is 1-2-3-4-5, try making it to 4-1-5-2-3)

**Expected behavior**
This should be possible to be done in 2 sets of dragging (if I understand the feature's usability correctly). (move 4 to the top, then move 5 above 2). But even after numerous drags, it is just very difficult to get in the exact order as wanted.

**Screenshots**
I made a screen recording of the same. Use this link - https://drive.google.com/file/d/1_QpVsDTo3hwdoUG4KFxqG8JAixvKoj-n/view?usp=sharing

**Desktop:**
 - OS: macOS 10.14.4
 - Browser: Chrome 73.0.3683.103

**Additional context**
Please let me know if I have an incorrect understanding of the feature.

**Comment by macrigiuseppe** [comment]
Hi @sidPhoenix17 , 
would you be able to provide a repo and data to reproduce your issue?

Thank you

**Comment by sidPhoenix17** [comment]
Hi,
To replicate this issue, please open this map - https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/kxb7ld5qsds29c1/keplergl_mzf9wf.json
I created this map by adding couple of additional layers on top of the nyctrips demo mapview.

Current order of layers is: new_layer - pickup - line view - dropoff - arc

When I tried to move it to a new order (say: line view - arc - new_layer - dropoff - pickup), I couldn't do it even after multiple drags and attempts. 

Also just for reference, I had shared a screen recording of how the tool was behaving on another dataset. (https://drive.google.com/file/d/1_QpVsDTo3hwdoUG4KFxqG8JAixvKoj-n/view?usp=sharing)
It is behaving in a similar manner even for this map.

**Comment by macrigiuseppe** [comment]
> Hi,
> To replicate this issue, please open this map - https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/kxb7ld5qsds29c1/keplergl_mzf9wf.json
> I created this map by adding couple of additional layers on top of the nyctrips demo mapview.
> 
> Current order of layers is: new_layer - pickup - line view - dropoff - arc
> 
> When I tried to move it to a new order (say: line view - arc - new_layer - dropoff - pickup), I couldn't do it even after multiple drags and attempts.
> 
> Also just for reference, I had shared a screen recording of how the tool was behaving on another dataset. (https://drive.google.com/file/d/1_QpVsDTo3hwdoUG4KFxqG8JAixvKoj-n/view?usp=sharing)
> It is behaving in a similar manner even for this map.

hello @sidPhoenix17 , I tried your map and it seems working, see below

![issues-503](https://user-images.githubusercontent.com/2554552/57590955-c0a5cb80-74e3-11e9-9e38-9f5a28a22fd2.gif)

Would you mind creating a video with the nyc taxi map and try to replicate the issue so it will be easier to reproduce it on my side.

**Comment by sidPhoenix17** [comment]
Hi, the issue is visible in your screen recording that you have attached as well. The problem that I am facing, is not in the map but in the navigation drawer w.r.t re-positioning layers in a desired order.
As I can see in your video as well:
1. In one of your attempts, you try to move "drop-off" from position 3 to position 2 but it ends up moving to position 4.
2. In another of your attempts, you try to move "new layer" to position 4 but it ends up moving to the top. 

Here's the link to my screen recording - 
https://drive.google.com/file/d/1xY8UQWdgJR7dorIrq91ZAw9Qv_dkx2kJ/view?usp=sharing

**Comment by macrigiuseppe** [comment]
> Hi, the issue is visible in your screen recording that you have attached as well. The problem that I am facing, is not in the map but in the navigation drawer w.r.t re-positioning layers in a desired order.
> As I can see in your video as well:
> 
> 1. In one of your attempts, you try to move "drop-off" from position 3 to position 2 but it ends up moving to position 4.
> 2. In another of your attempts, you try to move "new layer" to position 4 but it ends up moving to the top.
> 
> Here's the link to my screen recording -
> https://drive.google.com/file/d/1xY8UQWdgJR7dorIrq91ZAw9Qv_dkx2kJ/view?usp=sharing

I see the issue. The behavior is definitely wrong.

**Comment by macrigiuseppe** [comment]
This is now fixed in master and deployed on our Kepler.gl website.
It will also be part of next Kepler release

**Comment by divyanshiisinghal** [comment]
Even after saving the map, layers reorder themselves 
Any solution for this?
