### ISSUE TITLE
Get coordinates of the mouse pointer 

### ISSUE THREAD

**Issue by patofw** [keplergl/kepler.gl#504]
It's hard to locate yourself in the map without having the coordinates displayed with the pointer. 
I consider it to be a great enhancement as it would open the door for new use cases, specially in navigation. 
I've seen this feature in many Mapbox apps and was wondering if anyone knows how to incorporate it in Kepler. 

Here is a Mapbox example on how to do it: 
https://docs.mapbox.com/mapbox-gl-js/example/mouse-position/

**Comment by patofw** [comment]
Any updates?

**Comment by heshan0131** [comment]
Should be easy to do, all you need is latitude and longitude right? We can add a tooltip config to enable display mouse geo location. I will start a PR

**Comment by patofw** [comment]
That would be perfect!!! Thanks

The pin could be useful as well.

**Comment by macrigiuseppe** [comment]
Completed
