### ISSUE TITLE
What can be passed in query string to kelper? can I pass csv and config?

### ISSUE THREAD

**Issue by MosheMalin** [keplergl/kepler.gl#518]
I am able to open kepler with data set by using the query string ?mapurl=<my_url_of_data>.csv
I can also use json, but I need to use csv (it's a dynamic request that provides the data in run time, and the csv produces much smaller response).

So, with csv - can I also provide configuration? can I have multiple layers in the csv ?

Thank you!
Moshe

**Comment by briantcl** [comment]
Can you clarify on what do you refer to as saving the config in a csv?

**Comment by MosheMalin** [comment]
I meant to set the configuration information about the layers (like: setting colors, layer type, radius, etc. for the layer in the csv).
I assume it's not doable.
But this is less important now (for us...), as we switched to wrapping kepler with an application and we pass the info programatically.
