### ISSUE TITLE
Jupyter: Keplergl map not saving to html

### ISSUE THREAD

**Issue by sidPhoenix17** [keplergl/kepler.gl#522]
**Describe the bug**
Whenever I am trying to save a map to html from my jupyter notebook, there is an error as shown below:
```
/opt/conda/lib/python3.6/site-packages/keplergl_jupyter/keplergl_jupyter.py in save_to_html(self, data, config, file_name, read_only)
    140 
    141         with open(file_name,'w') as f:
--> 142             f.write(frame_txt.encode('utf-8'))
    143 
    144         print("Map saved to {}".format(file_name))

TypeError: write() argument must be str, not bytes
```
I am using this documentation to https://github.com/keplergl/kepler.gl/tree/keplergl-jupyter/bindings/keplergl-jupyter 

**To Reproduce**
1. While I first faced this issue when I was trying to save a kepler map with a decent chunk of data (3-4 csv/dataframes being used), I then decided to try this on the simplest map.
I am using this code:
```
import keplergl_jupyter as keplergl
map_1 = keplergl.KeplerGl()
map_1.save_to_html()
```
and it is still giving me the same error. 

**Expected behavior**
Expected it to let me save an html file - my intent is to share the html with other team members.

**Screenshots**
![Screenshot 2019-05-20 at 2 31 19 PM](https://user-images.githubusercontent.com/16644933/58071198-7c888a00-7bb9-11e9-8a2f-13f462faf7b4.png)

**Desktop (please complete the following information):**
I tried this on:
(a) Mac OS Mojave 10.14.4 - jupyter notebook installed through anaconda. Keplergl-jupyter installed from https://pypi.org/project/keplergl-jupyter/ - latest version. (0.1.0a3)
(b) Ubuntu 16.04 - jupyter notebook. Keplergl-jupyter installed from https://pypi.org/project/keplergl-jupyter/ - latest version. (0.1.0a3)

It returns the same error on both.

**Comment by heshan0131** [comment]
@sidPhoenix17 `save_to_html()` works when data is loaded. Add you try add some data to it and test it out? Anyhow I am working on fixing more issues with the package. the newest release should address that

**Comment by heshan0131** [comment]
also just published `keplergl_jupyter=0.1.0a4` updated user guides at 
https://github.com/keplergl/kepler.gl/blob/keplergl-jupyter/docs/keplergl-jupyter/user-guide.md

**Comment by sidPhoenix17** [comment]
It is not working even when the data is loaded onto the map and same error was shown even in that case. Let me update to the latest version, go through the user guide and get back to you on the behaviour! 

Thank you !

**Comment by sidPhoenix17** [comment]
Hi,
Using the updated version, the issue of being unable to save the map still persists (Even with data added to the maps). I made the following change in save_to_html function in the keplergl_jupyter.py file and I was able to save the file:

Original
```
with open(file_name,'w') as f:
```
Updated:
```
with open(file_name,'wb') as f:
```

The html file does have all the data saved but it is now not opening on the browser. ([Attaching the html file for your reference](https://drive.google.com/file/d/1nkPCqsJ3M5Gv0iII-GMpc2U86VhrHO98/view?usp=sharing)).

I am using python 3.6.8 (could this be the concern? because pip mentions compatibility upto Python 3.5) on Mac OS Mojave 10.14.4

**Comment by heshan0131** [comment]
Attaching the HTML helps, thanks. I found the problem, the GEOJSON data embedded in the HTML was not properly stringified. It's probably not a python version problem

```python
"data": {"cluster_polygons": "{\n\"type\": \"FeatureCollection\",\n\"crs\": { \"type\": \"name\", \"properties\": { \"name\": \"urn:ogc:def:crs:OGC:1.3:CRS84\" } },\n\"features\": [\n{ \"type\": \"Feature\", \"properties\": { \"id\": 2, \"cluster_name\": \"Sector 31\", \"city_id\": 1 }, \"geometry\": { \"type\": \"Polygon\", \"coordinates\": [ [ [ 77.066032, 28.445493 ], [ 77.065708, 28.443082 ], ... [ 77.066166, 28.446438 ], [ 77.066032, 28.445493 ] ] ] } },\n{ \"type\": \"Feature\", \"properties\": { \"id\": 5, \"cluster_name\": \"DLF Phase 4\", \"city_id\": 1 }, \"geometry\": { \"type\": \"Polygon\", \"coordinates\": 
```

**Comment by sidPhoenix17** [comment]
Hi,
Sorry for the late reply here - somehow I missed the reply notification. 
In 0.1.0.a4, after making the change as mentioned above, the save_to_html functionality is working and I'm able to save the file!
Thank you!

**Comment by macrigiuseppe** [comment]
Closing because no issue

**Comment by sidPhoenix17** [comment]
I meant - the issue/error **still exists** but if I make the below code change in keplergl_jupyter.py save_to_html() function, then the issue is resolved:
Original
`
with open(file_name,'w') as f:
`
Updated:
`
with open(file_name,'wb') as f:
`
