### ISSUE TITLE
[Help]: Height Based On dont work for me

### ISSUE THREAD

**Issue by 1701413420** [keplergl/kepler.gl#526]
Hi, 
Im trying to add the height of a polygon based on a property as shown here.
![image](https://user-images.githubusercontent.com/31360909/58293469-3a16a700-7d8b-11e9-800a-9ad5a7949952.png)
But it does not work for me, I have the following dataset:
![image](https://user-images.githubusercontent.com/31360909/58293537-6cc09f80-7d8b-11e9-8d16-1aecca154f0e.png)
This is the configuration that I add to Kepler.gl
![image](https://user-images.githubusercontent.com/31360909/58293634-f40e1300-7d8b-11e9-9e91-6bfb13a8c480.png)
in the heightField property I add the property of the dataset that I want to take as height, but the result is always the same, the property is not reset, even if I manually add the height it seems that it stays at 0.
![image](https://user-images.githubusercontent.com/31360909/58293725-5cf58b00-7d8c-11e9-844c-cbac576dcf5a.png)

"react": "^16.6.0",
"kepler.gl": "^1.0.0-2",
"mapbox-gl": "^0.53.1",

Thanks a lot.

**Comment by heshan0131** [comment]
Can you open the data table next to the dataset name on top of the layer panel and make sure `requests` is indeed an `integer` field? Sometimes when your data contains none integer value (string), kepler.gl will determine it is not an integer field. Let me know

**Comment by 1701413420** [comment]
Hi, I already solved the problem, thank you!!!
