### ISSUE TITLE
P2: Enable data aggregation or transformation

### ISSUE THREAD

**Issue by ziyili66** [keplergl/kepler.gl#53]
**Problem:**
Currently, kepler.gl doesn’t do much with data aggregation or transformation. User has to massage the data in certain way that fits the layer paradigm. For example, I have to deserialize the points of each trip into a set of points with trip id to plot them by point layer.

**Suggestions:**

- Enable to do nearest neighbor joins to create line or arc layers from two csv files of points.  https://github.com/mourner/geokdbush can be helpful.
- Join sequence of points (by timestamp/sequence id) into line

**Comment by macrigiuseppe** [comment]
Closing because duplicated

**Comment by akuckartz** [comment]
Another duplicate was also closed as a duplicate. Where is the original?
