### ISSUE TITLE
Saving Kepler Config JSON without dataset

### ISSUE THREAD

**Issue by activatedgeek** [keplergl/kepler.gl#532]
**Is your feature request related to a problem? Please describe.**

When saving the Kepler Config as a JSON, it also exports my CSV data in the JSON. For potentially large CSVs as compared to small configurations, this becomes prohibitive as I try to make reproducible map configurations.

**Describe the solution you'd like**

In the "Export Map" menu, it would be great to have a flag which does not dump the dataset (perhaps additionally with a warning that the dataset IDs must be preserved).

**Describe alternatives you've considered**

So far, before deploying my Kepler instance, I manually remove the data from the exported config during development and then programmatically merge on component mount.

**Comment by heshan0131** [comment]
![Screen Shot 2019-06-06 at 5 32 08 PM](https://user-images.githubusercontent.com/3605556/59074608-0c4c5a80-8881-11e9-92a3-3a0445bc4619.png)

you can copy the config from the input box.
We use to support export config only, but people say they don't know what to do with it. We can add that back if copy from input box is not convenient in some caes?

**Comment by activatedgeek** [comment]
> We use to support export config only, but people say they don't know what to do with it.

It actually helps me keep the config from exploding. I have a dataset file and a config file which I load during runtime (`componentWillMount`).

But just to be clear, I might have missed it but this configuration does not have the data?

**Comment by heshan0131** [comment]
yes, the configuration displayed in the input box does not have the data

**Comment by activatedgeek** [comment]
Perfect! Thank you. I think that's all I wanted.
