### ISSUE TITLE
Polygon colors are not being update when weightField changes.

### ISSUE THREAD

**Issue by gcoimbra** [keplergl/kepler.gl#537]
Is there a way for it to preserve the original dataset?

**Comment by gcoimbra** [comment]
In a custom layer based on geojson-layer and heatmap-layer, I have a custom getFillColor that works only when the layer is added but not when I change the weightField. 

Is there any trigger that I'm missing somewhere?

**Comment by briantcl** [comment]
are you using deck.gl or kepler.gl when you see this issue? Can you also provide more detailed information and code snippet for us to reproduce this error?

**Comment by gcoimbra** [comment]
Hello @briantcl thanks for the reply. I was able to figure out the issue recently.
I was using just using the kepler.gl layer based on GeoJSON.
All I had to do was change, updateTriggers to this:
```


const updateTriggers = {
      getElevation: {
        heightField: this.config.heightField,
        heightScale: this.config.heightScale,
        heightRange: visConfig.heightRange
      },
      getFillColor: {

        color: this.config.weightField,
        colorField: this.config.colorField,
        colorRange: visConfig.colorRange,
        colorScale: this.config.colorScale
      },
      ...
```
