### ISSUE TITLE
Export Image Refreshing Without Heatmap Layer

### ISSUE THREAD

**Issue by sleepybjr** [keplergl/kepler.gl#539]
**Describe the bug**
When clicking on "Export Image", the preview image constantly refreshes without loading the heatmap layer onto it. When I am able to click download, there is no heatmap layer visible on the image.

**To Reproduce**
1. Upload latitude/longitude data.
2. Add a new heatmap layer using that data.
3. Reduce radius to < 6.
4. Select Export Image.
5. See error (reproduced at every refresh)
![image](https://user-images.githubusercontent.com/22383876/58743915-5d76cd00-83ef-11e9-9394-80b32c6a357f.png)

**Expected behavior**
When clicking on "Export Image", the visible heatmap layer will be visible on the preview and after downloading.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome, firefox, firefox dev edition
 - Version: latest for all

**Additional context**
Tried it on live demo site and cloned repo, occurred in both.

**Comment by cschlessinger** [comment]
Hi! Wondering if there's an ETA for the fix?

**Comment by macrigiuseppe** [comment]
We are currently looking into this issue

**Comment by macrigiuseppe** [comment]
hi @cschlessinger we are currently looking into this issue

**Comment by heshan0131** [comment]
This is fixed with release v1.1.2
