### ISSUE TITLE
[Bug] Geojson failure when property contains JS object

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#547]
**Describe the bug**

When are geojson contains js object in the property, Kepler failed to render it in tooltip and data table

**To Reproduce**
1. download geojson at https://transit.land/api/v1/operators/o-9q8y-sfmta.geojson?per_page=false
2. upload to kepler
3. fail to render immediately

**Expected behavior**
Parse js objects as a string

**Comment by matheusmonte** [comment]
@heshan0131  Can I work to solve this?

**Comment by heshan0131** [comment]
YES! my thinking is when read in geojson from files, stringify properties that contain object. You can dig into [`geojson-processor`](https://github.com/keplergl/kepler.gl/blob/master/src/processors/data-processor.js#L414-L454)

**Comment by matheusmonte** [comment]
Sure, I will work on this. Maybe on Saturday I send a PR solving this. Thanks

**Comment by matheusmonte** [comment]
Hi @heshan0131 , I solve this. You're right, the problem occurs in geojson-processor , so I add a check type in properties and bug crash is avoid, but I'm not sure if this result is correct, you can see the render result in this image.

![Screen Shot 2019-06-18 at 13 59 18](https://user-images.githubusercontent.com/5808206/59708709-53b4de00-91d3-11e9-9dc7-ecba4673673c.png)

**Comment by matheusmonte** [comment]
The code is in PR #564

**Comment by heshan0131** [comment]
This is fixed, please reopen if this is anything else needed
Special thanks to @matheusmonte
