### ISSUE TITLE
How to disable the "Add Data To Map" model?

### ISSUE THREAD

**Issue by ddolheguy** [keplergl/kepler.gl#548]
I'm playing around with Kepler (awesome too), and once data is loaded it works a treat, but is there a prop i can pass to not display the "Add Data To Map" dialogue? 

It disappears once I load the data, but there is a quick flash which I'd like to remove?

**Comment by heshan0131** [comment]
Yes you can use [Custom Initial State](https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/custom-initial-state.md), and change the default [`uiState`](https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/reducers/ui-state.md#initial_ui_state) by passing `uiState: {currentModal: null}`

**Comment by ddolheguy** [comment]
Thanks so much
