### ISSUE TITLE
Use custom component

### ISSUE THREAD

**Issue by Adel-J** [keplergl/kepler.gl#555]
I'm using kepler to visualization the data to clients so I put ui state to `uiState: {readOnly: true}` now there is no panel to control the maps and work perfect.

Now I want the clients to choose the map style for base such as dark, light and ..., so I created my component and add the 'MapStyleSelectorFactory' component to render inside my component so I get an error:
`Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

My question is can I use extracted components from kepler with same style and props just to show on custom component.

**Comment by macrigiuseppe** [comment]
Hey @Adel-J , would you mind including your MapStyleSelectorFactory component code in your issue so we will be able to provide better support.

Thank you

**Comment by Adel-J** [comment]
Thanks Macrì for your help.
Just to note it is work when inject the component but I don't want the whole side panel I want to use it in custom component.
I know the Redux retrieve the state for active side panel and trying to get it for MapStyleSelectorFactory but I couldn't.

> CustomMapStyleSelector.js


```
function CustomMapStyleSelector() {
  const MapStyleSelector = MapStyleSelectorFactory();
  const CustomMapStyle = (props) => (
    <MapStyleContainer>
      <MapStyleLabel>Choose your map style:</MapStyleLabel>
      <MapStyleSelector {...props}/>
    </MapStyleContainer>
  );
  return CustomMapStyle;
}

export default CustomMapStyleSelector;
```

> app.js


```
return (
      <div style={{position: 'absolute', width: '100%', height: '100%'}}>
          <AutoSizer>
            {({height, width}) => (
            <KeplerGl
              mapboxApiAccessToken={MAPBOX_TOKEN}
              id="map1"
              width={width}
              height={height}
            />
          )}
          </AutoSizer>
          <StyledMapDisplay>
            {CustomMapStyleSelector()}
          </StyledMapDisplay>
      </div>
    );
```

**Comment by heshan0131** [comment]
If you plan to render the `MapStyleSelector` inside your CustomMapStyleSelector, you need to pass along its dependencies like this:

```js
const CustomMapStyleSelector.deps = MapManagerFactory.deps;

function CustomMapStyleSelector(...deps) {
  const MapStyleSelector = MapStyleSelectorFactory(...deps);
  const CustomMapStyle = (props) => (
    <MapStyleContainer>
      <MapStyleLabel>Choose your map style:</MapStyleLabel>
      <MapStyleSelector {...props}/>
    </MapStyleContainer>
  );
  return CustomMapStyle;
}

export default CustomMapStyleSelector;

```

**Comment by heshan0131** [comment]
closing it until more discussion cone along

**Comment by RedRosh** [comment]
how can we use a custom LayerManager for example inside another component ( I want to put it inside another panel ) and to keep the first one that exist in layer-panel untouched  ?
