### ISSUE TITLE
Updating data is impossible

### ISSUE THREAD

**Issue by geoHeil** [keplergl/kepler.gl#560]
After configuring a visualization I want to update the data.

Am I missing a replace data layer button? The only way forward seems to add a new file and then manually switch all layers over to the new file and then drop the old one. Is there a smoother workflow available? How can I replace the data contents of a layer simply like replacing a file in QGIS.

https://github.com/keplergl/kepler.gl/issues/176

> Currently we don't have a straight way to update an existing dataset.
> 
> In the meanwhile, you can change your flow by skipping removeDataSet and call addDataToMap with your new data. Make sure the new dataset id that you are passing as addDataToMap call matches the existing one; by doing so you are going to override existing data with your new data.

How can I access this functionality on the demo app? Uploading the same file name twice will not replace but rather upload a different id for the same name.

**Comment by macrigiuseppe** [comment]
It's not possible right now, in the future when we will introduce the layer duplication you will be able to do so.

**Comment by cdolan92** [comment]
Any updates been made here ? Challenging to use this regularly in the kepler.gl/demo site without replace.

It looks like this functionality was added in a demo under vis.academy? http://vis.academy/#/kepler.gl/3-load-config
