### ISSUE TITLE
info regarding keplergl-jupyter

### ISSUE THREAD

**Issue by Koushik95** [keplergl/kepler.gl#563]
Hi, I'm exploring the python package of keplergl as given in the following link :- 
https://pypi.org/project/keplergl-jupyter/

But I'm not able to find any documentation on its usage. 
@heshan0131 - I was hoping you could help me with this?
Thanks

**Comment by heshan0131** [comment]
The official package is https://pypi.org/project/keplergl

**Comment by Koushik95** [comment]
yes @heshan0131 - I found this as well 
but is there any link for its documentation?
if so can you provide it here?
Thanks

**Comment by heshan0131** [comment]
Docs at:
https://github.com/keplergl/kepler.gl/blob/master/docs/keplergl-jupyter/user-guide.md

I just landed it into master. We haven't officially announce it yet

**Comment by Koushik95** [comment]
ok thank you for your assistance @heshan0131
