### ISSUE TITLE
Kepler.gl isn't visualiing

### ISSUE THREAD

**Issue by GIShoj** [keplergl/kepler.gl#565]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GIShoj** [comment]
I just tried to vizzualize a dataset on the website and it's not working. It's a simple point dataset in a geojson format.

Shouldn't it be working. I would like to install Kepler on a lokal server, if  I can make it work.

[Aalder.zip](https://github.com/keplergl/kepler.gl/files/3306165/Aalder.zip)

**Comment by heshan0131** [comment]
@GIShoj kepler.gl accepts geojson coordinates in web mercator projection. that is latitude [-90, 90] and longitude [-180, 180]. Yours is
`{ "geometry": { "type": "Point", "coordinates": [ 711385.82, 6167667.82 ] } }`
