### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by bissou** [keplergl/kepler.gl#566]
**Describe the bug**
I can not change the data source in Demo of kepler

**To Reproduce**
Upload 2 sources of data 
Add layer 
change the data source
error : can not  

**Expected behavior**
changing the file source.

**Comment by matheusmonte** [comment]
Hi,

Thanks for your issue. Can you provide more information about this? I can't reproduce locally 

Which version you're using? 
What is your platform? 
If web version, some error is throws in browser console? 

Thanks
