### ISSUE TITLE
keplergl python package not working in jupyterlab

### ISSUE THREAD

**Issue by Koushik95** [keplergl/kepler.gl#570]
Hi @heshan0131 ,

After following your updated documentation, I tried running keplergl python package in jupyterlabs and the respective widgets were not showing. I'm able to install the package but when I try the following command :- 

map = keplergl.KeplerGl()

I get the following console msg :- 
Could not instantiate widget
Error: Could not create a model.
    at promiseRejection (utils.js:125)
Exception opening new comm
Module keplergl-jupyter, semver range ^0.1.0 is not registered as a widget module
Uncaught (in promise) Module keplergl-jupyter, semver range ^0.1.0 is not registered as a widget module

Judging by the msg, it seems that it's looking for keplergl-jupyter binding, which is currently not available. So can you tell me how to resolve this?

Thanks

**Comment by heshan0131** [comment]
I updated the package name, The correct package should be `keplergl`
It is though not available on JupyterLabs yet. One step at a time

**Comment by Koushik95** [comment]
okay, do you have any ETA on when it will be ready on jupyterlabs - @heshan0131 ?

**Comment by heshan0131** [comment]
I am not very familiar with JupyerLabs and how to install widgets in it. After some reading, it seems I have to publish an extension just for JupyterLabs?

**Comment by Koushik95** [comment]
@heshan0131 - Yes, a new extension has to be published for jupyterlabs. Can you tell me the status of this?

**Comment by Koushik95** [comment]
@heshan0131 - any new updates on this request?

**Comment by davidnaughton** [comment]
Hey , I am also running into this issue , any idea when it will be available in jupyter labs ?

**Comment by heshan0131** [comment]
Add installation instruction for Jupyter Lab
https://github.com/keplergl/kepler.gl/tree/master/bindings/kepler.gl-jupyter#installation
Close this for now 🥂

**Comment by nanodan** [comment]
Following the new installation instructions for JupyterLab still produces the same "not registered as a widget module" error for me. JupyterLab v1.0.6, node v11.15.0. If I look at the extensions manager settings, keplergl-jupyter has been installed successfully.

![Screenshot 2020-01-23 at 11 40 23 AM](https://user-images.githubusercontent.com/5264336/73004383-2ff2ef80-3dd5-11ea-9649-071dc596cb46.png)
