### ISSUE TITLE
Blank page when share public URL is selected [Bug]

### ISSUE THREAD

**Issue by ruvenguna** [keplergl/kepler.gl#580]
**Describe the bug**
The page goes blank everytime I try to share a public URL. I select the upload to dropbox option, then it goes blank. I am using google chrome

**To Reproduce**
1. Upload any dataset or use available dataset
2. Click on share public URL

**Expected behavior**
Create a link with a URL to share map

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by heshan0131** [comment]
@ruvenguna 
could you please open your javascript console ()and send us a screenshot of any error there? We can not reproduce this on our end.
To open js console in chrome: View > Developer > Javascript Console
Thanks

**Comment by ruvenguna** [comment]
Here are the screenshots from the error console. Actually, this is a new problem. I was able to export the maps prior to the date I posted this issue. However, now it keeps producing a blank screen. Please advise me on how I can fix it. Thank you.


![Error Screen 2](https://user-images.githubusercontent.com/40380329/60312194-f36d2b80-998c-11e9-9ffe-567db98e61d6.png)
![Error screen 1](https://user-images.githubusercontent.com/40380329/60312195-f36d2b80-998c-11e9-80ed-75b15a002cae.png)

**Comment by ruvenguna** [comment]
After viewing the error files, I realized that my dropbox is full. However, how can I sign out of dropbox on the Kepler app?


![Error screen 1](https://user-images.githubusercontent.com/40380329/60312640-a8ecae80-998e-11e9-9257-1a2c75676833.png)
![Error Screen 2](https://user-images.githubusercontent.com/40380329/60312641-a8ecae80-998e-11e9-8b3a-52aa3b6228f5.png)

**Comment by heshan0131** [comment]
@macrigiuseppe ?

**Comment by macrigiuseppe** [comment]
> After viewing the error files, I realized that my dropbox is full. However, how can I sign out of dropbox on the Kepler app?
> 
> ![Error screen 1](https://user-images.githubusercontent.com/40380329/60312640-a8ecae80-998e-11e9-9257-1a2c75676833.png)
> ![Error Screen 2](https://user-images.githubusercontent.com/40380329/60312641-a8ecae80-998e-11e9-8b3a-52aa3b6228f5.png)

There is no current feature in Kepler.gl to logout users from their dropbox account but you can perform the following:

![delete-mapbox-token](https://user-images.githubusercontent.com/2554552/61177052-dabe6180-a599-11e9-9935-60afcb704f34.gif)

Kepler.gl store dropbox into the browser local storage using the key __dropbox__, if you delete the entry from your browser, you will no longer be logged in dropbox through Kepler.gl.


I created an issue to implement the UI behavior for logout: https://github.com/keplergl/kepler.gl/issues/608

**Comment by heshan0131** [comment]
closing it for now, please follow #608
