### ISSUE TITLE
[Bug][Jupyter Widget] Data Stops Rendering after Additional Styling

### ISSUE THREAD

**Issue by d-wasserman** [keplergl/kepler.gl#586]
**Describe the bug**
I am seeing the following behavior: 

- Geodataframe (point file) gets a second layer added classified as a polygon, even though one is specified. 
- Heatmaps seem to the be only layer configuration that seems to work (but the classifications are the issue). Data appears in the legend, but not the map. 
- Points initially appear, but when styled they fall off the map. It is very odd behavior. 

Bones of something great are here though, automatic zoom extent, instant reactivity, interactive styling and configuration, and sharing methodology are oriented around geospatial workflows. 

**To Reproduce**
1. pip install keplergl-0.1.0
2. start a jupyternotebook
3. Fix python 3 error relating to print statements
3. Call KeplerGL with a geodataframe of LEHD point data, height 800. 
4. Points appear in correct location and get expected behavior. 
5. Points are styled, **then they drop off**. 
6. Legend seems to work and react to controls, other visualization types do not work. Heatmap is an exception, but does not react well to outlier values (likely a feature request). 

**Expected behavior**
At step 5, I expected styling controls to be reactive and change the map, but the data disappears. It seems to be specifically an issue with rendering the data, as the legend **seems** to continue to be reactive to changes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8280073/60227573-b85fe080-9844-11e9-98a6-d68b88ae34cf.png)
**Environment (please complete the following information):**
 - Python 3
 - keplergl Widget  0.1.0
- OS Windows 10
- Pip Freeze attached. 
[pip_freeze.zip](https://github.com/keplergl/kepler.gl/files/3332623/pip_freeze.zip)

**Comment by heshan0131** [comment]
in step 5. How did you style the point? Did you click in the side panel or call `jobsGL.config()` with python. What exact style did you apply?

**Comment by d-wasserman** [comment]
Hi @heshan0131, 

Side panel edits. I tried hexbin, point, polygon, grid, heatmap, and cluster. In all attempts, only heatmap symbolized. 

Using a different environment at home, this morning, I have full functionality. I can even load pickled configurations and apply them. This makes me think it is not an os issue. I don't have some of the UDST libraries (pandana/urbanaccess) in this environment, but I am not sure that is the issue. 

![image](https://user-images.githubusercontent.com/8280073/60276010-a36c6700-98af-11e9-9c0a-0d9029b95aaa.png)

**Comment by heshan0131** [comment]
Interesting. If you can reproduce previews error, try open javascript console and see if any error appears there. Please take a screenshot if there is any and paste in this thread.

**Comment by d-wasserman** [comment]
Good idea. I will follow up later.

**Comment by d-wasserman** [comment]
For a brief moment, i was able to style points, but after a second it fell off. When I changed to another style same errors started to appear. When looking at the JS console, I see 212 errors that change in number with setting changes. Screen shot attached. 

Read out of one of them:

> Uncaught TypeError: c.querySelectorAll is not a function
    at MutationObserver.<anonymous> (content_script_bundle.js:16)
utils.js:37 Loading extension: jupyter-js-widgets/extension

![image](https://user-images.githubusercontent.com/8280073/60285037-e8999480-98c1-11e9-90f4-c1a4b31cbc0a.png)

**Comment by heshan0131** [comment]
keplergl 0.1.0 is published, can you try installing it?

**Comment by d-wasserman** [comment]
When the opportunity presents it self, I will report back on whether an update works.
