### ISSUE TITLE
Saved HTML file keeps flashing when opening with browser

### ISSUE THREAD

**Issue by HLiuUS** [keplergl/kepler.gl#592]
**Describe the bug**
When the map contains a filter, the map keeps flashing when opened with a browser

**To Reproduce**
1. Created a map within Jupyter Notebook
2. Add a filter 
3. Call .save_to_html method to save to HTML

**Environment (please complete the following information):**
 - Python version: python3
 - keplergl Widget version: 
[test-fake1.zip](https://github.com/keplergl/kepler.gl/files/3343163/test-fake1.zip)

0.1.0.a7

**Comment by rubenseijioto** [comment]
I'm having the same issue and for it's happening when I add a timestamp filter, other types works fine for me.

**Comment by HLiuUS** [comment]
> I'm having the same issue and for it's happening when I add a timestamp filter, other types works fine for me.

Exactly the same thing happened to me.

**Comment by heshan0131** [comment]
@HLiuUS What browser (chrome, safari, firefox) and operating system (mac, windows) are you on?
mind attach the html?

**Comment by HLiuUS** [comment]
@heshan0131 It was on Windows 10 and I tried with both Chrome and Edge, same issue. You can find a html file in the zip file I uploaded.

**Comment by heshan0131** [comment]
@macrigiuseppe will look into this

**Comment by Bwsutton1990** [comment]
> I'm having the same issue and for it's happening when I add a timestamp filter, other types works fine for me.

This seems to be the same for me. It stops flashing when I remove it from the map by selecting "Time Playback" in the filter section. But starts again when I select it again.

**Comment by macrigiuseppe** [comment]
Based on my findings it looks like the browser page keeps on showing/hiding scrollbars and creates a flashing effect.

This is the recording

https://drive.google.com/file/d/1V_kQWjZD8L4Qgtn1bEbBBHX5YYXAS_1b/view?usp=sharing

@Bwsutton1990 @HLiuUS can you please confirm that's the actual problem you are experiencing?

If not, can you please provide a recording of your issue?

Thank you

**Comment by Bwsutton1990** [comment]
Hi @macrigiuseppe 

I cant access the file, but having looked at the flashing more closely, that seems to make sense.

Thanks
Ben

**Comment by HLiuUS** [comment]
Hi @macrigiuseppe, I cant access the file either, but it seemscorrect based on your description.

**Comment by macrigiuseppe** [comment]
@Bwsutton1990 @HLiuUS i updated the link. Let me know

**Comment by Bwsutton1990** [comment]
@macrigiuseppe that is the problem I am having.

**Comment by Bwsutton1990** [comment]
Hi, I was wondering if any solution had been found for this yet? Thanks!

**Comment by TheMLman** [comment]
Hi, I'm experiencing the same issue with the html file. Is there any solution yet?

**Comment by jaykinghorn** [comment]
@HLiuUS I've had the same problem. I tried a different environment with an earlier version of KeplerGL installed and I didn't have the issue when I selected a solid color for the trip origin and a separate color for the destination, rather than having the origin color selected based on categorical data from a column in my dataset. Perhaps this will be helpful in troubleshooting?

**Comment by TheMLman** [comment]
Opening HTML file in Edge resolved the issue for me.

**Comment by heshan0131** [comment]
`keplergl==0.1.0a9` is published, can you give it a try?

**Comment by HLiuUS** [comment]
> `keplergl==0.1.0a9` is published, can you give it a try?

Problem solved for me!
