### ISSUE TITLE
Can't export images kepler.gl [Bug]

### ISSUE THREAD

**Issue by troboukis** [keplergl/kepler.gl#594]
**Describe the bug**
The images exported from kepler.gl, don't show the data. Are empty. 

**Screenshots**
<img width="1279" alt="Screenshot 2019-07-02 at 11 37 20" src="https://user-images.githubusercontent.com/39416082/60497724-144fbc80-9cbe-11e9-9e17-89648da121b2.png">

**Desktop (please complete the following information):**
 - OS: 10.14.5
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by troboukis** [comment]
It works with Firefox, but not with Chrome.

**Comment by heshan0131** [comment]
We will try to reproduce it. @troboukis Can you paste your map config and a smaller set of data?

**Comment by saihacm** [comment]
I have the same problem with the exporting images as you.

Screenshot:
![image](https://user-images.githubusercontent.com/18748377/61602579-5d16e780-ac64-11e9-8af7-0a60a13aafa0.png)

Map config & data:
[keplergl.txt](https://github.com/keplergl/kepler.gl/files/3415510/keplergl.txt)

**Comment by trietphan94** [comment]
Hi @heshan0131, When will this task be released?

**Comment by macrigiuseppe** [comment]
> Hi @heshan0131, When will this task be released?

@trietphan94 the feature is already available on https://kepler.gl/

**Comment by trietphan94** [comment]
@macrigiuseppe How about npm package?

**Comment by macrigiuseppe** [comment]
> @macrigiuseppe How about npm package?

@trietphan94 I am not sure about the exact day but it should happen soon
