### ISSUE TITLE
Instructions on MapboxLayerGL

### ISSUE THREAD

**Issue by Harrisandwich** [keplergl/kepler.gl#597]
**Describe the solution you'd like**
Instructions on the usage of the MapboxLayerGL layer within kepler

**Describe alternatives you've considered**
Currently there is no efficient layer type for rendering MVT layers. I'm currently using the mapbox map ref to render tile layers, but I would like the state of these layers to be managed by the kepler redux store. I noticed a MapboxLayerGL layer class in the Kepler source and was wondering how it works.

For example, could I pass it a layer source like this?

```js
    {
      type: 'vector',
      tiles: [tileURL],
      minzoom: 6,
      maxzoom: 14,
    }
``` 

with properties like this?

```js
{
    source: sourceName,
    'source-layer': sourceName,
    id: mapLayerID,
    type: 'fill',
    paint
}
```

Quick edit:
Are there ways to hook up interaction with mapbox layers into the kepler store? I noticed the heatmap layer is a mapbox layer, but doesn't pass click events.

**Comment by heshan0131** [comment]
@Harrisandwich Most of kepler.gl's layers except the heatmap layer is Deck.gl layer. We are actually planning to replace heatmap with a deck.gl Native heatmap layer. 

In your case, however, you want to render Mapbox Layer but use kepler.gl's layer config UI to control it? Will you be building it as a custom kepler.gl layer? If so, you can always take a look at kepler's [heatmap layer](https://github.com/keplergl/kepler.gl/blob/master/src/layers/heatmap-layer/heatmap-layer.js). Pay attention to `computeHeatmapConfiguration` and `formatLayerData` method. The first convert kepler.gl layer config to mapboxGl layer config, the second config kepler.gl data to Geojson.

Let me know if this helps
