### ISSUE TITLE
Can't start development server

### ISSUE THREAD

**Issue by marigibara** [keplergl/kepler.gl#598]
Following steps for local development after `yarn --ignore-engines` got this:

    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@1.2.9: The platform "win32" is incompatible with this module.
    info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > react-palm@2.0.0" has unmet peer dependency "enzyme-adapter-utils@^1.8.0".
		warning " > react-palm@2.0.0" has unmet peer dependency "react-test-renderer@^16.4.1".
    warning " > @deck.gl/test-utils@7.1.5" has unmet peer dependency "@deck.gl/core@^7.0.0".
    warning " > eslint-config-uber-es2015@3.1.2" has incorrect peer dependency "eslint@>= 3.0.0 < 5".
    warning "eslint-config-uber-es2015 > eslint-config-uber-es5@2.0.3" has incorrect peer dependency "eslint@>= 3.0.0 < 5".
    warning " > eslint-config-uber-jsx@3.3.3" has incorrect peer dependency "eslint@>= 3.0.0 < 5".
    warning "eslint-config-uber-jsx > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
	  warning " > url-loader@0.5.9" has unmet peer dependency "file-loader@*".
    [4/4] Building fresh packages...
    [1/4] ? puppeteer
    [2/4] ? gl
    [-/4] ? waiting...
    error C:\Users\Mari\Documents\_DEV\KEPLER.GL\dev\kepler.gl\node_modules\gl: Command failed.
    Exit code: 1
    Command: prebuild-install || node-gyp rebuild
    Arguments:
    Directory: C:\Users\Mari\Documents\_DEV\KEPLER.GL\dev\kepler.gl\node_modules\gl
    Output:
    prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 libc= platform=win32)
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@10.15.3 | win32 | x64
    gyp info spawn C:\Python27\python.exe
    gyp info spawn args [ 'C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
		gyp info spawn args   'msvs',
		gyp info spawn args   '-G',
		gyp info spawn args   'msvs_version=auto',
		gyp info spawn args   '-I',
		gyp info spawn args   'C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\gl\\build\\config.gypi',
		gyp info spawn args   '-I',
		gyp info spawn args   'C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\node-gyp\\addon.gypi',
		gyp info spawn args   '-I',
		gyp info spawn args   'C:\\Users\\Mari\\.node-gyp\\10.15.3\\include\\node\\common.gypi',
		gyp info spawn args   '-Dlibrary=shared_library',
		gyp info spawn args   '-Dvisibility=default',
		gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Mari\\.node-gyp\\10.15.3',
		gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\node-gyp',
		gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Mari\\.node-gyp\\10.15.3\\<(target_arch)\\node.lib',
		gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\gl',
		gyp info spawn args   '-Dnode_engine=v8',
		gyp info spawn args   '--depth=.',
		gyp info spawn args   '--no-parallel',
		gyp info spawn args   '--generator-output',
		gyp info spawn args   'C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\gl\\build',
		gyp info spawn args   '-Goutput_dir=.' ]
		Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
		Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
		gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
		gyp info spawn args [ 'build/binding.sln',
		gyp info spawn args   '/clp:Verbosity=minimal',
		gyp info spawn args   '/nologo',
		gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
		Compilando os projetos desta solu??o um de cada vez. Para habilitar a compila??o paralela, adicione a op??o "/m".
		MSBUILD : error MSB3428: N?o foi poss?vel carregar componente "VCBuild.exe" do Visual C++. Para corrigir isso, 1) instale o .NET Framework 2.0 SDK, 2) instale o Microsoft Visual Studio 2005 ou 3) adicione o local do component
		e ao caminho do sistema se ele estiver instalado em outro local.  [C:\Users\Mari\Documents\_DEV\KEPLER.GL\dev\kepler.gl\node_modules\gl\build\binding.sln]
		gyp ERR! build error
		gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
		gyp ERR! stack     at ChildProcess.onExit (C:\Users\Mari\Documents\_DEV\KEPLER.GL\dev\kepler.gl\node_modules\node-gyp\lib\build.js:262:23)
		gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
		gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
		gyp ERR! System Windows_NT 10.0.17763
		gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mari\\Documents\\_DEV\\KEPLER.GL\\dev\\kepler.gl\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
		gyp ERR! cwd C:\Users\Mari\Documents\_DEV\KEPLER.GL\dev\kepler.gl\node_modules\gl
		gyp ERR! node -v v10.15.3

**Comment by matheusmonte** [comment]
Hi @marigibara 

Thanks for your issue, I tried to reproduce here and didn't happens. Are you following this [link](https://github.com/keplergl/kepler.gl/blob/master/contributing/DEVELOPERS.md)? 

Can you provide more information about your configuration, by your errors message, looks is some permission problem in your local folder or something like this.

I hope hear from you soon.

**Comment by marigibara** [comment]
Following this tutorial, gotta this error and just stopped trying.
Now I tried again until `npm start` and, even with this error, it works.

I'm closing this issue.
Thanks for your response.
