### ISSUE TITLE
save_to_html - Object of type 'Timestamp' is not JSON serializable

### ISSUE THREAD

**Issue by Stephane-Thales** [keplergl/kepler.gl#602]
Within jupyter using the save_to_html function of the keplergl map produce the error: 
"Object of type 'Timestamp' is not JSON serializable"
The data loaded do contain two datetime64[ns] fields.

Environement :
 - Python version: 3.6.8
 - keplergl Widget version: 0.1.0a7

**Comment by heshan0131** [comment]
Are you passing the `datetime64[ns] fields` inside a dataframe? Can you paste code snippet on how you passed the data to kepler?

To make it work for now, You can try convert it into a string. kepler.gl will detect string as a `time` type

**Comment by Stephane-Thales** [comment]
> Are you passing the `datetime64[ns] fields` inside a dataframe? Can you paste code snippet on how you passed the data to kepler?
> 
> To make it work for now, You can try convert it into a string. kepler.gl will detect string as a `time` type

Hi, 
Yes I'm using pandas and passing the data in a dataframe

Here is the part where I load the data :

```
# Load an empty map and add data
map_1 = KeplerGl(height=800)
map_1.add_data(data=dfcluster, name='arc')
```

Then I apply a previously saved config

```
configKepler = json.load( open( "/home/Me/configKepler.json" ) )
map_1.config = configKepler
```

the dataframe dtypes return :

```
EntryCluster               int64
ExitCluster                int64
Cnt                        int64
Entrylongitude           float64
Entrylatitude            float64
Entrydatetime     datetime64[ns]
Exitlongitude            float64
Exitlatitude             float64
Exitdatetime      datetime64[ns]
EntryPoly                 object
ExitPoly                  object
```

the config file is attached here :
[configKepler.json.txt](https://github.com/keplergl/kepler.gl/files/3390652/configKepler.json.txt)


Following your recomendations, I've converted to str before loading the data in the map.

```
dfcluster["Entrydatetime"] = dfcluster["Entrydatetime"].astype(str)
dfcluster["Exitdatetime"] = dfcluster["Exitdatetime"].astype(str)
```
What's great is that the config file still work with that change.
then the save work well

```
map_1.save_to_html(file_name='/home/Me/mapArcandPoly.html')
Map saved to /home/Me/mapArcandPoly.html!
```

Thanks

**Comment by heshan0131** [comment]
👍 
closing it for now

**Comment by Jacey-Chang** [comment]
After I convert it to a string the config don't work any more.

**Comment by keepfighting666** [comment]
It works. Thanks!
