### ISSUE TITLE
Changing of histogram-bars color [Bug]

### ISSUE THREAD

**Issue by vladimir-kondratenko** [keplergl/kepler.gl#603]
**Describe the bug**
Judging by the source code, the color of the active histogram-bar is changed using the variable `activeColor` of theme. But changing of this variable doesn't change anything.

**To Reproduce**
1. Load a data to the map
2. Add time range filter
3. Provide you'r own theme to the kepler's instance with `activeColor` variable
4. See the default color of active histogram bars

**Expected behavior**
Active histogram bars color the same as value of `activeColor` theme variable

**Screenshots**
<img width="945" alt="Screen Shot 2019-07-10 at 12 47 22 PM" src="https://user-images.githubusercontent.com/23726536/60959595-25797880-a311-11e9-9cfc-8327a6aed27a.png">

**Desktop:**
 - OS: macOS Mojave 10.14.5
 - Browser chrome version 75.0.3770.100 (64-bit)

**Additional context**
I'm using kepler.gl@1.1.1

**Comment by heshan0131** [comment]
You are right, the `theme` used on histogram bar is not from the `theme` context, but from directly import `theme` object (https://github.com/keplergl/kepler.gl/blob/master/src/components/common/range-plot.js#L31). That's why changing the theme passed to `KeplerGl` prop did not affect the bars. I will make a PR to

**Comment by vladimir-kondratenko** [comment]
Thanks. Sorry to bother with such small issue, I wanted to create PR by myself but I have strange problems with dev setup.

**Comment by heshan0131** [comment]
👍 merged into master, will be available in the next release
