### ISSUE TITLE
Load dynamic data with the dynamic kepler.gl configuration

### ISSUE THREAD

**Issue by trietphan94** [keplergl/kepler.gl#605]
I store the Kepler.gl configuration as a template. I already have Kepler.gl data from the server and I want to synchronize the data and configuration above. But it seems the data and configuration are different about `id`. Do we have a way to synchronize them? Thanks.

**Comment by heshan0131** [comment]
Do you know what `dataId` is in your config template? If you saved the dataId, you can call `addDataToMap` passing the same id and data from the server

```
const dataId = 'saved_id'
  addDataToMap({
    datasets: {
      info: {
        label: '',
        id: 'dataId
      },
      data: sampleTripData
    },
    option: {
      centerMap: true,
    },
    config: configTemplate
  })
```
