### ISSUE TITLE
Community Server

### ISSUE THREAD

**Issue by derek-nascent** [keplergl/kepler.gl#612]
Is there a community Dischord server or something like that? I'd love to be able to interact with the community in real time.

**Comment by heshan0131** [comment]
We have a slack room for core developers and some beta testing users. Would you like to join that?

**Comment by derek-nascent** [comment]
That would be awesome. Thanks for the invite.

**Comment by shishirmehto** [comment]
Hi @heshan0131  
I am currently working on Kepler and actively using it. It would be great to stay in touch with the developer community. Do let me know how I can get an invite for the slack room.
Thanks,
Shishir

**Comment by heshan0131** [comment]
Yes, what's your email address?

**Comment by shishirmehto** [comment]
it's shishir.mehto@gmail.com, thank you

**Comment by matheusmonte** [comment]
Hi @heshan0131 Can you invite me too? my slack email is clark.monte1@gmail.com

**Comment by derek-nascent** [comment]
is there a way I can give you my email privately and not on the open web?

**Comment by heshan0131** [comment]
@derek-nascent you can use [this invite link](https://join.slack.com/t/kepler-gl/shared_invite/enQtNzAyMTEzMzAyNDMzLWRkN2FkYTU4ODVmZGMzMDQ2Mjg4NWQyYTg1MzkxM2I1M2FmYzBiNzE2ZTYwM2M4ZDJmMzIzNTU1YWYwNDU3ZDM). it expires on 30 days
