### ISSUE TITLE
don't show null for labels if there is no data

### ISSUE THREAD

**Issue by djouallah** [keplergl/kepler.gl#614]
i have 65K points, but I want to show labels only for some points, kepler show null if there is no labels, which is problematic 
![image](https://user-images.githubusercontent.com/12554469/61349492-ab646900-a8a7-11e9-84e4-a1c37996f3f5.png)

**Comment by heshan0131** [comment]
I will look into this

**Comment by heshan0131** [comment]
This should be fixed and deployed to demo app
