### ISSUE TITLE
Custom tooltip

### ISSUE THREAD

**Issue by MosheMalin** [keplergl/kepler.gl#616]
Is there a way to get an handle to the event that raises the tooltip, in order to provide a custom tooltip instead? 
Alternatively, is there a way to add html elements to the tooltip or to otherwise customize it?

Thanks!

**Comment by kunalganglani** [comment]
+1

**Comment by bskrt** [comment]
Related to this, some more clarifications on how to use the ``onLayerClick, onMapClick, ...`` visStateActions would be nice.

**Comment by heshan0131** [comment]
You can replace `MapPopoverFactory` to implement your own tooltip. Here is the source code https://github.com/keplergl/kepler.gl/blob/master/src/components/map/map-popover.js#L84

**Comment by MosheMalin** [comment]
Thank you! 
checking it.

**Comment by MoRadwan74** [comment]
@heshan0131 How to pass the props to `MapPopoverFactory` function?
