### ISSUE TITLE
How override color to 3D Building layer ?

### ISSUE THREAD

**Issue by eportico** [keplergl/kepler.gl#630]
Hi, I created new style in mapbox studio. I have customized color in building layer, but in kepler.gl, this layer is same color always. I think that the color depend of theme. In light theme I can see good definitons for buildings, but in dark theme, I can`t see good visualization of buildings.

How I can override this building color ?

**Comment by heshan0131** [comment]
building color is based on background color of the style by default.
Added a 3d building color editor
https://github.com/keplergl/kepler.gl/pull/633

**Comment by macrigiuseppe** [comment]
Going to close this one since the feature is now available
