### ISSUE TITLE
Reset the mapbox.gl style

### ISSUE THREAD

**Issue by GloriaCHL** [keplergl/kepler.gl#631]
**Is your feature request related to a problem? Please describe.**
Can I change mapbox style url in kepler.gl?
Like this in mapboxgl:
```
var map = new mapboxgl.Map({ 
            container: 'map', // container id 
            style: 'http://****',        
            center: [104.13689, 33.96498], // starting position [lng, lat] 
            zoom: 9 // starting zoom 
        }); 
```

or how can I do it in any other way?

**Comment by heshan0131** [comment]
you can add custom map style
https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/f-map-styles/3-custom-styles.md

**Comment by GloriaCHL** [comment]
> you can add custom map style
> https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/f-map-styles/3-custom-styles.md

Thank you for your help, it work for me. And, can I change the map engine? I don't want to use Mapbox, I want openstreet

**Comment by macrigiuseppe** [comment]
> > you can add custom map style
> > https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/f-map-styles/3-custom-styles.md
> 
> Thank you for your help, it work for me. And, can I change the map engine? I don't want to use Mapbox, I want openstreet

@GloriaCHL we currently support only Mapbox
