### ISSUE TITLE
When add add to map by selecting a map demo, Map Display is blank

### ISSUE THREAD

**Issue by theseusyang** [keplergl/kepler.gl#635]
When starting Kepler Server, After adding data to map , then find Map Display is blank.

**Comment by theseusyang** [comment]
![image](https://user-images.githubusercontent.com/863136/61930135-7646cd80-afaf-11e9-9a01-56ab6aa7d5cf.png)

the result is:

![image](https://user-images.githubusercontent.com/863136/61930157-89f23400-afaf-11e9-843c-a3854c0bdf30.png)

**Comment by macrigiuseppe** [comment]
@theseusyang it looks like you are missing the mapbox token in order to run kepler.gl.

Before you start Kepler.gl in the same console window fo the following:
```bash
export MapboxAccessToken=<insert_your_token>
```

**Comment by heshan0131** [comment]
closing it for now, waiting for more response
