### ISSUE TITLE
Data not being displayed in the map

### ISSUE THREAD

**Issue by mmo84** [keplergl/kepler.gl#636]
**Describe the bug**
I have a very simple CSV file including project code, project title, project description, sector, latitude and longitude. I would like these projects to appear on the map, but when I load my data in kepler, nothing is displayed on the map. I saw some related issues, but I am not a coder at all and I don't what geometry collection means ... I would really be grateful if someone could translate the solution in a way that I can understand :)

**To Reproduce**
I just loaded this data but in CSV format: 
[Geolocalisation projets AS -Test - Copie.xlsx](https://github.com/keplergl/kepler.gl/files/3435255/Geolocalisation.projets.AS.-Test.-.Copie.xlsx)

And nothing happens basically... I tried to add a layer but the following happears: 
![image](https://user-images.githubusercontent.com/53336272/61943562-ff540980-af9b-11e9-9d54-e26fb72dfd94.png)
And it seems that I cannot select the "column" which corresponds to latitude or longitude... 

Once again many thanks in advance for your help on this :)

**Comment by erickndava** [comment]
I opened the file you attached, exported it as CSV and then loaded into Kepler.gl.

The points data displays fine and Kepler even auto-loads it as points (No need to specify Lat*, Lng*

![sample](https://user-images.githubusercontent.com/5484204/61946742-a8eac900-afa3-11e9-8a8f-633ae23508c6.PNG)

Maybe this is related to your Browser?

The CSV file I used is attached

[Geolocalisation_test2.zip](https://github.com/keplergl/kepler.gl/files/3435392/Geolocalisation_test2.zip)

**Comment by mmo84** [comment]
Many thanks for your quick feedback ! 
It's weird because when I upload the same file, I get : 
![image](https://user-images.githubusercontent.com/53336272/61947844-92923c80-afa6-11e9-94e7-71ddff77bf93.png)
I tried with Mozzila firefox and with google chrome but I get the same result with both browser ....

**Comment by mmo84** [comment]
Ah no when I try with your file, it's working... maybe my issue is when converting my excel file to CSV ? How did you proceed ?

**Comment by erickndava** [comment]
Great you have it working along the way atleast.

From your excel file I **_Saved As_**, then chose CSV under **_Save as type_**. 

![File Export](https://user-images.githubusercontent.com/5484204/61948513-4c3ddd00-afa8-11e9-896b-ca119a41bbe2.PNG)

My guess it that other csv type options give rise to issues.

**Comment by mmo84** [comment]
I did the same but it does not work... And actually when I open your file, it does look like a CSV file whereas mine still look like a table ...

**Comment by erickndava** [comment]
Sometimes MS Excel has a way of adding unwanted characters to data.(I used Excel 2016) As an alternative you can try and export your CSV using OpenCalc of the OpenOffice suite - https://www.openoffice.org/

**Comment by macrigiuseppe** [comment]
Confirmed the Excel file is being displayed correctly once converted to CSV.

Closing this one

**Comment by nazatreka** [comment]
Hi, I have the same issue as the original poster, I have convert the file correctly to .csv.
[AADT.xlsx](https://github.com/keplergl/kepler.gl/files/5501350/AADT.xlsx)

but the map does not show anything. I have tried running in on another form of spreadsheet-like  open office, but still the same.
![image](https://user-images.githubusercontent.com/70991155/98369256-9b136700-2073-11eb-9002-933a0805d7e4.png)

I have no clue what went wrong.
