### ISSUE TITLE
Rotate mapbox token in exported HTML

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#638]
To avoid miss-use we are going to invalidate our old token in exported html.

Please refer to [this giude](https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/k-save-and-export.md#how-to-update-an-exported-map-token) to update to your own mapbox token in exported HTML map

**Comment by macrigiuseppe** [comment]
Mapbox token has been update in netlify.
At the next production deployment the token will be available to users.
