### ISSUE TITLE
[Bug] Logic issue in Layer.registerVisConfig preventing custom boolean properties

### ISSUE THREAD

**Issue by Harrisandwich** [keplergl/kepler.gl#644]
**Describe the bug**
I'm creating a custom layer that has two boolean visConfig props, but they aren't getting registered while default layers seem to use boolean types just fine. When debugging I noticed this `if` statment:

```javascript
   if (
        typeof item === 'string' &&
        LAYER_VIS_CONFIGS[layerVisConfigs[item]]
      ) {
        // if assigned one of default LAYER_CONFIGS
        this.config.visConfig[item] =
          LAYER_VIS_CONFIGS[layerVisConfigs[item]].defaultValue;
        this.visConfigSettings[item] = LAYER_VIS_CONFIGS[layerVisConfigs[item]];
      } else if (
        ['type', 'defaultValue'].every(p => layerVisConfigs[item][p])
      ) {
        // if provided customized visConfig, and has type && defaultValue
        // TODO: further check if customized visConfig is valid
        this.config.visConfig[item] = layerVisConfigs[item].defaultValue;
        this.visConfigSettings[item] = layerVisConfigs[item];
      }
```

It seems that default visConfig props get loaded correctly because of the first condition, since you only pass a string to define them. However, if a custom prop with a `defaultValue` of `false` gets checked by the second condition, it doesn't get registered because it evaluates to false. This is a simple falsey logic issue that could likely be fixed by changing the condition to `['type', 'defaultValue'].every(p => layerVisConfigs[item][p] !== undefined)`

**To Reproduce**
1. Add a custom boolean visConfig prop to a new or existing layer
2. Set the `defaultValue` to `false`
3. View the visConfig of the layer either from redux devtools or a console.log call
4. You will notice the custom boolean prop is missing

**Comment by heshan0131** [comment]
looks about right, or use `layerVisConfigs[item].hasOwnProperty(p)`

Wanna open a one-line PR with this?

**Comment by Harrisandwich** [comment]
Can do!

**Comment by macrigiuseppe** [comment]
closing because merged in master
