### ISSUE TITLE
Publish kepler.gl jupyter to JupyterLabs

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#651]
Related issues:

https://github.com/keplergl/kepler.gl/issues/570
https://github.com/keplergl/kepler.gl/issues/331#issuecomment-507775765
https://github.com/keplergl/kepler.gl/issues/583

**Comment by Koushik95** [comment]
@heshan0131 - just wanted to know if you had any update on this? An ETA of any kind? Thanks.

**Comment by sergiolucero** [comment]
Maybe we should offer a bounty. I feel a big chunk of the python
geoplotting world is holding their breath for this one.

**Comment by n0012** [comment]
+1
Really would love this working in Jupyterlab.  I tried to follow saulshanabrook@ custom build, but didn't get it to compile.  Seems with all the managed JupyterLab environments hitting the market, this will be a more and more asked for feature.   Any word on ETA?

**Comment by nateraluis** [comment]
+1
It would be great to have Kepler working with jupyterlab

**Comment by itamar-otonomo** [comment]
+1

**Comment by heshan0131** [comment]
Just published `keplergl-jupyter` for jupyter labs
try
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager keplergl-jupyter
```

Require jupyterLab > 1
