### ISSUE TITLE
How to translate into Chinese?

### ISSUE THREAD

**Issue by cosunj** [keplergl/kepler.gl#653]
Hi, I want to translate into Chinese. How can I do this? Thank you

**Comment by heshan0131** [comment]
You want to help us translate our UI to chinese?

**Comment by heshan0131** [comment]
We could use this to provide localization service in our demo-app
https://www.npmjs.com/package/react-localization

**Comment by Joonalai** [comment]
I would like to translate Kepler to finnish. Is [react-localization(https://www.npmjs.com/package/react-localization) still considered the best tool for this?

**Comment by cartolover** [comment]
I want to translate in Italian!
Can I help?

**Comment by Joonalai** [comment]
@cartolover localization is implemented in #994 and after that it would be easy to add additional languages.

**Comment by macrigiuseppe** [comment]
refer to #970

**Comment by macrigiuseppe** [comment]
> I want to translate in Italian!
> Can I help?

Feel free to add Italian as supported language

**Comment by goldbergrvd** [comment]
What is the process of this issues? I need Chinese language.
