### ISSUE TITLE
Error when trying to export image in kepler.gl

### ISSUE THREAD

**Issue by ceturner22** [keplergl/kepler.gl#656]
**Describe the bug**
When trying to export an image in kepler.gl I am getting a blank image with the error 'arrChildren is not defined' where the data should be showing. The same issue is happening in Chrome and Firefox browsers.

**Screenshots**
![image](https://user-images.githubusercontent.com/53747080/62451072-73916880-b765-11e9-87f6-56fc0ff08c86.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome & Firefox
- Version: 75.0.3770.100 & 68.0

**Comment by heshan0131** [comment]
This is not related to createRef
This has been fixed in prod
