### ISSUE TITLE
Create an Example node based app

### ISSUE THREAD

**Issue by varunsharma27** [keplergl/kepler.gl#664]
**Is your feature request related to a problem? Please describe.**
So I recently ran into this issue with integrating kepler.gl to a Node based app. The issue was mainly because of `d3-request` and fixed by tweaking webpack configuration. [Solution](https://github.com/d3/d3-request/issues/24#issuecomment-364168377)

**Describe the solution you'd like**
Create a simple app with express + react + webpack (for build) + babel. And that should be representative enough for a basic node app.

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/issues/654

**Comment by macrigiuseppe** [comment]
PR: https://github.com/keplergl/kepler.gl/pull/704
