### ISSUE TITLE
Items placed on non-80 port can not be accessed? How to configure it?

### ISSUE THREAD

**Issue by luanwei** [keplergl/kepler.gl#675]
Packed files can only run on port 80, otherwise they cannot be accessed.

**Comment by heshan0131** [comment]
Can you describe what you are trying to do? the webpack config in the demo-app uses default port, which is 8080. You can change the webpack dev server to run on other port

https://webpack.js.org/configuration/dev-server/#devserverport

**Comment by luanwei** [comment]
> Can you describe what you are trying to do? the webpack config in the demo-app uses default port, which is 8080. You can change the webpack dev server to run on other port
> 
> https://webpack.js.org/configuration/dev-server/#devserverport
The packaged bundle. js and index. js can not be displayed on the server's non-80 port. Does secondary packaging result? Need this configuration?

**Comment by luanwei** [comment]
> Can you describe what you are trying to do? the webpack config in the demo-app uses default port, which is 8080. You can change the webpack dev server to run on other port
> 
> https://webpack.js.org/configuration/dev-server/#devserverport

The packaged bundle. js and index.html can not be displayed on the server's non-80 port. Does secondary packaging result? Need this configuration?

**Comment by macrigiuseppe** [comment]
> > Can you describe what you are trying to do? the webpack config in the demo-app uses default port, which is 8080. You can change the webpack dev server to run on other port
> > https://webpack.js.org/configuration/dev-server/#devserverport
> 
> The packaged bundle. js and index.html can not be displayed on the server's non-80 port. Does secondary packaging result? Need this configuration?

I am not sure if I completely understood your description but if you are trying to serve both bundle.js and index.html through some sort of webserver, you need to look at your webserver configuration.
Webpack-dev-server is only used for development.

**Comment by luanwei** [comment]
> > > Can you describe what you are trying to do? the webpack config in the demo-app uses default port, which is 8080. You can change the webpack dev server to run on other port
> > > https://webpack.js.org/configuration/dev-server/#devserverport
> > 
> > 
> > The packaged bundle. js and index.html can not be displayed on the server's non-80 port. Does secondary packaging result? Need this configuration?
> 
> I am not sure if I completely understood your description but if you are trying to serve both bundle.js and index.html through some sort of webserver, you need to look at your webserver configuration.
> Webpack-dev-server is only used for development.

I want to deploy it on the server
