### ISSUE TITLE
[Bug] Base maps (Light, Muted Light) are not loading. Getting errors 404 (Not Found) with tile images while running the project locally.

### ISSUE THREAD

**Issue by dev1165** [keplergl/kepler.gl#690]
**Describe the bug**
Base maps (Light, Muted Light) are not loading. Getting errors 404 (Not Found) with tile images while running the project locally.

**To Reproduce**
1. Go to 'Base Map (tab) >Map style'
2. Click on 'Light, Muted Light'
3. Browser Console 
4. See error 404(Not Found)

**Expected behavior**
All map should load properly without showing any error 
**Screenshots**
![image](https://user-images.githubusercontent.com/54061575/63249396-09a9b080-c287-11e9-98e8-1c99be4f927e.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS 10.14.6]
 - Browser :chrome
 - Version [Version 76.0.3809.100 (Official Build) (64-bit)]]

**Comment by macrigiuseppe** [comment]
it should be fixed
