### ISSUE TITLE
[Bug] : error while initializing ClusterLayer({id: 'qujpxk9'})  TypeError: kdbush is not a function

### ISSUE THREAD

**Issue by abhisek2713** [keplergl/kepler.gl#693]
**Describe the bug**
Facing error while clustering a copy of keplerJS in local:
error while initializing ClusterLayer({id: 'qujpxk9'})
 TypeError: kdbush is not a function

**To Reproduce**
1. Copy kepler.gl into local, load it with a default csv and config.
2. Open console.
3. Change the Source layer type to be cluster. It doesn't cluster.
4. See error in console.

**Expected behavior**
The data should be clustered and there should not error message in the clusters.

**Screenshots**
![image](https://user-images.githubusercontent.com/45587119/63348333-a5661a00-c376-11e9-862c-1bb6ccfd4e0e.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS 10.14.6]
 - Browser: chrome
 - Version :[Version 76.0.3809.100 (Official Build) (64-bit)]]

**Comment by macrigiuseppe** [comment]
this should be fixed
