### ISSUE TITLE
[Bug] Inconsistent version numbers on PyPI and GitHub 

### ISSUE THREAD

**Issue by deeplook** [keplergl/kepler.gl#694]
While debugging some KeplerGl behavior I found out that I have 0.1.0a from PyPI installed (via pip), see https://pypi.org/project/keplergl/#history, which claims to have been the latest and uploaded on Aug, 6th, while https://github.com/keplergl/kepler.gl/releases says it's 1.1.3 from Aug, 5th. This is pretty confusing. This is on 2019-08-21.

**Comment by deeplook** [comment]
Now I see that 0.1.0a comes from https://github.com/keplergl/kepler.gl/blob/master/bindings/kepler.gl-jupyter/keplergl/_version.py, and likely refers only to the Jupyter notebook binding. This might still cause some confusion and maybe it would be helpful to point out in the docs the different version numbers used.

**Comment by macrigiuseppe** [comment]
@deeplook given several differences in feature between jupyter widget and npm library we are not planning on keeping them in sync
