### ISSUE TITLE
OpenStreetMaps Integration

### ISSUE THREAD

**Issue by rhaegar453** [keplergl/kepler.gl#698]
Can I integrate OpenStreetMaps with Kepler.gl instead of Mapbox. I already have an OSM server and I want to run Kepler.gl on top of that map. Please let me know if that is a possibility

**Comment by laurids-reichardt** [comment]
Depends on what kind of OSM server you're running. Kepler.gl uses Mapbox GL JS to display the base map, which in turn renders mapbox vector tiles. The OpenMapTiles project offers a convenient solution to convert OSM data to mapbox vector tiles. For a very simple solution you could run [TileServer GL](https://openmaptiles.org/docs/host/tileserver-gl/) an your server and paste the resulting style URL (e.g. http://localhost:8080/styles/osm-bright/style.json) inside kepler.gl as a custom map style.

**Comment by rhaegar453** [comment]
@laurids-reichardt  Thanks man
