### ISSUE TITLE
[Bug] Can't able to load data from Bigquery.

### ISSUE THREAD

**Issue by syedzubair-dev** [keplergl/kepler.gl#701]
Trying to load data from the big query. I have done the environment variable setup for google app credentials and also loaded the external module in the webpack-dev-server config part.

![image](https://user-images.githubusercontent.com/44016150/63803909-94e40f80-c933-11e9-9268-2e0ad9393571.png)

![image](https://user-images.githubusercontent.com/44016150/63803946-b04f1a80-c933-11e9-87b4-649e6e3705be.png)

**Comment by macrigiuseppe** [comment]
@syedzubair-dev based on your description and screenshots it looks like there is an issue with google auth library. 
Please take a look here: https://github.com/googleapis/google-auth-library-nodejs/issues/150
