### ISSUE TITLE
"Load data" pop-up appears when loading heavy html file [Bug]

### ISSUE THREAD

**Issue by guyts** [keplergl/kepler.gl#702]
**Describe the bug**
After exporting a map to HTML (html file size is approx. 15-30MB, depends on the data sets, but all cause the bug), loading the html page outside of kepler (new browser session for example), causes the `Add Data To Map` window to pop-up, although the data was part of the export. The window disappears after a few seconds, and the visual loads properly, but when publishing a visual online, this is an issue.

**To Reproduce**
Load a data set into Kepler (preferably one that's over 15MB
Build your visual
Export to HTML
Load the HTML in a new session elsewhere

**Expected behavior**
The visual loads where the first view is the map, and after a reasonable loading time, the data displayed on the map.

**Screenshots**
The window for the first few seconds:
![image](https://user-images.githubusercontent.com/16499234/64042705-81ea5e80-cb30-11e9-8588-24cdbcd6a305.png)

**Desktop (please complete the following information):**
 - OS: Win10 Home
 - Browser Chrome 75, Firefox

**Comment by djouallah** [comment]
Yes,  happen to me too

**Comment by macrigiuseppe** [comment]
@guyts @djouallah can you please provide a dataset to use as test case to reproduce the issue?

thank you

**Comment by djouallah** [comment]
I don't know what happen, today, I can't reproduce it.

**Comment by guyts** [comment]
@macrigiuseppe see attached a sample html file (open it to see what I mean. Note that even if it requests a mapbox token, you can still see the 'load data' window pop up).
Also, attached the with the data in this kepler visual.

[kepler_issues.zip](https://github.com/keplergl/kepler.gl/files/3569683/kepler_issues.zip)

**Comment by macrigiuseppe** [comment]
I see the issue. Based on the size of data we try to load there may be a delay in hiding the initial add data dialog box.
This is not high priority but we will keep it in our backlog as reference and will provide updates.

**Comment by pctnumbers2017** [comment]
I'm having this same problem on http://www.longtrailsmap.net/pct/elevation, but the dataset is only 2.6 megs.

Is there a fix I can implement w/o being familiar w/ React?

Kepler is an amazing tool, but for users with connections that take several seconds to load the page, being met with a large 'Add data" dialog and nothing else on page load is not a great experience.

Thanks!

**Comment by pctnumbers2017** [comment]
The entire html file is now 1.4m, same problem occurs.

**Comment by macrigiuseppe** [comment]
@macrigiuseppe  keplerGl: keplerGl.keplerGlReducer.initialState({
                uiState: {
                  readOnly: false,
     currentModal: null
                }
              })
