### ISSUE TITLE
Split Map - getMapboxRef

### ISSUE THREAD

**Issue by Goondrious** [keplergl/kepler.gl#710]
**Is your feature request related to a problem? Please describe.**
When using the split-map feature, it would be ideal to easily access and monitor the `mapboxRefs`.  I'm working on a map that uses multiple datasets and I think something is getting lost in translation with the multiple refs.

**Describe the solution you'd like**
An exposed callback when `isSplit` is toggled or a further guarantee of the interaction between the two mapbox refs. Currently `getMapboxRef` seems to only show when a ref is initialized, but not enough detail about which ref it is.

**Describe alternatives you've considered**
Inferring which ref I have using `getMapboxRef` or Kepler's internal state, but couldn't think of a way to do so.

**Comment by Harrisandwich** [comment]
I found that because a new MapContainer was mounting, it was calling the getMapboxRef callback again, overwriting the first one. I worked around this issue by checking if my mapbox ref variable was already set and if so, setting the new ref to a splitMapRef variable. I then sent that variable to all the places the initial ref was sent and called all the necessary functions on the new ref alongside the old one.

**Comment by robert-claypool** [comment]
The `getMapboxRef` callback sends 0 or 1 for the second parameter, `index`. That should tell you if the ref points to the "original" or "split" map.

> This simplifies the handling of getMapboxRef so that KeplerGL forwards your callback function to MapContainer unchanged. It also adds support for multiple maps. Use 'index' (0 or 1) to identify which map triggered the callback. If 'mapbox' is null, then that map has been removed by toggleSplitMap. - https://github.com/keplergl/kepler.gl/commit/5975a95f6f

Also note that the callback will send a `null` ref if the split map is being closed.

Does that help?

**Comment by Harrisandwich** [comment]
> The `getMapboxRef` callback sends 0 or 1 for the second parameter, `index`. That should tell you if the ref points to the "original" or "split" map.
> 
> > This simplifies the handling of getMapboxRef so that KeplerGL forwards your callback function to MapContainer unchanged. It also adds support for multiple maps. Use 'index' (0 or 1) to identify which map triggered the callback. If 'mapbox' is null, then that map has been removed by toggleSplitMap. - [5975a95](https://github.com/keplergl/kepler.gl/commit/5975a95f6f)
> 
> Also note that the callback will send a `null` ref if the split map is being closed.
> 
> Does that help?

Oh nice! That does help quite a bit! Thanks a bunch :)

**Comment by heshan0131** [comment]
Thanks @Harrisandwich !close
