### ISSUE TITLE
Use a custom image as a map?

### ISSUE THREAD

**Issue by FrBLD** [keplergl/kepler.gl#712]
Hello,

I discovered few days ago this kepler.gl and it's awesome! I tested to it with a data sample and directly with custom poly form to create a 'game map'.

But I don't find how to 'import' a custom image of a game level as a map. As example, I have a map 1000*1000 pixel, and I have in my data all players positions. I would like to display these data in my game map.

Is there a way? Don't find anything in mapbox too..

Regards

**Comment by robert-claypool** [comment]
Try getting a ref to your `<KeplerGl>` Mapbox Map instance. This provides full access to [MapboxGL's API](https://docs.mapbox.com/mapbox-gl-js/api/#map). I'm not sure how to make the Map load your static image, but I believe their API supports it.

```JSX
_getMapboxRef = (mapbox, index) => {
  if (!mapbox) {
    // The ref has been unset.
    // https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
    // console.log(`Map ${index} has closed`);
  } else {
    // We expect an InteractiveMap created by KeplerGl's MapContainer.
    // https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map
    const map = mapbox.getMap();
    // TODO: Add your image
  }
};

// In your render function ...
<KeplerGl getMapboxRef={this._getMapboxRef} />
```

**Comment by heshan0131** [comment]
Closing it for now
