### ISSUE TITLE
[Bug], regression  Export to HTML. the generated file stopped working since 1.1.6

### ISSUE THREAD

**Issue by djouallah** [keplergl/kepler.gl#716]
when I export to html, the exported html does not open (empty), when I change the reference to 1.1.5, it works fine
![image](https://user-images.githubusercontent.com/12554469/64400315-2596ba00-d0af-11e9-9979-859d79b753e2.png)

**Comment by mjp92067** [comment]
Same exact issue here

**Comment by macrigiuseppe** [comment]
@djouallah can you share more details about your issue?
OS, Browser

Is the same bug happening on the demo site http://kepler.gl?

Unfortunately I am not able to reproduce the issue on Mac os and Chrome

**Comment by djouallah** [comment]
demo site works fine

windows 10, chrome , for now, I manually edit the html file to change the link to 1.1.5

**Comment by djouallah** [comment]
very strange, i generate a new map today and it did work, thanks for whatever you did

**Comment by djouallah** [comment]
I am going to close it as it stopped happening
