### ISSUE TITLE
feat request U.S. zip code mapping

### ISSUE THREAD

**Issue by jawz101** [keplergl/kepler.gl#718]
**Is your feature request related to a problem? Please describe.**
source location data type

**Describe the solution you'd like**
It would be nice to be able to have U.S. zip code recognition.  This would expand the tools use significantly for systems that don't collect geo coordinates.  Country codes, area codes, and IP addressing would also be nice as well. (There are public data sets for a lot of these things)

**Describe alternatives you've considered**
Replacing zip codes in my source data with a lat/long in the center of each zip code.

**Comment by heshan0131** [comment]
Yes it would. However, all zipcode mapping services are for profit. We can't find an open zip code geo provider (if you know of any, let us know). Talked to Mapbox before,  their enterprise account holder will have access to more spatial dataset including zip cond, state, county and census tract boundaries, we can connect with that, but you would have to have a more premium mapbox account.

**Comment by jawz101** [comment]
Thank you.  I was able to download some shp files for use in [QGIS ](https://qgis.org/en/site/) earlier this week from the United States Census Bureau .  They say they are intended for public use.  It also looks like they have files for legislative districts, school districts, railways, hydro

a few links
https://www.census.gov/programs-surveys/geography.html
https://catalog.data.gov/dataset/zip-codetabilation-area-boundaries
https://www.census.gov/cgi-bin/geo/shapefiles/index.php
https://www2.census.gov/geo/tiger/TIGER2019/

**Comment by scivm** [comment]
I use open postal codes from https://download.geonames.org/export/zip/.  They have about 90 countries.
