### ISSUE TITLE
[Bug] oldLayer.updateLayerConfig is not a function

### ISSUE THREAD

**Issue by jofri99** [keplergl/kepler.gl#731]
**Describe the bug**
When I try to dispatch the layerVisConfigChange action to the props, I get an error that updateLayerConfig is not a function.

**To Reproduce**
1. Call the the following function (with your Layer):
```js
this.props.dispatch(layerVisConfigChange(this.state.config.config.visState.layers[0],{thickness:1.0}));
```
2. Go to the console and see error

**Expected behavior**
thickness should be updatet to 1.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chromium
 - Version: 1.1.7

**Comment by heshan0131** [comment]
The `oldLayer` should be the actual layer stored kepler.gl's state. It is a class that has inherited methods. You should call it

`this.props.dispatch(layerVisConfigChange(this.state.keplerGl.map.visState.layers[0],{thickness:1.0}));`

**Comment by jofri99** [comment]
Yea, thanks that was the problem.
