### ISSUE TITLE
Memory leak when I pack kepler as a node module

### ISSUE THREAD

**Issue by RinaB** [keplergl/kepler.gl#734]
Hi,

I want to create my custom closed component based on kepler and the use it in another app.
I packed my component that used kepler to an npm module. (with npm pack)
Then when I import it in another react app: 
`import MyWrapper from 'demo-app';`
It fails with :

**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**

I also tried to pack demo-app under examples and use it as node-module and I get same results.

Can you help me?
Thanks

**Comment by heshan0131** [comment]
It's hard to know what exactly is going on with just a error msg, is your module somewhere we can access?

**Comment by RinaB** [comment]
I packed custom-theme example. (I changed only the package.json and main.js)
[custom-theme](https://github.com/RinaB/kepler-error)
See: custom-theme-1.0.0.tgz
Then when I install it on another new fresh react- app and use it :
`import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

import * as serviceWorker from './serviceWorker';
import  Root from 'custom-theme';
import App from "./App";

ReactDOM.render(<Root />, document.getElementById('root'));

serviceWorker.unregister();
`
I get the memory leak error or the following error:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by heshan0131** [comment]
You are not rendering an actual React Component. 

shouldn't it be:
```
ReactDOM.render(App, document.getElementById('root'));
```

**Comment by RinaB** [comment]
I render it.  It was escaped somehow when I posted it in this site.  
I use :
ReactDOM.render(<Root/> , document.getElementById('root'));
Please try to run my example.

**Comment by heshan0131** [comment]
Looks to me your `Root` component is not exported from `custom-theme`. in your `main.js` in `kepler-error` repo. you should:
```
const Root = () => (
  <Provider store={store}>
    <App />
  </Provider>
);

export default Root;
```

**Comment by RinaB** [comment]
I added it, but I get the same error.
FYI, when I put in that component something else, like: simple div, it works correctly.

**Comment by RinaB** [comment]
I see that if I add:
``` libraryTarget:'umd'``` to webpack.config it solves it
Thank you!
