### ISSUE TITLE
Adding a input box for animation speed specification

### ISSUE THREAD

**Issue by garychowcmu** [keplergl/kepler.gl#740]
**Is your feature request related to a problem? Please describe.**
When we use the dynamic playing features for time of day, the speed with vertical slide bar is still a bit fast for my project. 

Is it possible to add a box to specify the actual value that we prefer? 

**Describe the solution you'd like**
Is it possible to add a box to specify the actual value that we prefer? Like users are allowed to input any decimal values, such as 0.001

**Describe alternatives you've considered**
Is it possible to add a box to specify the actual value that we prefer? Like users are allowed to input any decimal values, such as 0.001

**Additional context**

**Comment by heshan0131** [comment]
<img width="330" alt="Screen Shot 2019-09-27 at 11 18 00 AM" src="https://user-images.githubusercontent.com/3605556/65792386-7d599b80-e118-11e9-838d-f1ee2f5bda92.png">

But the step right now only allows 0.1

**Comment by garychowcmu** [comment]
Thanks! I tested just now, it supports 0.01 as the input.

**Comment by garychowcmu** [comment]
> <img alt="Screen Shot 2019-09-27 at 11 18 00 AM" width="330" src="https://user-images.githubusercontent.com/3605556/65792386-7d599b80-e118-11e9-838d-f1ee2f5bda92.png">
> 
> But the step right now only allows 0.1

Thanks! I tested just now, it supports 0.01 as the input.
