### ISSUE TITLE
Kepler Feature Request

### ISSUE THREAD

**Issue by apiszcz** [keplergl/kepler.gl#741]
Shen, et al. thank you for all the work
1. GeoTIFF export
2. The time filter animation widget is great and based on very dense data sets. For sparse data sets it would be useful to allow a much wider range of speed up. Some dense data may benefit form a much lower speed interval. I'm seeing 0.5 to 10x, ideally this would 0.00001 to 100000x or similar. Allow user to edit numeric value for rate control, and time interval. For very narrow intervals the horizontal slider widget becomes difficult to adjust. Consider adding seconds and milliseconds to for the time interval text display over the timeline histogram.
3. Time playback, is it possible to synchronize all or a selected group of layers synchronously with the timer filter?
3. PDF export artifact for the user manual and maybe the Roadmap.

**Comment by akuckartz** [comment]
Please avoid generic titles like "Kepler Feature Request" and use one issue per feature request.
