### ISSUE TITLE
Adding Animation Filter Causes Visualization to Vibrate

### ISSUE THREAD

**Issue by jaykinghorn** [keplergl/kepler.gl#747]
**Describe the bug**
I have an arc visualization with ~100k rows of data in it, generated from a pandas data frame in a Jupyter Notebook. A static visualization works correctly, but when I add the time-series filter from a column based on a Unix Timecode, the visualization starts to vibrate uncontrollably, making the visualization unusable. I've reduced the number of rows and the number of columns in case I was sending too much data. I've also tried it in Chrome and Safari, with the same results in each. 

**To Reproduce**
1. Export HTML file from Jupyter Notebook
2. Set Map options within browser (Arc type, Color based on MSA column)
3. Add filter on Unix VisitStartDate

**Expected behavior**
Animation window will appear and allow visualization to animate based on time series values. 

**Screenshots**

**Environment (please complete the following information):**
 - Python version: Python 3.7.3
 - keplergl Widget version keplergl==0.1.0a8

**Additional context**
I haven't had this problem outputting similarly sized files in the past. 

Thanks!
[Hattiesburg3.html.zip](https://github.com/keplergl/kepler.gl/files/3649817/Hattiesburg3.html.zip)

**Comment by heshan0131** [comment]
#592

**Comment by heshan0131** [comment]
`keplergl==0.1.0a9` is published, can you give it a try?
