### ISSUE TITLE
[Bug] Rendering artifacts when using an H3 layer and hexagons reach the edge of the map canvas

### ISSUE THREAD

**Issue by qscripter** [keplergl/kepler.gl#754]
**Describe the bug**
When rendering an H3 dataset using the h3_id column of a csv, the H3 hexagons at the map edges exhibit rendering effects where horizontal lines appear.

**To Reproduce**
1. add a dataset using H3 to kepler
2. pan around the map so that cells reach the map edge

**Expected behavior**
Hexagons do not create horizontal lines when they reach map edge.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser bug tested on Firefox, Safari, and Chrome

**Additional context**
It's possible that this bug is an artifact of the H3 Javascript libraries, which seem to re-create this bug when used to create GeoJSON, but I figured I would start here

<img width="811" alt="Screen Shot 2019-09-30 at 2 23 17 PM" src="https://user-images.githubusercontent.com/3092244/65905100-e9910500-e38d-11e9-85ad-739ca91e4a9c.png">

**Comment by qscripter** [comment]
[sample_h3.csv.zip](https://github.com/keplergl/kepler.gl/files/3672682/sample_h3.csv.zip)

**Comment by macrigiuseppe** [comment]
@Pessimistress can you please look into this?

**Comment by heshan0131** [comment]
Merged fixes, please confirm, closing it now
