### ISSUE TITLE
Timeline Toggle stops animation

### ISSUE THREAD

**Issue by sevkibaba** [keplergl/kepler.gl#759]
Hello guys, this is a wonderful product, very good job!

I want to make animation going when the timeline is toggled. Right now we are using enlargeFilter action to toggle back the timeline.

When the timeline is closed the animation stops as default behavior, but we want it to keep playing the animation. Is there a way to do that?

Thanks in advance.

**Comment by macrigiuseppe** [comment]
Hey @sevkibaba, you can take advantage of Kepler.gl plugin features and override the toggle action behavior.

You can find some info here: https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/advanced-usages/reducer-plugin.md

We have an example available that takes advantage of the same feature and you can find it here: https://github.com/keplergl/kepler.gl/blob/master/examples/custom-reducer/src/store.js
