### ISSUE TITLE
Increase upload limit

### ISSUE THREAD

**Issue by itch96** [keplergl/kepler.gl#76]
I am trying to upload 540 MB of data. Chrome won't support but it throws no error. Safari crashes and reloads the web page. Firefox too won't load the data.

**Comment by heshan0131** [comment]
@itch96 how many rows do you have? is it a csv or geojson? try to limit the size of your data by removing unused properties and columns. The upper limit is usually 250mb

**Comment by matheusmonte** [comment]
Can I get this to solve?

**Comment by yiyaya66** [comment]
We will revisit this after we upgrade to Deck.gl V6.0 where client-side filtering will be more performant

**Comment by quentindurpoix** [comment]
How many lines from a CSV is the limit at this time ?

**Comment by RILUCK** [comment]
@heshan0131  is there any method to increase file size?

**Comment by heshan0131** [comment]
#1156 addresses it. Upload limit has been increase to 1G or as much as the amount of data a browser can handle
