### ISSUE TITLE
uploading json/geojson in demo app not working

### ISSUE THREAD

**Issue by sanderp42** [keplergl/kepler.gl#761]
When I try to upload data in the demo app it just keeps on loading forever. I tried both safari and chrome. Anybody knows what I do wrong?

<img width="1014" alt="Schermafbeelding 2019-10-02 om 19 58 12" src="https://user-images.githubusercontent.com/40459403/66069675-24429b00-e550-11e9-9898-a754fecdab13.png">

**Comment by heshan0131** [comment]
probably because your json is not the right format, can you 
1. open js console and paste an error you see
2. paste a snippet of your json here so we can take a look

**Comment by johachi-dw** [comment]
@heshan0131 

I was just about to report the same problem. The `.csv` format works, but the `.json` format just keeps on loading forever. There are no error messages in the console.

I have tried with Firefox Developers Version (Version 70.0b10 (64-bit)) and Chrome (Version 77.0.3865.90 (Official Build) (64-bit)) on Macbook Pro.

I have tried to remove the Japanese characters in the name without any change.

CSV file:
```csv
category,name,latitude,longitude
school,Route H(ルートエイチ),35.694474,139.759096
school,Z会進学教室 御茶ノ水教室,35.694956,139.767603
```

JSON file:
```json
[
  {
    "category": "school",
    "name": "Route H(ルートエイチ)",
    "latitude": "35.694474",
    "longitude": "139.759096"
  },
  {
    "category": "school",
    "name": "Z会進学教室 御茶ノ水教室",
    "latitude": "35.694956",
    "longitude": "139.767603"
  }
]
```

**Comment by sanderp42** [comment]
Hi Shan, 
As far as I know there are no errors in the console. The geojson I have is quite big and complex so not so easy to share. 

Here is a small bit: 


{"jobName":"Amsterdam","creationTime":"2019-09-01T14:18:37.403Z","userPreference":{"distanceUnit":"KILOMETERS"},"dateRanges":[{"@id":1,"name":"year_2019","from":"2019-01-01","to":"2019-09-01","exclusions":[],"excludedDaysOfWeek":[]}],"timeSets":[{"@id":2,"name":"Timeset 1","dayToTimeRanges":[{"dayOfWeek":"MONDAY","timeRanges":["00:00-07:00","23:00-24:00"]},{"dayOfWeek":"TUESDAY","timeRanges":["00:00-07:00","23:00-24:00"]},{"dayOfWeek":"WEDNESDAY","timeRanges":["00:00-07:00","23:00-24:00"]},{"dayOfWeek":"THURSDAY","timeRanges":["00:00-07:00","23:00-24:00"]},{"dayOfWeek":"FRIDAY","timeRanges":["00:00-07:00","23:00-24:00"]},{"dayOfWeek":"SATURDAY","timeRanges":["00:00-07:00","23:00-24:00"]},{"dayOfWeek":"SUNDAY","timeRanges":["00:00-07:00","23:00-24:00"]}]},{"@id":3,"name":"Timeset 2","dayToTimeRanges":[{"dayOfWeek":"MONDAY","timeRanges":["07:00-10:00"]},{"dayOfWeek":"TUESDAY","timeRanges":["07:00-10:00"]},{"dayOfWeek":"WEDNESDAY","timeRanges":["07:00-10:00"]},{"dayOfWeek":"THURSDAY","timeRanges":["07:00-10:00"]},{"dayOfWeek":"FRIDAY","timeRanges":["07:00-10:00"]},{"dayOfWeek":"SATURDAY","timeRanges":["07:00-10:00"]},{"dayOfWeek":"SUNDAY","timeRanges":["07:00-10:00"]}]},{"@id":4,"name":"Timeset 3","dayToTimeRanges":[{"dayOfWeek":"MONDAY","timeRanges":["10:00-15:00"]},{"dayOfWeek":"TUESDAY","timeRanges":["10:00-15:00"]},{"dayOfWeek":"WEDNESDAY","timeRanges":["10:00-15:00"]},{"dayOfWeek":"THURSDAY","timeRanges":["10:00-15:00"]},{"dayOfWeek":"FRIDAY","timeRanges":["10:00-15:00"]},{"dayOfWeek":"SATURDAY","timeRanges":["10:00-15:00"]},{"dayOfWeek":"SUNDAY","timeRanges":["10:00-15:00"]}]},{"@id":5,"name":"Timeset 4","dayToTimeRanges":[{"dayOfWeek":"MONDAY","timeRanges":["16:00-23:00"]},{"dayOfWeek":"TUESDAY","timeRanges":["16:00-23:00"]},{"dayOfWeek":"WEDNESDAY","timeRanges":["16:00-23:00"]},{"dayOfWeek":"THURSDAY","timeRanges":["16:00-23:00"]},{"dayOfWeek":"FRIDAY","timeRanges":["16:00-23:00"]},{"dayOfWeek":"SATURDAY","timeRanges":["16:00-23:00"]},{"dayOfWeek":"SUNDAY","timeRanges":["16:00-23:00"]}]}],"network":{"networkName":"Amsterdam","zoneId":"Europe/Amsterdam","probeSource":"ALL","mapsVersions":["NorthernEurope+nosplit_TeleAtlasMNR_eur2018.12.004-22.95-1@1547733338"],"segmentResults":[{"segmentId":-15280000018485,"newSegmentId":"-00004e4c-3100-0400-0000-000000042c99","speedLimit":30,"frc":6,"streetName":"Da Costakade","distance":193.7,"shape":[{"latitude":52.3692,"longitude":4.8721},{"latitude":52.36888,"longitude":4.87231},{"latitude":52.36868,"longitude":4.87245},{"latitude":52.36759,"longitude":4.8732}],"segmentProbeCounts":[{"timeSet":2,"dateRange":1,"probeCount":590},{"timeSet":3,"dateRange":1,"probeCount":582},{"timeSet":4,"dateRange":1,"probeCount":1475},{"timeSet":5,"dateRange":1,"probeCount":2056}]},{"segmentId":-15280000863435,"newSegmentId":"-00004e4c-3100-0400-0000-000000043be8","speedLimit":30,"frc":7,"streetName":"Prinseneiland","distance":285.52,"shape":[{"latitude":52.38564,"longitude":4.8866},{"latitude":52.38516,"longitude":4.88655},{"latitude":52.38509,"longitude":4.88655},{"latitude":52.38506,"longitude":4.88655},{"latitude":52.38503,"longitude":4.88656},{"latitude":52.38501,"longitude":4.88659},{"latitude":52.38454,"longitude":4.88744},{"latitude":52.38448,"longitude":4.88755},{"latitude":52.38448,"longitude":4.88756},{"latitude":52.38448,"longitude":4.88758},{"latitude":52.38449,"longitude":4.88761},

**Comment by heshan0131** [comment]
@johachi-dw 
The json file has to be one of 2:

1. A [Geojson Feature Collection](https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md#for-geojson-files)

2. A JSON exported directlyt from kepler.gl using export map as json
