### ISSUE TITLE
[Bug] Demo app can't load external data from URL with queryString params

### ISSUE THREAD

**Issue by matteo-s** [keplergl/kepler.gl#763]
**Describe the bug**
As per title, the demo (https://kepler.gl/demo/) can not load resources from external URLs which contain query string parameters. The loading spinner keeps running forever and the only way to regain control is to reload the whole page.

**To Reproduce**
1. Open '+ Add data' modal 
2. Select 'Load map using URL'
3. Insert an URL with params, for example https://raw.githubusercontent.com/uber-web/kepler.gl-data/master/earthquakes/data.csv?test=123
4. The map never loads, and the console reports the following error

```
bundle.js:55 Uncaught (in promise) TypeError: (0 , e.handler) is not a function
    at bundle.js:55
    at bundle.js:99
    at r (bundle.js:27)
    at s (bundle.js:99)
    at Object.run (bundle.js:27)
    at bundle.js:27
    at Array.map (<anonymous>)
    at bundle.js:27
    at Object.run (bundle.js:27)
    at t._run (bundle.js:27)
```

**Expected behavior**
The app should load the map

**Screenshots**

![Schermata del 2019-10-03 14-51-42](https://user-images.githubusercontent.com/10365731/66128068-5eae4580-e5ed-11e9-9953-76e2c3216b19.png)

**Comment by heshan0131** [comment]
@matteo-s 
It works when you remove the `?test=123` from URL. 

http://localhost:8080/?mapUrl=https://raw.githubusercontent.com/uber-web/kepler.gl-data/master/earthquakes/data.csv

The Url has to end with an file extension `.csv`

https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md#load-map-using-url

**Comment by matteo-s** [comment]
@heshan0131  That is *exactly* the point, the URL has to end with ```.csv```, and the user can not specify any parameter on the URL.. 

If you want to load the csv from an API, usually you'll have to append some parameters as query string, to specify for example the range of results, the pagination etc.
As of now, this doesn't work, but it's easily fixable when parsing the URL, by simply stripping the query string and *then* validate the extension.

BTW, the assumption that an URL **must** end with a specific extension is pretty bold, a more flexible way would be to read the ``Content-Type`` from response headers and act accordingly.

Also, the initial report states that the whole app crashes, and becomes unusable, thrashing all the previous work the user could have done in the app. Even in the case that you won't support loading from such formatted URLs, the app should simply provide an error message and skip the import, not crash. 

I kindly ask you to re-read the report and reopen the issue.

**Comment by heshan0131** [comment]
@macrigiuseppe I thinks this worth us looking into the loading logic.

**Comment by macrigiuseppe** [comment]
We currently determine the type of file using the '.csv' or '.json' part of the URL. I will look investigate how to change the logic to detect the file/buffer type without using an extension

**Comment by macrigiuseppe** [comment]
PR: #780

**Comment by matteo-s** [comment]
Thanks for the response @macrigiuseppe 
I fully agree that content-type ```text/plain``` could be misleading, but as you suggest checking first for specific MIME types and then for the extension could really improve the usability of the tool.

Regarding 1) I think you need to also add some checks or exception handling to ensure that a "wrong" file (as in wrongly formatted, or not a csv/json but anything else) won't lock the app and require a full reload. As an example, you can paste a non existing URL ```https://your.map.url/map.json``` and the loading modal will remain stuck.
