### ISSUE TITLE
[Bug] Getting error message after upgrading from version 1.1.3 to 1.1.8

### ISSUE THREAD

**Issue by trietphan94** [keplergl/kepler.gl#765]
**Describe the bug**
My application still works fine on version 1.1.3 but after upgrading to version 1.1.8, I had some errors.
**Screenshots**
![image](https://user-images.githubusercontent.com/18748377/66178010-f82d3400-e68d-11e9-990f-c6dfd72561de.png)

**Additional context**
If I change that line `var mapState = config.mapState;` to `var mapState = config && config.mapState;`, my application will work but very laggy. Please help me to resolve this issue. Thank you

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by heshan0131** [comment]
How are you calling `addDataToMap`?
