### ISSUE TITLE
[Bug][Jupyter Widget]

### ISSUE THREAD

**Issue by wzy6642** [keplergl/kepler.gl#776]
**Describe the bug**
code:
from keplergl import KeplerGl
map1 = KeplerGl(height=500)
map1

return:
User Guide: https://github.com/keplergl/kepler.gl/blob/master/docs/keplergl-jupyter/user-guide.md

**Environment (please complete the following information):**
 - Python version: [python3]
 - keplergl Widget version [0.1.0]

**Comment by rubenseijioto** [comment]
Facing the same issue, on Chrome

**Comment by heshan0131** [comment]
please listing your OS (window or Mac)
version of:
ipywidgets and notebook

**Comment by wzy6642** [comment]
My OS is Windows
ipywidgets: 7.1.1
jupyter: 1.0.0
jupyter-console: 5.2.0
node: v10.16.3

**Comment by wzy6642** [comment]
![屏幕截图(4)](https://user-images.githubusercontent.com/33506993/66447607-62c0e400-ea81-11e9-9fd4-f08047dbee3c.png)
and I find this.

**Comment by rubenseijioto** [comment]
OS: Linux Ubuntu 19.04
ipywidgets: 7.4.2
jupyter notebook: 5.7.8
![image](https://user-images.githubusercontent.com/45436568/66481051-6b5fed00-ea76-11e9-943d-305493750d28.png)

**Comment by heshan0131** [comment]
Can you provide more info on which installation instruction did you follow? 
Are you trying to directly install from the repo folder?
I am confused because in the screenshot it says it's trying to build from `Users/shanhe/Uber/kepler.gl...`

**Comment by rubenseijioto** [comment]
I used, pip install keplergl

**Comment by heshan0131** [comment]
My bad :(... the 0.1.0 built was broken. please upgrade to `keplergl==0.1.1` now

**Comment by wzy6642** [comment]
Wow, your solution is useful. Thanks!

**Comment by rubenseijioto** [comment]
Cool!!! It's working!!! Many Thanks!!!

**Comment by heshan0131** [comment]
:) close!
