### ISSUE TITLE
Trip layer use with addDataToMap

### ISSUE THREAD

**Issue by eportico** [keplergl/kepler.gl#777]
Hi guys,
How can I use trip data in program using store ?  Can you upload little example ?
Thanks a lot

import { store } from '../redux/store';

store.dispatch(
        addDataToMap(jsondata));
    });

**Comment by heshan0131** [comment]
[Trip layer md](https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/c-types-of-layers/k.trip.md) shows you how to format your geojson feature collection

It is called like this in demo app
https://github.com/keplergl/kepler.gl/blob/master/examples/demo-app/src/app.js#L209-L220
