### ISSUE TITLE
[Bug] Cannot see mapDraw feature on demo_app

### ISSUE THREAD

**Issue by lydiavi** [keplergl/kepler.gl#786]
**Bug : **
I am currently working on a version of kepler.gl including Giuseppe Macri's draw polygon  (mapDraw) feature (branch 390_apply_polygon-filters). According to the demo_app webpack.config.local.js file it should load kepler.gl from the src directory in the repo. 

![image](https://user-images.githubusercontent.com/35256484/66845637-ad09ff80-ef70-11e9-8dc1-64b203d64d21.png)

However it loads kepler.gl from the node_modules file. And therefore i can't see any of the draw_polygon feature. 

**To Reproduce : **
I verified this by changing something in the src repo and it didn't show, but if you do it in the node_modules/kepler.gl folder it does change.
I changed "Add Data To Map" by "Add Data" for the test. Didn't work when changing src repo, worked when changing in node_modules.

**Desktop : **
I'm working on a Linux Server.
Kepler Version :  https://github.com/keplergl/kepler.gl/tree/390_apply_polygon_filters

**Comment by macrigiuseppe** [comment]
@lydiavi if you would like to run the demo app using kepler source you need to perform the following steps:
you must be in the project root folder
```
$ yarn
$ yarn start
```

FYI __390_apply_polygon_filters__ will soon be updated with new code

**Comment by lydiavi** [comment]
I don't have yarn on the server (I don't have admin rights)
But I use **npm** to start the demo app, and the app works it just doesn't take kepler.gl from the right repo. I want it to use kepler.gl from src and not node_modules.
Does it only work with yarn ? If so, why ?

Sorry if it is not very clear, I can reformulate if needed.

Thank you

**Comment by macrigiuseppe** [comment]
yarn is similar to npm. If you want to use npm just do the following form the root source:
```
npm run install
npm run start
```

**Comment by lydiavi** [comment]
This is already what i do.

The problem is not starting the demo_app but using the code in src as the module kepler.gl (import kepler.gl).

Currently the demo_app takes the code in "examples/demo_app/node_modules/kepler.gl/" as module kepler.gl. 
However according to the "webpack.config.local.js" it should take the code in "src/" for module kepler.gl.

**Comment by macrigiuseppe** [comment]
@lydiavi the demo_app pull the code directly from the source when you run it following the developer guide instructions https://github.com/keplergl/kepler.gl/blob/master/contributing/DEVELOPERS.md

In fact, we use the demo to develop and test kepler

**Comment by macrigiuseppe** [comment]
I am gonna close this task because the title is completely misleading. If you still have issues running Kepler, please open a new issue and provide a an example of your project
