### ISSUE TITLE
[Bug] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by gautamtata** [keplergl/kepler.gl#796]
**Describe the bug**
I am not sure if this is a bug or a memory limitation of my computer. I used Kepler.gl's web application in order to visualize data from Uber Movement and downloaded a JSON file which Kepler.gl accepts. The file size is around 1G big.

I'm trying to load this dataset into my own react application using the  code: 

`  componentDidMount() {

    const data = Processors.processKeplerglJSON(uberData);

    const dataset = {

      data,

      info: {

        id: 'my_data'

      }

    }; 

    this.props.dispatch(addDataToMap({datasets : dataset, config: nycConfig}))`

Which errors out. with the folliwing errors: 
`
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x39469f21e6e9 <JSObject>
    0: builtin exit frame: stringify(this=0x39469f211a21 <Object map = 0x39468ee042a9>,0x394621f826f1 <undefined>,0x394621f826f1 <undefined>,0x3946ff6ac581 <Object map = 0x3946d0c06e51>,0x39469f211a21 <Object map = 0x39468ee042a9>)

    1: arguments adaptor frame: 1->3
    2: stringifySafe(aka stringifySafe) [0x3946fea9b2f9] [/Users/gautam/Desktop/osm-uber/webapp/node_modules/webpack/lib/JsonGen...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003d035 node::Abort() [/usr/local/bin/node]
 2: 0x10003d23f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b8e15 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100586d72 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100589845 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x1005856ef v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005838c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10059015c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x1005901df v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
`

**To Reproduce**
1. Try to load a large JSON file using Processors.processKeplerglJSON()

**Expected behavior**
The application should compile and the dataset should be loaded with the configuration file.

**Screenshots**

**Desktop (please complete the following information):**
- MacOSX 10.14.6 Mojave

**Comment by heshan0131** [comment]
Are you trying to load the file using `import jsonData from 'data.json';`? 
That's probably not going to work. Webpack will have to compile the file into js string. 
 If your file is 1G size, you might need to start a node server (using express) and load it via fs.

**Comment by macrigiuseppe** [comment]
you may also be able to place your file into a CDN and try to load using the file url
