### ISSUE TITLE
[Bug] `ColorField` property missing from `KeplerGlSchema.save` config

### ISSUE THREAD

**Issue by jasonleehodges** [keplergl/kepler.gl#802]
**Describe the bug**
I'm trying to save the exact configuration of a kepler.gl map to a nosql datastore so that users can pick back up where they left off. I'm using `KeplerGlSchema.save` to save the configuration. However, it seems that when using the `save` method, the `colorField` property is not present in the `visState.layers[0].config` object. Therefore, when I save the result of the `save` method, and reload it the next time the user loads the map, their colors are not loaded because the selected colorField is no longer there. Any advice on how to remedy this?

`console.log(KeplerGlSchema.save(state.demo.keplerGl.map));` yields:

![Screen Shot 2019-10-21 at 5 10 18 PM](https://user-images.githubusercontent.com/12241349/67249696-d1108980-f425-11e9-8724-794669303cc3.png)

**Expected behavior**
`KeplerGlSchema.save(state.demo.keplerGl.map))` should yield a colorField property.

When manually adding the colorField in the UI the resulting Redux state change is this:

![Screen Shot 2019-10-21 at 5 18 24 PM](https://user-images.githubusercontent.com/12241349/67249981-e1753400-f426-11e9-841a-bccfc7ecec1f.png)

Thus I would think that the `colorField`, `colorDomain`, and `colorScale` properties likely need to be in the resulting object of the `save` method.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - Version: "kepler.gl": "1.1.9"

**Comment by heshan0131** [comment]
`colorField` will be saved to `layer.visualChannels`, instead of `layer.config`. You need to call `KeplerGlSchema.load` before passing the saved schema to `addDataToMap`.

**Comment by jasonleehodges** [comment]
@heshan0131 I do call the load method and then `addDataToMap` but the `colorField` is blank on the map after the redux action completes.

**Comment by jasonleehodges** [comment]
@heshan0131 I've done a `console.log` to demonstrate the result of calling `KeplerGlSchema.load` and the `colorField` does indeed seem to be where you say it should be, but after loading the result to the map, as you can see it is not registering in the UI. The UI should show a color field of "Category" but instead it is blank.

```
const mapToLoad = KeplerGlSchema.load(content.state.datasets, content.state.config);
console.log(mapToLoad);
this.props.dispatch(addDataToMap(mapToLoad));
```

![Screen Shot 2019-10-28 at 9 06 34 AM](https://user-images.githubusercontent.com/12241349/67690347-57672700-f962-11e9-9169-993bb75b3f7d.png)

**Comment by macrigiuseppe** [comment]
@jasonleehodges in order to import an existing configuration, you need to use  the following:

```
const config = KeplerGlSchema.parseSavedConfig(content.state.config)
this.props.dispatch(addDataToMap(mapToLoad, config));
...

**Comment by heshan0131** [comment]
@jasonleehodges
interesting `visualChannels` should not be present after `KeplerGlSchema.load`. It should be folded into `layer.config` could you paste your entire `content.state.config` in here? the one you passed to `KeplerGlSchema.load`

**Comment by jasonleehodges** [comment]
@heshan0131 
```
"config": {
    "version": "v1",
    "config": {
      "visState": {
        "layers": [
          {
            "id": "p6qug8",
            "type": "point",
            "config": {
              "textLabel": [
                {
                  "anchor": "start",
                  "size": 18,
                  "field": null,
                  "color": [
                    255,
                    255,
                    255
                  ],
                  "offset": [
                    0,
                    0
                  ],
                  "alignment": "center"
                }
              ],
              "label": "First Layer",
              "color": [
                201,
                0,
                0
              ],
              "dataId": "domo data",
              "columns": {
                "lat": "latitude",
                "lng": "longitude",
                "altitude": null
              },
              "isVisible": true,
              "visConfig": {
                "outline": false,
                "colorRange": {
                  "name": "Custom Palette",
                  "type": "custom",
                  "category": "Custom",
                  "colors": [
                    "#0615f7",
                    "#f80c05"
                  ]
                },
                "radiusRange": [
                  0,
                  50
                ],
                "strokeColorRange": {
                  "name": "Global Warming",
                  "type": "sequential",
                  "category": "Uber",
                  "colors": [
                    "#5A1846",
                    "#900C3F",
                    "#C70039",
                    "#E3611C",
                    "#F1920E",
                    "#FFC300"
                  ]
                },
                "thickness": 2,
                "radius": 19.3,
                "fixedRadius": false,
                "opacity": 0.8,
                "strokeColor": null,
                "filled": true
              }
            },
            "visualChannels": {
              "sizeField": null,
              "colorField": {
                "name": "Category",
                "type": "string"
              },
              "strokeColorField": null,
              "sizeScale": "linear",
              "colorScale": "ordinal",
              "strokeColorScale": "quantile"
            }
          },
          {
            "id": "cu21kxk",
            "type": "geojson",
            "config": {
              "textLabel": [
                {
                  "anchor": "start",
                  "size": 18,
                  "field": null,
                  "color": [
                    255,
                    255,
                    255
                  ],
                  "offset": [
                    0,
                    0
                  ],
                  "alignment": "center"
                }
              ],
              "label": "polygon",
              "color": [
                55,
                29,
                168
              ],
              "dataId": "domo data",
              "columns": {
                "geojson": "test_polygon"
              },
              "isVisible": true,
              "visConfig": {
                "heightRange": [
                  0,
                  500
                ],
                "sizeRange": [
                  0,
                  10
                ],
                "colorRange": {
                  "name": "Global Warming",
                  "type": "sequential",
                  "category": "Uber",
                  "colors": [
                    "#5A1846",
                    "#900C3F",
                    "#C70039",
                    "#E3611C",
                    "#F1920E",
                    "#FFC300"
                  ]
                },
                "radiusRange": [
                  0,
                  50
                ],
                "stroked": false,
                "strokeColorRange": {
                  "name": "Global Warming",
                  "type": "sequential",
                  "category": "Uber",
                  "colors": [
                    "#5A1846",
                    "#900C3F",
                    "#C70039",
                    "#E3611C",
                    "#F1920E",
                    "#FFC300"
                  ]
                },
                "thickness": 0.5,
                "radius": 10,
                "elevationScale": 5,
                "opacity": 0.06,
                "enable3d": false,
                "wireframe": false,
                "strokeColor": null,
                "filled": true
              }
            },
            "visualChannels": {
              "sizeField": null,
              "heightScale": "linear",
              "radiusScale": "linear",
              "colorField": null,
              "strokeColorField": null,
              "sizeScale": "linear",
              "colorScale": "quantile",
              "radiusField": null,
              "heightField": null,
              "strokeColorScale": "quantile"
            }
          }
        ],
        "layerBlending": "normal",
        "splitMaps": [],
        "filters": [],
        "animationConfig": {
          "currentTime": null,
          "speed": 1
        },
        "interactionConfig": {
          "tooltip": {
            "fieldsToShow": {
              "domo data": [
                "Time",
                "Category"
              ]
            },
            "enabled": true
          },
          "brush": {
            "size": 0.5,
            "enabled": false
          }
        }
      },
      "mapState": {
        "latitude": 45.77100769541074,
        "isSplit": false,
        "longitude": -85.37486820122642,
        "pitch": 0,
        "dragRotate": false,
        "zoom": 3.3187992198429406,
        "bearing": 0
      },
      "mapStyle": {
        "mapStyles": {},
        "styleType": "light",
        "threeDBuildingColor": [
          9.665468314072013,
          17.18305478057247,
          31.1442867897876
        ],
        "topLayerGroups": {},
        "visibleLayerGroups": {
          "border": true,
          "land": true,
          "label": true,
          "building": true,
          "water": true,
          "road": true
        }
      }
    }
  },
```

**Comment by heshan0131** [comment]
I notices a `"` missing in geojson `layer.config.dataId`. But it might not be the problem.

I tested your config with this:
```` 
const loadConfig = SchemaManager.parseSavedConfig(config);
console.log(loadConfig.visState.layers[0])
```

and I see this:
![Screen Shot 2019-11-13 at 4 46 38 PM](https://user-images.githubusercontent.com/3605556/68817011-2f9be280-0635-11ea-99e8-d9a17e0b9ec9.png)

Note `colorField: { name: 'Category', type: 'string' }` is correctly added into `config`

**Comment by jonsadka** [comment]
@heshan0131 when using the `Export Map` tool to generate a JSON blob, I was not getting a `colorField` set on `config.visState.layers[0].config`. 

I needed `colorField` so that I could use the `ordinal` color scale set in line 431 of `validateSavedVisualChannels` https://github.com/keplergl/kepler.gl/blob/master/src/reducers/vis-state-merger.js#L431

**Comment by macrigiuseppe** [comment]
> @heshan0131 when using the `Export Map` tool to generate a JSON blob, I was not getting a `colorField` set on `config.visState.layers[0].config`. Might be related
> 
> FYI I needed `colorField` so that I could use the `ordinal` color scale set in line 431 of `validateSavedVisualChannels` https://github.com/keplergl/kepler.gl/blob/master/src/reducers/vis-state-merger.js#L431

Hey @jonsadka, when you export the map, you won't see the colorField property in the layer.config object, but you will find it as part of layer.visualChannel.

In fact, if you try to export the map for https://kepler.gl/demo/sfcontour, you will see 
```
"visualChannels": {
              "colorField": {
                "name": "elevation",
                "type": "integer"
              },
              "colorScale": "quantize",
              "sizeField": null,
              "sizeScale": "linear",
              "strokeColorField": {
                "name": "elevation",
                "type": "integer"
              },
              "strokeColorScale": "quantize",
              "heightField": null,
              "heightScale": "linear",
              "radiusField": null,
              "radiusScale": "linear"
            }
```

notive
```
"colorField": {
                "name": "elevation",
                "type": "integer"
              },
```

**Comment by jonsadka** [comment]
@macrigiuseppe yeah I saw that but the issue I ran into is that the JSON file exported from Kepler's `Export Map` does not appear to be backwards compatible when calling `addDataToMap`. 

For example when I set a quantize color scale on a layer, export the JSON config, and try to reimport that layer using `addDataToMap`, the color scale does not apply because `colorField` is being set on `config.visState.layers[0].visualChannels` instead of `config.visState.layers[0].config` in the exported JSON. Is this intentional?

**Comment by macrigiuseppe** [comment]
> @macrigiuseppe yeah I saw that but the issue I ran into is that the JSON file exported from Kepler's `Export Map` does not appear to be backwards compatible when calling `addDataToMap`.
> 
> For example when I set a quantize color scale on a layer, export the JSON config, and try to reimport that layer using `addDataToMap`, the color scale does not apply because `colorField` is being set on `config.visState.layers[0].visualChannels` instead of `config.visState.layers[0].config` in the exported JSON. Is this intentional?

@jonsadka some of the properties in the configuration are transient. At rest, visualChannels property is used to store all field settings/customization.

In order to pass the right configuration to addDataToMap, you need to use __KeplerGlSchema.load__

The basic flow is the following:

- Create map
- Export map to JSON
- Import Map
- Load the map using __KeplerGlSchema.load__
- Call addDataToMap with datasets and loaded configuration

For instance, when uploading files, kepler.gl demo app performs the above steps

**Comment by jasonleehodges** [comment]
@heshan0131 I've been able to get the colorfield to save but now using that same methodology the zoom level and center point are no longer loading. Any thoughts there?

**Comment by heshan0131** [comment]
@jasonleehodges you need to pass `options: {centerMap: false}` when calling `addDataToMap

**Comment by jasonleehodges** [comment]
@heshan0131 yeah, I already had that property set to false. I also tried 'keepExistingConfig' set to both true and false and it is still not loading with the correct center point or zoom level.

**Comment by macrigiuseppe** [comment]
@jasonleehodges since you are describing a new problem, can you please create a new issue?
Please make sure you provide the following info:
- are you using Kepler.gl/demo or embedding kepler.gl in your own app?
- describe your use case, step by step. It is important to know the full sequence
