### ISSUE TITLE
[Bug] Last Graphic Layer in Stack Not Displayed

### ISSUE THREAD

**Issue by tcr-su** [keplergl/kepler.gl#808]
**Describe the bug**
Within the past few weeks (not sure exactly when), kepler.json upload files we have been producing for the past year or so have stopped displaying properly. The symptoms are that all layers in a stack of 18 graphics layers (derived from 9 data sources) display properly except for the last two (point and line layers of aircraft sighting data). The data table for the sightings appears to be empty, except that the correct column headings are present. Also the built in time filter histogram shows a profile obviously derived from the sighting data source.

**To Reproduce**
I'm attaching a kepler.json file (FA_Sightings.KeplerPointPlot.test.json) that illustrates the problem. The test file is a 2MB abbreviated version of a full sighting file. Upon loading, the display opens with the first 2 graphics layers enabled ("Airports" and "Waypoints") as well as the 17th layer ("Sightings: 190920"). The display should look something like the attached screen shot. You can see that the time filter histogram has data, but there are no sighting points displayed. If you click on the "Show data table" button for the sighting data source (1st data layer), it is empty except for the column headings. If you enable any of the other graphics layers, they display properly

**Expected behavior**
See the attached screen shot for how the sighting layer should look with a full (not abbreviated) kepler file.

**Screenshots**
Screen shot attached below.

**Desktop (please complete the following information):**
 - OS: Windows 10 (1809)
 - Browser Firefox
 - Version  70.0 and earlier versions

**Additional context**
Our use of kepler.gl has been working flawlessly for over a year (Thanks Uber!). This problem is of very recent origin.
[FA_Sightings.KeplerPointPlot.test.zip](https://github.com/keplergl/kepler.gl/files/3776511/FA_Sightings.KeplerPointPlot.test.zip)
![All-Airports 1024x588](https://user-images.githubusercontent.com/32944139/67642991-df035600-f8ce-11e9-9a29-05da2ac62371.jpg)

**Comment by heshan0131** [comment]
Hi @tcr-su  I just deployed a fix to kepler. I now can see this when upload the attached file. The last 2 layers seem to display fine. It doesn't show as much points as your screenshot, but it might just be the dataset contains less points. 


![Screen Shot 2019-11-13 at 4 25 46 PM](https://user-images.githubusercontent.com/3605556/68816117-4d1b7d00-0632-11ea-94d0-2f7a69b90727.png)

**Comment by heshan0131** [comment]
@tcr-su I assume this has been fixed :) closing it for now
