### ISSUE TITLE
[Bug][Docs] Dead link

### ISSUE THREAD

**Issue by bumbeishvili** [keplergl/kepler.gl#810]
**Describe the bug**
Dead link inside docs

**To Reproduce**
1. Go to kepler.gl => documentation
2. Click on first link ([Overview](https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/1))
3. You will see 404 error

**Expected behavior**
Overview of kepler.gl should open

**Screenshots**

![404](https://user-images.githubusercontent.com/6873202/67858157-f68e4900-fb31-11e9-8a0b-14c150c2c870.gif)

**Comment by heshan0131** [comment]
Thanks for the PR. it has been merged
