### ISSUE TITLE
[Bug] PR #787 stops the demo-app from loading

### ISSUE THREAD

**Issue by amrfaisal** [keplergl/kepler.gl#811]
The PR https://github.com/keplergl/kepler.gl/pull/787 results in errors, stopping the demo-app from working.

Resetting the master to commit https://github.com/keplergl/kepler.gl/commit/43ed0752ff236a9ab9349eab0d07e4a357ccf825 solved the issue.

1. Clone the master
2. Navigate to kepler.gl/examples/demo-app/
3. Run `yarn --ignore-engines`
4. Run `export MapboxAccessToken=<your_mapbox_token>`
5. Run `yarn start`
6. Check DevTools for errors stopping the page from loading.

**Comment by heshan0131** [comment]
Master is fixed, please give it a try

**Comment by amrfaisal** [comment]
Confirmed. It's now working. Thanks a lot
