### ISSUE TITLE
[Bug] Export Map HTML is broken

### ISSUE THREAD

**Issue by reubengan93** [keplergl/kepler.gl#813]
**Describe the bug**
After exporting the map as an HTML file, the exported file will load a blank screen in the browser instead of the map that was created in Kepler. Both read-only mode and edit map mode produce the same issue.

**To Reproduce**
1. Upload any data to the map (csv, json)
2. Click on 'share'
3. Select 'export map'
4. Select 'HTML'
5. Input Mapbox Access Token
6. Select either 'read mode' or 'map mode'
7. Click export
8. Open exported HTML file

**Expected behavior**
The exported file should produce a Kepler map of whatever was saved previously. I would assume even a blank map?

**Screenshots**
![Screenshot 2019-11-01 at 7 07 53 PM](https://user-images.githubusercontent.com/30720221/68021150-989d6500-fcdb-11e9-973d-b2470b765177.png)
This is the browser page after opening the HTML file.

**Desktop (please complete the following information):**
 - OS: [macOS Mojave]
 - Browser [Chrome]
 - Version [Version 77.0.3865.120 (Official Build) (64-bit)]

**Additional context**

**Comment by kindjacket** [comment]
I'm getting the same on Safari macOS Catalina

**Comment by macrigiuseppe** [comment]
we were able to reproduce the issue and we are working on fixing it. We are gonna post some updates soon.

**Comment by heshan0131** [comment]
Fix just deployed. Please confirm fixes

**Comment by kindjacket** [comment]
@heshan0131 fix confirmed! Thanks for the quick fix!

**Comment by ichsan2895** [comment]
This bug still happen on me

OS: [Windows 7 64 bit]
Browser [Opera]
Version [68.0.3618.173 (64-bit)]
