### ISSUE TITLE
Can't export in any way html/json/dropbox

### ISSUE THREAD

**Issue by nicosalvia** [keplergl/kepler.gl#815]
**Describe the bug**
When i try to export the map, it doesn't show any information, it shows "like" it has information, but when you open the datatable it doesn't have any data (even when it says that it has rows in it.)

**To Reproduce**
1. Go to Export Map or save with dropbox
2. Click on html/json
3. Scroll down to accept and then copy the link in a new tab.

**Expected behavior**
That shows the correct information. Perhaps is something of my data? I am attaching the file that i am using

**Screenshots**
![image](https://user-images.githubusercontent.com/43279595/68241063-ca207400-ffec-11e9-9d58-a61247d1ee1b.png)

[_select_a_user_id_max_requests_requested_pickup_lat_as_latitude__201911051639.zip](https://github.com/keplergl/kepler.gl/files/3810955/_select_a_user_id_max_requests_requested_pickup_lat_as_latitude__201911051639.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 78 / Firefox 70.0.1 

**Additional context**
Please help! I think perhaps there is an issue with the datetime field, but not quite sure.

**Comment by nicosalvia** [comment]
Update, the problem happens when i use the "requestedhour" field as a filter

**Comment by macrigiuseppe** [comment]
@nicosalvia I was able to reproduce the issue and indeed the issue is related to the requestedhour format. I will do a deeper investigation and get back to you

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/829

**Comment by heshan0131** [comment]
Fix was deployed, please confirm it has been resolved
