### ISSUE TITLE
[BUG] HTML file is not opening in browser "ReferenceError: KeplerGl is not defined" 

### ISSUE THREAD

**Issue by alihassan2203** [keplergl/kepler.gl#817]
**Describe the bug**
I uploaded my dataset and the visual and point plotting on the kepler.gl is fine but After exporting HTML. It is not showing a map. Nothing loads on the screen and when I see the developer console of firefox then see this error "ReferenceError: KeplerGl is not defined". I even added my public API key of mapbox but nothing happened.

**To Reproduce**
1. Go to kepler.gl
2. Upload any dataset with lat long and export it as HTML and open your browser
3. See the developer console of firefox
4. See error ""ReferenceError: KeplerGl is not defined" 

**Expected behavior**
It should show me the map with all points on the browser when I export HTML 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/50858006/68289629-4b890c80-00a8-11ea-9af0-d27a2f0322b5.PNG)
![Capture2](https://user-images.githubusercontent.com/50858006/68290658-209fb800-00aa-11ea-9f10-f7a94069fce7.PNG)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox , Chrome (updated)
 

**Additional context**
This issue is from days please solve this horrible issue even my all existing HTML files that I made 3 months ago are not running too. They all have the same error in the developer console ""ReferenceError: KeplerGl is not defined" "

**Comment by heshan0131** [comment]
@alihassan2203 Can you confirm this is happening also to the new saved maps? I was able to save a html and load it today.

**Comment by lperozzi** [comment]
Hi, with a new saved map I have this error that may be related

![image](https://user-images.githubusercontent.com/6198369/68802099-92a16f80-065d-11ea-8ae3-5d606438af25.png)

**Comment by alihassan2203** [comment]
@heshan0131 The issue has been resolved on its own. It may an issue from the Kepler side.

**Comment by CC1707** [comment]
Hi there, this issue keep persisting, any idea?  
Same as above, nothing new to replicate.
