### ISSUE TITLE
[Bug] Load Map using URL not working

### ISSUE THREAD

**Issue by edwinvandenbelt** [keplergl/kepler.gl#819]
**Describe the bug**
using an url to provide a csv ends up in a javascript error:
Uncaught (in promise) TypeError: a is not a function
    at bundle.js:54
    at bundle.js:98
    at r (bundle.js:27)
    at s (bundle.js:98)
    at Object.run (bundle.js:27)
    at bundle.js:27
    at Array.map (<anonymous>)
    at bundle.js:27
    at Object.run (bundle.js:27)
    at t._run (bundle.js:27)

**To Reproduce**
1. Go to 'https://kepler.gl/demo'
2. Click on 'Load Map using URL'
3. enter a url producing a csv ('https://..../', returns 200 an valid csv in body)
4. it keeps on 'loading' and an error is in te console. 
Manually you can download the csv and use 'load your data' tab without any problem...
This goes wrong as well with points and linestrings...

**Expected behavior**
The csv plotted on a map. 

**Screenshots**
manually uploaded:
![image](https://user-images.githubusercontent.com/10400054/68399780-37601080-0177-11ea-8984-313b66091a55.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version Versie 78.0.3904.87

**Comment by macrigiuseppe** [comment]
@edwinvandenbelt I tried to replicate the issue but loading through URL works correctly.
Can you please share a dataset that triggers the above issue?

**Comment by hkt999** [comment]
For this issue, maybe you can try https://lass.mgmeet.io/datasets/all.csv 
Browser: Chrome 

<img width="915" alt="截圖 2019-12-29 下午1 57 15" src="https://user-images.githubusercontent.com/1061756/71553051-3050d280-2a43-11ea-9f61-bc3c0f9374c5.png">
 as a dataset and I have the same issue, here.

**Comment by macrigiuseppe** [comment]
> For this issue, maybe you can try https://lass.mgmeet.io/datasets/all.csv as a dataset and I have the same issue, here.
> Browser: Chrome 79.0.3945.88
> OS: MacOS 10.15.2
> 
> <img alt="截圖 2019-12-29 下午1 57 15" width="915" src="https://user-images.githubusercontent.com/1061756/71553051-3050d280-2a43-11ea-9f61-bc3c0f9374c5.png">

@hkt999 the url provided has a 502 gateway error

**Comment by hkt999** [comment]
> @edwinvandenbelt I tried to replicate the issue but loading through URL works correctly.
> Can you please share a dataset that triggers the above issue?

Sorry, issue fixed. https://lass.mgmeet.io/datasets/all.csv

**Comment by macrigiuseppe** [comment]
> > @edwinvandenbelt I tried to replicate the issue but loading through URL works correctly.
> > Can you please share a dataset that triggers the above issue?
> 
> Sorry, issue fixed. https://lass.mgmeet.io/datasets/all.csv

@hkt999 make sure the provided URL supports CORS from different domains. Based on the response it looks like your server doesn't provide CORS correctly.

I am gonna close this issue for now, but feel free to re-open if the problem still persists
