### ISSUE TITLE
[Bug] Reg Prev Bug #808: Point Display Type Not Working -- See CA Earthquake example

### ISSUE THREAD

**Issue by tcr-su** [keplergl/kepler.gl#827]
I previously reported a bug #808 in which some layers in kepler.gl files that used to work are no longer working. The layers that do not render are POINT display types. The input data files from our project that used to work are no longer working. Your example display of California Earthquakes illustrates the problem.

**To Reproduce**
1. Go to 'https://kepler.gl/demo'
2. Click on 'Try sample data > California Earthquakes'
3. ...

**Expected behavior**
When the display comes up, there are no points rendered. The Time Filter contains a histogram of the data, but the Layers "new dataset" table is empty

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser Firefox
 - Version [e.g. 22] 70.0.1

**Additional context**

**Comment by heshan0131** [comment]
The point display should work now

![Screen Shot 2019-11-13 at 4 28 40 PM](https://user-images.githubusercontent.com/3605556/68816236-abe0f680-0632-11ea-9691-f32f557e5a3a.png)

**Comment by demartsc** [comment]
@heshan0131 - what version of kepler.gl was this fixed in? trying to trace through whether we need to bump tableau extension as well. Thanks!

**Comment by tcr-su** [comment]
On 2/9/2021 8:08 PM, Chris DeMartini
      wrote:
    
    @heshan0131
      - what version of kepler.gl was this fixed in? trying to trace
      through whether we need to bump tableau extension as well. Thanks!
    Sorry, I don't recall...  Tom R.
