### ISSUE TITLE
[Bug][Jupyter Widget] - How can I enable timeseries functionality in jupyter plugin ?

### ISSUE THREAD

**Issue by sundas01** [keplergl/kepler.gl#833]
**Describe the bug**
This is more of a question. Does jupyter plugin support time series analysis using filter on a date column ?

in jupyter when i choose date col as filter it just asks me to select a value from in list and doesnt show was filter on map it self. 

**To Reproduce**
1. load kepler
2. Add data & config
3. Export map

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python version: [e.g. python2, python3]
 - keplergl Widget version [e.g. 0.1.0]

**Additional context**

**Comment by macrigiuseppe** [comment]
@sundas01 does your dataset contain datetime values or just date?
