### ISSUE TITLE
[Bug] Changing filter field back and forth breaks the filter widget

### ISSUE THREAD

**Issue by chrisirhc** [keplergl/kepler.gl#838]
**Describe the bug**
Filter values are broken after switching between fields.

**To Reproduce**
1. Go to https://kepler.gl/demo/world_flights
2. Click on Filter
3. Add Filter, and pick `origin_country`
4. Click on "Enter a value". See that countries show up. Don't select anything.
5. Click on "origin_country" to change the field to be filtered on.
6. Pick `callsign`.
7. Click on "Enter a value". See that callsigns show up. Don't select anything.
8. Pick `origin_country`
9. Click on "Enter a value". See that callsigns show up. 

**Expected behavior**
To be able to see filter values for countries, instead of callsigns.

**Screenshots**
![image](https://user-images.githubusercontent.com/132584/69082221-823e1b80-09f4-11ea-8b25-46361b0ff8cb.png)

**Desktop (please complete the following information):**
 - Chrome Version 78.0.3904.87, Mac

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/841
