### ISSUE TITLE
Kepler improperly truncating large int values in csv files

### ISSUE THREAD

**Issue by jlabarbera11** [keplergl/kepler.gl#839]
**Describe the bug**
Kepler will identify columns as integers if they are all numeric, which could lead to overflowed values.

**To Reproduce**
1. create a simple csv
```
id, lat, lng                              
182891173641581479, 37.777955, -122.398576
```
2. Drop the csv into kepler
3. Observe the point's `id` is now `182891173641581470`

**Expected behavior**
The point id should be `182891173641581479`.

**Screenshots**
<img width="1018" alt="Screen Shot 2019-11-18 at 5 51 04 PM" src="https://user-images.githubusercontent.com/406389/69109252-0790f280-0a2c-11ea-963c-9ee06a7e1814.png">

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by heshan0131** [comment]
kepler.gl probably thinks the `id` is an integer. can you confirm that's the case by openning the data table and let me know what data type is showing for the id column？ Regardless, I think we should add a case when the column names is `id` we parse it as string by default...

<img width="548" alt="Screen Shot 2019-11-20 at 8 02 00 PM" src="https://user-images.githubusercontent.com/3605556/69303134-a48c9080-0bd0-11ea-923a-6970f4c54a58.png">

I created an issue for this
https://github.com/keplergl/kepler.gl/issues/840

**Comment by jlabarbera11** [comment]
It is an integer, I believe since https://github.com/uber-web/type-analyzer labels it as an int type by matching against a regex. A more reliable fix might be to label such fields as a `Number` type in type-analyzer by making the [isInt](https://github.com/uber-web/type-analyzer/blob/371f641aa779c29fe190544779cf51a61b28bfba/src/validator-map.js#L57) check more robust, and then treat those Number types as strings in kepler. What do you think?

**Comment by jlabarbera11** [comment]
I created https://github.com/uber-web/type-analyzer/pull/8 to treat large ints as numbers. If the change is acceptable, a change can be made to kepler to treat number types as strings
