### ISSUE TITLE
[Bug] Point count for clusters are wrong

### ISSUE THREAD

**Issue by nataliateruel** [keplergl/kepler.gl#843]
The point count for the input data is wrong. The sizes of the clusters are right, but when I tooltip them the numbers of points are wrong. Sometimes a small cluster has more points them a big one, and sometimes the number in only one cluster is bigger than the total number of rows of the file.

To reproduce it you can use data on CSV or geoJSON (I have tried both), with points that are not that distant from each other (different cities, in my case), and put them in clusters with the size determined by the number of points. Then, with the tooltip you can see the point count, that in my case is often a lot bigger than it should be.

<img width="1418" alt="Screen Shot 2019-11-24 at 11 01 20 PM" src="https://user-images.githubusercontent.com/56839341/69511529-7a0f4000-0f0e-11ea-8f29-01cfc241ea00.png">
<img width="1423" alt="Screen Shot 2019-11-24 at 11 01 34 PM" src="https://user-images.githubusercontent.com/56839341/69511530-7aa7d680-0f0e-11ea-9a95-313f04debb06.png">

 - OS: Catalina MacOS
 - Browser: chrome and jupyter notebook
 - Version: 1.1.11

**Comment by macrigiuseppe** [comment]
@nataliateruel you are using a time filter in your map, have you tried removing the time filter and validate your map?

**Comment by nataliateruel** [comment]
@macrigiuseppe without the time filter the map is right. I have searched the data file for days to see if it was a mistake on the dates there, but it is not

**Comment by macrigiuseppe** [comment]
@nataliateruel we are gonna work on this issue

**Comment by macrigiuseppe** [comment]
Implemented
