### ISSUE TITLE
fixed radius to meter bug[Bug]

### ISSUE THREAD

**Issue by AlessiaZarzani** [keplergl/kepler.gl#844]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macrigiuseppe** [comment]
@AlessiaZarzani update the description with all the necessary information to reproduce and troubleshoot the issue. 
Include steps and pricing along with data if necessary
