### ISSUE TITLE
[Bug] Interactions: Coordinate setting is not saved to the Map Config

### ISSUE THREAD

**Issue by MakoSDV** [keplergl/kepler.gl#846]
**Describe the bug**
The state of the Coordinate setting under Interactions is not saved in the Map Config.  The Tooltip and Brush settings are saved, but the Coordinate is not.

**To Reproduce**
1. Enable Coordinate under the Interactions settings
2. Select Share and Export Map
3. Select the JSON format
4. Look at the Map Config
5. Under "interactionConfig" the only saved settings are for "tooltip" and "brush".  There is nothing related to Coordinate.

Tested using Kepler.gl version 1.1.11 on https://kepler.gl/demo/

**Expected behavior**
The Coordinate setting should be saved to the Map Config like the other Interaction Config settings and that Coordinate setting should be likewise be applied when loading a map from a JSON Map Config.

**Related Issue**
#504

**Comment by macrigiuseppe** [comment]
We are going to look into this one
