### ISSUE TITLE
[Bug] Auto styling properties in GeoJSON get parsed as data fields creating ghost layers

### ISSUE THREAD

**Issue by daaain** [keplergl/kepler.gl#847]
**Describe the bug**

When adding "auto styling" properties into GeoJSON `Feature`s – ie one or more of `"lineColor"`, `"lineWidth"`, `"fillColor"`, `"radius"` – as per the [documentation](https://github.com/keplergl/kepler.gl/blob/ba656d14209f4320818baf06b4240d2ec39486fa/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md#2-auto-styling), these also get picked up as data columns. While `"lineWidth"` and `"radius"` will only show up as extra properties in the tooltip and data table, the color ones (`"lineColor"` and `"fillColor"`) are especially problematic as being Arrays they are detected as GeoJSON themselves and generate an extra layer for each.

The "auto styling" properties do get applied afterwards though, so the feature itself works.

**To Reproduce**
1. Add "auto styling" properties into GeoJSON `Feature`
2. Observe extra data columns and layers via the tooltips and side panel

**Expected behavior**

These properties should be recognised as "auto styling" and removed from the data.

**Screenshots**

<img width="288" alt="image" src="https://user-images.githubusercontent.com/69962/69674416-583fc580-1094-11ea-966b-e3508ee4a246.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/69962/69674444-61c92d80-1094-11ea-9610-c703e43e4d0c.png">

**Desktop (please complete the following information):**

 - OS: Mac
 - Browser: chrome
 - Kepler Version: 1.1.11

**Comment by daaain** [comment]
Until the fix is in place this workaround seems to do the trick if placed right after the `addDataToMap` call:

```js
let ghostLayerIndex
while (
    (ghostLayerIndex = this.props.keplerGl.map.visState.layers.findIndex(
    layer => layer.dataToFeature && layer.dataToFeature[0] === null,
    )) > -1
) {
    this.props.dispatch(removeLayer(ghostLayerIndex))
}
```

**Comment by daaain** [comment]
Since this issue is so popular 🙄 let me also add that it seems if a `LineString` layer has coordinates with timestamps to make it a `Trip` layer, it will not apply these styling features any more. Can open another issue for this if you want, but thought I'll mention here first.

**Comment by macrigiuseppe** [comment]
@daaain can you provide a sample of your dataset?

**Comment by macrigiuseppe** [comment]
@daaain we need in particular those columns containing: "stations https://......"

**Comment by daaain** [comment]
It's a big one, so put it in a gist: https://gist.github.com/daaain/3cce6e820a4ece2e24ce8c74680ad2be

What you can see there is the result of loading GBFS datasets and parsing them using `processGeojson`, see: https://github.com/team-blaze/custom_visualizations_v2/blob/kepler/src/examples/kepler/utils.js#L84

If you want to run that function yourself, here are the GBFS urls: https://github.com/team-blaze/custom_visualizations_v2/blob/kepler/src/examples/kepler/kepler.js#L52

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/872
This should fixed it. please check demo app

**Comment by daaain** [comment]
Finally having got around to test in our setup I just wanted to confirm that it fixed the issue, thanks a lot 🙏
