### ISSUE TITLE
[Bug] not table to render and export map as image using ClusterLayer

### ISSUE THREAD

**Issue by littlebirdalice** [keplergl/kepler.gl#848]
When click on export image, it either shows blank preview or basic map preview without plotted points - I've tried both on safari and chrome and retried many times after restarting browser.
The data I used is very small - 9.5 MB. 

<img width="1354" alt="Screen Shot 2019-11-27 at 1 01 21 AM" src="https://user-images.githubusercontent.com/16776117/69710447-479f4780-10b4-11ea-9d05-d3b6944dc482.png">

**Comment by macrigiuseppe** [comment]
@littlebirdalice would you be able to share your dataset?
I tested using our examples and it works.

**Comment by macrigiuseppe** [comment]
There is an issue with the cluster layer. We are going to fix it.

**Comment by macrigiuseppe** [comment]
fixed
