### ISSUE TITLE
ReceiveMapConfig multiple times

### ISSUE THREAD

**Issue by RinaB** [keplergl/kepler.gl#849]
Hi,
In order to pass my config I use receiveMapConfig (with configuraton A )and then call addDataToMap without configuration. It works fine.
I want to get configuration from a file (configuration B) so I call again to receiveMapConfig  and I expect the configuration to be B in the new calls of addDataToMap .
But I didn't succeed.
I saw your note: receiveMapConfig needs to be called before data is loaded.
My question is: I don't mind to miss current data. I want to return to the start point of the map.
How can I load new config and then load needed data again?

**Comment by daaain** [comment]
Have you tried calling [resetmapconfig](https://github.com/keplergl/kepler.gl/blob/master/docs/api-reference/actions/actions.md#resetmapconfig)?

**Comment by RinaB** [comment]
Yes
But it didn't help

**Comment by macrigiuseppe** [comment]
there is an option keepExistingConfig for addDataToMap and by default its value is false.

https://github.com/keplergl/kepler.gl/blob/1d503f3c5a832223ea32bf8b26e31f322b124676/src/actions/actions.js#L51

**Comment by heshan0131** [comment]
@RinaB Just to clarify here is the sequence of calls you made and your expected behavior:
1. `receiveMapConfig(configA)`
2. `addDataToMap(config: null, data)` -> load data with configA
3. `receiveMapConfig(configB)`
4. `addDataToMap(config: null, data)` -> load data with configB

**Comment by RinaB** [comment]
Yes, that's I tried to do. The data is same.
I found workaround without use the recieveMapConfig twice.
Thank you
