### ISSUE TITLE
[Bug] Visualizing different H3 size at the same time 

### ISSUE THREAD

**Issue by quentindurpoix** [keplergl/kepler.gl#851]
**Describe the bug**
Hi,
I'm working on kepler.gl and H3 and I have to visualize different sizes of H3 hexagones at the same time (same CSV). Unfortunately  There is a problem when I'm trying to do it, the hexagones are taking the same 'tilt' as the first size but don't differ in function of their actual size. 

Thank you in advance ! 

Quentin

**Screenshots** 
Here is an example of my problem.

![image](https://user-images.githubusercontent.com/16835517/69967905-9ff1a180-1519-11ea-8db3-e9c39f13a375.png)

The representation of 871f90254ffffff should be in the yellow part only, but it is look like the upper resolution. 

It should be like this : 

![image](https://user-images.githubusercontent.com/16835517/69968476-c95efd00-151a-11ea-9b11-63ea2fdd1a79.png)

**Comment by macrigiuseppe** [comment]
h3 layer in kepler supports only one resolution per layer, if you have multiple resolution you need to create multiple layers. 
This was a design decision made for performance
