### ISSUE TITLE
[Bug] Component factory function with rest arguments

### ISSUE THREAD

**Issue by tVienonen** [keplergl/kepler.gl#865]
**Describe the bug**

If Im creating a factory function and I specify the arguments as a rest argument. Kepler's injector will raise an error saying that my function is expecting 0 dependencies even if I have declared the deps in the deps property.

For example if I want to modify the deckGlProps for the MapContainer:
```
import { MapContainerFactory } from 'kepler.gl/components';

MyMapContainerFactory.deps = [...MapContainerFactory.deps];
export function MyMapContainerFactory(...keplerDeps) {
    const MapContainer = MapContainerFactory(...keplerDeps);

    return (props) => {
        const deckGlProps = {
            ...props.deckGlProps,
            pickingRadius: 10,
        };

        return <MapContainer {...props} deckGlProps={deckGlProps} />;
    };
}
```

This will cause an error because length of MyMapContainerFactory is 0.
**To Reproduce**
1. Create the factory shown in example and try to inject it to Kepler.

**Expected behavior**
I think Kepler should allow having the rest argument in the factory function's signature. It allows the developer to easily extend existing factories behaviour. This was also working fine in the 1.1.11 release.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 78

**Additional context**
Issue with Kepler version 1.1.12

EDIT:
My current workaround is to use Object.defineProperty to redefine the length property to the correct value:
```
Object.defineProperty(factory, 'length', { value: parentFactory.deps.length });
```

**Comment by heshan0131** [comment]
1.1.12 added a check to whether argument passed to factory has the same length with factory.deps

unfortunately when argument is passed as `MyMapContainerFactory(...keplerDeps)`. MyMapContainerFactory.length will be 1. 

Looks ilke there is no easy way to check customize factory argument length...will disable the check for now.

https://github.com/keplergl/kepler.gl/pull/899

**Comment by heshan0131** [comment]
1.1.13 is published. this should be fixed. closing it for now
