### ISSUE TITLE
[Bug] An exported HTML map cannot be rendered correctly.

### ISSUE THREAD

**Issue by hkt999** [keplergl/kepler.gl#880]
**Describe the bug**
An exported HTML map cannot be rendered correctly. But the exported mapState structure is correct.

**To Reproduce**
1. Go to https://kepler.gl/demo
2. Add one data source (for example, a csv file as the attachment)
[csvall.csv.txt](https://github.com/keplergl/kepler.gl/files/4007673/csvall.csv.txt)
3. Do some operation on the data set
4. Export the HTML map
5. Open the map with Chrome browser

**Expected behavior**
The map should follow the setting value in mapState structure.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.2
 - Browser: Chrome
 - Version: 79.0.3945.88

<img width="1076" alt="edit" src="https://user-images.githubusercontent.com/1061756/71551535-e3f69a00-2a24-11ea-8aa6-f188af7da6da.png">
<img width="1077" alt="exported-and-show" src="https://user-images.githubusercontent.com/1061756/71551537-e822b780-2a24-11ea-955c-3ead57c810b6.png">

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/913

**Comment by macrigiuseppe** [comment]
this is fixed and merged into master. Please confirm
