### ISSUE TITLE
P1: Allow to edit individual colors

### ISSUE THREAD

**Issue by ziyili66** [keplergl/kepler.gl#89]
Request:
I would love the ability to edit the individual colors or have a custom color array type for use in “color based on”.

Reasoning:
Frequently the colors on a map represent an actual data value as opposed to just needing to visually differentiate between the values. For an overly  simple example if an analysis is supposed to show locations that are being green lighted for another process, I should have the ability to set a specific green color for those points. And likewise set red, orange, yellow for points depending on their data value.

**Comment by aakim26** [comment]
+1 for custom color schemes / the ability to reduce the available color schemes

**Comment by oliverclock** [comment]
+1

**Comment by oliverclock** [comment]
Has anyone got a suggested work around for this in the mean time?

**Comment by congeo** [comment]
Firstly, Thanks for this great software! I think this request is very important one. In addition to the current Quantize and Quantile options, I believe two new types of color scales should be considered: Threshold and Ordinal (based on D3 JS scales). I believe, these two are critical for adoption of Kepler.gl in the scientific community.
