### ISSUE TITLE
[Bug] Exported HTML map doesn't render on mobile

### ISSUE THREAD

**Issue by yanisIk** [keplergl/kepler.gl#902]
**Describe the bug**
Any exported map using Kepler.gl website doesn't render on mobile. It shows a blank screen. 

**To Reproduce**
1. Go to kepler.gl website
2. Add any valid data
3. Use 1 layer
4. Export map to HTML (with no edit permission) with your own public Mapbox Token.
5. Open the HTML file on your mobile device using any browser.

**Expected behavior**
The map should be displayed on the mobile phone browser.

**Screenshots**
Entire blank screen.

**Smartphone (please complete the following information):**
 - Devices: Samsung Galaxy Note 8 & Iphone X
 - OS: Android 9 & iOS (latest version)
 - Browsers: Chrome (Android & iOS), Brave (Android), Android Webview, Safari

**Additional context**
The exported map works correctly on desktops on multiple browsers.

**Comment by Joonalai** [comment]
The same thing happens with the demo site as well. For example [nyctrips](https://kepler.gl/demo/nyctrips) produces blank screen after loading:
![kepler-nyctrips-mobile-blank](https://user-images.githubusercontent.com/33314057/77433667-55f23b80-6de8-11ea-8f85-0204f5df7174.gif).

The following logs are produced (and captured with the help of logcat):

```

[INFO:CONSOLE(0)] "[GroupMarkerNotSet(crbug.com/242999)!:54D2B3C3]GL ERROR :GL_INVALID_ENUM : BackFramebuffer::Create: <- error from previous GL command", source: https://kepler.gl/demo/nyctrips (0)
[INFO:CONSOLE(85)] "deck: WebGL2 not supported by this browser. Transition animation is disabled.", source: https://kepler.gl/bundle.js (85)
[INFO:CONSOLE(22)] "deck: error while initializing ScatterplotLayer({id: 'pnidnry'})", source: https://kepler.gl/bundle.js (22)
[INFO:CONSOLE(22)] "deck: error while initializing ScatterplotLayer({id: '4bonnee'})", source: https://kepler.gl/bundle.js (22)
[INFO:CONSOLE(106)] "Error: WebGL instanced rendering not supported", source: https://kepler.gl/bundle.js (106)
[INFO:CONSOLE(49)] "Image "dot-11" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.", source: https://kepler.gl/bundle.js (49)
[INFO:CONSOLE(49)] "Image "dot-10" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.", source: https://kepler.gl/bundle.js (49)
[INFO:CONSOLE(12)] "Uncaught (in promise) Error: WebGL instanced rendering not supported", source: https://kepler.gl/bundle.js (12)

```

**Comment by macrigiuseppe** [comment]
@Joonalai thank you for sharing this, mobile devices are not our highest priority right now. Also, I tried nyctrips demo on my iPhone 11 and it works
