### ISSUE TITLE
Kepler identify numbers as string

### ISSUE THREAD

**Issue by grial** [keplergl/kepler.gl#907]
Recently, kepler does not identify some of my data as numbers, but as "string". 
![FireShot Capture 007 - kepler gl - kepler gl](https://user-images.githubusercontent.com/3502100/72435126-a7a19880-379d-11ea-908b-9b4532d64f31.png)
![FireShot Capture 008 - kepler gl - kepler gl](https://user-images.githubusercontent.com/3502100/72435140-b12b0080-379d-11ea-9ad0-1e2ac44cc33c.png)

They are numbers with decimals, and on previous maps, Kepler recognized.
Greetings

**Comment by heshan0131** [comment]
@grial to clarify were you using demo app?
Could you send us a sample of your csv?

**Comment by heshan0131** [comment]
@jlabarbera11 This is related to the latest change in your PR
https://github.com/keplergl/kepler.gl/pull/891

**Comment by heshan0131** [comment]
I did some investigation. when I used my test data with long decimals. kepler.gl recognized it as float.
@grial could it be your data contain some random characters like `n/a` `/N` that spoiled the pot? 


zipcode | large_int | zero_pad | long_decimal
-- | -- | -- | --
94107 | 28376251627 | 1 | 68.9768976898
94103 | 21876216 | 2 | 70.938215103
94102-1193 | 2376483 | 12 | 75.294117671
94107 | 2910218728 | 9 | 66.666666667
94103 | 12910218728 | 1 | 68.9768976898
94102-1193 | 21212 | 100 | 70.938215103
94107 | 121244 | 1234 | 75.294117671
94103 | 28376251627 | 21 | 66.666666667
94102-1193 | 21876216 | 111 | 68.9768976898
94107 | 2376483 | 311 | 70.938215103
94103 | 2910218728 | 221 | 75.294117671
94102-1193 | 12910218728 | 1 | 66.666666667
94107 | 21212 | 12 | 68.9768976898
94103 | 121244 | 34 | 70.938215103
94102-1193 | 44221 | 2 | 75.294117671
94117 | 11 | 998 | 66.666666667
93182 | 9076652 | 110 | 79.3831168831

<img width="692" alt="Screen Shot 2020-01-16 at 1 41 40 PM" src="https://user-images.githubusercontent.com/3605556/72565078-f61a6a00-3865-11ea-99a0-fa9360a7c11f.png">

**Comment by jlabarbera11** [comment]
I did notice that https://github.com/uber-web/type-analyzer will mark a column mixed with floats and ints as a number. @heshan0131 the commit you linked to changes kepler behavior to characterize type-analyzer numbers as strings.

**Comment by heshan0131** [comment]
I see. When it encounter a mix of int and float, type-analyzer should return float. Because float is a super set of int. Also  int and float are treated the same in kepler

**Comment by grial** [comment]
> @grial to clarify were you using demo app?
> Could you send us a sample of your csv?

Yes, I am using the demo app in a Google Chrome browser, but I tried it with several browsers and two different PCs.
This is my file.
[mapa_galegas_2016_geojson.zip](https://github.com/keplergl/kepler.gl/files/4076141/mapa_galegas_2016_geojson.zip)

> I did some investigation. when I used my test data with long decimals. kepler.gl recognized it as float.
> @grial could it be your data contain some random characters like `n/a` `/N` that spoiled the pot? 

I already saw that this could be a problem and I cleaned the data with N / A or without data

> You can test it with less than 20 rows and see if the results are different

I just did it with very few and it works. I think the problem may be that there is "int" and "float" in the same column and that is what makes it identify as "string", because they are voting percentages. But two months ago I made a similar map, with similar data from another year, and it worked.

It also happens if I use test data in Kepler. These, for example:

https://github.com/uber-web/kepler.gl-data/blob/master/county_unemployment/data.geojson

Look at unemployment_rate!
![FireShot Capture 001 - kepler gl - kepler gl](https://user-images.githubusercontent.com/3502100/72602620-d93e6f00-3917-11ea-8a9b-c8013255fddf.png)

**Comment by grial** [comment]
I did a test. I added the decimal zeros to the "int" numbers, and kepler.gl removes them if they are 0, so re-interpret the column as "string".

**Comment by macrigiuseppe** [comment]
type-analizer

**Comment by jlabarbera11** [comment]
The reason this broke was mixed int/float columns were always treated as numbers, but my pr in kepler.gl made numbers be treated as strings.

I can change type-analyzer to treat mixed int/float columns as floats, or keep the current behavior and treat columns with large numbers as strings. Which is preferred @heshan0131 ?

**Comment by macrigiuseppe** [comment]
@jlabarbera11 it would be great to update type-analizer to handle mix int/flow columns as float otherwise kepler.gl will recognize mixed content (int/float) as string columns

**Comment by heshan0131** [comment]
> The reason this broke was mixed int/float columns were always treated as numbers, but my pr in kepler.gl made numbers be treated as strings.
> 
> I can change type-analyzer to treat mixed int/float columns as floats, or keep the current behavior and treat columns with large numbers as strings. Which is preferred @heshan0131 ?

Let's go with `change type-analyzer to treat mixed int/float columns as floats`.

**Comment by jlabarbera11** [comment]
Added a pr here https://github.com/uber-web/type-analyzer/pull/14

**Comment by heshan0131** [comment]
merged in master and deployed. Please check again

**Comment by endolith** [comment]
Still a problem in 3.0.0?  I'm using kepler for the first time and ChatGPT code is generating the files, so I'm not sure about anything.

![2024-06-22 23_43_05- Roaming  kepler gl - kepler gl_ — Mozilla Firefox](https://github.com/keplergl/kepler.gl/assets/58611/7cd7b79f-d19a-467a-93f4-8f4c3b364ae5)


![image](https://github.com/keplergl/kepler.gl/assets/58611/7618cc19-dec9-4fa2-94b0-e405776bf958)
