### ISSUE TITLE
[Bug] Crash on loading GEOJSON file

### ISSUE THREAD

**Issue by LtChae** [keplergl/kepler.gl#926]
**Describe the bug**
When uploading certain GEOJSON files, kepler crashes abruptly.

**To Reproduce**
1. Go to 'add data'
2. Upload one of the attached files
3. UI will blank to a white screen
4. See error in console logs of the browser

**Expected behavior**
As far as I can tell, this is valid geojson. It should upload correctly and display in the interface.

**Screenshots**
<img width="579" alt="Screen Shot 2020-01-24 at 10 04 45 AM" src="https://user-images.githubusercontent.com/5122881/73078807-fc759b00-3e90-11ea-98d5-fa007fcedc15.png">

[Valet_Zones.geojson.zip](https://github.com/keplergl/kepler.gl/files/4109101/Valet_Zones.geojson.zip)

[Neighborhood_Commercial_Revitalization_Areas.json.zip](https://github.com/keplergl/kepler.gl/files/4109123/Neighborhood_Commercial_Revitalization_Areas.json.zip)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
Thiese geojson files were converted from shapefiles.

This was encountered using the `https://kepler.gl/demo` interface.

The shapefiles were sourced from http://opendata.columbus.gov/

They were converted using https://mapshaper.org/

**Comment by heshan0131** [comment]
The coordinate is not using Web Mercator projection. To convert projection mode, you can use QGIS
