### ISSUE TITLE
[Bug] Hexbin crashes on demo site

### ISSUE THREAD

**Issue by kuanb** [keplergl/kepler.gl#928]
**Describe the bug**
Hexbin view causes application to error, go to white screen. Console logs the following:
```
Uncaught TypeError: Cannot read property 'gpuFilter' of undefined
```

**To Reproduce**
1. Go to `https://kepler.gl/demo`

2. Upload a CSV of points data - can be simple, for example: [points.txt](https://github.com/keplergl/kepler.gl/files/4125576/points.txt)

3. Select hexbin from style option:
![image](https://user-images.githubusercontent.com/6053396/73317797-31b11e80-41ec-11ea-9b06-f359a5f0fc9b.png)

4. Wait a few seconds, and the app should crash. Zooming in or adjusting the scale of the hexagon radius can also trigger this behavior.

**Expected behavior**
App does not crash.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser: Version 79.0.3945.88 (Official Build) (64-bit)
 - Version: 1.1.13

**Additional context**
Screen capture before crash:
![image](https://user-images.githubusercontent.com/6053396/73317967-cae03500-41ec-11ea-94f7-0b5e3d62d4eb.png)

about ~3-5 seconds later, without any window events...

Screen capture after crash:
![image](https://user-images.githubusercontent.com/6053396/73317940-ba2fbf00-41ec-11ea-935a-f0279a42faee.png)

**Comment by mikima** [comment]
Same problem here.
I have seen that it crashes depending on the grid size.
E.g. on my computer, if I keep hex radius less than 15, it doesn't crash

**Comment by AnthonyMockler** [comment]
Same for me too. Chrome 79, Macbook Pro 13 (Intel Iris Plus 640 GPU)

**Comment by heshan0131** [comment]
The crash is caused by hover over the hexagon. Fix will come today

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/933

**Comment by AnthonyMockler** [comment]
Can confirm, #933 works for me now

**Comment by macrigiuseppe** [comment]
fixed
