### ISSUE TITLE
[Bug] Cannot build and display v1.1.3 demo app

### ISSUE THREAD

**Issue by rickyshelton** [keplergl/kepler.gl#930]
**Cannot build and run demo app for 1.1.3**
Can't build & launch demo application. Yarn seems to complete successfully, but browser displays empty blank window with error in console.

`Uncaught TypeError: _window.default.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ is not a function
    at Object../src/store.js (bundle.js:345084)
    at __webpack_require__ (bundle.js:727)
    at fn (bundle.js:101)
    at Object../src/main.js (bundle.js:344738)
    at __webpack_require__ (bundle.js:727)
    at fn (bundle.js:101)
    at Object.0 (bundle.js:345349)
    at __webpack_require__ (bundle.js:727)
    at bundle.js:794
    at bundle.js:797
`

**To Reproduce**

1. cd examples/demo-app
2. export MapboxAccessToken=token
3. yarn --ignore-engines && yarn start

**Expected behaviour**
Demo application successfully loads

**Desktop (please complete the following information):**
 - OS: MacOS Mohave 10.14.6
 - Browser Chrome 79.0.3945.130
 - Yarn 1.21.1
- NodeJS v12.11.0

**Comment by heshan0131** [comment]
https://github.com/keplergl/kepler.gl/pull/932

**Comment by heshan0131** [comment]
fixed. please check again
