### ISSUE TITLE
[Bug] Points and polygons have bizarre aspect ratios, shapes (v 1.1.13)

### ISSUE THREAD

**Issue by jonathan-airsage** [keplergl/kepler.gl#938]
I use kepler.gl weekly and just noticed some strange behavior on https://kepler.gl/demo:

1.) Upload the attached .geojson file (polygons), or any file with points. Note: remove the .txt in the filename.
2.) Points have varying aspect ratios as you zoom in/out, and polygons have bizarre shapes (see screenshots below)

<img width="1373" alt="polygons" src="https://user-images.githubusercontent.com/45101018/73877065-05b61e80-4826-11ea-94f5-1c594dddedca.png">
<img width="1297" alt="points" src="https://user-images.githubusercontent.com/45101018/73877075-08b10f00-4826-11ea-981f-cb41207753db.png">

[square_buildings.geojson.txt](https://github.com/keplergl/kepler.gl/files/4161709/square_buildings.geojson.txt)

**Comment by macrigiuseppe** [comment]
@jonathan-airsage this is fixed, please check again

**Comment by jonathan-airsage** [comment]
Looks good!
