### ISSUE TITLE
[Bug] H3 Layers Vibrate on Zoom

### ISSUE THREAD

**Issue by johachi-dw** [keplergl/kepler.gl#942]
**Describe the bug**
After adding H3 layer on current version (1.1.13) available on [kepler.gl/demo](http://kepler.gl/demo) the H3 layers hexagons are not aligned, and vibrate on zoom.

Same error occurs when running Kepler.gl locally.

Same error occurs when dispatching addDataToMap.

**To Reproduce**
1. Go to http://kepler.gl/demo
1. Click on **Add Data**
1. Add the file attached to this document (or any file with h3 id's)
1. Add a H3 layer
1. See error: Move map to where you can see the data
1. See error: Zoom in and out to see the hexagons vibrate

Behavior is the same even if we move to the area first, and then add the data and layer.

**Expected behavior**
Hexagons should not overlap and should not move on zoom.

**Screenshots**
![ScreenShot Move Short](https://user-images.githubusercontent.com/54825952/73995394-cf021480-499b-11ea-8dbc-3b30032296ae.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - Browser: Firefox Developer Edition, Chrome
 - Version: Firefox: 73.0b7 (64-bit), Chrome: Version 80.0.3987.87 (Official Build) (64-bit)

**Additional context**
Data used: [Home H3 IDs Smalls.csv.zip](https://github.com/keplergl/kepler.gl/files/4168656/Home.H3.IDs.Smalls.csv.zip)

This is probably related to #938 

I first discovered this about a week ago but did not do an error report until now.

**Comment by johachi-dw** [comment]
Here is a video clip demonstrating the vibration:
[Vibrating_h3_hexagons.mp4.zip](https://github.com/keplergl/kepler.gl/files/4168776/Vibrating_h3_hexagons.mp4.zip)

**Comment by macrigiuseppe** [comment]
@johachi-dw this should be already fixed, please check again
