### ISSUE TITLE
Hexbin Heat Map Issue

### ISSUE THREAD

**Issue by TamirShwartz** [keplergl/kepler.gl#944]
Hi. 
I'm trying to create a heat map by hexagons and it comes out really bad. 
I have tried to modify radius, coverage, etc. but I think that there is a systematic issue.
My friend created the wanted haxbin before the last commit,  and it came much batter.
I will appreciate if you will check this issue that. 
<img width="317" alt="2" src="https://user-images.githubusercontent.com/57898737/74098876-e0772800-4b25-11ea-8876-98298231e49a.png">
<img width="397" alt="1" src="https://user-images.githubusercontent.com/57898737/74098879-e66d0900-4b25-11ea-8a7a-83d41e3c6169.png">

**Comment by heshan0131** [comment]
Hi @TamirShwartz couod you please share a sample data with us so we can debug. I thinks will be fixed when [this PR](https://github.com/keplergl/kepler.gl/pull/889) is landed. still with the sample data I can test it

**Comment by heshan0131** [comment]
this should be fixed by now, please check
