### ISSUE TITLE
[FEAT] Get Map Bounds of map?

### ISSUE THREAD

**Issue by gabrielsaruhashi** [keplergl/kepler.gl#951]
Is there a way to get the map bounds of the map?
Similar to Google Maps' map.getBounds())

**Comment by macrigiuseppe** [comment]
> Is there a way to get the map bounds of the map?
> Similar to Google Maps' map.getBounds())

@gabrielsaruhashi you can take advantage of getMapboxRef callback. Example here: https://github.com/keplergl/kepler.gl/blob/master/examples/demo-app/src/app.js#L302

Once you have acquired the mapbox reference, you can use it to extract map bounds: https://docs.mapbox.com/mapbox-gl-js/api/#map#getbounds
