### ISSUE TITLE
Feature request: Allow render custom panels in side panel

### ISSUE THREAD

**Issue by ibgreen** [keplergl/kepler.gl#957]
**Is your feature request related to a problem? Please describe.**

The dependency injection system is really nice. However it seems there is no easy way to add another panel in the side panel, including the icons on the top. 

**Describe the solution you'd like**
Some kind of API would be great

**Describe alternatives you've considered**
Right now the alternative is effectively to copy/duplicate a lot of code from kepler.gl core, which e.g. creates maintenance concerns when upgrading the kepler core.

**Additional context**
N/A

**Comment by heshan0131** [comment]
#962
