### ISSUE TITLE
Kepler crashes on hexbin radius <0.5-1 with colour based on a column [Bug]

### ISSUE THREAD

**Issue by seizethedata** [keplergl/kepler.gl#960]
**Describe the bug**
kepler.gl crashes when trying to set up hexbin size less than 0.5km, sometimes even o 1km. My file size is reduces to 9mb already. 117k rows x 3 columns.

**To Reproduce**
1. Load point file into kepler ~100k rows
2. Change point layer to hex, set hex radius to 0.2-0.5km, colour based on a column
3. Zoom in or out
4. Screen goes white - kepler crashed

**Expected behavior**
I've done this before on larger datasets (~300mb) and it worked just fine. But this week it started crashing even on light datasets.

**Screenshots**
Here's a screenshot with settings I'm trying to get
![Screen Shot 2020-02-20 at 12 54 42](https://user-images.githubusercontent.com/29729619/74922685-a25cec80-53e0-11ea-9a59-69ede29fda3d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by heshan0131** [comment]
should be fixed, please check

**Comment by seizethedata** [comment]
Everything works, thanks!
