### ISSUE TITLE
Translating Kepler UI to different languages

### ISSUE THREAD

**Issue by Joonalai** [keplergl/kepler.gl#967]
**Is your feature request related to a problem? Please describe.**
I would like to translate the Kepler UI to Finnish. I already posted a question about this here #653 

**Describe the solution you'd like**
I would like to use method for translating that could be easily adapted by developers.

**Describe alternatives you've considered**
* One possible solution for translating is to use [react-localization](https://www.npmjs.com/package/react-localization). 
* Other alternative could be to use [react-intl](https://github.com/formatjs/react-intl). For example [Mapstore2](https://github.com/geosolutions-it/MapStore2/blob/master/docs/developer-guide/internationalization.md) uses react-intl successfully for huge translations. 

What do you think? What would be the best way of doing this?

**Comment by macrigiuseppe** [comment]
refer to #970
