### ISSUE TITLE
Kepler.gl Localization feature

### ISSUE THREAD

**Issue by macrigiuseppe** [keplergl/kepler.gl#970]
We are currently looking for someone who would love to work with Kepler.gl code base and implement the new localization feature.

Going through all UI components, extract all embedded text out and create a single js file that can be used with [react-intl](https://github.com/formatjs/react-intl)

[Example on how to use react-intl](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-react-app-with-react-intl)

Please let us know if you want to collaborate on this new and popular feature.

**Comment by Joonalai** [comment]
I would like to help with this. I actually already posted a similar issue #967.

**Comment by macrigiuseppe** [comment]
> #967

@Joonalai thank you for your interest. If you are interested I will assign this issue to you and start working on it.

**Comment by Joonalai** [comment]
@macrigiuseppe that sounds great.

**Comment by mayteio** [comment]
Give me a yell if you’d like to divide and conquer, I’d be happy to contribute too.

**Comment by Joonalai** [comment]
Thanks @mayteio! I am almost done with the task but I'll give you a yell if I find something you could help with.

**Comment by Joonalai** [comment]
@mayteio, would you perhaps have the time to check out the failing [browser tests](https://travis-ci.com/keplergl/kepler.gl/jobs/296469055)? I can check those later but maybe not during this week.

**Comment by macrigiuseppe** [comment]
> @mayteio, would you perhaps have the time to check out the failing [browser tests](https://travis-ci.com/keplergl/kepler.gl/jobs/296469055)? I can check those later but maybe not during this week.

your error is the following: 

```
✖ Show not fail without props
    ------------------------------
      operator: throws
      expected: |-
        undefined
      actual: |-
        [Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.]
      at: Test.<anonymous> (/home/travis/build/keplergl/kepler.gl/test/browser/components/modals/save-map-modal-test.js:39:5)
      stack: |-
```

It means you need to inject IntlProvider in your tests or find a better way to isolate components from your localization implementation

**Comment by Joonalai** [comment]
@macrigiuseppe, @mayteio I just fixed the tests related to localization.

**Comment by mayteio** [comment]
Sorry guys, am on holiday without a laptop! Glad you got it sorted 👏

**Comment by heshan0131** [comment]
@mayteio @Joonalai  I added some followup questions regarding future works, maybe this is something you can help on.

**Comment by Joonalai** [comment]
@heshan0131 @mayteio I added some initial code to the followup questions.

**Comment by leodavinci1** [comment]
Hey guys, can I add portuguese translations with [#1062 ](https://github.com/keplergl/kepler.gl/issues/1062) ?

**Comment by macrigiuseppe** [comment]
this is implemented in https://github.com/keplergl/kepler.gl/pull/994

I am gonna close this one

**Comment by KovalevArtem** [comment]
Convenient translations

I suggest using **[Weblate](https://weblate.org/en/hosting/)** or any other service. It is completely free for open source projects.
![image](https://user-images.githubusercontent.com/36500228/98449379-2b20e180-2144-11eb-8870-57606b640a77.png)

This will simplify the process for new translators.
It will also make it more convenient to keep up-to-date translations up to date.

And of course, more translators and more new languages will appear 😏
