### ISSUE TITLE
[Bug] Export Map HTML is broken

### ISSUE THREAD

**Issue by ibrahimabadi** [keplergl/kepler.gl#975]
**Describe the bug**
After clicking 'export' and going through the menu to export the map as an HTML, the file will load as blank in Chrome, Safari and Firefox. This happens for both read only and edit map mode and occurs when you switch out Mapbox tokens.

**To Reproduce**
1. Upload data to the map (csv in my case)
2. Add layers, etc.
3. Click 'export map'
4. Select HTML
5. Go through the HTML export options
6. Open export HTML

**Expected behavior**
I expected the HTML file to open up with my data and selected basemap included. Instead I got blank.

**Screenshots**
![Screen Shot 2020-02-26 at 12 13 07 PM](https://user-images.githubusercontent.com/52184163/75369395-5ce16900-5891-11ea-864a-976bd1979f20.png)

This is what my browser looks like after opening 

**Desktop (please complete the following information):**
 - OS: [macOS Mojave]
 - Browser [Chrome]
 - Version [80.0.3987.122 (Official Build) (64-bit)]

**Additional context**

**Comment by ibrahimabadi** [comment]
I am inspecting the page in Chrome and it looks like Kepler's server is 404ing.

![Screen Shot 2020-02-26 at 12 16 14 PM](https://user-images.githubusercontent.com/52184163/75369632-cfeadf80-5891-11ea-91b8-44cfe5fd6294.png)

**Comment by ibrahimabadi** [comment]
I seem to have fixed the issue in the HTML's code -- hopefully this helps you all diagnose the issue. If I change the line that defines where to load Kepler from:

        <script src="https://unpkg.com/kepler.gl@2.0.0/umd/keplergl.min.js" crossorigin></script>

to the value found in an older working version of a Kepler export:

        <script src="https://unpkg.com/kepler.gl@1.1.13/umd/keplergl.min.js" crossorigin></script>

Everything runs fine then. Hope this helps.

**Comment by VincentAntoine** [comment]
Same problem here. Changing to an older version of kepler in the html code does not solve the issue for me. In fact, I cannot even open older maps that were exported weeks ago and which I used to be able to open. Like you I get a blank page when I open the maps in Google Chrome.

**Comment by heshan0131** [comment]
yep, we just updated to the newest version in html template. it should works now

**Comment by heshan0131** [comment]
@VincentAntoine you shouldn't change the version in the html that exported weeks ago. kepler has to be pin to the version when you exported the map. If it still not working. could you send us a screenshot of error in your console?

**Comment by ibrahimabadi** [comment]
Thanks for the quick response @heshan0131 !
