### ISSUE TITLE
Hi! i noticed that the tooltip is not working, would you please check it?[Bug]

### ISSUE THREAD

**Issue by ethanwenbinlu** [keplergl/kepler.gl#976]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by heshan0131** [comment]
Can you help us reproduce? it seems to be working fine for us

<img width="738" alt="Screen Shot 2020-02-28 at 11 06 43 AM" src="https://user-images.githubusercontent.com/3605556/75579350-795cdd00-5a1a-11ea-8ef8-e01bba5291b4.png">

**Comment by macrigiuseppe** [comment]
@ethanwenbinlu I am gonna close this one. If you are still seeing an issue, please create a new one and make you provide clear details on how to reproduce the bug.
