### ISSUE TITLE
Trouble running demo-app on new version [Bug]

### ISSUE THREAD

**Issue by MorganGellert** [keplergl/kepler.gl#977]
**Describe the bug**
The demo app is not running for me on newer commits. The problem appears to start on commit 52124820e06430a63b4257af9e7e037c106a707a. I simply get a white screen. The web console debugger reads the following error:

> TypeError: item is undefined
panel-header.js:308
    render panel-header.js:308
    map self-hosted:291
    render panel-header.js:305
    React 10
    performSyncWorkOnRoot self-hosted:1063
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:653
    React 6
    js main.js:45
    Webpack 6
The above error occurred in the <PanelHeader> component:
    in PanelHeader (created by SidePanel)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by SideBar)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by SideBar)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by SideBar)
    in SideBar (created by SidePanel)
    in div (created by SidePanel)
    in SidePanel (created by KeplerGL)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by KeplerGL)
    in ThemeProvider (created by KeplerGL)
    in KeplerGL (created by Context.Consumer)
    in WithTheme(KeplerGL) (created by ConnectFunction)
    in ConnectFunction (created by WithConnectSelector)
    in WithConnectSelector (created by Container)
    in Container (created by ConnectFunction)
    in ConnectFunction (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by App)
    in div (created by App)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by App)
    in ThemeProvider (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Root)
    in Provider (created by Root)
    in Root

> Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:19560
TypeError: item is undefinedpanel-header.js:308
    render panel-header.js:308
    map self-hosted:291
    render panel-header.js:305
    React 10
    performSyncWorkOnRoot self-hosted:1063
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:653
    React 6
    js main.js:45
    Webpack 6

**To Reproduce**
1. Add MapboxAccessToken to environment variables
2. Run npm install and npm start on examples/demo-app

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox
 - Version : 70.0.1

**Comment by jhludwig** [comment]
Same issue for me running on v2.0.0 release.  

- OS: Ubuntu 18.04.3 LTS
- Browser: Chromium Version 80.0.3987.122 (Official Build) snap (64-bit)

**Comment by jhludwig** [comment]
git bisect suggests that commit 52124820e06430a63b4257af9e7e037c106a707a is the start of the issue

**Comment by heshan0131** [comment]
did you upgrade kepler.gl to v2.0.0 in your demo app package.json?

**Comment by jhludwig** [comment]
i did a fresh clone of kepler.gl repo and checked out the v2.0.0 release.  looks like the demo app package.json still refers to v1.1.13 at this commit.  i just made the version change in package.json and all works well now, thanks!

**Comment by heshan0131** [comment]
yes, there is 1 day delay between when we publish 2.0 and when we update the version in demo app, due to some issue with github publish. it should be all good now
