### ISSUE TITLE
[Bug] "Show data table" double scroll bar

### ISSUE THREAD

**Issue by larsgw** [keplergl/kepler.gl#982]
**Describe the bug**
When I open a data table in the demo, two scroll bars appear. Apart from generally being difficult to navigate the table, I could not find the horizontal scroll bar the first time.

**To Reproduce**
1. Hover over a layer consisting of a CSV file
2. Click on the button with the "Show data table" tool tip
3. See error

**Expected behavior**
I expect a single set of scroll bars.

**Screenshots**
![kepler gl_demo](https://user-images.githubusercontent.com/14018963/75595379-68e54a80-5a8c-11ea-8be5-e7960086e674.png)

(As you can see, cell values also have some problems with scroll bars but I cannot think of an immediate solution for that)

**Desktop:**
 - OS: debian
 - Browser google-chrome
 - Version 80

**Additional context**
It seems that the dimensions of `ReactVirtualized__Grid` are set to the exact dimensions of the modal, disregarding the data set/layer tabs and the button to close the modal. This seems to be confirmed by the JSX (`width` and `height` are parameters of the `DataTableModal`):

https://github.com/keplergl/kepler.gl/blob/10e9238bd14f375daaf1ac3f42d0804b30005192/src/components/modals/data-table-modal.js#L86-L93

**Comment by heshan0131** [comment]
@should be fixed now. Please check

**Comment by larsgw** [comment]
Yes, seems to work. Thank you!
