### ISSUE TITLE
[Bug] Can't resolve 'kepler.gl/cloud-providers'

### ISSUE THREAD

**Issue by EvsChen** [keplergl/kepler.gl#983]
**Describe the bug**
I tried running the demo-app locally by following the tutorial
```
yarn --ignore-engines && yarn start
```
 and ran into this error
```bash
ERROR in ./src/cloud-providers/dropbox/dropbox-provider.js
Module not found: Error: Can't resolve 'kepler.gl/cloud-providers' in '/Users/elvischen/kepler.gl/examples/demo-app/src/cloud-providers/dropbox'
 @ ./src/cloud-providers/dropbox/dropbox-provider.js 36:22-58
 @ ./src/cloud-providers/index.js
 @ ./src/app.js
 @ ./src/main.js
```
I tried setting all the environment variables but it doesn't seem to work. No additional error occurs during the `yarn` and `yarn start` step. It seems that others have also met this problem https://github.com/keplergl/kepler.gl/issues/979.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: Chrome 80.0.3987.122 & Safari 13.0.5 

**Additional context**
kepler.gl 2.0.0
node 10.19.0
yarn 1.12.1

**Comment by cperbost** [comment]
I switched back to an older version and it works. But I haven't found a solution for Kepler 2.0.0 ...

**Comment by cperbost** [comment]
Any updates?

**Comment by heshan0131** [comment]
2.0.1 has the fixes

**Comment by worldsayshi** [comment]
I checked out the current kepler.gl master (commit id 9029b8ea3f059fed3d901e81686a9a7c27284178), tried to run the demo-app and got this error:

```
ERROR in ./src/cloud-providers/carto/carto-provider.js
Module not found: Error: Can't resolve '@kepler.gl/cloud-providers' in '/home/myuser/workspace/kepler.gl/examples/demo-app/src/cloud-providers/carto'
 @ ./src/cloud-providers/carto/carto-provider.js 65:0-54 655:2-10
 @ ./src/cloud-providers/index.js
 @ ./src/app.js
 @ ./src/main.js

ERROR in ./src/cloud-providers/dropbox/dropbox-provider.js
Module not found: Error: Can't resolve '@kepler.gl/cloud-providers' in '/home/myuser/workspace/kepler.gl/examples/demo-app/src/cloud-providers/dropbox'
 @ ./src/cloud-providers/dropbox/dropbox-provider.js 68:0-54 828:2-10
 @ ./src/cloud-providers/index.js
 @ ./src/app.js
 @ ./src/main.js

ERROR in ./src/cloud-providers/carto/carto-provider.js
Module not found: Error: Can't resolve '@kepler.gl/table' in '/home/myuser/workspace/kepler.gl/examples/demo-app/src/cloud-providers/carto'
 @ ./src/cloud-providers/carto/carto-provider.js 66:0-55 572:26-45
 @ ./src/cloud-providers/index.js
 @ ./src/app.js
 @ ./src/main.js

ERROR in ./src/cloud-providers/carto/carto-provider.js
Module not found: Error: Can't resolve 'reducers' in '/home/pfredeli/workspace/kepler.gl/examples/demo-app/src/cloud-providers/carto'
 @ ./src/cloud-providers/carto/carto-provider.js 67:0-37 573:17-26
 @ ./src/cloud-providers/index.js
 @ ./src/app.js
 @ ./src/main.js
```

I use 
yarn 1.22.17
node v14.18.0

The demo depends on
kepler.gl 2.5.5

**Comment by abe15** [comment]
@worldsayshi, 
Going through the list of errors change any imports like @kepler/ with kepler/
Example: '@kepler.gl/cloud-providers'  -> 'kepler.gl/cloud-providers'
Module not found: Error: Can't resolve '@kepler.gl/cloud-providers' in 


Also,
in carto-provider.js
change
import { formatCsv } from "./reducers";
to
import { formatCsv } from "../../reducers";
