### ISSUE TITLE
[Bug] Log out in Load from Storage doesn't refresh the UI

### ISSUE THREAD

**Issue by VictorVelarde** [keplergl/kepler.gl#990]
**Describe the bug**
Pressing the Logout link under cloud providers, doesn't refresh the UI

**To Reproduce**
1. Go to 'Add data'
2. Click on 'Load from Storage'
3. Login into a provider, then Logout

**Expected behavior**
UI refreshes accordingly

**Comment by macrigiuseppe** [comment]
fixed
