### ISSUE TITLE
[Bug] When aggregation takes too long only a few color bins show up. 

### ISSUE THREAD

**Issue by MorganGellert** [keplergl/kepler.gl#992]
**Describe the bug**
When doing a hex bin aggregation on a lot of data where you want to color by a field (aggregating by mode) and the aggregation takes too long or the granularity is reduced to small bins bins only show up for a few of the classes. 

**To Reproduce**
If you use the earthquake demo and switch to the hexbin and color by MagType you may see that very little data shows up for a radius of 2km but much more shows up for a radius of 5 km. 

The following warning appears as well every time the config changes in the sidebar. Unclear how related it is but it may point in the correct direction.
`Warning: Cannot update a component from inside the function body of a different component.
    in DeckGL (created by MapContainer)
    in div (created by Context.Consumer)
    in div (created by AutoSizer)
    in AutoSizer (created by StaticMap)
    in div (created by StaticMap)
    in StaticMap (created by InteractiveMap)
    in div (created by InteractiveMap)
    in InteractiveMap (created by MapContainer)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by MapContainer)
    in MapContainer (created by KeplerGL)
    in div (created by KeplerGL)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by KeplerGL)
    in ThemeProvider (created by KeplerGL)
    in KeplerGL (created by Context.Consumer)
    in WithTheme(KeplerGL) (created by ConnectFunction)
    in ConnectFunction (created by WithConnectSelector)
    in WithConnectSelector (created by Container)
    in Container (created by ConnectFunction)
    in ConnectFunction (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by App)
    in div (created by App)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by App)
    in ThemeProvider (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Root)
    in Provider (created by Root)
    in Root`

**Desktop (please complete the following information):**
 - OS: Mac Os Mojave
 - Browser chrome and firefox

**Comment by heshan0131** [comment]
Hi @MorganGellert the error is actually unrelated to your aggregation case. How many points are we talking about? Do you have other filters applied at the same time?

**Comment by MorganGellert** [comment]
I guess the california earthquake dataset is only ~55K rows. Here are some screenshots showing the disparity. When coloring by `Magnitude` (a float) everything is fine. But when you try to color by `MagType` (a string) many of the bins no longer show up. 
<img width="1570" alt="Screen Shot 2020-03-10 at 10 30 32 AM" src="https://user-images.githubusercontent.com/2454079/76341488-5b189c00-62ba-11ea-9604-1418800ed36a.png">
<img width="1613" alt="Screen Shot 2020-03-10 at 10 30 23 AM" src="https://user-images.githubusercontent.com/2454079/76341494-5ce25f80-62ba-11ea-83f6-fc5816ae0dd7.png">

**Comment by MorganGellert** [comment]
I did a little more digging. It appears that when doing a mode aggregation for assigning color there is some failure in rendering. If I edit the mode type aggregation in `aggregate-utils.js` to return a constant integer then all the bins consistently show up. Any ideas why coloring by a string type would result in such issues?

**Comment by MorganGellert** [comment]
FYI if you go to https://kepler.gl/demo/earthquakes and switch the layer type to Hexbin and color by MagType you can see this as well.

**Comment by MorganGellert** [comment]
With the merge of 1070 this is resolved
