### ISSUE TITLE
[Bug] Share map shows last saved URL

### ISSUE THREAD

**Issue by neokore** [keplergl/kepler.gl#997]
**Describe the bug**
After saving a map, share map URL modal shows previously saved map URL as sharing URL.

**To Reproduce**
1. Load any map
2. Go to "Cloud Storage" > "Save"
3. Select a cloud provider
4. Fill the name field
5. Click on "Save"
6. After map is saved, go to "Share" > "Share Map URL"
7. On the modal, the "Share URL" field shows an URL

**Expected behavior**
"Share URL" field must not appear because the map is not shared yet.

**Comment by macrigiuseppe** [comment]
fixed
